CONTINUATIONS_KO = {
    0: [
        ("다음 날 아침, 아지즈는 일곱 시 정각에 다시 나에게 전화했다.", "Ertasi kuni ertalab Aziz yana soat yettida aniq qo'ng'iroq qildi."),
        ("그는 빵집 아주머니에게 제대로 된 아침 식사로 감사를 전하고 싶어 했다.", "U nonvoyxonachi ayolga to'g'ri nonushta bilan minnatdorchilik bildirmoqchi edi."),
        ("우리는 여전히 어제 비 냄새가 나는 채로 같은 버스 정류장에서 만났다.", "Biz xuddi shu bekatda uchrashdik, kechagi yomg'ir hidida."),
        ("도시는 갓 씻은 듯 보였고 곳곳에 은빛 물웅덩이가 고여 있었다.", "Shahar endigina yuvilgandek ko'rindi, hamma joyda kumush suv havzalari."),
        ("카페에서 우리는 라떼 두 잔과 커다란 쿠키 하나를 주문했다.", "Kafeda ikkita latte va bitta ulkan pechene buyurtma qildik."),
        ("아지즈는 사업 계산으로 가득 찬 수첩을 펼쳤다.", "Aziz biznes hisob-kitoblari bilan to'lgan daftarini ochdi."),
        ("숫자는 그를 조금 겁나게 했지만, 그는 용감하게 마주했다.", "Raqamlar uni biroz qo'rqitardi, lekin u ularga jasurlik bilan yuzlashdi."),
        ("나는 매우 진지하게 그의 계산을 두 번 확인하는 것을 도왔다.", "Men uning hisoblarini ikki marta juda jiddiy tekshirib berdim."),
        ("그 대신 그는 내 끔찍한 영어 발음을 부드럽게 고쳐 주었다.", "Buning evaziga u mening dahshatli inglizcha talaffuzimni muloyimlik bilan tuzatdi."),
        ("나이 든 웨이터가 우리를 지켜보며 청춘을 기억하는 듯 미소 지었다.", "Keksa ofitsiant bizni kuzatdi va yoshligini eslagondek tabassum qildi."),
        ("그는 계획을 가진 젊은이들이 자신에게 희망을 준다고 말했다.", "U rejaga ega yoshlar unga umid berishini aytdi."),
        ("커피를 마신 후, 우리는 낡은 영화관 건물을 천천히 지나쳤다.", "Qahvadan keyin eski kinoteatr binosi oldidan sekin o'tdik."),
        ("그 건물은 스무 해의 잿빛 세월 끝에 마침내 다시 칠해지고 있었다.", "Yigirma kulrang yildan keyin u nihoyat bo'yalayotgan edi."),
        ("높은 사다리 위의 작업자들이 우리에게 활짝 손을 흔들었다.", "Baland narlarda turgan ishchilar bizga quvonch bilan qo'l silkitdi."),
        ("아지즈는 '미래의 추억 폴더'를 위해 모든 것을 사진으로 담았다.", "Aziz hammasini 'kelajak xotiralari papkasi' uchun suratga oldi."),
        ("그의 그 재미있는 표현은 항상 나를 소리 내어 웃게 만든다.", "Uning bu kulgili iborasi meni doim baland ovozda kuldiradi."),
        ("늦은 오후에는 어쩌다 보니 강 부두에 이르렀다.", "Kechki paytga kelib bir yo'i daryo pristaniga borib qoldik."),
        ("우리는 조급한 오리들에게 빵 부스러기를 주며 배에 대해 다투었다.", "Biz sabzavot nonlarini sabrsiz o'rdaklarga berdik va kemalar haqida bahslashdik."),
        ("집에 가는 길에 우리는 우리 도시를 계속 탐험하기로 약속했다.", "Uyga qaytayotib, o'z shahrimizni o'rganishda davom etishga va'da berdik."),
        ("어떤 주말은 값비싼 해외 휴가보다 더 가치 있다.", "Ba'zi dam olish kunlari chet eldagi qimmat ta'tillardan ham qadrli."),
    ],
    1: [
        ("이스탄불은 소금기와 굽은 밤나무 냄새로 나를 맞이했다.", "Istanbul meni tuz va qovurilgan kashtan hidi bilan kutib oldi."),
        ("삼촌의 아파트는 고양이들로 가득한 좁은 거리에 서 있었다.", "Amakimning kvartirasi mushuklarga to'la tor ko'chada joylashgan edi."),
        ("매일 저녁 우리는 아주 작은 생선 요리점까지 걸어 내려갔다.", "Har kechqurun mayda baliq restoraniga pastga tushardik."),
        ("웨이터들은 내 억양을 놀리면서 진짜 표현들을 가르쳐 주었다.", "Ofitsiantlar talaffuzimni masxara qilishdi, lekin haqiqiy iboralarni o'rgatishdi."),
        ("나는 실수가 사람들을 웃게 하고 마음을 열게 한다는 것을 배웠다.", "Xatolar odamlarni tabassumga keltiradi va ochilishga undaydi deb o'rgandim."),
        ("어느 날 아침 우리는 페리를 타고 보스포루스를 건넜다.", "Bir ertalab Bosfor bo'ylab paromga chiqdik."),
        ("갈매기들이 배를 따라다니며 승객의 손에서 빵을 낚아챘다.", "Chag'alalar kemaning ortidan borib, yo'lovchilar qo'lidan non tutdi."),
        ("두 대륙 사이에 서 있는 것은 처음엔 비현실적으로 느껴졌다.", "Ikki qit'a orasida turish avvaliga g'ayrioddiy tuyuldi."),
        ("아시아 쪽에서 우리는 튤립 모양 잔으로 차를 마셨다.", "Osiyo tomonida lola shaklidagi stakanda choy ichdik."),
        ("늙은 선장이 지나가는 모든 섬과 요새를 설명해 주었다.", "Keksa kapitan o'tayotgan har bir orol va qal'ani tushuntirdi."),
        ("그의 터키어는 느리고 명확해서 초보자에게 완벽했다.", "Uning turkchasi sekin va ravon edi, boshlovchilar uchun mukammal."),
        ("나는 절반을 이해하고, 4분의 1을 추측하며, 전부 사랑했다.", "Yarmisini tushundim, choragini taxmin qildim va hammasini sevdim."),
        ("고향에 돌아오자 모두가 케밥과 시장에 대해 물었다.", "Vatanimga qaytgach, hamma shashlik va bozorlar haqida so'radi."),
        ("하지만 나는 대신 그 페리 타기에 대한 이야기를 계속했다.", "Lekin men o'rniga o'sha parom sayohati haqida gapirib berardim."),
        ("흐르는 물에는 낯선 사람을 친구로 만드는 무언가가 있다.", "Harakatlanuvchi suv odamlar nimani do'stlarga aylantirishining sirini bildi."),
        ("집으로 가는 공항에는 3시간 일찍 도착했다.", "Uyga qaytayotganda aeroportga uch soat oldin bordim."),
        ("이번에는 보안 검색이 익숙하게, 거의 일상처럼 느껴졌다.", "Bu safar xavfsizlik tekshiruvi tanish, deyarli kundalik ishdek tuyuldi."),
        ("나는 엽서를 사서 탑승구에서 기다리며 그것들에 편지를 썼다.", "Postkartalar sotib oldim va reja kutayotib ularni yozdim."),
        ("비행기가 떠오를 때 나는 얼굴을 창에 붙였다.", "Samolyotimiz ko'tarilganda yuzimni oynaga bosdim."),
        ("이스탄불은 아름다운 손으로 그린 지도처럼 아래로 작아졌다.", "Istanbul ostda go'zal qo'lda chizilgan xaritadek kichiklashdi."),
        ("집으로 가는 비행은 달랐다. 더 차분하고, 더 자랑스럽고, 이미 그리웠다.", "Uyga parvoz boshqacha tuyuldi: sokinroq, faxrliroq, allaqachon nostaljiya bilan."),
    ],
    2: [
        ("다음 화요일은 카페에서 뜻밖의 놀라움을 가져왔다.", "Keyingi seshanba kuni kafeda kutilmagan syurpriz kutib turardi."),
        ("웨이트리스는 내가 카운터에 도착하기 전에 내 주문을 기억했다.", "Ofitsiant men dollar oldiga yetmasdan buyurtmamni esladi."),
        ("\"카푸치노와 사과파이 맞으신가요?\" 그녀가 조용한 긍지로 물었다.", "'Kapuchino va olcha pie?' deb so'radi u sokin iftixor bilan."),
        ("나는 끄덕였다. 비밀 클럽의 일원이 된 기분이었다.", "Men bosh irg'atdim, sirli klubga a'zo bo'lgandek his qildim."),
        ("그날 긴장한 젊은 남자가 구석에 혼자 앉아 있었다.", "O'sha kun burchakda asabiylashgan yosh yigit yolg'iz o'tirdi."),
        ("그는 휴대폰 카메라를 향해 무언가를 조용히 연습하고 있었다.", "U bir narsani telefon kamerasiga jim mashq qilib ko'rardi."),
        ("바리스타는 부탁받지도 않고 그의 옆에 핫초코를 놓았다.", "Barista so'ralmasdan uning yoniga issiq shokolad qo'ydi."),
        ("그녀는 모든 사람이 면접 전에 용기가 필요하다고 속삭였다.", "U ish suhbatidan oldin hammaga jur'at kerakligini shivirladi."),
        ("그가 마침내 떠날 때 그는 챔피언처럼 주먹을 들어 올렸다.", "Nihoyat chiqib ketayotib, u g'olib kabi mushtini ko'tardi."),
        ("카페 전체가 손짓만으로 조용히 박수를 쳤다.", "Butun kafe jim qarsak chaldi, faqat qo'llarni harakatga keltirib."),
        ("잠시 후 창가에서 늙은 체스 라이벌 대결이 시작되었다.", "Lahzadan keyin oynaning yaqinida eski shaxmat raqobati boshlandi."),
        ("두 명의 연금 수령자가 지난주의 한 수를 두고 다투었다.", "Ikkita nafaqaxur o'tgan haftadagi yurish haqida bahslashdi."),
        ("그들은 나를 심판으로 초대했지만 나는 체스를 거의 모른다.", "Ular menga hakamlikni taklif qilishdi, holbuki men shaxmatni zo'rg'a bilaman."),
        ("나는 아무 데나 가리켰고 한 선수는 고마움에 내 손에 입을 맞추었다.", "Men tasodifiy ko'rsatdim; bir o'yinchi minnatdorchilik bilan qo'llarimni o'pdi."),
        ("다른 선수는 재대결을 요구하며 축하 케이크를 주문했다.", "Ikkinchisi revansh talab qildi va nishon tortini buyurtma qildi."),
        ("밖에는 비가 다시 왔지만 아무도 서두르지 않아 보였다.", "Tashqarida yomg'ir qaytdi, lekin hech kim shoshilmayotganday edi."),
        ("카페는 내 작은 인간 이야기들의 대학교가 되었다.", "Kafe mening kichik insoniy hikoyalar universitetiga aylandi."),
        ("나는 그것들을 담기 위해 노트를 어디든 가지고 다니기 시작했다.", "Daftarchamni ularni yozib olish uchun hamma joyga olib yuradigan bo'ldim."),
        ("한 페이지에는 이렇게만 적혀 있다. \"사람들은 뉴스가 말하는 것보다 더 친절하다.\"", "Bir sahifada shunday deyilgan: 'Odamlar yangiliklardagidan ham mehrliroq.'"),
        ("매주 화요일은 그 문장을 거듭 증명한다.", "Har seshanba bu jumlaning rostligini yana bir bor tasdiqlaydi."),
    ],
    3: [
        ("사무실에서의 두 번째 주는 진짜 책임감을 가져왔다.", "Ofisdagi ikkinchi haftam haqiqiy mas'uliyat olib keldi."),
        ("매니저가 나에게 나만의 작은 프로젝트를 맡겼다.", "Menejer menga o'zimning kichik loyihani topshirdi."),
        ("폴더를 받으면서 내 손이 살짝 떨렸다.", "Papkani qabul qilayotib qo'llarim biroz titradi."),
        ("그것은 아무도 읽고 싶어 하지 않는 고객 피드백 보고서였다.", "Bu hech kim o'qishni istamagan mijoz fikrlari hisoboti edi."),
        ("나는 그것을 무시할 수 없게 만들기로 결심했다.", "Men uni e'tiborsiz qoldirib bo'lmaydigan qilishga qaror qildim."),
        ("표 대신 나는 간단하고 알록달록한 차트를 그렸다.", "Jadvalalar o'rniga men oddiy rangli diagrammalar chizdim."),
        ("도스톤이 회사 프레젠테이션 프로그램을 인내심 있게 가르쳐 주었다.", "Doston ofis taqdimot dasturini sabr bilan o'rgatdi."),
        ("우리는 두 번 늦게까지 남아 서식 재앙을 두고 웃었다.", "Biz ikki marta kechgacha qoldik, formatlash baxtsizliklaridan kulib."),
        ("청소 아주머니가 우리에게 비스킷과 진한 홍차를 가져다 주었다.", "Tozalovchi ayol bizga pechene va kuchli choy olib keldi."),
        ("그녀는 피곤한 눈에는 설탕과 신선한 공기가 필요하다고 했다.", "U charchagan ko'zlar shakar va toza havoga muhtoj deb aytdi."),
        ("목요일에 나는 전체 팀에게 내 조사 결과를 발표했다.", "Payshanba kuni xulosalarimni butun jamoaga taqdim etdim."),
        ("내 목소리는 정확히 1분간 떨렸다가 안정되었다.", "Ovozim aynan bir daqiqa titradi, keyin barqarorlashdi."),
        ("사람들이 실제로 자신 있게 대답할 수 있는 질문을 던졌다.", "Odamlar men ishonch bilan javob bera oladigan savollar berishdi."),
        ("이사가 말했다. \"드디어 데이터가 말을 하게 만드는 사람이 나타났군요.\"", "Direktor dedi: 'Nihoyat, kimdir ma'lumotlarni gapira qildi.'"),
        ("그 문장은 저녁 종일 내 머릿속에서 반복되었다.", "O'sha jumla butun kechqurun miyamda takrorlandi."),
        ("금요일 아침, 경리 부서의 동료가 점심 식사에 초대했다.", "Juma ertalab hisob bo'limidagi hamkasb tushlikka taklif qildi."),
        ("그녀는 불과 8개월 전 자신도 새내기였던 것을 기억했다.", "U sakkiz oy oldin bu yerda yangi bo'lganini esladi."),
        ("그녀의 조언은 간단했다. 모두의 이름에 대한 메모를 유지하라.", "Uning maslahati oddiy edi: hamma odamning ismi haqida yozib boring."),
        ("작은 세부 사항들이 큰 신뢰를 천천히 쌓는다고 그녀는 말했다.", "Kichik tafsilotlar katta ishonchni sekin quradi dedi u."),
        ("금요일 저녁까지 내 프로젝트는 공식적으로 승인되었다.", "Juma kechqurunga kelib loyham rasman tasdiqlandi."),
        ("나는 싼 피자와 값비싼 행복으로 혼자 축하했다.", "Men arzon pitsa va qimmat baxt bilan yolg'iz nishonladim."),
    ],
    4: [
        ("그 일요일 점심 후 할머니는 특별한 임무를 발표하셨다.", "O'sha shanba tushlikdan keyin Bobomiz maxsus vazifa e'lon qildi."),
        ("온실 뒤의 포도나무에 긴급한 수확이 필요했다.", "Issiqxona ortidagi uzum tokining shoshilinch terilishi kerak edi."),
        ("당연히 우리 손주들 외에 모두가 바쁜 일정을 주장했다.", "Hamma band jadvalini da'vo qildi, albatta biz nabiralar bundan mustasno."),
        ("할머니는 메달처럼 가위와 엮은 바구니들을 나눠 주셨다.", "U bizga medallar kabi qaychi va to'qima savatlarni berdi."),
        ("포도나무는 보라색 송이들로 높고 무겁게 서 있었다.", "Toklar binafsha gullari bilan baland va og'ir turardi."),
        ("사촌 바호디르는 아무도 막기도 전에 절반쯤 올라갔다.", "Amakivachcha Bahodir hech kim to'xtatmasdan yarmigacha chiqib oldi."),
        ("말벌이 그의 귀를 조사했고 사다리가 크게 흔들렸다.", "Bir asalari qulog'ini tekshirdi narlar kuchli silkindi."),
        ("그는 올라갈 때보다 빠르게 내려왔다. 자존심은 살짝 상한 채로.", "U chiqqanidan tezroq tushdi, izzati biroz shikastlangan holda."),
        ("할머니는 아래에서 모든 것을 지켜보며 소리 없이 웃으셨다.", "Bobomiz hamma narsani pastdan kuzatdi, ovozisiz kuldi."),
        ("우리는 끈적한 한 시간의 작업으로 바구니 세 개를 채웠다.", "Yopishqoq ishning bir soati ichida uch savat to'ldirdik."),
        ("보라색 얼룩이 임시 문신처럼 우리 손가락을 덮었다.", "Binafsha dog'lar barmoqlarimizni vaqtinchalik tatuka kabi qoplaydi."),
        ("가장 어린 사촌은 자신이 딴 것보다 더 많은 포도를 먹었다.", "Eng kichkina amakivachcha tabiiyki terganidan ko'p uzum yedi."),
        ("할머니는 아무것도 세지 않으시고 모두에게 두 번씩 감사하셨다.", "Bobomiz hech narsani sanamadi lekin hammaga ikki marta rahmat aytdi."),
        ("저녁에 할머니는 포도를 검은 주스로 끓이셨다.", "Kechkirib u uzumlarni qora sharbatga qaynatdi."),
        ("집 전체가 과일 공장처럼 달콤한 냄새가 났다.", "Butun uy mevazavoddek shirin hid berardi."),
        ("우리는 별이 떠오르는 것을 보며 베란다에서 따뜻한 주스를 마셨다.", "Verandada iliq sharbat ichib, yulduzlar paydo bo'lishini kuzatdik."),
        ("할아버지께서 1980년에 그 포도나무를 심었던 이야기를 해 주셨다.", "Bobo o'sha toklarni 1980-yilda ekkanini gapirdi."),
        ("작은 보라색 열매 안에서 자라난 40년의 인내.", "Qirq yillik sabr mayda binafsha mevalar ichida yetilibdi."),
        ("아무도 자고 싶어 하지 않았다. 휴대폰들마저 실내에 잊혀 있었다.", "Hech kim uxlamoqchi emas edi; hatto telefonlar ham uyda unutilgan edi."),
        ("우리가 마침내 떠날 때 차에는 주스와 포도와 평화가 실렸다.", "Nihoyat ketganda mashina sharbat, uzum va tinchlik olib ketaardi."),
    ],
    5: [
        ("코트의 첫 번째 진짜 시험은 학교 소풍 중에 왔다.", "Paltoning birinchi haqiqiy sinovi maktab sayohati paytida keldi."),
        ("우리는 금요일에 40명의 아이들을 겨울 동물원에 데려갔다.", "Juma kuni qirq bolani qishki zooparkga olib bordik."),
        ("나는 책임 있는 성인이었는데, 지금도 가족들은 그걸 놀란다.", "Men mas'ul katta odam edim, bu hali ham oilamni hayron qiladi."),
        ("눈이 아침 9시부터 계속 내렸다.", "Qor soat to'qqizdan boshlab uzluksiz tushardi."),
        ("코트는 펭귄과 팝콘의 3시간을 통틀어 나를 따뜻하게 해 주었다.", "Palto uch soat pengvinlar va popkorn orasida meni iliq saqladi."),
        ("말리카라는 어린 소녀가 그날 나를 영구적으로 입양했다.", "Malika ismli mayda qiz o'sha kun menga abadiy biriktirildi."),
        ("그녀는 어디서나 작은 경비원처럼 내 소매를 붙잡았다.", "U hamma joyda kurtagimdan mayda xavfsizlik xodimidek ushlab turdi."),
        ("늑대 우리에서 그녀가 가장 큰 질문을 속삭였다.", "Bo'ri qafasi oldida eng katta savolini shivirladi."),
        ("\"늑대도 추워요?\" — 나는 그들의 털이 더 두꺼워진다고 말했다.", "'Bo'rilar muzlaydimi?' — Ularning paltolari qalinroq o'sadi dedim."),
        ("그녀는 심각하게 고민하더니 인간에게는 가게가 필요하다고 결론지었다.", "U buni jiddiy o'ylob odamlarga do'konlar kerak deb qaror qildi."),
        ("점심 때 우리는 핫초코 포장마차가 문을 닫은 것을 발견했다.", "Tushlik paytida issiq shokolad savati yopilganini aniqladik."),
        ("20개의 실망한 얼굴이 한꺼번에 나를 올려다보았다.", "Yigirma xafa yuz birdan menga qaradi."),
        ("그래서 코트는 이야기가 되었다. 나는 농담을 미소로 교환했다.", "Shuning uchun palto hikoyaga aylandi: hazillarimni tabassumlarga almashtirdim."),
        ("돌아가는 버스에서 모두가 몇 분 안에 잠들었다.", "Orqaga qaytayotgan avtobusda hamma bir necha daqiqada uxlab qoldi."),
        ("말리카는 작은 주먹 하나로 내 단추를 쥔 채 잠들었다.", "Malika bitta kichik musht bilan tugmamni ushlab uxlab qoldi."),
        ("선생님께서 고마워하며 보온병의 따뜻한 차를 권하셨다.", "Ular o'qituvchisi menga rahmat aytdi va termosidan issiq choy taklif qildi."),
        ("그날 저녁 나는 코트의 눈을 조심스럽게 털어냈다.", "O'sha kechqurun paltoni qordan ehtiyotkorlik bilan artib oldim."),
        ("그것은 이미 깊은 주머니에 이야기들을 담고 있었다.", "U allaqachon chuqur cho'ntaklarida hikoyalar olib yurardi."),
        ("어머니는 왼쪽 주머니 안에서 접힌 크레용 그림을 찾으셨다.", "Onam chap cho'ntak ichida bukilgan rangli chizma topdi."),
        ("큰 하얀 눈 낙서 아래 두 개의 막대인형.", "Katta oppoq qor chizig'i ostida ikkita cho'p odamcha."),
        ("말리카는 자랑스러운 비뚤어진 글자 M 하나로 서명해 놓았다.", "Malika uni faxr bilan bitta qiyshiq M harfi bilan imzolagan edi."),
    ],
    6: [
        ("결승 다음 날 아침 우리 거리는 다르게 느껴졌다.", "Finaldan keyingi ertalab ko'chamiz boshqacha tuyuldi."),
        ("한 번도 인사한 적 없던 이웃들이 갑자기 베란다에서 손을 흔들었다.", "Hech qachon salom bermagan qo'shnilar birdan verandalardan qo'l silkitdi."),
        ("누군가 하룻밤 새 낡은 공장 벽에 '챔피언'이라고 분필로 써 두었다.", "Kimdir kechasi eski zavod devoriga bo'rdan 'CHEMPIONLAR' yozdi."),
        ("자수르는 진짜 플라스틱 트로피를 들고 연습에 나타났다.", "Jasur mashg'ulotga haqiqiy plastik kubok olib keldi."),
        ("삼촌이 파티용품 가게를 소유하고 있었다.", "Uncasining to'y buyumlari sotadigan do'koni bor edi."),
        ("우리는 10분 동안 웃고 나서 그럼에도 진지하게 훈련했다.", "Biz o'n daqiqa kuldik va baribir jiddiy mashq qilishda davom etdik."),
        ("이긴다는 것은, 자수르가 설명했듯이, 챔피언으로 남는 것보다 쉽다.", "G'alaba, deb tushuntirdi Jasur, g'olib bo'lib qolishdan osonroq."),
        ("그래서 우리는 압박 속에서의 패스 훈련을 설계했다.", "Shuning uchun bosim ostida pass berish uchun mashqlar tuzdik."),
        ("두 명이 압박하고 한 명이 공과 함께 빠져나갔다.", "Ikkala o'yinchi bosim berganda bittasi to'p bilan qochardi."),
        ("내 역할은 중앙의 조용한 연결자가 되었다.", "Mening rolim markazdagi sokin bog'lovchiga aylandi."),
        ("나는 빠르지 않지만 공간을 일찍 본다.", "Men tez emasman, lekin bo'sh joylarni erta ko'raman."),
        ("사르도르는 매일 해질녘까지 프리킥 연습을 했다.", "Sardor har kuni quyosh botguncha jarima zarbalari mashq qildi."),
        ("아지즈는 양발, 대부분 왼발로 마무리 작업을 했다.", "Aziz ikkala oyog' bilan, ko'pincha chap bilan zarba yakunlash ustida ishladi."),
        ("우리 골키퍼는 각 훈련 전에 이상한 춤을 발명했다.", "Darvozabonimiz har bir mashqdan oldin g'alati raqslar ixtiro qildi."),
        ("아무도 그것을 이해하지 못했지만 아무도 그에게 골을 넣지도 못했다.", "Hech kim ularni tushunmadi, lekin hech kim unga gol ham urmadi."),
        ("한 달 후 다른 지역의 팀이 우리에게 도전장을 던졌다.", "Bir oy o'tib boshqa tumanlik jamoa bizga chiqishdi."),
        ("그들은 같은 유니폼과 같은 자신감으로 도착했다.", "Ular bir xil forma va bir xil ishonch bilan kelishdi."),
        ("우리는 어긋난 셔츠와 절대적인 믿음을 대신 입었다.", "Biz esa nomuvofiq ko'ylaklar va mutlaqo ishonch kiydik."),
        ("그 경기는 3-1로 끝났고 우리의 축구가 먼저 말했다.", "O'sha uchrashuv uch-bir yakunlandi va futbolimiz avval gapirdi."),
        ("경기 후 우리는 공장 계단에서 함께 수박을 먹었다.", "Keyinchalik zavod narlarida birga tarvuz yedik."),
        ("자수르는 주스 팩을 들어 올리며 말했다. \"드리블하기 전에 패스해 — 인생에서도.\"", "Jasur sharbat qutisini ko'tarib dedi: 'Hayotda ham chalg'idan oldin pass ber.'"),
    ],
    7: [
        ("우리는 산을 너무 좋아해서 가을에 다시 돌아갔다.", "Biz tog'larni shu qadar yaxshi ko'rdik kech kuzda qaytib bordik."),
        ("10월은 사면을 구리색, 황금색, 진홍색으로 칠했다.", "Oktyabr yon bag'irlarni mis, oltin va to'q qizil ranglarga bo'ydi."),
        ("이번에는 모두가 우비와 여분의 양말을 챙겼다.", "Bu safar hamma yomg'irpoq va ehtiyot paypoq olib chiqdi."),
        ("경험은 비싸지만 그 교훈은 영원히 남는다.", "Tajriba qimmat turadi, lekin uning darslari abadiy qoladi."),
        ("공기는 살살 물어뜻기에 좋을 만큼 상쾌했다.", "Havo yumshoq tishlashga yetarli darajada tetik edi."),
        ("파리스는 중력에 대한 개인적 복수를 가진 사람처럼 앞장섰다.", "Faris tortishish kuchiga shaxsiy qasos oluvchi odamdek oldinda yurardi."),
        ("딜노자는 식물학 과제 폴더를 위해 나뭇잎을 모았다.", "Dilnoza botanika loyiha papkasi uchun yaproqlar yig'di."),
        ("그녀는 사진 찍은 나무들을 제외하고 모든 나무 이름을 알았다.", "U suratga olganlaridan boshqa har bir daraxt nomini biladi."),
        ("중턱에서 우리는 계곡을 마주한 나무 벤치를 발견했다.", "Yarmiga kelib vodiga qaragan yog'och skameyka topdik."),
        ("몇 해 전 누군가 등받이에 '여기서 호흡하라'고 새겨 놓았다.", "Kimdir yillar oldin orqasiga 'Bu yerda nafas ol' deb o'yma edi."),
        ("그래서 우리는 그 고대의 지시에 복종하며 깊이 숨을 쉬었다.", "Shuning uchun qadimiy ko'rsatmaga bo'ysundik va chuqur nafas oldik."),
        ("아래로 내려다보면 마을이 흩어진 장난감 집들처럼 보였다.", "Ostimizda qishloq tarqoq o'yinchoq uylarga o'xshab ko'rindi."),
        ("연기가 완벽하게 게으른 기둥으로 굴뚝에서 피어올랐다.", "Mo'rilardan mukammal dangasa ustunlar bo'ylab tutun ko'tarildi."),
        ("매가 몇 분 동안 우리 위를 길게 선회했다.", "Bir lochin bizning atrofimizda bir necha uzun daqiqa aylanardi."),
        ("자수르는 그것이 우리가 이번엔 준비됐는지 확인하는 것이라 주장했다.", "Jasur bu safar biz tayyorlanganimizni tekshirayotganini da'vo qildi."),
        ("정상 근처에서 우리는 아주 작은 얼어붙은 폭포를 발견했다.", "Cho'qqi yaqinida mayda muzlagan sharshara topdik."),
        ("물은 불가능할 만큼 인내심 있게 유리 조각처럼 중간에 매달려 있었다.", "Suv o'rtada oyna haykali kabi osilgan edi, aql bovar qilmas sabr bilan."),
        ("딜노자가 과학을 설명했지만 우리는 대부분 그저 바라보았다.", "Dilnoza ilmiy tomonni tushuntirdi; biz asosan faqat boqib turardik."),
        ("정상에서 바람이 모든 피로를 순식간에 지웠다.", "Eng yuqorida shamol barcha charchoqni birdan o'chirib tashladi."),
        ("우리는 구름이 부츠 아래에서 경주하는 것을 보며 샌드위치를 먹었다.", "Bo'tinkalar ostida poyga qilayotgan bulutlarni kuzatib sendvich yedik."),
        ("내려오기는 쉬웠고 마을의 차는 다시 전설적으로 맛있었다.", "Pasayish oson tuyuldi va qishloq choyi yana afsonaviy ta'm berdi."),
    ],
    8: [
        ("결과 발표의 날은 친구들에 대해서도 가르쳐 주었다.", "Natijalar kuni do'stlarim haqida ham dars berdi."),
        ("루스탐이 정확히 2점 차로 수학을 떨어졌다.", "Rustam matematikadan aynan ikki bal bilan o'tolmadi."),
        ("그는 눈이 다른 말을 하는 동안 용감하게 미소 지었다.", "U jasur tabassum qildi, ko'zlari esa boshqa gapirardi."),
        ("우리는 그가 항의하기도 전에 구출 계획을 세웠다.", "U e'tiroz qilmasdan oldin qutqaruv rejasini uyushtirdik."),
        ("2주 동안 매일 저녁 누군가 그와 함께 공부했다.", "Ikki hafta davomida har kechqurun kimdir uning bilan o'qidi."),
        ("나는 미분을, 딜노자는 적분을 맡았다. 우리는 교대했다.", "Men hosilalarni oldim; Dilnoza integrallarni; almashib ishladik."),
        ("재시험은 6월 마지막 날로 예정되었다.", "Qayta imtihoni iyun oxirgi kuniga belgilandi."),
        ("그날 아침 우리 모두가 그를 건물까지 데려갔다.", "O'sha ertalab hamma binogacha uni kutib bordik."),
        ("딜노자가 메달처럼 초콜릿 바 하나를 그의 손바닥에 쥐여 주었다.", "Dilnoza shokoladni mushtiga mukofotday bosdi."),
        ("그는 90분 후 다시 정상적인 인간처럼 걸으며 돌아왔다.", "U to'qson daqiqadan keyin yana oddiy odamdek yurib qaytdi."),
        ("\"78점.\" 그가 발표했고 거리가 박수를 쳤다.", "'Yetmish sakkiz', deb e'lon qildi va ko'cha olqish chaldi."),
        ("대학교 총장님이 연설에서 우리 스터디 그룹을 언급하셨다.", "Universitet rektorimiz nutqida o'quv guruhimizni tilga oldi."),
        ("총장님은 상부상조를 '진짜 커리큘럼'이라고 부르셨다.", "U o'zaro yordamni 'haqiqiy o'quv dasturi' dedi."),
        ("그 말씀이 피곤한 저녁 2주를 모든 가치 있는 것으로 만들었다.", "Bu jumla charchoqli kechki mashg'ulotlarning ikki haftasini arziydigon qildi."),
        ("이제 루스탐은 매주 목요일 1학년 학생들에게 자원봉사로 과외한다.", "Endi Rustam har payshanba birinchi kurs talabalariga ko'ngilli ravishda saboq beradi."),
        ("그는 가르치는 것은 목격자와 함께하는 학습일 뿐이라고 말한다.", "U o'qitish guvohlar bilan o'rganish ekanini aytdi."),
        ("시험 주간의 내 공황은 이제 오래된 사진처럼 느껴진다.", "Mening imtihon haftasi vahimi endi eski suratga o'xshaydi."),
        ("그것은 내가 된 사람이 아니라 내가 있던 사람을 보여 준다.", "U kim bo'lganimni ko'rsatadi, kim bo'lganimni emas."),
    ],
    9: [
        ("때로 야간 버스는 가져가는 것보다 더 돌려준다.", "Ba'zan tungi avtobus olganidan ko'proq qaytaradi."),
        ("지난달 나는 어떤 노인이 자기 거리를 찾도록 도왔다.", "O'tgan oy keksa odamga o'z ko'chasini topishda yordam berdim."),
        ("그는 겨우 이틀 전에 도시로 이사 온 참이었다.", "U shaharga atigi ikki kun oldin kelgan edi."),
        ("그의 종이 쪽지는 정성스러운 글씨로 적힌 주소를 보여 주었다.", "Qog'oz varag'i diqqat bilan yozilgan manzilni ko'rsatardi."),
        ("운전사는 그를 더 가까이 내려주려고 세 정류장을 돌아갔다.", "Haydovchi uni yaqinroq tushirish uchun uch bekat chetlab o'tdi."),
        ("아무도 반대하지 않았다. 밤 승객들은 조용한 의회를 공유한다.", "Hech kim e'tiroz etmadi; tungi yo'lovchilar sokin parlament bo'lishadi."),
        ("또 어느 저녁, 비가 신부 한 명을 내 정류장에 가두었다.", "Boshqa bir shom yomg'ir kelingni bekatcha qamab qo'ydi."),
        ("흰 드레스, 우산 없이, 나쁜 날씨 타이밍을 향해 웃으면서.", "Oq libos, soyabonsiz, ob-havoning yomon vaqtini kulib."),
        ("여섯 명의 낯선 사람이 여섯 가지 해결책을 동시에 크게 제안했다.", "Olti begona odam bir vaqtda baland ovozda oltita yechim taklif qildi."),
        ("그녀는 깃발처럼 드레스를 지키며 우리와 함께 탔다.", "U biz bilan chiqib ketdi, libosini bayroqday asrab."),
        ("누군가 신랑에게 전화했고 누군가는 휴지를 나눠 주었다.", "Kimdir kuyoviga qo'ng'iroq qildi; kimdir boshqasi sovuq qog'oz berdi."),
        ("그녀의 정류장에 도착할 때쯤 버스 전체가 그녀의 결혼 메뉴를 알게 되었다.", "Uning bekatiga kelib butun avtobus to'y menyusini bildi."),
        ("그녀는 버스가 모퉁이를 돌아 멀어질 때까지 손을 흔들었다.", "Avtobus burilib ketguncha u qo'l silkitib turdi."),
        ("이런 작은 극장들이 매일 밤 요금 한 번으로 공연된다.", "Bunday mayda teatrlar har kecha bitta chipta narxida o'ynaydi."),
        ("나는 이제 야간 버스 등장인물들의 노트를 유지한다.", "Endi tungi avtobus qahramonlari haqidagi daftarchani saqlayman."),
        ("운전사는 그것을 알고 구두로 항목을 추가한다.", "Haydovchi bundan xabardor va og'zaki qatorlar qo'shib beradi."),
        ("그의 최고의 이야기는 자고 있는 아코디언 연주자와 관련되어 있다.", "Eng zo'r hikoyasi uyloqotgan garmonchi haqida."),
        ("언젠가는 그것들을 제대로 전부 적어볼지도 모른다.", "Ehtimol bir kuni ularning hammasini to'g'ri yozaman."),
        ("지금은 그저 타고, 듣고, 사람들이 얼마나 좋은지 기억한다.", "Hozircha men faqat o'tiraman, tinglayman va odamlarning qanchalik yaxshi ekanini eslayman."),
    ],
}
