CONTINUATIONS_AR = {
    0: [
        ("في صباح اليوم التالي، اتّصل بي عزيز مجدّدًا في السابعة تمامًا.", "Ertasi kuni ertalab Aziz yana soat yettida aniq qo'ng'iroq qildi."),
        ("أراد أن يشكر صاحبة المخبز بفطور لائق.", "U nonvoyxonachi ayolga to'g'ri nonushta bilan minnatdorchilik bildirmoqchi edi."),
        ("التقينا عند نفس موقف الحافلة، الذي لا تزال رائحة مطر الأمس تفوح منه.", "Biz xuddi shu bekatda uchrashdik, kechagi yomg'ir hidida."),
        ("بدت المدينة وكأنها غُسلت للتوّ، ببرك فضّية في كلّ مكان.", "Shahar endigina yuvilgandek ko'rindi, hamma joyda kumush suv havzalari."),
        ("في المقهى، طلبنا كوبَي لاتيه وقطعة بسكويت ضخمة.", "Kafeda ikkita latte va bitta ulkan pechene buyurtma qildik."),
        ("فتح عزيز دفتره المليء بحسابات المشروع.", "Aziz biznes hisob-kitoblari bilan to'lgan daftarini ochdi."),
        ("أخافته الأرقام قليلًا، لكنه واجهها بشجاعة.", "Raqamlar uni biroz qo'rqitardi, lekin u ularga jasurlik bilan yuzlashdi."),
        ("ساعدته في مراجعة حساباته مرّتَين، بجدّية تامّة.", "Men uning hisoblarini ikki marta juda jiddiy tekshirib berdim."),
        ("في المقابل، صحّح لفظي الإنجليزي الرديء بلطف.", "Buning evaziga u mening dahshatli inglizcha talaffuzimni muloyimlik bilan tuzatdi."),
        ("راقبنا نادل مسنّ وابتسم وكأنه تذكّر شبابه.", "Keksa ofitsiant bizni kuzatdi va yoshligini eslagondek tabassum qildi."),
        ("قال إنّ الشباب أصحاب الخطط يمنحونه الأمل.", "U rejaga ega yoshlar unga umid berishini aytdi."),
        ("بعد القهوة، مشينا ببطء أمام مبنى السينما القديم.", "Qahvadan keyin eski kinoteatr binosi oldidan sekin o'tdik."),
        ("كان يُعاد طلاؤه أخيرًا بعد عشرين عامًا من الرمادية.", "Yigirma kulrang yildan keyin u nihoyat bo'yalayotgan edi."),
        ("لوّح لنا عمّال على سلالم عالية بمرح.", "Baland narlarda turgan ishchilar bizga quvonch bilan qo'l silkitdi."),
        ("صوّر عزيز كلّ شيء من أجل «ملفّ ذكرياته المستقبلية».", "Aziz hammasini 'kelajak xotiralari papkasi' uchun suratga oldi."),
        ("عبارته الطريفة تلك تجعلني أضحك بصوت عالٍ دائمًا.", "Uning bu kulgili iborasi meni doim baland ovozda kuldiradi."),
        ("بحلول أواخر بعد الظهر، وجدنا أنفسنا بطريقة ما عند رصيف النهر.", "Kechki paytga kelib bir yo'i daryo pristaniga borib qoldik."),
        ("أطعمنا فتات الخبز لبطّ نافد الصبر وتجادلنا حول القوارب.", "Biz sabzavot nonlarini sabrsiz o'rdaklarga berdik va kemalar haqida bahslashdik."),
        ("في طريق العودة، وعدنا أنفسنا بمواصلة استكشاف مدينتنا.", "Uyga qaytayotib, o'z shahrimizni o'rganishda davom etishga va'da berdik."),
        ("بعض عطلات نهاية الأسبوع تساوي أكثر من إجازات باهظة في الخارج.", "Ba'zi dam olish kunlari chet eldagi qimmat ta'tillardan ham qadrli."),
    ],
    1: [
        ("استقبلتني إسطنبول برائحة الملح والكستناء المشوي.", "Istanbul meni tuz va qovurilgan kashtan hidi bilan kutib oldi."),
        ("كانت شقّة عمّي في شارع ضيّق مليء بالقطط.", "Amakimning kvartirasi mushuklarga to'la tor ko'chada joylashgan edi."),
        ("كلّ مساء، كنّا ننزل مشيًا إلى مطعم أسماك صغير.", "Har kechqurun mayda baliq restoraniga pastga tushardik."),
        ("مزح النادلون بشأن لكنتي لكنّهم علّموني عبارات حقيقية.", "Ofitsiantlar talaffuzimni masxara qilishdi, lekin haqiqiy iboralarni o'rgatishdi."),
        ("تعلّمتُ أنّ الأخطاء تجعل الناس يبتسمون وينفتحون.", "Xatolar odamlarni tabassumga keltiradi va ochilishga undaydi deb o'rgandim."),
        ("في صباح ما، استقللنا العبّارة عبر مضيق البوسفور.", "Bir ertalab Bosfor bo'ylab paromga chiqdik."),
        ("تبعت طيور النورس السفينة، تلتقط الخبز من أيدي الركّاب.", "Chag'alalar kemaning ortidan borib, yo'lovchilar qo'lidan non tutdi."),
        ("بدا الوقوف بين قارّتين غير واقعي في البداية.", "Ikki qit'a orasida turish avvaliga g'ayrioddiy tuyuldi."),
        ("على الجانب الآسيوي، شربنا الشاي من أكواب على شكل زهرة التوليب.", "Osiyo tomonida lola shaklidagi stakanda choy ichdik."),
        ("شرح قبطان عجوز كلّ جزيرة وقلعة كنّا نمرّ بها.", "Keksa kapitan o'tayotgan har bir orol va qal'ani tushuntirdi."),
        ("كانت تركيّته بطيئة وواضحة، مثالية للمبتدئين.", "Uning turkchasi sekin va ravon edi, boshlovchilar uchun mukammal."),
        ("فهمتُ نصفها، وخمّنتُ ربعها، وأحببتُها كلّها.", "Yarmisini tushundim, choragini taxmin qildim va hammasini sevdim."),
        ("عند عودتي، سأل الجميع عن الكباب والأسواق.", "Vatanimga qaytgach, hamma shashlik va bozorlar haqida so'radi."),
        ("لكنني ظللتُ أتحدّث عن رحلة العبّارة تلك بدلًا من ذلك.", "Lekin men o'rniga o'sha parom sayohati haqida gapirib berardim."),
        ("هناك شيء في الماء المتحرّك يحوّل الغرباء إلى أصدقاء.", "Harakatlanuvchi suv odamlar nimani do'stlarga aylantirishining sirini bildi."),
        ("عند المطار في طريق العودة، وصلتُ قبل موعدي بثلاث ساعات.", "Uyga qaytayotganda aeroportga uch soat oldin bordim."),
        ("هذه المرّة بدا التفتيش الأمني مألوفًا، شبه روتيني.", "Bu safar xavfsizlik tekshiruvi tanish, deyarli kundalik ishdek tuyuldi."),
        ("اشتريتُ بطاقات بريدية وكتبتها بينما كنتُ أنتظر عند البوّابة.", "Postkartalar sotib oldim va reja kutayotib ularni yozdim."),
        ("عندما أقلعت طائرتنا، ألصقتُ وجهي بالنافذة.", "Samolyotimiz ko'tarilganda yuzimni oynaga bosdim."),
        ("تقلّصت إسطنبول في الأسفل مثل خريطة جميلة مرسومة باليد.", "Istanbul ostda go'zal qo'lda chizilgan xaritadek kichiklashdi."),
        ("شعر الطيران عائدًا بشكل مختلف: أكثر هدوءًا، وأكثر فخرًا، وحنينًا بالفعل.", "Uyga parvoz boshqacha tuyuldi: sokinroq, faxrliroq, allaqachon nostaljiya bilan."),
    ],
    2: [
        ("جاء يوم الثلاثاء التالي بمفاجأة غير متوقّعة في المقهى.", "Keyingi seshanba kuni kafeda kutilmagan syurpriz kutib turardi."),
        ("تذكّرت النادلة طلبي قبل أن أصل إلى المنضدة.", "Ofitsiant men dollar oldiga yetmasdan buyurtmamni esladi."),
        ("سألت بفخر هادئ: «كابتشينو وفطيرة تفّاح؟»", "'Kapuchino va olcha pie?' deb so'radi u sokin iftixor bilan."),
        ("أومأتُ برأسي، وشعرتُ وكأنني أنتمي إلى نادٍ سرّي.", "Men bosh irg'atdim, sirli klubga a'zo bo'lgandek his qildim."),
        ("في ذلك اليوم، جلس شابّ متوتّر بمفرده في الزاوية.", "O'sha kun burchakda asabiylashgan yosh yigit yolg'iz o'tirdi."),
        ("كان يتدرّب على شيء ما بهدوء أمام كاميرا هاتفه.", "U bir narsani telefon kamerasiga jim mashq qilib ko'rardi."),
        ("وضع صانع القهوة شوكولاتة ساخنة بجانبه دون أن يُطلب منه ذلك.", "Barista so'ralmasdan uning yoniga issiq shokolad qo'ydi."),
        ("همست بأنّ الجميع يحتاجون إلى الشجاعة قبل مقابلات العمل.", "U ish suhbatidan oldin hammaga jur'at kerakligini shivirladi."),
        ("عندما غادر أخيرًا، رفع قبضته مثل بطل.", "Nihoyat chiqib ketayotib, u g'olib kabi mushtini ko'tardi."),
        ("صفّق المقهى بأكمله بصمت، محرّكين أيديهم فقط.", "Butun kafe jim qarsak chaldi, faqat qo'llarni harakatga keltirib."),
        ("بعد لحظات، بدأت منافسة شطرنج قديمة بالقرب من النافذة.", "Lahzadan keyin oynaning yaqinida eski shaxmat raqobati boshlandi."),
        ("تجادل متقاعدان حول نقلة من الأسبوع الماضي.", "Ikkita nafaqaxur o'tgan haftadagi yurish haqida bahslashdi."),
        ("دعواني للحكم، رغم أنني بالكاد أعرف الشطرنج.", "Ular menga hakamlikni taklif qilishdi, holbuki men shaxmatni zo'rg'a bilaman."),
        ("أشرتُ عشوائيًا؛ فقبّل أحد اللاعبَين يدي امتنانًا.", "Men tasodifiy ko'rsatdim; bir o'yinchi minnatdorchilik bilan qo'llarimni o'pdi."),
        ("طالب الآخر بمباراة إعادة وطلب كعكة احتفالية.", "Ikkinchisi revansh talab qildi va nishon tortini buyurtma qildi."),
        ("عاد المطر في الخارج، لكن لم يبدُ أحد في عجلة من أمره.", "Tashqarida yomg'ir qaytdi, lekin hech kim shoshilmayotganday edi."),
        ("أصبح المقهى جامعتي لقصص إنسانية صغيرة.", "Kafe mening kichik insoniy hikoyalar universitetiga aylandi."),
        ("بدأتُ أحمل دفتري إلى كلّ مكان لتدوينها.", "Daftarchamni ularni yozib olish uchun hamma joyga olib yuradigan bo'ldim."),
        ("تقول إحدى الصفحات ببساطة: «الناس ألطف ممّا تقوله الأخبار».", "Bir sahifada shunday deyilgan: 'Odamlar yangiliklardagidan ham mehrliroq.'"),
        ("يُثبت كلّ ثلاثاء صحّة تلك الجملة مرارًا وتكرارًا.", "Har seshanba bu jumlaning rostligini yana bir bor tasdiqlaydi."),
    ],
    3: [
        ("جلب أسبوعي الثاني في المكتب مسؤولية حقيقية.", "Ofisdagi ikkinchi haftam haqiqiy mas'uliyat olib keldi."),
        ("سلّمني المدير مشروعًا صغيرًا خاصًّا بي.", "Menejer menga o'zimning kichik loyihani topshirdi."),
        ("ارتجفت يداي قليلًا وأنا أستلم الملفّ.", "Papkani qabul qilayotib qo'llarim biroz titradi."),
        ("كان تقرير آراء عملاء لا يرغب أحد في قراءته.", "Bu hech kim o'qishni istamagan mijoz fikrlari hisoboti edi."),
        ("قرّرتُ أن أجعله مستحيل التجاهل.", "Men uni e'tiborsiz qoldirib bo'lmaydigan qilishga qaror qildim."),
        ("بدلًا من الجداول، رسمتُ مخطّطات بيانية ملوّنة بسيطة.", "Jadvalalar o'rniga men oddiy rangli diagrammalar chizdim."),
        ("علّمني دوستون برنامج العروض التقديمية بصبر.", "Doston ofis taqdimot dasturini sabr bilan o'rgatdi."),
        ("بقينا متأخّرَين مرّتَين، نضحك على كوارث التنسيق التي ارتكبناها.", "Biz ikki marta kechgacha qoldik, formatlash baxtsizliklaridan kulib."),
        ("أحضرت لنا عاملة النظافة بسكويتًا وشايًا قويًا.", "Tozalovchi ayol bizga pechene va kuchli choy olib keldi."),
        ("قالت إنّ العيون المتعبة تحتاج إلى السكّر والهواء النقي.", "U charchagan ko'zlar shakar va toza havoga muhtoj deb aytdi."),
        ("يوم الخميس، عرضتُ نتائجي على الفريق بأكمله.", "Payshanba kuni xulosalarimni butun jamoaga taqdim etdim."),
        ("ارتجف صوتي لمدّة دقيقة واحدة بالضبط، ثم استقرّ.", "Ovozim aynan bir daqiqa titradi, keyin barqarorlashdi."),
        ("طرح الناس أسئلة تمكّنتُ فعلًا من الإجابة عنها بثقة.", "Odamlar men ishonch bilan javob bera oladigan savollar berishdi."),
        ("قال المدير: «أخيرًا، جعل أحدهم البيانات تتكلّم».", "Direktor dedi: 'Nihoyat, kimdir ma'lumotlarni gapira qildi.'"),
        ("تردّدت تلك الجملة في ذهني طوال المساء.", "O'sha jumla butun kechqurun miyamda takrorlandi."),
        ("صباح الجمعة، دعتني زميلة من قسم المحاسبة لتناول الغداء.", "Juma ertalab hisob bo'limidagi hamkasb tushlikka taklif qildi."),
        ("تذكّرت أنها كانت جديدة هنا قبل ثمانية أشهر فقط.", "U sakkiz oy oldin bu yerda yangi bo'lganini esladi."),
        ("كانت نصيحتها بسيطة: احتفظ بملاحظات عن أسماء الجميع.", "Uning maslahati oddiy edi: hamma odamning ismi haqida yozib boring."),
        ("قالت إنّ التفاصيل الصغيرة تبني ثقة كبيرة ببطء.", "Kichik tafsilotlar katta ishonchni sekin quradi dedi u."),
        ("بحلول مساء الجمعة، تمّت الموافقة على مشروعي رسميًا.", "Juma kechqurunga kelib loyham rasman tasdiqlandi."),
        ("احتفلتُ بمفردي ببيتزا رخيصة وسعادة غالية.", "Men arzon pitsa va qimmat baxt bilan yolg'iz nishonladim."),
    ],
    4: [
        ("بعد الغداء في ذلك الأحد، أعلنت جدّتي عن مهمّة خاصّة.", "O'sha shanba tushlikdan keyin Bobomiz maxsus vazifa e'lon qildi."),
        ("كانت دالية العنب خلف البيت الزجاجي بحاجة إلى قطاف عاجل.", "Issiqxona ortidagi uzum tokining shoshilinch terilishi kerak edi."),
        ("ادّعى الجميع انشغالهم إلّا نحن الأحفاد بالطبع.", "Hamma band jadvalini da'vo qildi, albatta biz nabiralar bundan mustasno."),
        ("وزّعت علينا المقصّات والسلال المنسوجة مثل الأوسمة.", "U bizga medallar kabi qaychi va to'qima savatlarni berdi."),
        ("كانت الكروم شامخة وثقيلة بعناقيد أرجوانية.", "Toklar binafsha gullari bilan baland va og'ir turardi."),
        ("تسلّق ابن العمّ بهادير نصف الطريق قبل أن يستطيع أحد إيقافه.", "Amakivachcha Bahodir hech kim to'xtatmasdan yarmigacha chiqib oldi."),
        ("تفحّصت دبّورة أذنه، فاهتزّ السلّم بعنف.", "Bir asalari qulog'ini tekshirdi narlar kuchli silkindi."),
        ("نزل أسرع ممّا صعد، وكرامته تضرّرت قليلًا.", "U chiqqanidan tezroq tushdi, izzati biroz shikastlangan holda."),
        ("راقبت جدّتي كلّ شيء من الأسفل، تضحك من دون صوت.", "Bobomiz hamma narsani pastdan kuzatdi, ovozisiz kuldi."),
        ("ملأنا ثلاث سلال في نحو ساعة من العمل اللزج.", "Yopishqoq ishning bir soati ichida uch savat to'ldirdik."),
        ("غطّت بقع أرجوانية أصابعنا مثل وشوم مؤقّتة.", "Binafsha dog'lar barmoqlarimizni vaqtinchalik tatuka kabi qoplaydi."),
        ("أكلت أصغر بنات العمّ عنبًا أكثر ممّا جمعت، بطبيعة الحال.", "Eng kichkina amakivachcha tabiiyki terganidan ko'p uzum yedi."),
        ("لم تحسب جدّتي شيئًا لكنها شكرت الجميع مرّتَين.", "Bobomiz hech narsani sanamadi lekin hammaga ikki marta rahmat aytdi."),
        ("في المساء، غلت العنب حتى صار عصيرًا داكنًا.", "Kechkirib u uzumlarni qora sharbatga qaynatdi."),
        ("فاحت من البيت كلّه رائحة حلوة مثل مصنع فواكه.", "Butun uy mevazavoddek shirin hid berardi."),
        ("شربنا العصير الدافئ في الشرفة ونحن نشاهد النجوم تظهر.", "Verandada iliq sharbat ichib, yulduzlar paydo bo'lishini kuzatdik."),
        ("أخبرنا جدّي كيف زرع تلك الكروم عام ١٩٨٠.", "Bobo o'sha toklarni 1980-yilda ekkanini gapirdi."),
        ("أربعون عامًا من الصبر تنمو داخل ثمار أرجوانية صغيرة.", "Qirq yillik sabr mayda binafsha mevalar ichida yetilibdi."),
        ("لم يرغب أحد في النوم؛ حتى الهواتف بقيت منسيّة في الداخل.", "Hech kim uxlamoqchi emas edi; hatto telefonlar ham uyda unutilgan edi."),
        ("عندما غادرنا أخيرًا، حملت السيارة عصيرًا وعنبًا وسلامًا.", "Nihoyat ketganda mashina sharbat, uzum va tinchlik olib ketaardi."),
    ],
    5: [
        ("جاء الاختبار الحقيقي الأول للمعطف خلال رحلة مدرسية.", "Paltoning birinchi haqiqiy sinovi maktab sayohati paytida keldi."),
        ("اصطحبنا أربعين طفلًا إلى حديقة الحيوان الشتوية يوم الجمعة.", "Juma kuni qirq bolani qishki zooparkga olib bordik."),
        ("كنتُ الراشد المسؤول، وهو ما لا يزال يفاجئ عائلتي.", "Men mas'ul katta odam edim, bu hali ham oilamni hayron qiladi."),
        ("تساقط الثلج باستمرار منذ الساعة التاسعة صباحًا.", "Qor soat to'qqizdan boshlab uzluksiz tushardi."),
        ("أبقاني المعطف دافئًا طوال ثلاث ساعات بين البطاريق والفشار.", "Palto uch soat pengvinlar va popkorn orasida meni iliq saqladi."),
        ("تبنّتني فتاة صغيرة تُدعى ماليكا بشكل دائم ذلك اليوم.", "Malika ismli mayda qiz o'sha kun menga abadiy biriktirildi."),
        ("أمسكت بكمّي في كلّ مكان مثل ضابطة أمن صغيرة.", "U hamma joyda kurtagimdan mayda xavfsizlik xodimidek ushlab turdi."),
        ("عند حظيرة الذئاب، همست بأكبر سؤال لديها.", "Bo'ri qafasi oldida eng katta savolini shivirladi."),
        ("«هل تشعر الذئاب بالبرد؟» — قلتُ إنّ فراءها يصبح أكثر سماكة.", "'Bo'rilar muzlaydimi?' — Ularning paltolari qalinroq o'sadi dedim."),
        ("فكّرت في الأمر بجدّية وقرّرت أنّ البشر بحاجة إلى المتاجر.", "U buni jiddiy o'ylab odamlarga do'konlar kerak deb qaror qildi."),
        ("خلال الغداء، اكتشفنا أنّ كشك الشوكولاتة الساخنة قد أغلق.", "Tushlik paytida issiq shokolad savati yopilganini aniqladik."),
        ("نظر إليّ عشرون وجهًا خائب الأمل في آنٍ واحد.", "Yigirma xafa yuz birdan menga qaradi."),
        ("فأصبح المعطف قصّة: استبدلتُ النكات بالابتسامات.", "Shuning uchun palto hikoyaga aylandi: hazillarimni tabassumlarga almashtirdim."),
        ("في الحافلة عائدين، نام الجميع خلال دقائق.", "Orqaga qaytayotgan avtobusda hamma bir necha daqiqada uxlab qoldi."),
        ("نامت ماليكا ممسكة بزرّي بقبضة صغيرة واحدة.", "Malika bitta kichik musht bilan tugmamni ushlab uxlab qoldi."),
        ("شكرتني معلّمتهم وقدّمت لي شايًا ساخنًا من ترمسها.", "Ular o'qituvchisi menga rahmat aytdi va termosidan issiq choy taklif qildi."),
        ("في ذلك المساء، نفضتُ الثلج عن المعطف بعناية.", "O'sha kechqurun paltoni qordan ehtiyotkorlik bilan artib oldim."),
        ("كان يحمل بالفعل قصصًا في جيوبه العميقة.", "U allaqachon chuqur cho'ntaklarida hikoyalar olib yurardi."),
        ("وجدت أمي رسمة بالألوان الشمعية مطوية داخل الجيب الأيسر.", "Onam chap cho'ntak ichida bukilgan rangli chizma topdi."),
        ("شخصيّتان عصويّتان تحت خربشة بيضاء كبيرة من الثلج.", "Katta oppoq qor chizig'i ostida ikkita cho'p odamcha."),
        ("وقّعتها ماليكا بحرف M واحد معوجّ وفخور.", "Malika uni faxr bilan bitta qiyshiq M harfi bilan imzolagan edi."),
    ],
    6: [
        ("في الصباح التالي للنهائي، بدا حيّنا مختلفًا.", "Finaldan keyingi ertalab ko'chamiz boshqacha tuyuldi."),
        ("لوّح لنا جيران لم يحيّونا يومًا فجأة من الشرفات.", "Hech qachon salom bermagan qo'shnilar birdan verandalardan qo'l silkitdi."),
        ("كتب أحدهم بالطباشير كلمة «الأبطال» على جدار المصنع القديم أثناء الليل.", "Kimdir kechasi eski zavod devoriga bo'rdan 'CHEMPIONLAR' yozdi."),
        ("جاء جسور إلى التدريب حاملًا كأسًا بلاستيكيًا حقيقيًا.", "Jasur mashg'ulotga haqiqiy plastik kubok olib keldi."),
        ("كان عمّه يملك متجرًا يبيع مستلزمات الحفلات.", "Uncasining to'y buyumlari sotadigan do'koni bor edi."),
        ("ضحكنا لمدّة عشر دقائق ثم تدرّبنا بجدّية على أيّ حال.", "Biz o'n daqiqa kuldik va baribir jiddiy mashq qilishda davom etdik."),
        ("أوضح جسور أنّ الفوز أسهل من البقاء فائزين.", "G'alaba, deb tushuntirdi Jasur, g'olib bo'lib qolishdan osonroq."),
        ("لذا صمّمنا تمارين للتمرير تحت الضغط.", "Shuning uchun bosim ostida pass berish uchun mashqlar tuzdik."),
        ("ضغط لاعبان بينما يهرب ثالث بالكرة.", "Ikkala o'yinchi bosim berganda bittasi to'p bilan qochardi."),
        ("أصبح دوري الوصل الهادئ في الوسط.", "Mening rolim markazdagi sokin bog'lovchiga aylandi."),
        ("لستُ سريعًا، لكنني أرى المساحات مبكّرًا.", "Men tez emasman, lekin bo'sh joylarni erta ko'raman."),
        ("تدرّب ساردور على الركلات الحرّة حتى غروب الشمس كلّ يوم.", "Sardor har kuni quyosh botguncha jarima zarbalari mashq qildi."),
        ("عمل عزيز على إنهاء الهجمات بكلتا قدمَيه، غالبًا اليسرى.", "Aziz ikkala oyog' bilan, ko'pincha chap bilan zarba yakunlash ustida ishladi."),
        ("ابتكر حارس مرمانا رقصات غريبة قبل كلّ تمرين.", "Darvozabonimiz har bir mashqdan oldin g'alati raqslar ixtiro qildi."),
        ("لم يفهمها أحد، لكن لم يسجّل أحد في مرماه أيضًا.", "Hech kim ularni tushunmadi, lekin hech kim unga gol ham urmadi."),
        ("بعد شهر، تحدّانا فريق من حيّ آخر.", "Bir oy o'tib boshqa tumanlik jamoa bizga chiqishdi."),
        ("وصلوا بزيّ موحّد وثقة موحّدة.", "Ular bir xil forma va bir xil ishonch bilan kelishdi."),
        ("ارتدينا نحن قمصانًا غير متناسقة، وإيمانًا مطلقًا بدلًا من ذلك.", "Biz esa nomuvofiq ko'ylaklar va mutlaqo ishonch kiydik."),
        ("انتهت تلك المباراة ثلاثة-واحد، وتكلّمت كرة قدمنا أوّلًا.", "O'sha uchrashuv uch-bir yakunlandi va futbolimiz avval gapirdi."),
        ("بعد ذلك، أكلنا البطّيخ معًا على درج المصنع.", "Keyinchalik zavod narlarida birga tarvuz yedik."),
        ("رفع جسور علبة عصيره وقال: «مرّر قبل أن تراوغ — في الحياة أيضًا».", "Jasur sharbat qutisini ko'tarib dedi: 'Hayotda ham chalg'idan oldin pass ber.'"),
    ],
    7: [
        ("أحببنا الجبال كثيرًا لدرجة أننا عدنا إليها في الخريف.", "Biz tog'larni shu qadar yaxshi ko'rdik kech kuzda qaytib bordik."),
        ("طلى أكتوبر المنحدرات بألوان النحاس والذهب والأحمر الغامق.", "Oktyabr yon bag'irlarni mis, oltin va to'q qizil ranglarga bo'ydi."),
        ("هذه المرّة، حمل الجميع معطف مطر وجوارب احتياطية.", "Bu safar hamma yomg'irpoq va ehtiyot paypoq olib chiqdi."),
        ("التجربة مكلفة، لكنّ دروسها تبقى إلى الأبد.", "Tajriba qimmat turadi, lekin uning darslari abadiy qoladi."),
        ("كان الهواء منعشًا بما يكفي ليعضّ برفق.", "Havo yumshoq tishlashga yetarli darajada tetik edi."),
        ("سار فارس في المقدّمة وكأنه رجل يأخذ ثأرًا شخصيًا من الجاذبية.", "Faris tortishish kuchiga shaxsiy qasos oluvchi odamdek oldinda yurardi."),
        ("جمعت دلنوزا أوراقًا لملفّ مشروعها في علم النبات.", "Dilnoza botanika loyiha papkasi uchun yaproqlar yig'di."),
        ("استطاعت تسمية كلّ شجرة عدا تلك التي صوّرتها.", "U suratga olganlaridan boshqa har bir daraxt nomini biladi."),
        ("في منتصف الطريق، وجدنا مقعدًا خشبيًا يواجه الوادي.", "Yarmiga kelib vodiga qaragan yog'och skameyka topdik."),
        ("نقش أحدهم عبارة «تنفّس هنا» على مسنده منذ سنوات.", "Kimdir yillar oldin orqasiga 'Bu yerda nafas ol' deb o'yma edi."),
        ("فأطعنا التعليمات القديمة وتنفّسنا بعمق.", "Shuning uchun qadimiy ko'rsatmaga bo'ysundik va chuqur nafas oldik."),
        ("بدت القرية تحتنا مثل بيوت لعب متناثرة.", "Ostimizda qishloq tarqoq o'yinchoq uylarga o'xshab ko'rindi."),
        ("تصاعد الدخان من المداخن في أعمدة كسولة تمامًا.", "Mo'rilardan mukammal dangasa ustunlar bo'ylab tutun ko'tarildi."),
        ("حام صقر فوقنا لعدّة دقائق طويلة.", "Bir lochin bizning atrofimizda bir necha uzun daqiqa aylanardi."),
        ("ادّعى جسور أنه كان يتفقّد ما إذا كنّا مستعدّين هذه المرّة.", "Jasur bu safar biz tayyorlanganimizni tekshirayotganini da'vo qildi."),
        ("قرب القمّة، اكتشفنا شلالًا صغيرًا متجمّدًا.", "Cho'qqi yaqinida mayda muzlagan sharshara topdik."),
        ("تعلّق الماء في منتصف سقوطه مثل منحوتة زجاجية، بصبر يفوق التصوّر.", "Suv o'rtada oyna haykali kabi osilgan edi, aql bovar qilmas sabr bilan."),
        ("شرحت دلنوزا الجانب العلمي؛ أمّا نحن فاكتفينا بالتحديق غالبًا.", "Dilnoza ilmiy tomonni tushuntirdi; biz asosan faqat boqib turardik."),
        ("في الأعلى، محا الريح كلّ التعب على الفور.", "Eng yuqorida shamol barcha charchoqni birdan o'chirib tashladi."),
        ("أكلنا الشطائر ونحن نشاهد السحب تتسابق تحت أحذيتنا.", "Bo'tinkalar ostida poyga qilayotgan bulutlarni kuzatib sendvich yedik."),
        ("بدا النزول سهلًا، وكان طعم شاي القرية أسطوريًا مجدّدًا.", "Pasayish oson tuyuldi va qishloq choyi yana afsonaviy ta'm berdi."),
    ],
    8: [
        ("علّمني يوم النتائج أيضًا شيئًا عن أصدقائي.", "Natijalar kuni do'stlarim haqida ham dars berdi."),
        ("رسب رستم في الرياضيات بفارق نقطتَين بالضبط.", "Rustam matematikadan aynan ikki bal bilan o'tolmadi."),
        ("ابتسم بشجاعة بينما كانت عيناه تقولان شيئًا آخر.", "U jasur tabassum qildi, ko'zlari esa boshqa gapirardi."),
        ("نظّمنا خطّة إنقاذ قبل أن يتمكّن من الاعتراض.", "U e'tiroz qilmasdan oldin qutqaruv rejasini uyushtirdik."),
        ("كلّ مساء لمدّة أسبوعين، كان أحدنا يذاكر معه.", "Ikki hafta davomida har kechqurun kimdir uning bilan o'qidi."),
        ("تولّيتُ المشتقّات؛ وتولّت دلنوزا التكاملات؛ وتناوبنا.", "Men hosilalarni oldim; Dilnoza integrallarni; almashib ishladik."),
        ("حُدّد امتحانه الاستدراكي في آخر يوم من يونيو.", "Qayta imtihoni iyun oxirgi kuniga belgilandi."),
        ("في ذلك الصباح، رافقناه جميعًا إلى المبنى مشيًا.", "O'sha ertalab hamma binogacha uni kutib bordik."),
        ("وضعت دلنوزا لوح شوكولاتة في راحة يده مثل وسام.", "Dilnoza shokoladni mushtiga mukofotday bosdi."),
        ("عاد بعد تسعين دقيقة يمشي كإنسان طبيعي من جديد.", "U to'qson daqiqadan keyin yana oddiy odamdek yurib qaytdi."),
        ("أعلن: «ثمانية وسبعون»، فصفّق الشارع.", "'Yetmish sakkiz', deb e'lon qildi va ko'cha olqish chaldi."),
        ("ذكرت رئيسة جامعتنا مجموعتنا الدراسية في خطابها.", "Universitet rektorimiz nutqida o'quv guruhimizni tilga oldi."),
        ("سمّت التعاون المتبادل «المنهج الحقيقي».", "U o'zaro yordamni 'haqiqiy o'quv dasturi' dedi."),
        ("جعلت تلك العبارة أسبوعَين من الأمسيات المتعبة تستحقّ كلّ شيء.", "Bu jumla charchoqli kechki mashg'ulotlarning ikki haftasini arziydigon qildi."),
        ("الآن يقوم رستم بتدريس طلّاب السنة الأولى تطوّعًا كلّ خميس.", "Endi Rustam har payshanba birinchi kurs talabalariga ko'ngilli ravishda saboq beradi."),
        ("يقول إنّ التدريس ليس سوى تعلّم أمام شهود.", "U o'qitish guvohlar bilan o'rganish ekanini aytdi."),
        ("يبدو ذعري في أسبوع الامتحانات الآن مثل صورة قديمة.", "Mening imtihon haftasi vahimi endi eski suratga o'xshaydi."),
        ("تُظهر مَن كنتُ، لا مَن أصبحتُ.", "U kim bo'lganimni ko'rsatadi, kim bo'lganimni emas."),
    ],
    9: [
        ("أحيانًا تعطي الحافلة الليلية أكثر ممّا تأخذ.", "Ba'zan tungi avtobus olganidan ko'proq qaytaradi."),
        ("الشهر الماضي، ساعدتُ رجلًا مسنًّا في العثور على شارعه.", "O'tgan oy keksa odamga o'z ko'chasini topishda yordam berdim."),
        ("كان قد انتقل إلى المدينة قبل يومَين فقط.", "U shaharga atigi ikki kun oldin kelgan edi."),
        ("أظهرت ورقته عنوانًا مكتوبًا بحروف عناية.", "Uning qog'oz varag'i diqqat bilan yozilgan manzilni ko'rsatardi."),
        ("غيّر السائق مساره لثلاث محطّات فقط ليوصله أقرب إلى بيته.", "Haydovchi uni yaqinroq tushirish uchun uch bekat chetlab o'tdi."),
        ("لم يعترض أحد؛ فركّاب الليل يشتركون في برلمان هادئ.", "Hech kim e'tiroz etmadi; tungi yo'lovchilar sokin parlament bo'lishadi."),
        ("في مساء آخر، حاصر المطر عروسًا عند محطّتي.", "Boshqa bir shom yomg'ir kelingni bekatcha qamab qo'ydi."),
        ("بفستان أبيض، من دون مظلّة، تضحك على سوء توقيت الطقس.", "Oq libos, soyabonsiz, ob-havoning yomon vaqtini kulib."),
        ("قدّم ستّة غرباء ستّة حلول في آنٍ واحد وبصوت عالٍ.", "Olti begona odam bir vaqtda baland ovozda oltita yechim taklif qildi."),
        ("صعدت معنا، تحمي فستانها مثل راية.", "U biz bilan chiqib ketdi, libosini bayroqday asrab."),
        ("اتّصل أحدهم بعريسها؛ وقدّم آخر مناديل ورقية.", "Kimdir kuyoviga qo'ng'iroq qildi; kimdir boshqasi sovuq qog'oz berdi."),
        ("بحلول محطّتها، كانت الحافلة بأكملها تعرف قائمة طعام زفافها.", "Uning bekatiga kelib butun avtobus to'y menyusini bildi."),
        ("لوّحت حتى انعطفت الحافلة عند الزاوية بعيدًا.", "Avtobus burilib ketguncha u qo'l silkitib turdi."),
        ("مسارح صغيرة كهذه تُعرض كلّ ليلة بثمن تذكرة واحدة.", "Bunday mayda teatrlar har kecha bitta chipta narxida o'ynaydi."),
        ("أحتفظ الآن بدفتر لشخصيّات الحافلة الليلية.", "Endi tungi avtobus qahramonlari haqidagi daftarchani saqlayman."),
        ("يعرف السائق بأمره ويضيف قصصًا شفهيًا.", "Haydovchi bundan xabardor va og'zaki qatorlar qo'shib beradi."),
        ("أفضل قصصه تتعلّق بعازف أكورديون نائم.", "Eng zo'r hikoyasi uyloqotgan garmonchi haqida."),
        ("ربما في يوم ما سأكتبها جميعًا بشكل صحيح.", "Ehtimol bir kuni ularning hammasini to'g'ri yozaman."),
        ("أمّا الآن، فأنا فقط أركب، وأستمع، وأتذكّر مدى طيبة الناس.", "Hozircha men faqat o'tiraman, tinglayman va odamlarning qanchalik yaxshi ekanini eslayman."),
    ],
}
