CONTINUATIONS = {
    0: [
        ("The next morning, Aziz called me again at seven sharp.", "Ertasi kuni ertalab Aziz yana soat yettida aniq qo'ng'iroq qildi."),
        ("He wanted to thank the bakery lady with proper breakfast.", "U nonvoyxonachi ayolga to'g'ri nonushta bilan minnatdorchilik bildirmoqchi edi."),
        ("We met at the same bus stop, still smelling of yesterday's rain.", "Biz xuddi shu bekatda uchrashdik, kechagi yomg'ir hidida."),
        ("The city looked freshly washed, with silver puddles everywhere.", "Shahar endigina yuvilgandek ko'rindi, hamma joyda kumush suv havzalari."),
        ("At the café, we ordered two lattes and one huge cookie.", "Kafeda ikkita latte va bitta ulkan pechene buyurtma qildik."),
        ("Aziz opened his notebook full of business calculations.", "Aziz biznes hisob-kitoblari bilan to'lgan daftarini ochdi."),
        ("Numbers scared him a little, but he faced them bravely.", "Raqamlar uni biroz qo'rqitardi, lekin u ularga jasurlik bilan yuzlashdi."),
        ("I helped him check his sums twice, very seriously.", "Men uning hisoblarini ikki marta juda jiddiy tekshirib berdim."),
        ("In return, he corrected my terrible English pronunciation gently.", "Buning evaziga u mening dahshatli inglizcha talaffuzimni muloyimlik bilan tuzatdi."),
        ("An elderly waiter watched us and smiled like he remembered youth.", "Keksa ofitsiant bizni kuzatdi va yoshligini eslagondek tabassum qildi."),
        ("He said young people with plans give him hope.", "U rejaga ega yoshlar unga umid berishini aytdi."),
        ("After coffee, we walked slowly past the old cinema building.", "Qahvadan keyin eski kinoteatr binosi oldidan sekin o'tdik."),
        ("It was finally being repainted after twenty grey years.", "Yigirma kulrang yildan keyin u nihoyat bo'yalayotgan edi."),
        ("Workers on tall ladders waved at us cheerfully.", "Baland narlarda turgan ishchilar bizga quvonch bilan qo'l silkitdi."),
        ("Aziz photographed everything for his 'future memories folder'.", "Aziz hammasini 'kelajak xotiralari papkasi' uchun suratga oldi."),
        ("That funny phrase of his always makes me laugh out loud.", "Uning bu kulgili iborasi meni doim baland ovozda kuldiradi."),
        ("By late afternoon, we somehow ended up at the river pier.", "Kechki paytga kelib bir yo'i daryo pristaniga borib qoldik."),
        ("We fed breadcrumbs to impatient ducks and argued about boats.", "Biz sabzavot nonlarini sabrsiz o'rdaklarga berdik va kemalar haqida bahslashdik."),
        ("On the way home, we promised to keep exploring our own city.", "Uyga qaytayotib, o'z shahrimizni o'rganishda davom etishga va'da berdik."),
        ("Some weekends are worth more than expensive vacations abroad.", "Ba'zi dam olish kunlari chet eldagi qimmat ta'tillardan ham qadrli."),
    ],
    1: [
        ("Istanbul welcomed me with the smell of salt and roasted chestnuts.", "Istanbul meni tuz va qovurilgan kashtan hidi bilan kutib oldi."),
        ("My uncle's apartment stood on a narrow street full of cats.", "Amakimning kvartirasi mushuklarga to'la tor ko'chada joylashgan edi."),
        ("Every evening, we walked down to a tiny fish restaurant.", "Har kechqurun mayda baliq restoraniga pastga tushardik."),
        ("The waiters teased my accent but taught me real phrases.", "Ofitsiantlar talaffuzimni masxara qilishdi, lekin haqiqiy iboralarni o'rgatishdi."),
        ("I learned that mistakes make people smile and open up.", "Xatolar odamlarni tabassumga keltiradi va ochilishga undaydi deb o'rgandim."),
        ("One morning, we took the ferry across the Bosphorus.", "Bir ertalab Bosfor bo'ylab paromga chiqdik."),
        ("Seagulls followed the ship, catching bread from passengers' hands.", "Chag'alalar kemaning ortidan borib, yo'lovchilar qo'lidan non tutdi."),
        ("Standing between two continents felt unreal at first.", "Ikki qit'a orasida turish avvaliga g'ayrioddiy tuyuldi."),
        ("On the Asian side, we drank tea from tulip-shaped glasses.", "Osiyo tomonida lola shaklidagi stakanda choy ichdik."),
        ("An old captain explained every island and fortress passing by.", "Keksa kapitan o'tayotgan har bir orol va qal'ani tushuntirdi."),
        ("His Turkish was slow and clear, perfect for beginners.", "Uning turkchasi sekin va ravon edi, boshlovchilar uchun mukammal."),
        ("I understood half, guessed a quarter, and loved all of it.", "Yarmisini tushundim, choragini taxmin qildim va hammasini sevdim."),
        ("Back home, everyone asked about kebabs and markets.", "Vatanimga qaytgach, hamma shashlik va bozorlar haqida so'radi."),
        ("But I kept talking about that ferry ride instead.", "Lekin men o'rniga o'sha parom sayohati haqida gapirib berardim."),
        ("Something about moving water makes strangers into friends.", "Harakatlanuvchi suv odamlar nimani do'stlarga aylantirishining sirini bildi."),
        ("At the airport going home, I arrived three hours early.", "Uyga qaytayotganda aeroportga uch soat oldin bordim."),
        ("This time security felt familiar, almost like routine.", "Bu safar xavfsizlik tekshiruvi tanish, deyarli kundalik ishdek tuyuldi."),
        ("I bought postcards and wrote them while waiting at the gate.", "Postkartalar sotib oldim va reja kutayotib ularni yozdim."),
        ("When our plane lifted off, I pressed my face to the window.", "Samolyotimiz ko'tarilganda yuzimni oynaga bosdim."),
        ("Istanbul shrunk below like a beautiful hand-drawn map.", "Istanbul ostda go'zal qo'lda chizilgan xaritadek kichiklashdi."),
        ("Flying home felt different: calmer, prouder, already nostalgic.", "Uyga parvoz boshqacha tuyuldi: sokinroq, faxrliroq, allaqachon nostaljiya bilan."),
    ],
    2: [
        ("The following Tuesday brought an unexpected surprise at the café.", "Keyingi seshanba kuni kafeda kutilmagan syurpriz kutib turardi."),
        ("The waitress remembered my order before I reached the counter.", "Ofitsiant men dollar oldiga yetmasdan buyurtmamni esladi."),
        ("'Cappuccino and apple pie?' she asked with quiet pride.", "'Kapuchino va olcha pie?' deb so'radi u sokin iftixor bilan."),
        ("I nodded, feeling like I belonged to a secret club.", "Men bosh irg'atdim, sirli klubga a'zo bo'lgandek his qildim."),
        ("That day, a nervous young man sat alone in the corner.", "O'sha kun burchakda asabiylashgan yosh yigit yolg'iz o'tirdi."),
        ("He rehearsed something quietly into his phone camera.", "U bir narsani telefon kamerasiga jim mashq qilib ko'rardi."),
        ("The barista placed hot chocolate beside him without being asked.", "Barista so'ralmasdan uning yoniga issiq shokolad qo'ydi."),
        ("She whispered that everyone needs courage before job interviews.", "U ish suhbatidan oldin hammaga jur'at kerakligini shivirladi."),
        ("When he finally left, he raised his fist like a champion.", "Nihoyat chiqib ketayotib, u g'olib kabi mushtini ko'tardi."),
        ("The whole café clapped silently, moving hands only.", "Butun kafe jim qarsak chaldi, faqat qo'llarni harakatga keltirib."),
        ("Moments later, an old chess rivalry began near the window.", "Lahzadan keyin oynaning yaqinida eski shaxmat raqobati boshlandi."),
        ("Two pensioners argued about a move from last week.", "Ikkita nafaqaxur o'tgan haftadagi yurish haqida bahslashdi."),
        ("They invited me to judge, though I barely know chess.", "Ular menga hakamlikni taklif qilishdi, holbuki men shaxmatni zo'rg'a bilaman."),
        ("I pointed at random; one player kissed my hand gratefully.", "Men tasodifiy ko'rsatdim; bir o'yinchi minnatdorchilik bilan qo'llarimni o'pdi."),
        ("The other demanded a rematch and ordered celebratory cake.", "Ikkinchisi revansh talab qildi va nishon tortini buyurtma qildi."),
        ("Rain returned outside, but nobody seemed in a hurry.", "Tashqarida yomg'ir qaytdi, lekin hech kim shoshilmayotganday edi."),
        ("The café had become my university of small human stories.", "Kafe mening kichik insoniy hikoyalar universitetiga aylandi."),
        ("I started carrying my notebook everywhere to capture them.", "Daftarchamni ularni yozib olish uchun hamma joyga olib yuradigan bo'ldim."),
        ("One page simply says: 'People are kinder than news says.'", "Bir sahifada shunday deyilgan: 'Odamlar yangiliklardagidan ham mehrliroq.'"),
        ("Every Tuesday proves that sentence true again and again.", "Har seshanba bu jumlaning rostligini yana bir bor tasdiqlaydi."),
    ],
    3: [
        ("My second week at the office brought real responsibility.", "Ofisdagi ikkinchi haftam haqiqiy mas'uliyat olib keldi."),
        ("The manager handed me a small project of my own.", "Menejer menga o'zimning kichik loyihani topshirdi."),
        ("My hands trembled slightly as I accepted the folder.", "Papkani qabul qilayotib qo'llarim biroz titradi."),
        ("It was a customer feedback report nobody wanted to read.", "Bu hech kim o'qishni istamagan mijoz fikrlari hisoboti edi."),
        ("I decided to make it impossible to ignore.", "Men uni e'tiborsiz qoldirib bo'lmaydigan qilishga qaror qildim."),
        ("Instead of tables, I drew simple colourful charts.", "Jadvalalar o'rniga men oddiy rangli diagrammalar chizdim."),
        ("Doston taught me the office presentation software patiently.", "Doston ofis taqdimot dasturini sabr bilan o'rgatdi."),
        ("We stayed late twice, laughing at our formatting disasters.", "Biz ikki marta kechgacha qoldik, formatlash baxtsizliklaridan kulib."),
        ("The cleaning lady brought us biscuits and strong tea.", "Tozalovchi ayol bizga pechene va kuchli choy olib keldi."),
        ("She said tired eyes need sugar and fresh air.", "U charchagan ko'zlar shakar va toza havoga muhtoj deb aytdi."),
        ("On Thursday, I presented my findings to the whole team.", "Payshanba kuni xulosalarimni butun jamoaga taqdim etdim."),
        ("My voice shook for exactly one minute, then steadied.", "Ovozim aynan bir daqiqa titradi, keyin barqarorlashdi."),
        ("People asked questions I could actually answer confidently.", "Odamlar men ishonch bilan javob bera oladigan savollar berishdi."),
        ("The director said, 'Finally, someone made data speak.'", "Direktor dedi: 'Nihoyat, kimdir ma'lumotlarni gapira qildi.'"),
        ("That sentence replayed in my head all evening.", "O'sha jumla butun kechqurun miyamda takrorlandi."),
        ("Friday morning, a colleague from accounting invited me for lunch.", "Juma ertalab hisob bo'limidagi hamkasb tushlikka taklif qildi."),
        ("She remembered being new here just eight months ago.", "U sakkiz oy oldin bu yerda yangi bo'lganini esladi."),
        ("Her advice was simple: keep notes about everyone's names.", "Uning maslahati oddiy edi: hamma odamning ismi haqida yozib boring."),
        ("Small details, she said, build big trust slowly.", "Kichik tafsilotlar katta ishonchni sekin quradi dedi u."),
        ("By Friday evening, my project was officially approved.", "Juma kechqurunga kelib loyham rasman tasdiqlandi."),
        ("I celebrated alone with cheap pizza and expensive happiness.", "Men arzon pitsa va qimmat baxt bilan yolg'iz nishonladim."),
    ],
    4: [
        ("After lunch that Sunday, Grandma announced a special mission.", "O'sha shanba tushlikdan keyin Bobomiz maxsus vazifa e'lon qildi."),
        ("The grapevine behind the greenhouse needed urgent harvesting.", "Issiqxona ortidagi uzum tokining shoshilinch terilishi kerak edi."),
        ("Everyone claimed busy schedules except us grandchildren, obviously.", "Hamma band jadvalini da'vo qildi, albatta biz nabiralar bundan mustasno."),
        ("She handed out scissors and woven baskets like medals.", "U bizga medallar kabi qaychi va to'qima savatlarni berdi."),
        ("The vines stood tall and heavy with purple clusters.", "Toklar binafsha gullari bilan baland va og'ir turardi."),
        ("Cousin Bahodir climbed halfway up before anyone could stop him.", "Amakivachcha Bahodir hech kim to'xtatmasdan yarmigacha chiqib oldi."),
        ("A wasp investigated his ear, and the ladder shook violently.", "Bir asalari qulog'ini tekshirdi narlar kuchli silkindi."),
        ("He descended faster than he climbed, dignity slightly damaged.", "U chiqqanidan tezroq tushdi, izzati biroz shikastlangan holda."),
        ("Grandma watched everything from below, laughing without sound.", "Bobomiz hamma narsani pastdan kuzatdi, ovozisiz kuldi."),
        ("We filled three baskets in about an hour of sticky work.", "Yopishqoq ishning bir soati ichida uch savat to'ldirdik."),
        ("Purple stains covered our fingers like temporary tattoos.", "Binafsha dog'lar barmoqlarimizni vaqtinchalik tatuka kabi qoplaydi."),
        ("The youngest cousin ate more grapes than she collected, naturally.", "Eng kichkina amakivachcha tabiiyki terganidan ko'p uzum yedi."),
        ("Grandma counted nothing but thanked everyone twice.", "Bobomiz hech narsani sanamadi lekin hammaga ikki marta rahmat aytdi."),
        ("In the evening, she boiled the grapes into dark juice.", "Kechkirib u uzumlarni qora sharbatga qaynatdi."),
        ("The whole house smelled sweet like a fruit factory.", "Butun uy mevazavoddek shirin hid berardi."),
        ("We drank warm juice on the veranda watching stars appear.", "Verandada iliq sharbat ichib, yulduzlar paydo bo'lishini kuzatdik."),
        ("Grandpa told us how he planted those vines in 1980.", "Bobo o'sha toklarni 1980-yilda ekkanini gapirdi."),
        ("Forty years of patience growing inside small purple fruits.", "Qirq yillik sabr mayda binafsha mevalar ichida yetilibdi."),
        ("Nobody wanted to sleep; even phones stayed forgotten indoors.", "Hech kim uxlamoqchi emas edi; hatto telefonlar ham uyda unutilgan edi."),
        ("When we finally left, the car carried juice, grapes, and peace.", "Nihoyat ketganda mashina sharbat, uzum va tinchlik olib ketaardi."),
    ],
    5: [
        ("The coat's first real test came during a school trip.", "Paltoning birinchi haqiqiy sinovi maktab sayohati paytida keldi."),
        ("We took forty children to the winter zoo on Friday.", "Juma kuni qirq bolani qishki zooparkga olib bordik."),
        ("I was the responsible adult, which still surprises my family.", "Men mas'ul katta odam edim, bu hali ham oilamni hayron qiladi."),
        ("Snow fell steadily from nine in the morning onwards.", "Qor soat to'qqizdan boshlab uzluksiz tushardi."),
        ("The coat kept me warm through three hours of penguins and popcorn.", "Palto uch soat pengvinlar va popkorn orasida meni iliq saqladi."),
        ("A small girl named Malika adopted me permanently that day.", "Malika ismli mayda qiz o'sha kun menga abadiy biriktirildi."),
        ("She held my sleeve everywhere like a tiny security officer.", "U hamma joyda kurtagimdan mayda xavfsizlik xodimidek ushlab turdi."),
        ("At the wolf enclosure, she whispered her biggest question.", "Bo'ri qafasi oldida eng katta savolini shivirladi."),
        ("'Do wolves get cold?' — I said their coats grow thicker.", "'Bo'rilar muzlaydimi?' — Ularning paltolari qalinroq o'sadi dedim."),
        ("She considered this seriously and decided humans need shops.", "U buni jiddiy o'ylob odamlarga do'konlar kerak deb qaror qildi."),
        ("During lunch, we discovered the hot chocolate stand had closed.", "Tushlik paytida issiq shokolad savati yopilganini aniqladik."),
        ("Twenty disappointed faces looked up at me at once.", "Yigirma xafa yuz birdan menga qaradi."),
        ("So the coat became a story: I traded jokes for smiles.", "Shuning uchun palto hikoyaga aylandi: hazillarimni tabassumlarga almashtirdim."),
        ("On the bus back, everyone fell asleep within minutes.", "Orqaga qaytayotgan avtobusda hamma bir necha daqiqada uxlab qoldi."),
        ("Malika slept holding my button with one small fist.", "Malika bitta kichik musht bilan tugmamni ushlab uxlab qoldi."),
        ("Their teacher thanked me and offered hot tea from her flask.", "Ular o'qituvchisi menga rahmat aytdi va termosidan issiq choy taklif qildi."),
        ("That evening, I brushed snow off the coat carefully.", "O'sha kechqurun paltoni qordan ehtiyotkorlik bilan artib oldim."),
        ("It already carried stories in its deep pockets.", "U allaqachon chuqur cho'ntaklarida hikoyalar olib yurardi."),
        ("Mother found a crayon drawing folded inside the left one.", "Onam chap cho'ntak ichida bukilgan rangli chizma topdi."),
        ("Two stick figures under a big white scribble of snow.", "Katta oppoq qor chizig'i ostida ikkita cho'p odamcha."),
        ("Malika had signed it with one proud crooked letter M.", "Malika uni faxr bilan bitta qiyshiq M harfi bilan imzolagan edi."),
    ],
    6: [
        ("The morning after the final, our street felt different.", "Finaldan keyingi ertalab ko'chamiz boshqacha tuyuldi."),
        ("Neighbours who never greeted us suddenly waved from balconies.", "Hech qachon salom bermagan qo'shnilar birdan verandalardan qo'l silkitdi."),
        ("Someone had chalked 'CHAMPIONS' on the old factory wall overnight.", "Kimdir kechasi eski zavod devoriga bo'rdan 'CHEMPIONLAR' yozdi."),
        ("Jasur arrived at practice carrying a real plastic trophy.", "Jasur mashg'ulotga haqiqiy plastik kubok olib keldi."),
        ("His uncle owned a shop that sold party supplies.", "Uncasining to'y buyumlari sotadigan do'koni bor edi."),
        ("We laughed for ten minutes and then trained seriously anyway.", "Biz o'n daqiqa kuldik va baribir jiddiy mashq qilishda davom etdik."),
        ("Winning, Jasur explained, is easier than staying winners.", "G'alaba, deb tushuntirdi Jasur, g'olib bo'lib qolishdan osonroq."),
        ("So we designed drills for passing under pressure.", "Shuning uchun bosim ostida pass berish uchun mashqlar tuzdik."),
        ("Two players pressed while one escaped with the ball.", "Ikkala o'yinchi bosim berganda bittasi to'p bilan qochardi."),
        ("My role became the quiet connector in the middle.", "Mening rolim markazdagi sokin bog'lovchiga aylandi."),
        ("I am not fast, but I see spaces early.", "Men tez emasman, lekin bo'sh joylarni erta ko'raman."),
        ("Sardor practiced free kicks until sunset every day.", "Sardor har kuni quyosh botguncha jarima zarbalari mashq qildi."),
        ("Aziz worked on finishing with both feet, mostly left.", "Aziz ikkala oyog' bilan, ko'pincha chap bilan zarba yakunlash ustida ishladi."),
        ("Our goalkeeper invented strange dances before each drill.", "Darvozabonimiz har bir mashqdan oldin g'alati raqslar ixtiro qildi."),
        ("Nobody understood them, but nobody scored on him either.", "Hech kim ularni tushunmadi, lekin hech kim unga gol ham urmadi."),
        ("A month later, a team from another district challenged us.", "Bir oy o'tib boshqa tumanlik jamoa bizga chiqishdi."),
        ("They arrived in matching kits with matching confidence.", "Ular bir xil forma va bir xil ishonch bilan kelishdi."),
        ("We wore mismatched shirts and absolute belief instead.", "Biz esa nomuvofiq ko'ylaklar va mutlaqo ishonch kiydik."),
        ("That match ended three-one, and our football spoke first.", "O'sha uchrashuv uch-bir yakunlandi va futbolimiz avval gapirdi."),
        ("Afterwards, we ate watermelon on the factory steps together.", "Keyinchalik zavod narlarida birga tarvuz yedik."),
        ("Jasur raised his juice box and said: 'Pass before you dribble — in life too.'", "Jasur sharbat qutisini ko'tarib dedi: 'Hayotda ham chalg'idan oldin pass ber.'"),
    ],
    7: [
        ("We liked the mountains so much that we returned in autumn.", "Biz tog'larni shu qadar yaxshi ko'rdik kech kuzda qaytib bordik."),
        ("October painted the slopes in copper, gold, and deep red.", "Oktyabr yon bag'irlarni mis, oltin va to'q qizil ranglarga bo'ydi."),
        ("This time, everyone carried a raincoat and spare socks.", "Bu safar hamma yomg'irpoq va ehtiyot paypoq olib chiqdi."),
        ("Experience is expensive, but its lessons stay forever.", "Tajriba qimmat turadi, lekin uning darslari abadiy qoladi."),
        ("The air was crisp enough to bite gently.", "Havo yumshoq tishlashga yetarli darajada tetik edi."),
        ("Faris marched ahead like a man with personal revenge against gravity.", "Faris tortishish kuchiga shaxsiy qasos oluvchi odamdek oldinda yurardi."),
        ("Dilnoza collected leaves for her botany project folder.", "Dilnoza botanika loyiha papkasi uchun yaproqlar yig'di."),
        ("She could name every tree except the ones she photographed.", "U suratga olganlaridan boshqa har bir daraxt nomini biladi."),
        ("Halfway up, we found a wooden bench facing the valley.", "Yarmiga kelib vodiga qaragan yog'och skameyka topdik."),
        ("Someone had carved 'Breathe here' into its backrest years ago.", "Kimdir yillar oldin orqasiga 'Bu yerda nafas ol' deb o'yma edi."),
        ("So we obeyed the ancient instruction and breathed deeply.", "Shuning uchun qadimiy ko'rsatmaga bo'ysundik va chuqur nafas oldik."),
        ("Below us, the village looked like scattered toy houses.", "Ostimizda qishloq tarqoq o'yinchoq uylarga o'xshab ko'rindi."),
        ("Smoke rose from chimneys in perfectly lazy columns.", "Mo'rilardan mukammal dangasa ustunlar bo'ylab tutun ko'tarildi."),
        ("A hawk circled above us for several long minutes.", "Bir lochin bizning atrofimizda bir necha uzun daqiqa aylanardi."),
        ("Jasur claimed it was checking whether we were prepared this time.", "Jasur bu safar biz tayyorlanganimizni tekshirayotganini da'vo qildi."),
        ("Near the summit, we discovered a tiny frozen waterfall.", "Cho'qqi yaqinida mayda muzlagan sharshara topdik."),
        ("Water hung mid-fall like glass sculpture, impossibly patient.", "Suv o'rtada oyna haykali kabi osilgan edi, aql bovar qilmas sabr bilan."),
        ("Dilnoza explained the science; we mostly just stared.", "Dilnoza ilmiy tomonni tushuntirdi; biz asosan faqat boqib turardik."),
        ("At the top, wind erased all tiredness instantly.", "Eng yuqorida shamol barcha charchoqni birdan o'chirib tashladi."),
        ("We ate sandwiches watching clouds race beneath our boots.", "Bo'tinkalar ostida poyga qilayotgan bulutlarni kuzatib sendvich yedik."),
        ("Descent felt easy, and the village tea tasted legendary again.", "Pasayish oson tuyuldi va qishloq choyi yana afsonaviy ta'm berdi."),
    ],
    8: [
        ("Results day also taught me about my friends.", "Natijalar kuni do'stlarim haqida ham dars berdi."),
        ("Rustam failed mathematics by exactly two points.", "Rustam matematikadan aynan ikki bal bilan o'tolmadi."),
        ("He smiled bravely while his eyes said something else.", "U jasur tabassum qildi, ko'zlari esa boshqa gapirardi."),
        ("We organized a rescue plan before he could protest.", "U e'tiroz qilmasdan oldin qutqaruv rejasini uyushtirdik."),
        ("Every evening for two weeks, someone studied with him.", "Ikki hafta davomida har kechqurun kimdir uning bilan o'qidi."),
        ("I took derivatives; Dilnoza took integrals; we rotated.", "Men hosilalarni oldim; Dilnoza integrallarni; almashib ishladik."),
        ("His retake was scheduled for the last day of June.", "Qayta imtihoni iyun oxirgi kuniga belgilandi."),
        ("On that morning, we all walked him to the building.", "O'sha ertalab hamma binogacha uni kutib bordik."),
        ("Dilnoza pressed a chocolate bar into his palm like a medal.", "Dilnoza shokoladni mushtiga mukofotday bosdi."),
        ("He returned ninety minutes later walking like a normal human again.", "U to'qson daqiqadan keyin yana oddiy odamdek yurib qaytdi."),
        ("'Seventy-eight,' he announced, and the street applauded.", "'Yetmish sakkiz', deb e'lon qildi va ko'cha olqish chaldi."),
        ("Our university rector mentioned our study group in her speech.", "Universitet rektorimiz nutqida o'quv guruhimizni tilga oldi."),
        ("She called mutual help 'the real curriculum'.", "U o'zaro yordamni 'haqiqiy o'quv dasturi' dedi."),
        ("That phrase made two weeks of tired evenings worth everything.", "Bu jumla charchoqli kechki mashg'ulotlarning ikki haftasini arziydigon qildi."),
        ("Now Rustam tutors first-year students every Thursday voluntarily.", "Endi Rustam har payshanba birinchi kurs talabalariga ko'ngilli ravishda saboq beradi."),
        ("He says teaching is just learning with witnesses.", "U o'qitish guvohlar bilan o'rganish ekanini aytdi."),
        ("My exam-week panic now feels like an old photograph.", "Mening imtihon haftasi vahimi endi eski suratga o'xshaydi."),
        ("It shows who I was, not who I became.", "U kim bo'lganimni ko'rsatadi, kim bo'lganimni emas."),
    ],
    9: [
        ("Sometimes the night bus gives back more than it takes.", "Ba'zan tungi avtobus olganidan ko'proq qaytaradi."),
        ("Last month, I helped an elderly man find his street.", "O'tgan oy keksa odamga o'z ko'chasini topishda yordam berdim."),
        ("He had moved to the city only two days earlier.", "U shaharga atigi ikki kun oldin kelgan edi."),
        ("His paper note showed an address written in careful letters.", "Qog'oz varag'i diqqat bilan yozilgan manzilni ko'rsatardi."),
        ("The driver detoured three stops just to drop him closer.", "Haydovchi uni yaqinroq tushirish uchun uch bekat chetlab o'tdi."),
        ("Nobody objected; night passengers share a quiet parliament.", "Hech kim e'tiroz etmadi; tungi yo'lovchilar sokin parlament bo'lishadi."),
        ("Another evening, rain trapped a bride at my stop.", "Boshqa bir shom yomg'ir kelingni bekatcha qamab qo'ydi."),
        ("White dress, umbrellaless, laughing at the weather's bad timing.", "Oq libos, soyabonsiz, ob-havoning yomon vaqtini kulib."),
        ("Six strangers offered six solutions simultaneously and loudly.", "Olti begona odam bir vaqtda baland ovozda oltita yechim taklif qildi."),
        ("She boarded with us, protecting her dress like a flag.", "U biz bilan chiqib ketdi, libosini bayroqday asrab."),
        ("Someone called her groom; someone else shared tissues.", "Kimdir kuyoviga qo'ng'iroq qildi; kimdir boshqasi sovuq qog'oz berdi."),
        ("By her stop, the whole bus knew her wedding menu.", "Uning bekatiga kelib butun avtobus to'y menyusini bildi."),
        ("She waved until the bus turned the corner away.", "Avtobus burilib ketguncha u qo'l silkitib turdi."),
        ("Small theatres like this play nightly for one fare.", "Bunday mayda teatrlar har kecha bitta chipta narxida o'ynaydi."),
        ("I keep a notebook of night-bus characters now.", "Endi tungi avtobus qahramonlari haqidagi daftarchani saqlayman."),
        ("The driver knows about it and adds entries verbally.", "Haydovchi bundan xabardor va og'zaki qatorlar qo'shib beradi."),
        ("His best story involves a sleeping accordion player.", "Eng zo'r hikoyasi uyloqotgan garmonchi haqida."),
        ("Maybe someday I will write them all down properly.", "Ehtimol bir kuni ularning hammasini to'g'ri yozaman."),
        ("For now, I just ride, listen, and remember how good people are.", "Hozircha men faqat o'tiraman, tinglayman va odamlarning qanchalik yaxshi ekanini eslayman."),
    ],
}
