CONTINUATIONS_TR = {
    0: [
        ("Ertesi sabah Aziz beni yine tam saat yedide aradı.", "Ertasi kuni ertalab Aziz yana soat yettida aniq qo'ng'iroq qildi."),
        ("Fırıncı kadına düzgün bir kahvaltıyla teşekkür etmek istiyordu.", "U nonvoyxonachi ayolga to'g'ri nonushta bilan minnatdorchilik bildirmoqchi edi."),
        ("Hâlâ dünkü yağmurun kokusunu taşıyan aynı otobüs durağında buluştuk.", "Biz xuddi shu bekatda uchrashdik, kechagi yomg'ir hidida."),
        ("Şehir yeni yıkanmış gibi görünüyordu, her yerde gümüş su birikintileri vardı.", "Shahar endigina yuvilgandek ko'rindi, hamma joyda kumush suv havzalari."),
        ("Kafede iki latte ve kocaman bir kurabiye sipariş ettik.", "Kafeda ikkita latte va bitta ulkan pechene buyurtma qildik."),
        ("Aziz iş hesaplarıyla dolu defterini açtı.", "Aziz biznes hisob-kitoblari bilan to'lgan daftarini ochdi."),
        ("Sayılar onu biraz korkutuyordu ama onlarla cesurca yüzleşti.", "Raqamlar uni biroz qo'rqitardi, lekin u ularga jasurlik bilan yuzlashdi."),
        ("Hesaplarını çok ciddi bir şekilde iki kez kontrol etmesine yardım ettim.", "Men uning hisoblarini ikki marta juda jiddiy tekshirib berdim."),
        ("Karşılığında berbat İngilizce telaffuzumu nazikçe düzeltti.", "Buning evaziga u mening dahshatli inglizcha talaffuzimni muloyimlik bilan tuzatdi."),
        ("Yaşlı bir garson bizi izledi ve gençliğini hatırlıyormuş gibi gülümsedi.", "Keksa ofitsiant bizni kuzatdi va yoshligini eslagondek tabassum qildi."),
        ("Planları olan gençlerin ona umut verdiğini söyledi.", "U rejaga ega yoshlar unga umid berishini aytdi."),
        ("Kahveden sonra eski sinema binasının önünden yavaşça yürüdük.", "Qahvadan keyin eski kinoteatr binosi oldidan sekin o'tdik."),
        ("Yirmi gri yılın ardından sonunda yeniden boyanıyordu.", "Yigirma kulrang yildan keyin u nihoyat bo'yalayotgan edi."),
        ("Uzun merdivenlerdeki işçiler bize neşeyle el salladı.", "Baland narlarda turgan ishchilar bizga quvonch bilan qo'l silkitdi."),
        ("Aziz \"gelecek anılar klasörü\" için her şeyin fotoğrafını çekti.", "Aziz hammasini 'kelajak xotiralari papkasi' uchun suratga oldi."),
        ("Onun bu komik lafı beni hep kahkahaya boğar.", "Uning bu kulgili iborasi meni doim baland ovozda kuldiradi."),
        ("Öğleden sonranın geç saatlerinde nasılsa nehir iskelesinde bulduk kendimizi.", "Kechki paytga kelib bir yo'i daryo pristaniga borib qoldik."),
        ("Sabırsız ördeklere ekmek kırıntısı verdik ve tekneler hakkında tartıştık.", "Biz sabzavot nonlarini sabrsiz o'rdaklarga berdik va kemalar haqida bahslashdik."),
        ("Eve dönerken kendi şehrimizi keşfetmeye devam etmeye söz verdik.", "Uyga qaytayotib, o'z shahrimizni o'rganishda davom etishga va'da berdik."),
        ("Bazı hafta sonları, yurt dışındaki pahalı tatillerden daha değerlidir.", "Ba'zi dam olish kunlari chet eldagi qimmat ta'tillardan ham qadrli."),
    ],
    1: [
        ("İstanbul beni tuz ve kavrulmuş kestane kokusuyla karşıladı.", "Istanbul meni tuz va qovurilgan kashtan hidi bilan kutib oldi."),
        ("Amcamın dairesi kedilerle dolu dar bir sokaktaydı.", "Amakimning kvartirasi mushuklarga to'la tor ko'chada joylashgan edi."),
        ("Her akşam küçük bir balık restoranına doğru yürürdük.", "Har kechqurun mayda baliq restoraniga pastga tushardik."),
        ("Garsonlar aksanımla dalga geçti ama bana gerçek ifadeler öğretti.", "Ofitsiantlar talaffuzimni masxara qilishdi, lekin haqiqiy iboralarni o'rgatishdi."),
        ("Hataların insanları gülümsettiğini ve açılmalarını sağladığını öğrendim.", "Xatolar odamlarni tabassumga keltiradi va ochilishga undaydi deb o'rgandim."),
        ("Bir sabah Boğaz'ı geçen vapura bindik.", "Bir ertalab Bosfor bo'ylab paromga chiqdik."),
        ("Martılar gemiyi takip etti, yolcuların elinden ekmek kaptı.", "Chag'alalar kemaning ortidan borib, yo'lovchilar qo'lidan non tutdi."),
        ("İki kıta arasında durmak ilk başta gerçek dışı hissettirdi.", "Ikki qit'a orasida turish avvaliga g'ayrioddiy tuyuldi."),
        ("Anadolu yakasında lale biçimli bardaklardan çay içtik.", "Osiyo tomonida lola shaklidagi stakanda choy ichdik."),
        ("Yaşlı bir kaptan geçtiğimiz her adayı ve kaleyi anlattı.", "Keksa kapitan o'tayotgan har bir orol va qal'ani tushuntirdi."),
        ("Türkçesi yavaş ve netti, yeni başlayanlar için mükemmeldi.", "Uning turkchasi sekin va ravon edi, boshlovchilar uchun mukammal."),
        ("Yarısını anladım, çeyreğini tahmin ettim ve hepsini sevdim.", "Yarmisini tushundim, choragini taxmin qildim va hammasini sevdim."),
        ("Ülkeme dönünce herkes kebaplar ve çarşılar hakkında soru sordu.", "Vatanimga qaytgach, hamma shashlik va bozorlar haqida so'radi."),
        ("Ama ben bunun yerine o vapur yolculuğunu anlatıp durdum.", "Lekin men o'rniga o'sha parom sayohati haqida gapirib berardim."),
        ("Akan suda yabancıları dost yapan bir şey var.", "Harakatlanuvchi suv odamlar nimani do'stlarga aylantirishining sirini bildi."),
        ("Eve dönerken havalimanına üç saat erken vardım.", "Uyga qaytayotganda aeroportga uch soat oldin bordim."),
        ("Bu sefer güvenlik kontrolü tanıdık geldi, neredeyse rutin gibi.", "Bu safar xavfsizlik tekshiruvi tanish, deyarli kundalik ishdek tuyuldi."),
        ("Kartpostal aldım ve kapıda beklerken onları yazdım.", "Postkartalar sotib oldim va reja kutayotib ularni yozdim."),
        ("Uçağımız havalandığında yüzümü camdan pencereye dayadım.", "Samolyotimiz ko'tarilganda yuzimni oynaga bosdim."),
        ("İstanbul aşağıda elle çizilmiş güzel bir harita gibi küçüldü.", "Istanbul ostda go'zal qo'lda chizilgan xaritadek kichiklashdi."),
        ("Eve uçmak farklı hissettirdi: daha sakin, daha gururlu, şimdiden nostaljik.", "Uyga parvoz boshqacha tuyuldi: sokinroq, faxrliroq, allaqachon nostaljiya bilan."),
    ],
    2: [
        ("Bir sonraki salı günü kafede beklenmedik bir sürpriz vardı.", "Keyingi seshanba kuni kafeda kutilmagan syurpriz kutib turardi."),
        ("Garson, tezgaha varmadan önce siparişimi hatırladı.", "Ofitsiant men dollar oldiga yetmasdan buyurtmamni esladi."),
        ("\"Kapuçino ve elmalı turta mı?\" diye sordu, sessiz bir gururla.", "'Kapuchino va olcha pie?' deb so'radi u sokin iftixor bilan."),
        ("Gizli bir kulübe aitmişim gibi hissederek başımı salladım.", "Men bosh irg'atdim, sirli klubga a'zo bo'lgandek his qildim."),
        ("O gün köşede gergin genç bir adam tek başına oturuyordu.", "O'sha kun burchakda asabiylashgan yosh yigit yolg'iz o'tirdi."),
        ("Telefonunun kamerasına sessizce bir şeyler prova ediyordu.", "U bir narsani telefon kamerasiga jim mashq qilib ko'rardi."),
        ("Barista, sormadan yanına sıcak çikolata bıraktı.", "Barista so'ralmasdan uning yoniga issiq shokolad qo'ydi."),
        ("İş görüşmelerinden önce herkesin cesarete ihtiyacı olduğunu fısıldadı.", "U ish suhbatidan oldin hammaga jur'at kerakligini shivirladi."),
        ("Sonunda ayrılırken yumruğunu bir şampiyon gibi kaldırdı.", "Nihoyat chiqib ketayotib, u g'olib kabi mushtini ko'tardi."),
        ("Bütün kafe sessizce alkışladı, sadece elleri hareket ettirerek.", "Butun kafe jim qarsak chaldi, faqat qo'llarni harakatga keltirib."),
        ("Kısa süre sonra pencerenin yanında eski bir satranç rekabeti başladı.", "Lahzadan keyin oynaning yaqinida eski shaxmat raqobati boshlandi."),
        ("İki emekli geçen haftaki bir hamle yüzünden tartıştı.", "Ikkita nafaqaxur o'tgan haftadagi yurish haqida bahslashdi."),
        ("Satranç hakkında neredeyse hiçbir şey bilmesem de beni hakemliğe davet ettiler.", "Ular menga hakamlikni taklif qilishdi, holbuki men shaxmatni zo'rg'a bilaman."),
        ("Rastgele bir yer gösterdim; bir oyuncu minnetle elimi öptü.", "Men tasodifiy ko'rsatdim; bir o'yinchi minnatdorchilik bilan qo'llarimni o'pdi."),
        ("Diğeri rövanş istedi ve kutlama pastası sipariş etti.", "Ikkinchisi revansh talab qildi va nishon tortini buyurtma qildi."),
        ("Dışarıda yağmur yeniden başladı ama kimse acele ediyormuş gibi görünmüyordu.", "Tashqarida yomg'ir qaytdi, lekin hech kim shoshilmayotganday edi."),
        ("Kafe, küçük insan hikayelerinin üniversitesi haline gelmişti benim için.", "Kafe mening kichik insoniy hikoyalar universitetiga aylandi."),
        ("Onları not almak için defterimi her yere taşımaya başladım.", "Daftarchamni ularni yozib olish uchun hamma joyga olib yuradigan bo'ldim."),
        ("Bir sayfada sadece şöyle yazıyor: \"İnsanlar haberlerin söylediğinden daha nazik.\"", "Bir sahifada shunday deyilgan: 'Odamlar yangiliklardagidan ham mehrliroq.'"),
        ("Her salı bu cümlenin doğruluğunu tekrar tekrar kanıtlıyor.", "Har seshanba bu jumlaning rostligini yana bir bor tasdiqlaydi."),
    ],
    3: [
        ("Ofisteki ikinci haftam gerçek bir sorumluluk getirdi.", "Ofisdagi ikkinchi haftam haqiqiy mas'uliyat olib keldi."),
        ("Yönetici bana kendi küçük projemi verdi.", "Menejer menga o'zimning kichik loyihani topshirdi."),
        ("Dosyayı alırken ellerim hafifçe titredi.", "Papkani qabul qilayotib qo'llarim biroz titradi."),
        ("Kimsenin okumak istemediği bir müşteri geri bildirim raporuydu.", "Bu hech kim o'qishni istamagan mijoz fikrlari hisoboti edi."),
        ("Onu görmezden gelinmesi imkansız hale getirmeye karar verdim.", "Men uni e'tiborsiz qoldirib bo'lmaydigan qilishga qaror qildim."),
        ("Tablolar yerine basit ve renkli grafikler çizdim.", "Jadvalalar o'rniga men oddiy rangli diagrammalar chizdim."),
        ("Doston bana ofis sunum yazılımını sabırla öğretti.", "Doston ofis taqdimot dasturini sabr bilan o'rgatdi."),
        ("İki kez geç saatlere kadar kaldık, biçimlendirme felaketlerimize gülerek.", "Biz ikki marta kechgacha qoldik, formatlash baxtsizliklaridan kulib."),
        ("Temizlikçi kadın bize bisküvi ve sert bir çay getirdi.", "Tozalovchi ayol bizga pechene va kuchli choy olib keldi."),
        ("Yorgun gözlerin şekere ve temiz havaya ihtiyacı olduğunu söyledi.", "U charchagan ko'zlar shakar va toza havoga muhtoj deb aytdi."),
        ("Perşembe günü bulgularımı tüm ekibe sundum.", "Payshanba kuni xulosalarimni butun jamoaga taqdim etdim."),
        ("Sesim tam bir dakika titredi, sonra sakinleşti.", "Ovozim aynan bir daqiqa titradi, keyin barqarorlashdi."),
        ("İnsanlar gerçekten güvenle cevaplayabildiğim sorular sordu.", "Odamlar men ishonch bilan javob bera oladigan savollar berishdi."),
        ("Direktör, \"Sonunda biri verileri konuşturdu\" dedi.", "Direktor dedi: 'Nihoyat, kimdir ma'lumotlarni gapira qildi.'"),
        ("O cümle bütün akşam kafamda tekrar tekrar çaldı.", "O'sha jumla butun kechqurun miyamda takrorlandi."),
        ("Cuma sabahı muhasebeden bir meslektaşım beni öğle yemeğine davet etti.", "Juma ertalab hisob bo'limidagi hamkasb tushlikka taklif qildi."),
        ("Sadece sekiz ay önce burada yeni olduğunu hatırladı.", "U sakkiz oy oldin bu yerda yangi bo'lganini esladi."),
        ("Tavsiyesi basitti: herkesin isimleri hakkında notlar tut.", "Uning maslahati oddiy edi: hamma odamning ismi haqida yozib boring."),
        ("Küçük ayrıntılar, dedi, büyük güveni yavaş yavaş inşa eder.", "Kichik tafsilotlar katta ishonchni sekin quradi dedi u."),
        ("Cuma akşamına kadar projem resmen onaylandı.", "Juma kechqurunga kelib loyham rasman tasdiqlandi."),
        ("Ucuz pizza ve pahalı bir mutlulukla tek başıma kutladım.", "Men arzon pitsa va qimmat baxt bilan yolg'iz nishonladim."),
    ],
    4: [
        ("O pazar öğle yemeğinden sonra büyükannem özel bir görev ilan etti.", "O'sha shanba tushlikdan keyin Bobomiz maxsus vazifa e'lon qildi."),
        ("Serayı arkasındaki asma acilen hasat edilmeliydi.", "Issiqxona ortidagi uzum tokining shoshilinch terilishi kerak edi."),
        ("Tabii ki torunlar hariç herkes yoğun bir programı olduğunu iddia etti.", "Hamma band jadvalini da'vo qildi, albatta biz nabiralar bundan mustasno."),
        ("Bize makas ve örme sepetleri madalya gibi dağıttı.", "U bizga medallar kabi qaychi va to'qima savatlarni berdi."),
        ("Asmalar mor salkımlarla ağırlaşmış, uzun boylu duruyordu.", "Toklar binafsha gullari bilan baland va og'ir turardi."),
        ("Kuzenimiz Bahodir kimse onu durduramadan yarı yola kadar tırmandı.", "Amakivachcha Bahodir hech kim to'xtatmasdan yarmigacha chiqib oldi."),
        ("Bir eşek arısı kulağını incelemeye başladı ve merdiven şiddetle sallandı.", "Bir asalari qulog'ini tekshirdi narlar kuchli silkindi."),
        ("Çıktığından daha hızlı indi, onuru biraz zedelenmiş halde.", "U chiqqanidan tezroq tushdi, izzati biroz shikastlangan holda."),
        ("Büyükannem her şeyi aşağıdan izledi, sessizce gülerek.", "Bobomiz hamma narsani pastdan kuzatdi, ovozisiz kuldi."),
        ("Yaklaşık bir saat süren yapışkan bir çalışmayla üç sepet doldurduk.", "Yopishqoq ishning bir soati ichida uch savat to'ldirdik."),
        ("Mor lekeler parmaklarımızı geçici dövmeler gibi kaplamıştı.", "Binafsha dog'lar barmoqlarimizni vaqtinchalik tatuka kabi qoplaydi."),
        ("En küçük kuzenimiz doğal olarak topladığından daha fazla üzüm yedi.", "Eng kichkina amakivachcha tabiiyki terganidan ko'p uzum yedi."),
        ("Büyükannem hiçbir şeyi saymadı ama herkese iki kez teşekkür etti.", "Bobomiz hech narsani sanamadi lekin hammaga ikki marta rahmat aytdi."),
        ("Akşam üzümleri kaynatıp koyu bir suya dönüştürdü.", "Kechkirib u uzumlarni qora sharbatga qaynatdi."),
        ("Bütün ev bir meyve fabrikası gibi tatlı kokuyordu.", "Butun uy mevazavoddek shirin hid berardi."),
        ("Verandada yıldızların belirişini izlerken sıcak suyu içtik.", "Verandada iliq sharbat ichib, yulduzlar paydo bo'lishini kuzatdik."),
        ("Büyükbabam o asmaları 1980'de nasıl diktiğini anlattı.", "Bobo o'sha toklarni 1980-yilda ekkanini gapirdi."),
        ("Küçük mor meyvelerin içinde kırk yıllık bir sabır büyüyordu.", "Qirq yillik sabr mayda binafsha mevalar ichida yetilibdi."),
        ("Kimse uyumak istemedi; telefonlar bile içeride unutulmuş halde kaldı.", "Hech kim uxlamoqchi emas edi; hatto telefonlar ham uyda unutilgan edi."),
        ("Sonunda ayrıldığımızda araba üzüm suyu, üzüm ve huzur taşıyordu.", "Nihoyat ketganda mashina sharbat, uzum va tinchlik olib ketaardi."),
    ],
    5: [
        ("Montun ilk gerçek sınavı bir okul gezisinde geldi.", "Paltoning birinchi haqiqiy sinovi maktab sayohati paytida keldi."),
        ("Cuma günü kırk çocuğu kış hayvanat bahçesine götürdük.", "Juma kuni qirq bolani qishki zooparkga olib bordik."),
        ("Sorumlu yetişkin bendim, bu hâlâ ailemi şaşırtıyor.", "Men mas'ul katta odam edim, bu hali ham oilamni hayron qiladi."),
        ("Kar saat dokuzdan itibaren durmadan yağdı.", "Qor soat to'qqizdan boshlab uzluksiz tushardi."),
        ("Mont, penguenler ve patlamış mısırla geçen üç saat boyunca beni sıcak tuttu.", "Palto uch soat pengvinlar va popkorn orasida meni iliq saqladi."),
        ("Malika adında küçük bir kız o gün beni kalıcı olarak sahiplendi.", "Malika ismli mayda qiz o'sha kun menga abadiy biriktirildi."),
        ("Her yerde kolumu minik bir güvenlik görevlisi gibi tuttu.", "U hamma joyda kurtagimdan mayda xavfsizlik xodimidek ushlab turdi."),
        ("Kurt kafesinin önünde en büyük sorusunu fısıldadı.", "Bo'ri qafasi oldida eng katta savolini shivirladi."),
        ("\"Kurtlar üşür mü?\" — Kürklerinin daha kalınlaştığını söyledim.", "'Bo'rilar muzlaydimi?' — Ularning paltolari qalinroq o'sadi dedim."),
        ("Bunu ciddiyetle düşündü ve insanların dükkanlara ihtiyacı olduğuna karar verdi.", "U buni jiddiy o'ylob odamlarga do'konlar kerak deb qaror qildi."),
        ("Öğle yemeği sırasında sıcak çikolata standının kapandığını fark ettik.", "Tushlik paytida issiq shokolad savati yopilganini aniqladik."),
        ("Yirmi hayal kırıklığına uğramış yüz aynı anda bana baktı.", "Yigirma xafa yuz birdan menga qaradi."),
        ("Böylece mont bir hikayeye dönüştü: şakaları gülümsemelerle takas ettim.", "Shuning uchun palto hikoyaga aylandi: hazillarimni tabassumlarga almashtirdim."),
        ("Dönüş otobüsünde herkes dakikalar içinde uykuya daldı.", "Orqaga qaytayotgan avtobusda hamma bir necha daqiqada uxlab qoldi."),
        ("Malika küçük bir yumrukla düğmemi tutarak uyudu.", "Malika bitta kichik musht bilan tugmamni ushlab uxlab qoldi."),
        ("Öğretmenleri bana teşekkür etti ve termosundan sıcak çay ikram etti.", "Ular o'qituvchisi menga rahmat aytdi va termosidan issiq choy taklif qildi."),
        ("O akşam montun üzerindeki karı dikkatle fırçaladım.", "O'sha kechqurun paltoni qordan ehtiyotkorlik bilan artib oldim."),
        ("Derin cepleri zaten hikayeler taşıyordu.", "U allaqachon chuqur cho'ntaklarida hikoyalar olib yurardi."),
        ("Annem sol cebin içinde katlanmış bir pastel boya çizimi buldu.", "Onam chap cho'ntak ichida bukilgan rangli chizma topdi."),
        ("Büyük beyaz bir kar karalamasının altında iki çöp adam.", "Katta oppoq qor chizig'i ostida ikkita cho'p odamcha."),
        ("Malika onu gururla, eğri büğrü bir M harfiyle imzalamıştı.", "Malika uni faxr bilan bitta qiyshiq M harfi bilan imzolagan edi."),
    ],
    6: [
        ("Finalden sonraki sabah sokağımız farklı hissettirdi.", "Finaldan keyingi ertalab ko'chamiz boshqacha tuyuldi."),
        ("Bize hiç selam vermeyen komşular birden balkonlardan el salladı.", "Hech qachon salom bermagan qo'shnilar birdan verandalardan qo'l silkitdi."),
        ("Biri gece boyunca eski fabrika duvarına tebeşirle \"ŞAMPİYONLAR\" yazmıştı.", "Kimdir kechasi eski zavod devoriga bo'rdan 'CHEMPIONLAR' yozdi."),
        ("Jasur antrenmana gerçek bir plastik kupa taşıyarak geldi.", "Jasur mashg'ulotga haqiqiy plastik kubok olib keldi."),
        ("Amcasının parti malzemeleri satan bir dükkanı vardı.", "Uncasining to'y buyumlari sotadigan do'koni bor edi."),
        ("On dakika güldük ve yine de ciddi ciddi antrenman yaptık.", "Biz o'n daqiqa kuldik va baribir jiddiy mashq qilishda davom etdik."),
        ("Jasur, kazanmanın kazanan kalmaktan daha kolay olduğunu anlattı.", "G'alaba, deb tushuntirdi Jasur, g'olib bo'lib qolishdan osonroq."),
        ("Bu yüzden baskı altında pas verme egzersizleri tasarladık.", "Shuning uchun bosim ostida pass berish uchun mashqlar tuzdik."),
        ("İki oyuncu baskı yaparken biri topla kaçıyordu.", "Ikkala o'yinchi bosim berganda bittasi to'p bilan qochardi."),
        ("Benim rolüm ortadaki sessiz bağlayıcı olmaktı.", "Mening rolim markazdagi sokin bog'lovchiga aylandi."),
        ("Hızlı değilim ama boşlukları erken görürüm.", "Men tez emasman, lekin bo'sh joylarni erta ko'raman."),
        ("Sardor her gün gün batımına kadar serbest vuruş çalıştı.", "Sardor har kuni quyosh botguncha jarima zarbalari mashq qildi."),
        ("Aziz her iki ayakla, çoğunlukla solla bitirmek üzerinde çalıştı.", "Aziz ikkala oyog' bilan, ko'pincha chap bilan zarba yakunlash ustida ishladi."),
        ("Kalecimiz her egzersizden önce garip danslar icat etti.", "Darvozabonimiz har bir mashqdan oldin g'alati raqslar ixtiro qildi."),
        ("Kimse onları anlamadı ama ona gol de atamadı.", "Hech kim ularni tushunmadi, lekin hech kim unga gol ham urmadi."),
        ("Bir ay sonra başka bir bölgeden bir takım bize meydan okudu.", "Bir oy o'tib boshqa tumanlik jamoa bizga chiqishdi."),
        ("Uyumlu formalarla, uyumlu bir özgüvenle geldiler.", "Ular bir xil forma va bir xil ishonch bilan kelishdi."),
        ("Biz ise uyumsuz forma ve tam bir inançla oynadık.", "Biz esa nomuvofiq ko'ylaklar va mutlaqo ishonch kiydik."),
        ("O maç üç bir bitti ve futbolumuz önce konuştu.", "O'sha uchrashuv uch-bir yakunlandi va futbolimiz avval gapirdi."),
        ("Sonrasında fabrika merdivenlerinde birlikte karpuz yedik.", "Keyinchalik zavod narlarida birga tarvuz yedik."),
        ("Jasur meyve suyu kutusunu kaldırıp \"Çalım atmadan önce pas ver — hayatta da\" dedi.", "Jasur sharbat qutisini ko'tarib dedi: 'Hayotda ham chalg'idan oldin pass ber.'"),
    ],
    7: [
        ("Dağları o kadar çok sevdik ki sonbaharda tekrar döndük.", "Biz tog'larni shu qadar yaxshi ko'rdik kech kuzda qaytib bordik."),
        ("Ekim yamaçları bakır, altın ve koyu kırmızıya boyadı.", "Oktyabr yon bag'irlarni mis, oltin va to'q qizil ranglarga bo'ydi."),
        ("Bu sefer herkes bir yağmurluk ve yedek çorap taşıdı.", "Bu safar hamma yomg'irpoq va ehtiyot paypoq olib chiqdi."),
        ("Tecrübe pahalıdır ama dersleri sonsuza kadar kalır.", "Tajriba qimmat turadi, lekin uning darslari abadiy qoladi."),
        ("Hava, hafifçe ısırabilecek kadar taze ve keskindi.", "Havo yumshoq tishlashga yetarli darajada tetik edi."),
        ("Faris, yerçekimine karşı kişisel bir intikam peşindeymiş gibi öne doğru yürüdü.", "Faris tortishish kuchiga shaxsiy qasos oluvchi odamdek oldinda yurardi."),
        ("Dilnoza botanik proje dosyası için yapraklar topladı.", "Dilnoza botanika loyiha papkasi uchun yaproqlar yig'di."),
        ("Fotoğrafını çektiği ağaçlar hariç her ağacın adını biliyordu.", "U suratga olganlaridan boshqa har bir daraxt nomini biladi."),
        ("Yarı yolda vadiye bakan ahşap bir bank bulduk.", "Yarmiga kelib vodiga qaragan yog'och skameyka topdik."),
        ("Biri yıllar önce arkalığına \"Burada nefes al\" yazmıştı.", "Kimdir yillar oldin orqasiga 'Bu yerda nafas ol' deb o'yma edi."),
        ("Bu yüzden bu eski talimata uyduk ve derin bir nefes aldık.", "Shuning uchun qadimiy ko'rsatmaga bo'ysundik va chuqur nafas oldik."),
        ("Altımızda köy, dağılmış oyuncak evler gibi görünüyordu.", "Ostimizda qishloq tarqoq o'yinchoq uylarga o'xshab ko'rindi."),
        ("Bacalardan tembel tembel dumanlar yükseliyordu.", "Mo'rilardan mukammal dangasa ustunlar bo'ylab tutun ko'tarildi."),
        ("Bir şahin başımızın üzerinde uzun dakikalar boyunca daireler çizdi.", "Bir lochin bizning atrofimizda bir necha uzun daqiqa aylanardi."),
        ("Jasur, bu sefer hazır olup olmadığımızı kontrol ettiğini iddia etti.", "Jasur bu safar biz tayyorlanganimizni tekshirayotganini da'vo qildi."),
        ("Zirveye yakın minik, donmuş bir şelale keşfettik.", "Cho'qqi yaqinida mayda muzlagan sharshara topdik."),
        ("Su, cam bir heykel gibi düşerken donup kalmış, inanılmaz sabırlıydı.", "Suv o'rtada oyna haykali kabi osilgan edi, aql bovar qilmas sabr bilan."),
        ("Dilnoza bilimsel açıklamayı yaptı; biz ise çoğunlukla sadece baktık.", "Dilnoza ilmiy tomonni tushuntirdi; biz asosan faqat boqib turardik."),
        ("Zirvede rüzgar tüm yorgunluğu anında sildi.", "Eng yuqorida shamol barcha charchoqni birdan o'chirib tashladi."),
        ("Botlarımızın altında yarışan bulutları izleyerek sandviç yedik.", "Bo'tinkalar ostida poyga qilayotgan bulutlarni kuzatib sendvich yedik."),
        ("İniş kolay hissettirdi ve köy çayı yine efsanevi bir tat verdi.", "Pasayish oson tuyuldi va qishloq choyi yana afsonaviy ta'm berdi."),
    ],
    8: [
        ("Sonuçların açıklandığı gün bana arkadaşlarım hakkında da bir şeyler öğretti.", "Natijalar kuni do'stlarim haqida ham dars berdi."),
        ("Rustam matematikten tam iki puanla kaldı.", "Rustam matematikadan aynan ikki bal bilan o'tolmadi."),
        ("Cesurca gülümsedi ama gözleri başka bir şey söylüyordu.", "U jasur tabassum qildi, ko'zlari esa boshqa gapirardi."),
        ("O itiraz edemeden bir kurtarma planı hazırladık.", "U e'tiroz qilmasdan oldin qutqaruv rejasini uyushtirdik."),
        ("İki hafta boyunca her akşam biri onunla birlikte çalıştı.", "Ikki hafta davomida har kechqurun kimdir uning bilan o'qidi."),
        ("Ben türevleri üstlendim; Dilnoza integralleri; sırayla değiştik.", "Men hosilalarni oldim; Dilnoza integrallarni; almashib ishladik."),
        ("Bütünleme sınavı haziranın son gününe ayarlanmıştı.", "Qayta imtihoni iyun oxirgi kuniga belgilandi."),
        ("O sabah hep birlikte onu binaya kadar geçirdik.", "O'sha ertalab hamma binogacha uni kutib bordik."),
        ("Dilnoza bir çikolatayı avucuna madalya gibi bastırdı.", "Dilnoza shokoladni mushtiga mukofotday bosdi."),
        ("Doksan dakika sonra tekrar normal bir insan gibi yürüyerek geri döndü.", "U to'qson daqiqadan keyin yana oddiy odamdek yurib qaytdi."),
        ("\"Yetmiş sekiz\" diye ilan etti ve sokak alkışladı.", "'Yetmish sakkiz', deb e'lon qildi va ko'cha olqish chaldi."),
        ("Üniversite rektörümüz konuşmasında çalışma grubumuzdan bahsetti.", "Universitet rektorimiz nutqida o'quv guruhimizni tilga oldi."),
        ("Karşılıklı yardımlaşmayı \"gerçek müfredat\" olarak adlandırdı.", "U o'zaro yordamni 'haqiqiy o'quv dasturi' dedi."),
        ("Bu söz, iki haftalık yorgun akşamları her şeye değer kıldı.", "Bu jumla charchoqli kechki mashg'ulotlarning ikki haftasini arziydigon qildi."),
        ("Şimdi Rustam her perşembe gönüllü olarak birinci sınıf öğrencilerine ders veriyor.", "Endi Rustam har payshanba birinchi kurs talabalariga ko'ngilli ravishda saboq beradi."),
        ("Öğretmenin, tanıklar önünde öğrenmek olduğunu söylüyor.", "U o'qitish guvohlar bilan o'rganish ekanini aytdi."),
        ("Sınav haftasındaki panik şimdi eski bir fotoğraf gibi hissettiriyor.", "Mening imtihon haftasi vahimi endi eski suratga o'xshaydi."),
        ("Kim olduğumu gösteriyor, kim olduğumu değil.", "U kim bo'lganimni ko'rsatadi, kim bo'lganimni emas."),
    ],
    9: [
        ("Bazen gece otobüsü aldığından daha fazlasını geri verir.", "Ba'zan tungi avtobus olganidan ko'proq qaytaradi."),
        ("Geçen ay yaşlı bir adamın kendi sokağını bulmasına yardım ettim.", "O'tgan oy keksa odamga o'z ko'chasini topishda yordam berdim."),
        ("Şehre sadece iki gün önce taşınmıştı.", "U shaharga atigi ikki kun oldin kelgan edi."),
        ("Kağıdındaki notta özenle yazılmış bir adres vardı.", "Qog'oz varag'i diqqat bilan yozilgan manzilni ko'rsatardi."),
        ("Şoför onu daha yakına bırakabilmek için üç durak sapma yaptı.", "Haydovchi uni yaqinroq tushirish uchun uch bekat chetlab o'tdi."),
        ("Kimse itiraz etmedi; gece yolcuları sessiz bir meclis gibidir.", "Hech kim e'tiroz etmadi; tungi yo'lovchilar sokin parlament bo'lishadi."),
        ("Başka bir akşam, yağmur durağımda bir gelini mahsur bıraktı.", "Boshqa bir shom yomg'ir kelingni bekatcha qamab qo'ydi."),
        ("Beyaz elbise, şemsiyesiz, havanın kötü zamanlamasına gülerek.", "Oq libos, soyabonsiz, ob-havoning yomon vaqtini kulib."),
        ("Altı yabancı aynı anda yüksek sesle altı çözüm önerdi.", "Olti begona odam bir vaqtda baland ovozda oltita yechim taklif qildi."),
        ("Elbisesini bir bayrak gibi koruyarak bizimle bindi.", "U biz bilan chiqib ketdi, libosini bayroqday asrab."),
        ("Biri damadını aradı; bir başkası mendil verdi.", "Kimdir kuyoviga qo'ng'iroq qildi; kimdir boshqasi sovuq qog'oz berdi."),
        ("Durağına vardığında bütün otobüs düğün menüsünü biliyordu.", "Uning bekatiga kelib butun avtobus to'y menyusini bildi."),
        ("Otobüs köşeyi dönüp gözden kaybolana kadar el salladı.", "Avtobus burilib ketguncha u qo'l silkitib turdi."),
        ("Bunun gibi küçük tiyatrolar her gece tek bir bilet ücretine oynanır.", "Bunday mayda teatrlar har kecha bitta chipta narxida o'ynaydi."),
        ("Artık gece otobüsü karakterlerinin defterini tutuyorum.", "Endi tungi avtobus qahramonlari haqidagi daftarchani saqlayman."),
        ("Şoför bundan haberdar ve sözlü olarak kayıtlar ekliyor.", "Haydovchi bundan xabardor va og'zaki qatorlar qo'shib beradi."),
        ("En iyi hikayesi uyuyan bir akordeoncuyla ilgili.", "Eng zo'r hikoyasi uyloqotgan garmonchi haqida."),
        ("Belki bir gün hepsini düzgünce yazarım.", "Ehtimol bir kuni ularning hammasini to'g'ri yozaman."),
        ("Şimdilik sadece biniyorum, dinliyorum ve insanların ne kadar iyi olduğunu hatırlıyorum.", "Hozircha men faqat o'tiraman, tinglayman va odamlarning qanchalik yaxshi ekanini eslayman."),
    ],
}
