LONG_STORIES_B = {
    5: [
        ("Last winter, I decided to buy a serious winter coat.", "O'tgan qish men jiddiy qishki palto sotib olishga qaror qildim."),
        ("My old jacket was thin and betrayed me every December.", "Eski kurtkam ingichka edi va har dekabrda menga xiyonat qilardi."),
        ("I saved money for two months like a determined squirrel.", "Ikki oy davomida qat'iyatli sichqon kabi pul yig'dim."),
        ("On Saturday morning, my sister and I went to the big bazaar.", "Shanba ertalab opam bilan katta bozorga bordik."),
        ("The bazaar in winter is a sea of grey and black coats.", "Qishda bozor kulrang va qora paltolar dengizidir."),
        ("Every seller shouted that his shop had the best price.", "Har bir savdogar o'z do'konida eng zo'r narx borligini baqirdi."),
        ("One seller invited us for tea before we even looked around.", "Bir savdogar atrofga qaramay choyga taklif qildi."),
        ("We laughed and accepted, because refusing felt rude.", "Kulib qabul qildik, chunki rad etish qo'pollik tuyuldi."),
        ("The tea was hot, sweet, and dangerously refillable.", "Choy issiq, shirin va xavfli darajada qayta quyiladigan edi."),
        ("After three glasses, we finally talked about coats.", "Uch piyola choynan keyin nihoyat paltolar haqida gaplashdik."),
        ("He showed me a heavy black coat with deep pockets.", "U menga chuqur cho'ntakli og'ir qora paltoni ko'rsatdi."),
        ("It was warm but made me look like a moving wardrobe.", "U iliq edi, lekin meni yuruvchi shkafga o'xshatdi."),
        ("My sister tried not to laugh and failed completely.", "Opam kulmaslikka harakat qildi va butunlay muvaffaqiyatsiz bo'ldi."),
        ("The seller admitted it was 'a coat for fathers'.", "Savdogar bu 'otolar uchun palto' ekanini tan oldi."),
        ("Next shop, I found a dark blue coat with silver buttons.", "Keyingi do'konda kumush tugmali to'q ko'k palto topdim."),
        ("The mirror said yes before my wallet could argue.", "Oyna hamyonim bahslashidan oldin 'ha' dedi."),
        ("But the price made me sit down for a moment.", "Lekin narx meni bir lahza o'tirishga majbur qildi."),
        ("My sister started negotiating like a professional diplomat.", "Opam professional diplomatchidek savdohni boshladi."),
        ("She mentioned another shop, quality, and her brother's small salary.", "U boshqa do'konni, sifatni va akasining kichik maoshini tilga oldi."),
        ("The seller pretended to call his boss for permission.", "Savdogar ruxsat uchun boshlig'iga qo'ng'iroq qilganday bo'ldi."),
        ("Everyone knew there was no phone call, including him.", "Qo'ng'iroq yo'qligini hamma, hatto u ham bilardi."),
        ("Finally, we agreed on a price that surprised us both.", "Nihoyat ikkovimizni ham hayron qoldirgan narxda kelishdik."),
        ("I paid, and the coat went into my arms like a new friend.", "To'lov qildim va palto yangi do'stdek quchoqlarimga sig'di."),
        ("On the way out, we bought roasted corn from a street vendor.", "Chiqib ketayotib, ko'cha sotuvchisidan qovurilgan makkajo'xori oldik."),
        ("Eating corn in the cold wind is a special talent here.", "Sovuq shamolda makkajo'xori yeyish bu yerda maxsus qobiliyat."),
        ("At home, Father inspected the coat like a customs officer.", "Uyda otam paltoni bojxona xodimidek tekshirdi."),
        ("He checked seams, lining, buttons, and even smelled it.", "U choklar, astar, tugmalarni tekshirdi, hatto hidini ham sinadi."),
        ("Then he nodded slowly, which is his highest praise.", "Keyin u sekin bosh irg'adi — bu uning eng baland maqtovi."),
        ("Mother immediately sewed one button tighter 'just in case'.", "Onam bir tugmani 'ehtiyot uchun' darhol mustahkam tikdi."),
        ("That night, I hung the coat where I could see it.", "O'sha kechqurun paltoni ko'radigan joyimga osdim."),
        ("I know it sounds silly, but I was genuinely proud.", "Ahmoqona tuyulishini bilaman, lekin chin dildan faxrlanardim."),
        ("Two days later, real frost arrived in the city.", "Ikki kundan keyin shaharga haqiqiy qattiq sovuq keldi."),
        ("The coat wrapped me like warm silence against the wind.", "Palto meni shamolga qarshi iliq sokinlik kabi o'ray oldi."),
        ("At the bus stop, an old man asked where I bought it.", "Avtobus bekatida keksa odam uni qayerdan olganimni so'radi."),
        ("I pointed proudly towards the bazaar and gave full details.", "Faxr bilan bozor tomonga ishora qilib barcha tafsilotlarni berdim."),
        ("He wrote the address on his hand with a pencil stub.", "U manzilni qalam bo'lagi bilan kaftiga yozib oldi."),
        ("In January, my sister asked to borrow it for one evening.", "Yanvarda opam uni bir kecha so'rab oldi."),
        ("She returned it smelling faintly of her perfume.", "Uni engil parfyum hidi bilan qaytarib berdi."),
        ("I pretended to be angry and lent it again next week.", "Jahl ko'ringanday qildim va keyingi haftada yana berdim."),
        ("By February, the whole family had worn that coat once.", "Fevralga kelib butun oila o'sha paltoni bir marta kiyyan edi."),
        ("It survived snow, rain, and my cousin's football practice.", "U qor, yomg'ir va amakivachchamning futbol mashg'ulotidan omon chiqdi."),
        ("Now each winter starts with one important ceremony.", "Endi har qish muhim bir marosim bilan boshlanadi."),
        ("I open the wardrobe, shake the coat gently, and smile.", "Shkafni ochaman, paltoni yumshoq silkitaman va tabassum qilaman."),
        ("Some purchases are practical; this one also became a story.", "Ba'zi xaridlar amaliy; bu esa hikoyaga ham aylandi."),
    ],
}
