LONG_STORIES_E = {
    8: [
        ("Exam week arrived at our university like an invading army.", "Imtihon haftasi universitetimizga bosqinchilar armiyasiday keldi."),
        ("The library suddenly became more crowded than the bazaar.", "Kutubxona birdan bozordan ham gavjum bo'lib qoldi."),
        ("Students occupied tables with flags: notebooks, markers, energy drinks.", "Talabalar stollarni bayroqlar bilan band qildi: daftarlar, flomasterlar, energiya ichimliklari."),
        ("My roommate printed the schedule and stuck it on our wall.", "Xonadoshim jadvalni chop etib devoriga yopishtirdi."),
        ("Three exams in four days — mathematics, history, and English.", "To'rt kunda uch imtihon — matematika, tarix va ingliz tili."),
        ("Mathematics was scheduled first, which felt personally offensive.", "Matematika birinchi bo'lib belgilandi, bu shaxsan haqoratli tuyuldi."),
        ("I made a colour-coded plan and followed it for one day.", "Rang kodli reja tuzdim va uni bir kun bajardim."),
        ("Day two collapsed into scrolling and panic, honestly.", "Ikkinchi kun rostini aytsam aylansh va vahimaga aylandi."),
        ("My mother called every evening with the same question.", "Onam har kechqurun bir xil savol bilan qo'ng'iroq qildi."),
        ("'Have you eaten?' — never about grades, always about food.", "'Ovqat yedingizmi?' — hech qachon baholar haqida emas, doimo ovqat haqida."),
        ("The night before mathematics, our group organized a study session.", "Matematikadan oldingi kechqurun guruhimiz o'quv mashg'uloti uyushtirdi."),
        ("We met in the dormitory kitchen between two kettles.", "Ikki choynak orasida yotoqxona oshxonasida uchrashdik."),
        ("Someone explained derivatives using bread slices as examples.", "Kimdir hosilalarni non bo'laklari misolida tushuntirib berdi."),
        ("Another drew formulas directly on the table with flour.", "Yanasi formulalarni to'g'ridan-to'g'ri stolga un bilan chizdi."),
        ("By midnight, even the weak topics started making sense.", "Yarim kechaga kelib hatto zaif mavzular ham ma'noli bo'la boshladi."),
        ("We celebrated too early and went to bed at two.", "Biz juda erta nishonladik va ikkida uxlab qoldik."),
        ("Morning exams have a special kind of silence.", "Ertalabki imtihonlarda maxsus jimlik bor."),
        ("Two hundred pencils writing at once sound like soft rain.", "Ikkita yuz qalam bir vaqtda yozganda yumshoq yomg'irdek tovush chiqaradi."),
        ("The invigilator walked slowly, wearing shoes of pure menace.", "Nazoratchi sekin yurdi, sof tahdid poyabzalini kiyyan holda."),
        ("Question one was merciful; question four was criminal.", "Birinchi savol rahmli edi; to'rtinchi esa jinoyat edi."),
        ("I left it for later and kept moving forward.", "Uni keyinga qoldirdim va oldinga siljiy berdim."),
        ("Somewhere behind me, someone sighed like a dying engine.", "Ortamda kimdir o'layotgan dvigatelday nafas oldi."),
        ("In the last ten minutes, I returned and solved it.", "Oxirgi o'n daqiqa ichida qaytib keldim va uni yechdim."),
        ("Whether correctly, I would learn only next week.", "To'g'ri yoki yo'qligini faqat keyingi haftada bilardim."),
        ("History exam came after one desperate night of dates.", "Tarix imtihoni sanalarning bitta umidsiz kechasidan keyin keldi."),
        ("My brain stored kings like random phone numbers.", "Miyam podshohlarni tasodifiy telefon raqamlari kabi saqladi."),
        ("Luckily, the essay topic was the Silk Road — my favourite.", "Omadinga, esse mavzusi Ipak yo'li edi — mening sevimlim."),
        ("I wrote about caravans, spices, languages, and my hometown's role.", "Karvonlar, ziravorlar, tillar va tug'ilgan shahrim roli haqida yozdim."),
        ("Writing about something loved feels like talking, not testing.", "Sevgan narsa haqida yozish suhbatlashgandek, sinovdan o'tmagandek tuyuladi."),
        ("English came last, and the room relaxed visibly.", "Ingliz tili oxiri keldi va xona ko'rinib tinchlantirdi."),
        ("Reading comprehension told a story about a lighthouse keeper.", "O'qish tushunishi mayoqchining hikoyasini aytib berdi."),
        ("I almost enjoyed it, which felt illegal during exams.", "Deyarli zavqlandim, bu imtihon paytida noqonuniy tuyuldi."),
        ("After the final bell, the corridor erupted into freedom.", "Oxirgi jiringlashdan keyin koridor ozodlikka portladi."),
        ("Strangers hugged strangers; books flew into trash bins ceremonially.", "Tanish emaslar tanish emaslarni quchoqladi; kitoblar marosim ravishda axlat idishiga uchdi."),
        ("Some students immediately forgot everything, smiling blankly.", "Ba'zi talabalar hamma narsani darhol unutdilar, bo'sh tabassum bilan."),
        ("Our group went straight to the park near the river.", "Guruhimiz to'g'ridan-to'g'ri daryo yaqinidagi bog'ga bordi."),
        ("We bought ice cream despite the cold wind.", "Sovuq shamolga qaramay muzqaymoq sotib oldik."),
        ("Results arrived by email three endless days later.", "Natijalar cheksiz uch kundan keyin elektron pochta orqali keldi."),
        ("I opened mine standing in the middle of the corridor.", "O'zinikini koridorning o'rtasida turub ochdim."),
        ("Mathematics: passed. History: passed. English: ninety-one points.", "Matematika: o'tdim. Tarix: o'tdim. Ingliz tili: to'qson bir ball."),
        ("I called Mother first, before opening the door home.", "Uy eshigini ochishdan avval birinchi navbatda onamga qo'ng'iroq qildim."),
        ("She cried a little and asked if I had eaten again.", "U biroz yig'ladi va yana ovqat yeganimni so'radi."),
        ("That week taught me that panic is heavier than books.", "O'sha hafta vahim kitoblardan og'iroq ekanini o'rgatdi."),
        ("Next semester, I plan to study calmly from day one.", "Keyingi semestrda birinchi kundan sokin o'qishni rejalashtiryapman."),
    ],
}
