LONG_STORIES_KO = {
    0: [
        ("지난 토요일 아침, 나는 평소보다 일찍 일어났다.", "Shanba kuni ertalab odatdagidan erta turdim."),
        ("햇살이 창문으로 비추고 있었고, 하늘은 완전히 맑았다.", "Quyosh derazamdan porlab kirayotgan edi, osmon esa butunlay ochiq."),
        ("전화기가 울렸는데, 가장 친한 친구 아지즈였다.", "Telefonim jiringladi — bu eng yaxshi do'stim Aziz edi."),
        ("그는 말했다. \"준비해, 우리 온종일 함께 보낼 거야!\"", "U dediki: 'Tayyorlan, biz butun kunni birga o'tkazamiz!'"),
        ("나는 웃었다. 그는 항상 뜻밖의 일을 계획하기 때문이다.", "Men kulib qo'ydim, chunki u doim kutilmagan narsa rejalashtiradi."),
        ("우리는 아홉 시에 우리 집 근처 버스 정류장에서 만났다.", "Biz soat to'qqizda uyim yaqinidagi avtobus bekatida uchrashdik."),
        ("도시는 조용했고 거리는 거의 텅 비어 있었다.", "Shahar tinch edi, ko'chalar deyarli bo'sh."),
        ("먼저 우리는 모퉁이에 있는 작은 빵집으로 걸어갔다.", "Avval burchakdagi kichik nonvoyxonaga piyoda bordik."),
        ("갓 구운 빵 냄새가 우리 둘 다 즉시 미소 짓게 만들었다.", "Yangi non hidi ikkovimizni darhol tabassumga keltirdi."),
        ("아지즈는 따뜻한 빵 두 개를 사서 묻지도 않고 하나를 나에게 주었다.", "Aziz ikkita issiq bulochka oldi va so'ramasdan bittasini menga berdi."),
        ("그가 늘 그런 종류의 친구였다.", "U har doim shunday do'st bo'lgan."),
        ("아침을 먹은 후, 우리는 중앙 공원을 걷기로 했다.", "Nonushtadan keyin markaziy bog' bo'ylab yurishga qaror qildik."),
        ("노인들이 높고 푸른 나무 아래에서 체스를 두고 있었다.", "Qariyalar baland yashil daraxtlar ostida shaxmat o'ynayotgan edi."),
        ("아이들은 자전거를 타며 큰 소리로 웃고 있었다.", "Bolalar velosiped haydab, baland ovozda kulayotgan edilar."),
        ("우리는 벤치에 앉아 미래 계획에 대해 이야기했다.", "Biz skameykada o'tirdik va kelajak rejalarimiz haqida gaplashdik."),
        ("아지즈는 내년에 자신의 작은 사업을 시작하고 싶어 했다.", "Aziz kelasi yili o'zining kichik biznesini ochmoqchi."),
        ("나는 여행하고 새로운 언어를 배우고 싶다는 꿈을 그에게 말했다.", "Men unga sayohat qilish va yangi tillar o'rganish orzim haqida gapirdim."),
        ("우리는 서로 열심히 일하고 절대 포기하지 않겠다고 약속했다.", "Bir-birimizga qattiq ishlash va hech qachon taslim bo'lmaslikka va'da berdik."),
        ("정오 무렵, 우리의 배들이 큰 소리로 꼬르륵거리기 시작했다.", "Taxminan peshin vaqtida qorinlarimiz baland ovozda g'urillay boshladi."),
        ("그래서 우리는 이 도시에서 내가 가장 좋아하는 곳으로 갔다.", "Shuning uchun shahardagi sevimli joyimga bordik."),
        ("그곳은 동네에서 가장 맛있는 수프를 만드는 아주 작은 카페였다.", "Bu shaharda eng mazali sho'rva tayyorlaydigan juda kichik kafe."),
        ("주인은 우리를 잘 알았고 항상 빵을 추가로 주었다.", "Egasi bizni yaxshi biladi va doim qo'shimcha non qo'shib beradi."),
        ("우리는 천천히 먹으며 창밖으로 지나가는 사람들을 바라보았다.", "Biz sekin-asta yedik va derazadan o'tayotgan odamlarni kuzatdik."),
        ("갑자기 우리는 길을 건너는 옛 학교 선생님을 보았다.", "Birdan ko'chani kesib o'tayotgan eski maktab o'qituvchimizni ko'rdik."),
        ("선생님은 행복해 보여서, 우리는 인사하러 밖으로 달려갔다.", "U baxtli ko'rindi, shuning uchun uni kutib olish uchun tashqariga yugurdik."),
        ("선생님은 오랜 세월이 지난 후에도 우리 둘 다 기억했다.", "U shu yillar davomida ikkovimizni ham esladi."),
        ("우리는 학교 추억에 대해 십 분 동안 이야기했다.", "Biz maktab xotiralari haqida o'n daqiqa suhbatlashdik."),
        ("선생님은 우리가 되어가는 사람들이 자랑스럽다고 말했다.", "U biz aylanayotgan odamlar bilan faxrlanishini aytdi."),
        ("선생님의 말씀은 그날 하루 종일 내 마음에 남아 있었다.", "Uning so'zlari kun davomida yuragimda qoldi."),
        ("오후에는 시내의 큰 서점을 방문했다.", "Tushdan keyin shahar markazidagi katta kitob do'koniga bordik."),
        ("아지즈는 비즈니스와 돈에 관한 책을 보았다.", "Aziz biznes va pul haqidagi kitoblarga qaradi."),
        ("나는 영어 관용구가 실린 아름다운 삽화 사전을 발견했다.", "Men inglizcha iboralarning chiroyli rasmli lug'atini topdim."),
        ("우리는 책을 사서 밖에서 초콜릿 바 하나를 나누어 먹었다.", "Kitoblarimizni oldik va tashqarida bir shokoladni bo'lishdik."),
        ("집에 돌아가는 길에 검은 구름이 하늘을 덮었다.", "Uyga qaytayotganda qora bulutlar osmonni qopladi."),
        ("버스 정류장에 도착하자마자 폭우가 내리기 시작했다.", "Avtobus bekatiga yetib kelganimizda kuchli yomg'ir boshlandi."),
        ("우리는 새 책을 지키며 서로 꼭 붙어서 섰다.", "Yangi kitoblarimizni himoya qilib, yonma-yon turdik."),
        ("비는 깨끗한 냄새를 풍기며 공기는 시원하고 상쾌해졌다.", "Yomg'ir toza hid berdi va havo salqin, yangi bo'lib qoldi."),
        ("마침내 집에 도착했을 때 우리는 완전히 흠뻑 젖어 있었다.", "Nihoyat uyga yetganimizda butunlay ho'l bo'lgan edik."),
        ("어머니는 문 앞에서 물이 뚝뚝 떨어지는 우리를 보고 웃으셨다.", "Onam eshik oldida tomchiqayotganimizni ko'rib kuldi."),
        ("어머니는 우리에게 레몬을 넣은 뜨거운 차와 마른 옷을 주셨다.", "U bizga limon issiq choy va quruq kiyim berdi."),
        ("우리는 차를 마시며 어머니께 하루 종일의 이야기를 들려드렸다.", "Choyni ichdik va unga butun kunimiz haqida gapirdik."),
        ("저녁에 아지즈는 비 속에 있는 우리 사진을 나에게 보냈다.", "Kechqurun Aziz menga yomg'irdagi suratimizni yubordi."),
        ("사진 아래에 그는 이렇게 적었다. \"역대 최고의 토요일.\"", "Surat ostiga esa shunday yozdi: 'Eng zo'r shanba.'"),
        ("나는 미소 지으며 곧 다시 그렇게 해야 한다고 답장했다.", "Men tabassum bilan tez orada takrorlashimiz kerak deb yozdim."),
        ("좋은 친구는 평범한 날을 특별하게 느끼게 만든다.", "Yaxshi do'stlar oddiy kunlarni maxsus qilib ko'rsatadi."),
    ],
    1: [
        ("2년 전, 나는 처음으로 혼자 비행기를 탔다.", "Ikki yil oldin birinchi parvozimni yolg'iz amalga oshirdim."),
        ("나는 삼촌을 방문하러 타슈켄트에서 이스탄불로 가고 있었다.", "Toshkentdan amakisini ko'rgani Istanbulga uchyotgan edim."),
        ("전날 밤, 나는 전혀 잠을 이룰 수 없었다.", "Oldingi kechqurun umuman uxlolmadim."),
        ("나는 여권과 티켓을 스무 번쯤 확인했다.", "Pasportim va biletimni ehtimol yigirma marta tekshirdim."),
        ("어머니는 나를 위해 샌드위치와 과자, 따뜻한 양말을 싸 주셨다.", "Onam menga tovoq-tort, shirinlik va iliq paypoq solib berdi."),
        ("공항에서는 모든 것이 거대하고 복잡해 보였다.", "Aeroportda hamma narsa ulkan va chalkash tuyuldi."),
        ("긴 여행자들의 줄이 모든 모퉁이마다 감겨 있었다.", "Sayohatchilarning uzun navatlari har bir burchakda egri-bugri edi."),
        ("나는 여권을 보여 주었고 직원은 친절하게 미소 지었다.", "Pasportimi ko'rsatdim va xodim mehribon tabassum qildi."),
        ("보안 검색대는 벨트를 빼고 주머니를 비우라고 했다.", "Xavfsizlik xodimlari kamarimni yechish va cho'ntaklarimni bo'shatishni so'radi."),
        ("심장은 빠르게 뛰었지만 모든 일이 순조롭게 진행되었다.", "Yuragim tez urayotgan edi, lekin hammasi silliq o'tdi."),
        ("탑승구에서 나는 거대한 비행기들이 하나씩 이륙하는 것을 지켜보았다.", "Reja oldida ulkan samolyotlarning birma-bir ko'tarilishini kuzatdim."),
        ("그 엔진들은 잠든 거대한 짐승처럼 포효했다.", "Ularning dvigatellari ulkan uxlagan hayvonlar kabi g'irladi."),
        ("탑승은 출발 30분 전에 시작되었다.", "Yo'lovchilarni o'tkazish jo'nashdan o'ttiz daqiqa oldin boshlandi."),
        ("나는 살짝 떨리는 손으로 티켓을 내밀었다.", "Biletimni biroz titrayotgan qo'llarim bilan topshirdim."),
        ("친절한 승무원이 나를 기내로 맞이했다.", "Samimiy stuardessa menga bortda xush kelibsiz dedi."),
        ("내 좌석은 바라던 대로 창가 옆이었다.", "O'rinishim oynaga yondosh edi, aynan umid qilganimdek."),
        ("나이 든 여성이 내 옆에 앉아 따뜻하게 인사했다.", "Yonimga keksa ayol o'tirdi va meni iliqlik bilan kutib oldi."),
        ("그녀는 내 긴장한 얼굴을 알아차리고 대화를 시작했다.", "U bezovta yuzimni sezib, suhbatni boshladi."),
        ("그녀는 자신이 쉬십 번 넘게 비행기를 타봤다고 말했다.", "U ellik martadan ortiq parvoz qilganini aytdi."),
        ("그녀의 차분한 목소리가 나를 천천히 편안하게 만들었다.", "Uning osoyishta ovozi meni asta-sekin tinchlantirdi."),
        ("비행기는 활주로로 이동해 잠시 멈추었다.", "Samolyot uchish yo'lagiga chiqib bir lahza to'xtadi."),
        ("그러고 나서 엔진이 우리를 점점 더 빠르게 앞으로 밀었다.", "Keyin dvigatellar bizni tobora tezroq oldinga surdi."),
        ("바퀴가 땅을 떠났고 위장이 철렁했다.", "G'ildiraklar yerdan uzildi va qornim tushib ketdi."),
        ("집들이 작아졌고 도로는 가는 선으로 변했다.", "Uylar kichiklashdi, yo'llar ingichka chiziqlarga aylandi."),
        ("구름 위에서 세상은 밝고 고요했다.", "Bulutlar ustida dunyo ravon va jim edi."),
        ("아래쪽 구름들은 부드러운 하얀 산처럼 보였다.", "Ostimizdagi bulutlar yumshoq oq tog'largagina o'xshardi."),
        ("그 여성은 수평선 멀리 바다를 가리켰다.", "Ayol ufqdagi uzoq dengizni ko'rsatdi."),
        ("이륙 직후 식사가 나왔는데, 닭고기와 쌀이었다.", "Ko'tarilishdan ko'p o'tmay ovqat keldi — tovuq guruch bilan."),
        ("나는 신남 때문에 배가 고파서 전부 먹었다.", "Hammasini yedim, chunki hayajon meni och qiladi."),
        ("나중에 영화를 보려 했지만 자꾸 창밖을 보았다.", "Keyinchalik film ko'rishga harakat qildim, lekin doimo oyna tomonga qaradim."),
        ("흑해 상공 어딘가에서 우리는 가벼운 요동에 부딪혔다.", "Qora dengiz ustidagi bir joyda yengil silkinishga kirishdik."),
        ("비행기가 조금 흔들렸고 내 손이 얼어붙었다.", "Samolyot biroz larzaga keldi va qo'llarim qotib qoldi."),
        ("그 여성은 그저 말했다. \"그냥 울퉁불퉁한 길인 것뿐이야.\"", "Ayol shunchaki dediki: 'Faqat yo'ldagi to'siqlar'."),
        ("곧 하늘은 다시 완전히 잠잠해졌다.", "Tez orada osmon yana butunlay tinchlandi."),
        ("기장은 15분 안에 착륙한다고 발표했다.", "Kapitan o'n beshta daqiqada qo'nishimizni e'lon qildi."),
        ("위에서 내려다본 이스탄불은 수천 개의 불빛으로 반짝였다.", "Yuqoridan Istanbul minglab chiroqlar bilan yaltiradi."),
        ("보스포루스 해협은 두 대륙 사이의 은빛 리본처럼 나타났다.", "Bosfor ikki qit'a orasida kumir lenta kabi namoyon bo'ldi."),
        ("착륙은 과속방지턱을 넘는 것보다 부드럽게 느껴졌다.", "Qo'nish tezlik to'sig'idan o'tishdan ham silliqroq tuyuldi."),
        ("비행기가 멈추자 모두가 조용히 박수를 쳤다.", "Samolyot to'xtaganda hammam yengil qarsak chaldi."),
        ("나는 친절한 그 여성에게 감사를 전하고 건강을 빌었다.", "Mehmondo'st ayolga rahmat aytdi va sog'liq tiladim."),
        ("수하물 찾는 곳에서 내 여행가방이 놀랍게도 가장 먼저 나왔다.", "Bagaj olish joyida chamadonim kutilmaganda birinchi bo'lib keldi."),
        ("삼촌이 유리창 뒤에서 큰 팻말을 들고 기다리고 있었다.", "Amakim katta yozuv bilan shisha ortida kutib turgan edi."),
        ("그의 포옹은 내 두려움을 순식간에 없애 주었다.", "Uning quchoqlashi barcha qo'rquvni darhol yo'q qildi."),
        ("도시로 차를 몰며 나는 계속 중얼거렸다. \"나 정말 비행했어!\"", "Shahar tomon ketayotib, doim takrorladim: 'Men rostan uchdim!'"),
        ("그날 이후로 나는 모든 비행기를 사랑하게 되었다.", "O'sha kundan buyon har bir parvozni yaxshi ko'raman."),
    ],
    2: [
        ("비 오는 화요일, 나는 도서관 근처의 작은 카페를 발견했다.", "Yomg'irli seshanba kuni kutubxona yaqinida kichik kafeni kashf etdim."),
        ("나무 문에는 커피콩 모양의 작은 놋쇠 손잡이가 달려 있었다.", "Uning yog'och eshigida qahva donasiga o'xshash kichik guruch dastasi bor edi."),
        ("안으로 들어가자 공기에서 계피와 볶은 원두 냄새가 났다.", "Ichkarida havoda doljin va qovurilgan don hidi bor edi."),
        ("부드러운 재즈 음악이 낡은 스피커에서 조용히 흘러나왔다.", "Eski karnaydan nozik jaz musiqasi jim chalinayotgan edi."),
        ("노트북을 든 학생들이 차지한 테이블은 세 개뿐이었다.", "Faqat uch stul noutbukli talabalar bilan band edi."),
        ("카운터 뒤의 젊은 여성이 따뜻한 끄덕임으로 나를 맞이했다.", "Dollar ortidagi yosh ayol meni iliqlik bilan bosh irg'ab kutib oldi."),
        ("나는 카푸치노와 사과파이 한 조각을 주문했다.", "Men kapuchino va olcha pie bo'lagini buyurtma qildim."),
        ("기다리는 동안 칠판에 적힌 손글씨 메뉴를 읽었다.", "Kutayotib, doskadagi qo'lyozma menyuni o'qidim."),
        ("그곳에서는 '구름 라떼' 같은 재미있는 이름의 음료를 팔았다.", "Ularda 'Bulut latte' kabi kulgili nomlar bilan ichimliklar bor edi."),
        ("내 커피는 우유 거품에 그려진 작은 잎사귀와 함께 나왔다.", "Mening kahvam sut ko'pigi ichiga chizilgan mayda yaproq bilan keldi."),
        ("사과파이는 아직 오븐에서 나온 따뜻함을 간직하고 있었다.", "Olcha pie hali ham tandirdan chiqqancha iliq edi."),
        ("한 입 먹을 때마다 작은 마을의 가을 맛이 났다.", "Har bir luqma kichik shaharchadagi kuzni eslatardi."),
        ("나는 노트를 펴고 자신에게 쓰는 편지를 쓰기 시작했다.", "Daftarchamni ochdim va o'zimga xat yozishni boshladim."),
        ("비가 옆의 큰 창문을 부드럽게 두드렸다.", "Yomg'ir yonimdagi katta oynaga yumshoq urildi."),
        ("늙은 남자가 회색 우산에서 물을 털며 들어왔다.", "Keksaygan erkak kirdi, kulrang soyabonidan suv silkitib."),
        ("그는 주방의 요리사까지 포함해 모두를 이름으로 인사했다.", "U hammaga, hatto oshxona oshpazi ham, ismi bilan salom berdi."),
        ("분명히 그는 여러 해 동안 이곳의 단골이었다.", "Aniqki, u bu yerda ko'p yillardan beri doimiy mehmon edi."),
        ("웨이트리스는 묻지도 않고 그의 평소 주문을 가져왔다.", "Ofitsiant uning odatbuy buyurtmasini so'ramasdin keltirdi."),
        ("진한 홍차, 옆에 놓인 설탕 하나, 버터 쿠키.", "Kuchli choy, bir qoshiq shakar alohida va saryog'li pechene."),
        ("그를 바라보며 나는 사람들이 작은 카페를 사랑하는 이유를 이해했다.", "Uni kuzatib, odamlarning kichik kaflarni nega sevishi tushundim."),
        ("큰 곳은 당신에게 서비스를 제공하지만 작은 곳은 당신을 기억한다.", "Katta joylar sizga xizmat qiladi, kichik joylar esa eslab qoladi."),
        ("30분 후 두 명의 친구가 내 근처에 앉았다.", "Yarim soatdan keyin yonimga ikki dugona o'tirdi."),
        ("그들은 어떤 디저트를 나눌지 장난스럽게 다투었다.", "Ular qaysi desertni bo'lishish masalasida o'yinkam bahslashdi."),
        ("마침내 그들은 딸기 소스를 얹은 치즈케이크를 선택했다.", "Nihoyat, ular maydalangan pishiriqni tanlashdi."),
        ("그들의 웃음소리가 빗소리와 아름답게 어우러졌다.", "Ularning kulishi yomg'ir tovushlari bilan chiroyli qorishdi."),
        ("나는 커피를 다 마시고 죄책감 없이 두 번째 잔을 주문했다.", "Kahvamni tugatib, ikkinchi finjanni vijdontsiz buyurtma qildim."),
        ("웨이트리스는 완전히 찬성하는 듯 미소 지었다.", "Ofitsiant xuddi to'liq ma'qullayotgandek tabassum qildi."),
        ("한 모금씩 마시는 사이 나도 바리스타가 라떼 아트를 붓는 것을 지켜보았다.", "Luqmalar orasida barista latte san'atini quyayotganini tomosha qildim."),
        ("그녀의 손은 그림 그리는 예술가처럼 자신감 있게 움직였다.", "Uning qo'llari rassom chizayotgandek ishonch bilan harakatlanardi."),
        ("옆 테이블의 어린 소녀가 핫초코를 받았다.", "Qo'shni stoladagi kichkina qiz issiq shokolad oldi."),
        ("안에 떠 있는 마시멜로를 보고 그녀의 눈이 커졌다.", "Ichida suzayotgan zefirni ko'rib, ko'zlari kengaydi."),
        ("그녀가 속삭였다. \"제 인생에서 가장 좋은 날이에요.\"", "U shivirladi: 'Bu mening hayotimdagi eng yaxshi kun.'"),
        ("그녀의 어머니는 웃으며 몰래 마시멜로 하나를 훔쳤다.", "Onasi kuldi va bir zefirni maxfiy o'g'irladi."),
        ("이런 순간들은 계획하거나 살 수 없다.", "Bunday lahzalarni rejalashtirib yoki sotib olb bo'lmaydi."),
        ("밖에서 비가 마침내 가벼운 물방울로 부드러워졌다.", "Tashqarida yomg'ir nihoyat yengil tomchilarga aylandi."),
        ("황금빛 가로등이 젖은 보도에 반사되었다.", "Oltin ko'cha chiroqlari ho'l troyni aks ettirdi."),
        ("나는 계산서를 지불하고 후한 팁을 남겼다.", "Hisobni to'lab, saxiy chaqa qoldirdim."),
        ("웨이트리스는 고맙다고 하며 따뜻하게 작별 인사를 했다.", "Ofitsiant menga rahmat aytdi va iliq xayrli yol dedi."),
        ("문 앞에서 나는 마지막으로 한 번 돌아보았다.", "Eshik oldida oxirgi marta orqaga burilib qaradim."),
        ("카페는 잿빛 저녁 속 등불처럼 빛났다.", "Kafe kulrang kechda fonar kabi yonib turardi."),
        ("이제 나는 매주 화요일마다 그 카페에 간다.", "Endi har seshanba kuni o'sha kafega boraman."),
        ("같은 테이블, 같은 카푸치노, 같은 따뜻한 기분.", "Xuddi shu stol, xuddi shu kapuchino, xuddi shu iliq tuygu."),
        ("때로는 웨이트리스가 나를 위해 마지막 파이 조각을 남겨 준다.", "Ba'zan ofitsiant menga oxirgi pie bo'lagini saqlab qo'yadi."),
        ("이런 작은 일상 의식이 삶을 달콤하고 안정되게 만든다.", "Bunday kichik an'anelar hayotni shirin va muqim qiladi."),
    ],
    3: [
        ("새 사무실에서의 첫 주는 꿈처럼 느껴졌다.", "Yangi ofisdagi ilk haftam tushga o'xshab tuyuldi."),
        ("나는 첫 출근 전날 밤 옷을 미리 준비했다.", "Birinchi kundan oldingi kechqurun kiyimlarimni tayyorladim."),
        ("긴장한 나머지 40분 일찍 도착했다.", "Asabiyligidan qirq daqiqa erta yetib keldim."),
        ("경비원이 나에게 말을 건 첫 번째 사람이었다.", "Qo'riqchi menga gapirgan birinchi odam bo'ldi."),
        ("그가 말했다. \"진정하세요, 다들 첫 월요일은 견딥니다.\"", "U dediki: 'Bo'shasangiz, hamma birinchi dushanbasidan o'tadi.'"),
        ("내 매니저는 환한 미소로 로비에서 나를 맞이했다.", "Mening menejerim meni qabulxonda yorqin tabassum bilan kutib oldi."),
        ("그녀는 나에게 전체 층을 빠르게 둘러보게 해 주었다.", "U menga butun qavatni tezkor sayohat qilib ko'rsatdi."),
        ("카펫부터 컴퓨터 화면까지 모든 것이 새 냄새가 났다.", "Hamma narsa yangi hid berdi — gilamlardan kompyuter ekranlarigacha."),
        ("내 책상은 작았지만 넓은 창 바로 옆에 있었다.", "Stolim kichik edi, lekin katta oynaning yonida joylashgan."),
        ("점심 전까지 열 명의 낯선 사람들이 자신들을 소개했다.", "Tushlikkacha o'n noma'lum odam o'zini tanishtirdi."),
        ("솔직히 나는 그들의 이름 중 절반을 즉시 잊었다.", "Halos, ularning ismlarining yarmisini darhol unutdim."),
        ("동료 도스톤이 나중에 인쇄된 명단으로 나를 구해 주었다.", "Jamoadoshim Doston keyinroq chop etilgan ro'yxat bilan menga yordam berdi."),
        ("그는 부드러운 유머로 회사 규칙을 설명해 주었다.", "U ofis qoidalarini muloyim hazil bilan tushuntirib berdi."),
        ("예를 들어 회의는 항상 5분 늦게 시작된다.", "Masalan, uchrashuvlar doim besh daqiqa kech boshlanadi."),
        ("그리고 커피 머신은 매주 금요일 오후마다 고장 난다.", "Va qahva mashinasi har juma kuni tushdan keyin buziladi."),
        ("화요일에 나는 첫 진짜 팀 회의에 참석했다.", "Seshanba kuni ilk haqiqiy jamoa uchrashuvimda qatnashdim."),
        ("모두가 빠르게 말하고 신비로운 약어를 사용했다.", "Hamma tez gapirdi va sirli qisqartmalardan foydalandi."),
        ("나는 60%만 이해하면서도 진지하게 끄덕였다.", "Faqt faqat oltmish foizini tushungan bo'lsamda, jiddiy bosh irg'adim."),
        ("회의 후 나는 낯선 단어 하나하나를 적어 내려갔다.", "Keyin har bir tanish emas so'zni yozib oldim."),
        ("그날 저녁 나는 학교 영어 단어처럼 그것들을 공부했다.", "O'sha kechqurun ularni maktab lug'ati kabi o'rgandim."),
        ("수요일까지 나는 시스템에서 첫 작은 버그를 고쳤다.", "Chorshanba kunga kelib, tizimdagi ilk kichik xatoni tuzatdim."),
        ("상사가 모두 앞에서 내 작업을 칭찬했다.", "Rahbarim ishimni hamma oldida maqtadi."),
        ("내 귀가 빨개졌지만 스스로가 10센티미터는 더 큰 기분이었다.", "Quloqlarim qizaridi, lekin o'zimni o'n santimetr balandroq his qildim."),
        ("목요일은 회사 점심 전통을 가져왔다.", "Payshanba kuni ofis tushlik an'anasini olib keldi."),
        ("모두가 집에서 한 가지 요리를 만들거나 가져왔다.", "Har kim uyida bir taom tayyorlaydi yoki olib keladi."),
        ("나는 어머니의 플로프(기름밥)를 가져갔는데 금방 사라졌다.", "Onamning guruch palovini olib keldim, u tez tugadi."),
        ("다른 부서 사람들이 레시피를 물어오러 왔다.", "Boshqa bo'limlardagi odamlar retseptni so'rab kelishdi."),
        ("금요일은 누군가의 생일이라 케이크로 끝났다.", "Juma kuni tort bilan tugadi, chunki kimningdir tug'ilgan kuni edi."),
        ("우리는 사무실답게 절반은 노래하고 절반은 속삭이며 조용히 노래했다.", "Biz jim qo'shiq aytdik, ofislarda odat bo'lganidek, yarim kuylanib yarim shivirlab."),
        ("그 주 동안 나는 세 가지 중요한 교훈을 배웠다.", "O'sha hafta davomida uch muhim darsni o'rgandim."),
        ("첫째, 질문하는 것은 약함이 아니라 강함이다.", "Birinchisi, savol berish kuchsizlik emas, kuch."),
        ("둘째, 짧은 산책은 피곤한 뇌를 치유한다.", "Ikkinchisi, qisqa sayr charchagan miygacha yordam beradi."),
        ("셋째, 동료들은 예상보다 빨리 친구가 된다.", "Uchinchisi, hamkasblar kutgandan ham tezroq do'stga aylanadi."),
        ("금요일 저녁, 내 받은편지함은 마침내 비었다.", "Juma kechqurun pochtam nihoyat bo'sh edi."),
        ("나는 내 책상을 바라보며 조용한 자부심을 느꼈다.", "Stolimga qarab sokin iftixor his qildim."),
        ("1주일 전만 해도 이곳은 낯설고 무서웠다.", "Bir hafta oldin bu joy noma'lum va qo'rqinchli edi."),
        ("이제는 벌써 제2의 집처럼 느껴진다.", "Endi u allaqachon ikkinchi uyday tuyuladi."),
        ("경비원은 내가 떠날 때 나에게 손을 흔들었다.", "Chiqib ketayotib, qo'riqchi menga qo'l silkitdi."),
        ("\"월요일에 봐요.\" 그가 오랜 친구처럼 말했다.", "'Dushanba ko'rishamiz', deb aytdi u eski do'stday."),
        ("집으로 가는 버스에서 나는 특별한 이유 없이 미소 지었다.", "Uyga qaytayotgan avtobusda hech kimga bog'liq bo'lmagan sababsiz tabassum qildim."),
        ("발은 아팠지만 마음은 가벼웠다.", "Oyoqlarim og'ridi, lekin yuragim yengil edi."),
        ("나는 부모님께 이 일이 잘 맞는다고 문자를 보냈다.", "Ota-onamga bu ish to'g'ri kelayotganini yozdim."),
        ("아버지는 한 단어로 답하셨다. \"드디어.\"", "Otam bitta so'z bilan javob berdi: 'Nihoyat.'"),
        ("그날 밤 나는 회사 배지를 차고서 잠들었다.", "O'sha kechqurun ish belgisimni yechmasdan uxlab qoldim."),
    ],
    4: [
        ("격주 일요일마다 우리 가족은 할머니 댁에 모인다.", "Har juftshanba kuni oilamiz bobomizning uyida yig'iladi."),
        ("할머니 댁은 포플러 나무들로 가득한 조용한 거리 끝에 있다.", "Uning uyi teraklar bilan to'lgan sokin ko'chaning oxirida joylashgan."),
        ("대문을 두드리기도 전에 새소리를 들을 수 있다.", "Darvoza urishdan avval qushlar ovozini eshitishingiz mumkin."),
        ("할머니는 보라색 앞치마를 두르고 새벽부터 요리를 시작하신다.", "Bobomiz tong otishidan boshlab oshxona boshlaydi, binafsha fartugi kiyingan holda."),
        ("갓 구운 삼삼냄새가 문 앞에서 우리를 맞이한다.", "Yangi somsa hidi bizni eshik oldida kutib oladi."),
        ("삼촌들은 누구 차가 더 잘 주차됐는지 즐겁게 다투신다.", "Amakilar kimning mashinasi yaxshi to'xtaganligi haqida quvonch bilan bahslashadi."),
        ("사촌들은 오래된 축구공을 쫓으며 정원을 뛰어다닌다.", "Amakivachchalar bog'da eskicha futbol ortidan yugurishadi."),
        ("누군가는 매번 정원 호스에 걸려 넘어진다.", "Har safar kimdir bog'dagi shlangaga tiqilib yiqiladi."),
        ("이모들은 베란다에 앉아 휴대폰 속 사진들을 비교하신다.", "Xolalar verandada telefonlaridagi suratlarni solishtirib o'tirishadi."),
        ("할아버지는 자신의 체스판을 작은 왕처럼 지키신다.", "Bobomiz shaxmat taxtasini kichik qirol kabi qo'riqlaydi."),
        ("할아버지는 모든 손주에게 도전하셨고 우리 대부분을 이기신다.", "U har bir nabirasini o'yin chorlaydi va ko'pchiligimizni mag'lub etadi."),
        ("나는 오늘 두 번 졌고 점심 후 재대결을 요구했다.", "Bugun ikki marta yutqazdim va tushlikdan keyin revansh talab qildim."),
        ("주방에서 할머니는 아무것도 계량하지 않으신다.", "Oshxonada Bobomiz hech narsani o'lchamaydi."),
        ("할머니는 '음식의 소리를 들으며' 소금을 넣는다고 하신다.", "U tuzni 'ovqat tinglab' qo'shishini aytadi."),
        ("할머니의 반죽은 황금 종이처럼 얇게 늘어난다.", "Uning xamiri oltin qog'oz kabi ingichka cho'ziladi."),
        ("모든 비밀은 레시피가 아니라 할머니의 손목에 있다.", "Barcha sirlar retseptlarda emas, bilaklarida yashirilgan."),
        ("나는 설거지를 하고 따뜻한 빵을 훔치는 것으로 돕는다.", "Men idish yuvgani va iliq non o'g'irlashga yordam beraman."),
        ("할머니는 매번 나를 못 본 척하신다.", "U har safar meni ko'rmagan bo'lib qiyofa beradi."),
        ("두 시가 되면 긴 식탁이 음식 무게에 신음소리를 낸다.", "Soat ikkida uzun stol taomlar ostida ingichka ovoz chiqaradi."),
        ("플로프, 샐러드, 삼삼, 과일, 세 가지 종류의 차.", "Palov, salatlar, somsa, mevalar va uch xil choy."),
        ("먹기 전에 할아버지가 조용히 감사의 말씀을 몇 마디 하신다.", "Yeyishdan oldin Bobomiz bir nechta sokin minnatdorchilik so'zi aytadi."),
        ("그러면 방이 말과 웃음으로 폭발한다.", "Keyin xona gapirish va kulish bilan portlaydi."),
        ("모두가 동시에 말하지만 이상하게도 잘 굴러간다.", "Hamma bir vaqtda gapiradi va bir yo'l bilan hammasi mos keladi."),
        ("어린 주흐라가 의자 위에 서서 시를 암송한다.", "Kichkina Zuhra kursida turub she'r aytyapti."),
        ("우리는 너무 크게 박수를 치고 그녀는 배우처럼 허리를 숙인다.", "Biz juda baland qarsak chaldik va u aktrisa kabi egildi."),
        ("식사 후 어른들은 젊은 시절 이야기를 들려주신다.", "Ovqatdan keyin kattalar yoshliklaridagi hikoyalarni aytishadi."),
        ("오늘 이야기는 1975년 할아버지가 염소를 잃어버린 이야기였다.", "Bugungi hikoya Bobomizning 1975-yilda echisini yo'qotishi haqida edi."),
        ("할아버지는 그 절반을 부정하시는데, 그것이 사실임을 증명한다.", "U yarmi inkor etadi, bu esa uning rostligini isbotlaydi."),
        ("10대들은 듣지 않는 척하지만 전부 듣는다.", "O'smirliklar tinglamaslikka harakat qiladi, ammo hammasini eshitishadi."),
        ("나중에 우리는 집 뒷편 나무에서 사과를 따낸다.", "Keyinchalik uy ortidagi daraxtdan olma teramiz."),
        ("가장 좋은 것들은 당연히 가장 높이 걸려 있다.", "Eng zo'rlari tabiiy ravishda balandda osilgan bo'ladi."),
        ("사촌이 예전처럼 나를 어깨에 올려 준다.", "Amakivachcham meni eski vaqtlarday yelkasiga ko'taradi."),
        ("우리는 바구니 하나를 채우고 또 다른 바구니를 조용히 먹는다.", "Bir savat to'ldiramiz va yana bir savatni jim yeymiz."),
        ("할머니는 나중에 사과를 세시지만 알면서도 그냥 미소 지으신다.", "Bobomiz keyinchalik olmalarni sanab, anglagan holda tabassum qiladi."),
        ("저녁이 되자 누군가 오래된 사진첩을 꺼내온다.", "Kechga yaqin kimdir eskicha fotoalbomni olib chiqadi."),
        ("흑백 사진 속 조부모님들이 영원히 젊은 채로 우리를 바라본다.", "Qora-oq bobolarimiz bizga abadiy yosh holda qarashadi."),
        ("엄마가 할머니의 웨딩드레스를 가리키며 한숨을 쉰다.", "Onam Bobomizning to'y ko'ylagini ko'rsatib nafas oladi."),
        ("할머니는 손을 흔들며 유행은 되풀이된다고 말씀하신다.", "Bobomiz qo'l silkitadi va moda takrorlanishini aytadi."),
        ("하늘이 주황색으로 물들면 차들이 줄지어 서기 시작한다.", "Osmon to'qsarig' aylanganda mashinalar navbatga turadi."),
        ("아무도 처음으로 떠나는 가족이 되고 싶어 하지 않는다.", "Hech kim birinchi bo'lib ketadigan oila bo'lishni istamaydi."),
        ("우리는 평소처럼 대문 앞에서 백 번을 헤아리듯 포옹한다.", "Odatdagidek darvoza oldida yuz marta quchoqlashamiz."),
        ("할머니는 우리 가방들이 겨우 닫힐 만큼 채우신다.", "Bobomiz sumkalarimizni zo'rg'a yopiladigan darajada to'ldiradi."),
        ("집으로 가는 차 안은 사과와 따뜻한 빵 냄새가 났다.", "Uyga qaytayotib, mashina olma va iliq non hidi beradi."),
        ("남동생은 반쯤 먹은 과자를 쥔 채 잠들었다.", "Kichik ukam yarim yegan pecheneni qo'liga olib uxlab qoladi."),
        ("이런 일요일들은 단순하고 시끄럽고 완전히 완벽하다.", "Bu shanbalar oddiy, shovqinli va mutlaqo mukammal."),
    ],
    5: [
        ("지난겨울 나는 제대로 된 겨울 코트를 사기로 결심했다.", "O'tgan qish men jiddiy qishki palto sotib olishga qaror qildim."),
        ("내 오래된 재킷은 얇았고 매년 12월마다 나를 배신했다.", "Eski kurtkam ingichka edi va har dekabrda menga xiyonat qilardi."),
        ("나는 결심한 다람쥐처럼 두 달 동안 돈을 모았다.", "Ikki oy davomida qat'iyatli sichqon kabi pul yig'dim."),
        ("토요일 아침 여동생과 나는 큰 바자회에 갔다.", "Shanba ertalab opam bilan katta bozorga bordik."),
        ("겨울의 시장은 회색과 검은 코트들의 바다였다.", "Qishda bozor kulrang va qora paltolar dengizidir."),
        ("모든 상인이 자기 가게가 최저 가격이라고 외쳤다.", "Har bir savdogar o'z do'konida eng zo'r narx borligini baqirdi."),
        ("한 상인이 우리가 둘러보기도 전에 차를 마시라고 초대했다.", "Bir savdogar atrofga qaramay choyga taklif qildi."),
        ("우리는 웃으며 수락했다. 거절하는 것은 무례하게 느껴졌기 때문이다.", "Kulib qabul qildik, chunki rad etish qo'pollik tuyuldi."),
        ("그 차는 뜨겁고 달았고 위험할 만큼 계속 채워 주었다.", "Choy issiq, shirin va xavfli darajada qayta quyiladigan edi."),
        ("세 잔 후에야 우리는 마침내 코트에 대해 이야기했다.", "Uch piyola choynan keyin nihoyat paltolar haqida gaplashdik."),
        ("그는 깊은 주머니가 달린 무거운 검은 코트를 보여 주었다.", "U menga chuqur cho'ntakli og'ir qora paltoni ko'rsatdi."),
        ("따뜻했지만 나를 움직이는 장롱처럼 보이게 했다.", "U iliq edi, lekin meni yuruvchi shkafga o'xshatdi."),
        ("여동생은 웃지 않으려다 완전히 실패했다.", "Opam kulmaslikka harakat qildi va butunlay muvaffaqiyatsiz bo'ldi."),
        ("상인도 그것이 '아버지들을 위한 코트'라고 인정했다.", "Savdogar bu 'otolar uchun palto' ekanini tan oldi."),
        ("다음 가게에서 나는 은색 단추가 달린 짙은 파란 코트를 발견했다.", "Keyingi do'konda kumush tugmali to'q ko'k palto topdim."),
        ("거울이 내 지갑이 반박하기 전에 예스라고 말했다.", "Oyna hamyonim bahslashidan oldin 'ha' dedi."),
        ("하지만 그 가격에 잠깐 앉아 있게 되었다.", "Lekin narx meni bir lahza o'tirishga majbur qildi."),
        ("여동생이 프로 외교관처럼 흥정을 시작했다.", "Opam professional diplomatchidek savdohni boshladi."),
        ("그녀는 다른 가게, 품질, 그리고 오빠의 작은 월급을 언급했다.", "U boshqa do'konni, sifatni va akasining kichik maoshini tilga oldi."),
        ("상인은 허락을 받으려고 상사에게 전화하는 척했다.", "Savdogar ruxsat uchun boshlig'iga qo'ng'iroq qilganday bo'ldi."),
        ("그 본인을 포함해 모두가 그 전화가 거짓이라는 것을 알았다.", "Qo'ng'iroq yo'qligini hamma, hatto u ham bilardi."),
        ("마침내 우리는 우리 둘 다 놀란 가격에 합의했다.", "Nihoyat ikkovimizni ham hayron qoldirgan narxda kelishdik."),
        ("나는 돈을 지불했고 코트는 새 친구처럼 내 품으로 들어왔다.", "To'lov qildim va palto yangi do'stdek quchoqlarimga sig'di."),
        ("나오는 길에 우리는 노점에서 굽은 옥수수를 샀다.", "Chiqib ketayotib, ko'cha sotuvchisidan qovurilgan makkajo'xori oldik."),
        ("차가운 바람 속에서 옥수수 먹기는 이곳의 특별한 재능이다.", "Sovuq shamolda makkajo'xori yeyish bu yerda maxsus qobiliyat."),
        ("집에서 아버지가 세관원처럼 코트를 검사하셨다.", "Uyda otam paltoni bojxona xodimidek tekshirdi."),
        ("아버지는 솔기, 안감, 단추까지 확인하고 냄새까지 맡으셨다.", "U choklar, astar, tugmalarni tekshirdi, hatto hidini ham sinadi."),
        ("그러고 나서 아버지는 천천히 끄덕이셨는데, 그것이 가장 높은 칭찬이다.", "Keyin u sekin bosh irg'adi — bu uning eng baland maqtovi."),
        ("어머니는 즉시 '만약을 위해' 단추 하나를 더 단단히 꿰매셨다.", "Onam bir tugmani 'ehtiyot uchun' darhol mustahkam tikdi."),
        ("그날 밤 나는 보이는 곳에 코트를 걸었다.", "O'sha kechqurun paltoni ko'radigan joyimga osdim."),
        ("바보 같게 들린다는 것을 알지만 진심으로 자랑스러웠다.", "Ahmoqona tuyulishini bilaman, lekin chin dildan faxrlanardim."),
        ("2일 후 도시에 진짜 서리가 찾아왔다.", "Ikki kundan keyin shaharga haqiqiy qattiq sovuq keldi."),
        ("코트는 따뜻한 침묵처럼 바람으로부터 나를 감쌌다.", "Palto meni shamolga qarshi iliq sokinlik kabi o'ray oldi."),
        ("버스 정류장에서 늙은 남자가 어디서 샀냐고 물었다.", "Avtobus bekatida keksa odam uni qayerdan olganimni so'radi."),
        ("나는 자랑스럽게 시장 쪽을 가리키며 자세한 정보를 알려주었다.", "Faxr bilan bozor tomonga ishora qilib barcha tafsilotlarni berdim."),
        ("그는 연필 꼬리로 손바닥에 주소를 적었다.", "U manzilni qalam bo'lagi bilan kaftiga yozib oldi."),
        ("1월에 여동생이 하루 저녁 빌려달라고 요청했다.", "Yanvarda opam uni bir kecha so'rab oldi."),
        ("그녀가 돌려줄 때 그녀의 향수 냄새가 은은하게 배어 있었다.", "Uni engil parfyum hidi bilan qaytarib berdi."),
        ("나는 화난 척하며 다음 주에 또 빌려주었다.", "Jahl ko'ringanday qildim va keyingi haftada yana berdim."),
        ("2월에는 가족 전체가 그 코트를 한 번씩 입었다.", "Fevralga kelib butun oila o'sha paltoni bir marta kiyyan edi."),
        ("그것은 눈과 비와 사촌의 축구 연습을 버텨냈다.", "U qor, yomg'ir va amakivachchamning futbol mashg'ulotidan omon chiqdi."),
        ("이제 매년 겨울은 하나의 중요한 의식으로 시작된다.", "Endi har qish muhim bir marosim bilan boshlanadi."),
        ("나는 옷장을 열고 코트를 부드럽게 털며 미소 짓는다.", "Shkafni ochaman, paltoni yumshoq silkitaman va tabassum qilaman."),
        ("어떤 구매는 실용적이다. 이것은 이야기가 되었다.", "Ba'zi xaridlar amaliy; bu esa hikoyaga ham aylandi."),
    ],
    6: [
        ("우리 동네 축구팀은 5경기를 연달아 패배한 상태였다.", "Ko'cha futbol jamoamiz ketma-ket beshta o'yinda mag'lub bo'ldi."),
        ("토요일에는 동네 컵의 결승전이 예고되어 있었다.", "Shanba kuni mahalla kubogining final o'yini bo'lishi kerak edi."),
        ("우리의 상대는 다음 거리 소년들로, 키가 크고 빨랐다.", "Raqiblarimiz qo'shni ko'chaning baland va tez yigitlari edi."),
        ("모두가 그냥 포기하고 집에 있으라고 말했다.", "Hamma uyda qolib taslim bo'lishimizni aytdi."),
        ("하지만 우리 주장 자수르는 우리를 위한 다른 계획이 있었다.", "Lekin sardorimiz Jasurning biz uchun boshqa rejalar bor edi."),
        ("그는 목요일 저녁 추가 연습을 소집했다.", "U payshanba kechqurun qo'shimcha mashg'ulot chaqirdi."),
        ("7명의 선수만 왔고 그중 두 명은 감기 기운이 있었다.", "Faqat yetti o'yinchi keldi, ikkovimiz kasal edik."),
        ("우리는 가로등이 켜질 때까지 패스 연습을 했다.", "Ko'cha chiroqlari yoqilguncha paslar mashq qildik."),
        ("자수르는 한 문장을 거듭 반복했다. \"드리블하기 전에 패스해.\"", "Jasur bitta jumlani takrorladi: 'Chalib ketishdan oldin pass ber.'"),
        ("금요일 밤 나는 설렘 때문에 거의 잠을 못 잤다.", "Juma kechqurun hayajondan zo'rg'a uxladim."),
        ("나는 승리골을 넣는 상상을 마흔 번쯤 했다.", "G'alaba golini urganini taxminan qirq marta xayolimdan o'tkazdim."),
        ("토요일 아침은 추웠고 물웅덩이에는 얇은 얼음이 얼어 있었다.", "Shanba ertalab sovuq edi, suv havzalarida ingichka muz bor."),
        ("낡은 공장 뒤 운동장은 진흙으로 말랑했다.", "Eski zavod ortidagi maydon loy bilan yumshoq edi."),
        ("관중들이 양쪽에 줄지어 섰는데 보온병을 든 할아버지들도 있었다.", "Tomoshabinlar ikki tomonda saf tortdi, termosli bobolar ham bor edi."),
        ("심판은 엄격함으로 유명한 은퇴한 선생님이었다.", "Hakim qat'iyligi bilan mashhur nafaqadagi o'qituvchi edi."),
        ("첫 15분은 우리에게 재앙이었다.", "Dastlabki o'n beshta daqiqa biz uchun ofat bo'ldi."),
        ("그들이 두 골을 넣었고 그들의 팬들이 큰 소리로 노래했다.", "Ular ikki marta gol urdi va muxlislarari baland qo'shiq aytdi."),
        ("우리 골키퍼가 장군처럼 지시를 외쳤다.", "Darvozabonimiz generaldek ko'rsatmalar baqirdi."),
        ("천천히 우리는 목요일의 간단한 규칙을 떠올렸다.", "Astasekin, payshanbadagi oddiy qoidani esladi."),
        ("패스, 이동, 다시 패스 — 혼자서는 영웅 없음.", "Pass, harakat, yana pass — yakka qahramonlar bo'lmaslik."),
        ("우리의 게임이 갑자기 빠르고 깨끗해졌다.", "O'yinimiz birdan tez va toza bo'lib qoldi."),
        ("전반 종료 직전, 아지즈가 좁은 각도에서 골을 넣었다.", "Tanaffus oldi rostida, Aziz tor burchakdan gol urdi."),
        ("우리는 젖은 잔디에 미끄러지며 그를 안으러 달려갔다.", "Uni quchoqlash uchun yugurdik, ho'l o'tloqda sirg'alib."),
        ("전반 휴식은 숨이 찬 10분이었다.", "Tanaffus o'n daqiqa og'ir nafas olish bilan o'tdi."),
        ("자수르는 전술을 설명하며 진흙 바닥에 원을 그렸다.", "Jasur loy tuproqga aylanalar chizib taktikani tushuntirdi."),
        ("후반은 맹렬하게, 거의 화나게 시작되었다.", "Ikkinchi bo'lim shiddat bilan, deyarli g'azablangan holda boshlandi."),
        ("그들의 가장 키 큰 선수가 일부러 내 발가락을 밟았다.", "Ularning eng baland o'yinchisi oyog'imni ataylab bosdi."),
        ("나는 아무 말도 하지 않고 대신 공에 집중했다.", "Men hech narsa demadim va o'rniga to'pga e'tibor berdim."),
        ("20분이 남았을 때 우리는 프리킥을 얻었다.", "Yigirma daqiqa qolganda jarima zarbasiga erishdik."),
        ("모두가 우리의 조용한 전문가 사르도르를 바라보았다.", "Hamma jim ko'rinishdagi mutaxassisimiz Sardorga qaradi."),
        ("그는 공을 조심스럽게 놓고 이마를 닦았다.", "U to'pni ehtiyotkorlik joylashtirdi va peshonasini artidi."),
        ("수비벽이 뛰어올랐다. 공은 아름답게 그 주위로 휘어졌다.", "Devor sakradi; to'p uning atrofidan chiroyli egilib o'tdi."),
        ("2-2, 그리고 거리가 소음으로 폭발했다.", "Ikk-ikki, va ko'cha shovqin bilan portladi."),
        ("마지막 분에 내 다리는 나무 막대기처럼 느껴졌다.", "Oxirgi daqiqada oyog'im yog'och tayoqlardek his qildi."),
        ("그때 공 하나가 우연히 나를 향해 굴러왔다.", "Keyin erkin to'p tasodifan menga tomonga aylanib keldi."),
        ("나는 어딘가 멀리서 자수르가 내 이름을 외치는 것이 들렸다.", "Jasurning ismimni uzoqdan baqirayotganini eshitdim."),
        ("나는 슛 대신 패스했다 — 규칙이 나를 구했다.", "Zarba o'rniga pass berdim — qoida meni qutqardi."),
        ("아지즈가 그것을 받아 침착하게 승리골을 넣었다.", "Aziz uni qabul qildi va g'alaba golini tinch urdi."),
        ("휘슬이 울렸고 나는 웃으면서 잔디 위에 쓰러졌다.", "Chalqildi chalinadi va men kulgan holda o'tloqqa yiqildim."),
        ("할아버지들이 보온병을 트로피처럼 머리 위로 흔들었다.", "Bobolar termoslarni boshlaridan mukofotday silkitishdi."),
        ("엄격한 심판조차 잠깐 우리 주장에게 미소 지었다.", "Hattoning qattiqqo'l hakimi ham sardorimizga bir lahza tabassum qildi."),
        ("우리는 식은 레모네이드와 따뜻한 빵으로 축하했다.", "Biz gazsiz limonad va iliq non bilan nishonladik."),
        ("솔직히 아무도 오늘 정확한 스코어를 기억하지 못한다.", "Bugun hech kim aniq hisobni eslamaydi, rostini aytsam."),
        ("하지만 모두가 우리가 드디어 함께 플레이했다는 것을 기억한다.", "Lekin hamma nihoyat birga o'ynaganimizi eslaydi."),
    ],
    7: [
        ("6월에 나와 친구들은 침간 산으로 등산을 갔다.", "Iyun oyida do'stlarim bilan Chimyon tog'lariga yurish qildik."),
        ("일기예보는 맑음을 약속해서 아무도 우비를 챙기지 않았다.", "Bashorat quyoshni va'da qilgandi, shuning uchun hech kim yomg'irpoq olmadi."),
        ("그것이 우리 여행의 첫 번째 실수였다.", "Bu bizning sayohatimizdagi birinchi xato edi."),
        ("우리는 시원한 아침 공기와 함께 여섯 시에 오르기 시작했다.", "Salqin ertalabki havoda soat oltida chiqishni boshladik."),
        ("소나무들이 하부 사면을 녹색 군대처럼 덮고 있었다.", "Qarag'aylar pastki yonbag'irlarni yashil armiyalardek qoplaydi."),
        ("새들이 모든 방향에서 노래하며 자신들의 아침을 자랑했다.", "Qushlar har tomondan kuyladi, ertalablarini ko'rsatib turardi."),
        ("열 시쯤 땀이 우리 셔츠 위에 검은 지도를 그려 놓았다.", "O'nlikka kelib, ter ko'ylaklarimizda qora xaritalar chizdi."),
        ("우리는 물을 너무 빨리 마셨고 그것에 대해 웃었다.", "Suvni juda tez ichdik va buning ustidan kuldik."),
        ("길은 아래에 작은 시냇물이 있는 절벽을 따라 좁아졌다.", "Yo'l pastda kichik soy bo'lgan jarlik bo'ylab toraydi."),
        ("파리스는 배낭에 대해 극적으로 불평하며 뒤처졌다.", "Faris orqada qoldi, chamadoni haqida dramatik shikoyat qilib."),
        ("우리는 그를 놀렸지만 그럼에도 함께 속도를 늦췄다.", "Uni masxara qildik, lekin baribir birga sekinlashtirdik."),
        ("정오 무렵 하늘이 기분을 완전히 바꾸었다.", "Taxminan peshin vaqtida osmon kayfiyatini butunlay o'zgartirdi."),
        ("회색 구름의 벽이 먼 능선을 넘어 올라왔다.", "Kulrang bulut devori uzoq tizmadan oshib chiqa boshladi."),
        ("누군가 여름의 창문을 닫은 것처럼 기온이 떨어졌다.", "Harorat tushdi, xuddi kimdir yozga oynani yopib qo'yganidek."),
        ("첫 방울들은 크고 차가웠고 놀랍도록 친근했다.", "Birinchi tomchilar katta, sovuq va kutilmaganda samimiy edi."),
        ("그러고 나서 비가 박수처럼 도착했다. 무겁고 곳곳에서.", "Keyin yomg'ir olqish kabi keldi — kuchli va hamma joyda."),
        ("우리는 웃으면서 근처의 거대한 평평한 바위를 향해 달렸다.", "Yaqin atrofdagi ulkan tekis toshga kulib yugurdik."),
        ("일곱 명이 하나의 좁은 돌출부 아래 정어리처럼 웅크렸다.", "Yetti kishi bir tor qoyalarga sardinalardek sig'ishdi."),
        ("배낭들은 가운데로 들어갔고 우리는 반쯤 젖은 채 바깥에 있었다.", "Chamadonlar o'rtaga kirdi; biz yarim ho'l holda tashqarida qoldik."),
        ("비는 계곡 전체를 은색이고 시끄럽게 만들었다.", "Yomg'ir butun vodini kumushrang va shovqinli qildi."),
        ("전에 없던 폭포가 절벽에 나타났다.", "Oldin sharshara bo'lmagan jarliklarda sharsharalar paydo bo'ldi."),
        ("번개가 반대편 산을 가로질러 소리 없는 하얀 가지를 그렸다.", "Chaqqon oppoq shoxlarni qarama-qarshi tog' bo'ylab jim chizdi."),
        ("우리는 아이들처럼 번개와 천둥 사이의 초를 세었다.", "Biz yalt-ylt va g'umburlash orasidagi soniyalarni sanadik."),
        ("아래 어딘가에서 목동이 양들을 일찍 집으로 부르는 휘슬을 불었다.", "Pastlarda cho'pon qo'ylarini erta uyga chalqitdi."),
        ("우리는 비상 담요 하나로 함께 감싸며 초콜릿을 나누어 먹었다.", "Bir favqulodda ko'rpachaga o'ralgan holda shokolad bo'lishdik."),
        ("딜노자가 유령 이야기를 해서 우리가 그만해 달라고 빌 때까지 들었다.", "Dilnoza arvoh hikoyalarini aytdi, biz uni to'xtashiga yalinmaguncha."),
        ("폭풍은 자수르의 시계로 정확히 40분 동안 지속되었다.", "Bo'ron Jasurning soatiga aynan qirq daqiqa davom etdi."),
        ("폭풍이 떠났을 때 세상은 완전히 새로 태어난 냄새가 났다.", "U ketganda, dunyo butunlay yangi tug'ilgandek hid berdi."),
        ("모든 잎사귀가 작은 떨리는 물 다이아몬드를 들고 있었다.", "Har bir yaproqda mayda titrayotgan suv olmosi bor edi."),
        ("안개가 부드러운 연기처럼 계곡에서 천천히 피어올랐다.", "Tuman vodidan yumshoq tutun singari sekin ko'tarildi."),
        ("그러고 나서 무지개가 왔다. 거대하고, 겹쳐 보이고, 거의 건방졌다.", "Va kamalak keldi — ulkan, juftlashgan, deyarli mag'rur."),
        ("아무도 말하지 않았다. 파리스조차 불평을 잊었다.", "Hech kim gapirmadi; hatto Faris ham shikoyatlarini unutdi."),
        ("우리는 젖은 잔디와 빛나는 돌들 사이로 등산을 계속했다.", "Ho'l o'tloq va yalt-yaltiroq toshlar orasida chiqishda davom etdik."),
        ("정상이 갑자기 나타났다. 구름을 모자처럼 쓴 채.", "Cho'qqi birdan namoyon bo'ldi, bulutni shlyapa kabi kiygan holda."),
        ("우리는 메아리가 돌아오는 것을 듣기 위해 안개 속으로 외쳤다.", "Tumanga aks sadoni eshitish uchun baqirdik."),
        ("점심은 빵, 치즈, 토마토, 순수한 승리였다.", "Nonushta non, pishloq, pomidor va sof g'alaba edi."),
        ("비와 노력 후에는 모든 것이 더 맛있다.", "Yomg'ir va mehnatdan keyin har narsa mazaliroq tuyuladi."),
        ("내려가는 데는 시간은 덜 들었지만 더 많은 집중이 필요했다.", "Pasayish kamroq vaqt oldi, lekin ko'proq e'tibor talab qildi."),
        ("젖은 돌은 프로 수준으로 미끄럽다는 것을 우리는 빨리 배웠다.", "Ho'l toshlar professional darajadagi sirg'aluvchan ekanini tez o'rgandik."),
        ("마을에서 할머니 한 분이 뜨거운 차와 꿀을 우리에게 팔았다.", "Qishloqda keksa ayol bizga issiq choy va asal sotdi."),
        ("그녀는 산의 비는 방문객에게 항상 행운을 가져다준다고 말했다.", "U tog' yomg'iri mehmonlarga doimo omad keltirishini aytdi."),
        ("집으로 가는 버스에는 젖은 양모와 풀 냄새가 났다.", "Uyga avtobusda ho'l jun va o't hidi bor edi."),
        ("운전사와 딜노자의 유령 이야기를 제외하고 모두가 잠들었다.", "Haydovchi va Dilnozaning arvoh hikoyalaridan boshqa hamma uxlab qoldi."),
        ("그 여행 이후 우리는 다시는 일기예보를 믿지 않는다.", "O'sha sayohatdan keyin ob-havo bashoratiga umuman ishonmaymiz."),
    ],
    8: [
        ("시험 주간이 침략군처럼 우리 대학교에 도착했다.", "Imtihon haftasi universitetimizga bosqinchilar armiyasiday keldi."),
        ("도서관은 갑자기 시장보다 더 붐비게 되었다.", "Kutubxona birdan bozordan ham gavjum bo'lib qoldi."),
        ("학생들이 깃발로 테이블을 점령했다. 노트, 형광펜, 에너지 음료.", "Talabalar stollarni bayroqlar bilan band qildi: daftarlar, flomasterlar, energiya ichimliklari."),
        ("룸메이트가 시간표를 인쇄해 우리 벽에 붙였다.", "Xonadoshim jadvalni chop etib devoriga yopishtirdi."),
        ("4일 동안 3개의 시험 — 수학, 역사, 영어.", "To'rt kunda uch imtihon — matematika, tarix va ingliz tili."),
        ("수학이 첫날 배정되었는데 개인적으로 모욕적으로 느껴졌다.", "Matematika birinchi bo'lib belgilandi, bu shaxsan haqoratli tuyuldi."),
        ("나는 색상별 계획을 세우고 하루 동안은 지켰다.", "Rang kodli reja tuzdim va uni bir kun bajardim."),
        ("2일째는 솔직히 스크롤과 공황으로 무너졌다.", "Ikkinchi kun rostini aytsam aylansh va vahimaga aylandi."),
        ("어머니께서 매일 저녁 같은 질문으로 전화하셨다.", "Onam har kechqurun bir xil savol bilan qo'ng'iroq qildi."),
        ("\"밥은 먹었니?\" — 성적은 묻지 않고 항상 음식을 물으셨다.", "'Ovqat yedingizmi?' — hech qachon baholar haqida emas, doimo ovqat haqida."),
        ("수학 전날 밤, 우리 조는 스터디 모임을 조직했다.", "Matematikadan oldingi kechqurun guruhimiz o'quv mashg'uloti uyushtirdi."),
        ("우리는 기숙사 부엌에서 주전자 두 개 사이에서 만났다.", "Ikki choynak orasida yotoqxona oshxonasida uchrashdik."),
        ("누군가 빵 조각을 예로 들며 미분을 설명했다.", "Kimdir hosilalarni non bo'laklari misolida tushuntirib berdi."),
        ("또 다른 사람은 밀가루로 식탁 위에 직접 공식을 그렸다.", "Yanasi formulalarni to'g'ridan-to'g'ri stolga un bilan chizdi."),
        ("자정까지 약한 과목들조차 이해되기 시작했다.", "Yarim kechaga kelib hatto zaif mavzular ham ma'noli bo'la boshladi."),
        ("우리는 너무 일찍 축하하고 두 시에 잠들었다.", "Biz juda erta nishonladik va ikkida uxlab qoldik."),
        ("아침 시험에는 특별한 종류의 침묵이 있다.", "Ertalabki imtihonlarda maxsus jimlik bor."),
        ("200자루의 연필이 한꺼번에 쓰는 소리는 부드러운 비처럼 들린다.", "Ikkita yuz qalam bir vaqtda yozganda yumshoq yomg'irdek tovush chiqaradi."),
        ("감독관이 순수한 위협으로 만든 신발을 신고 천천히 걸었다.", "Nazoratchi sekin yurdi, sof tahdid poyabzalini kiyyan holda."),
        ("1번 문제는 자비로웠다. 4번 문제는 범죄였다.", "Birinchi savol rahmli edi; to'rtinchi esa jinoyat edi."),
        ("나는 그것을 나중으로 남기고 계속 앞으로 나아갔다.", "Uni keyinga qoldirdim va oldinga siljiy berdim."),
        ("내 뒤 어딘가에서 누군가 죽어 가는 엔진처럼 한숨을 쉬었다.", "Ortamda kimdir o'layotgan dvigatelday nafas oldi."),
        ("마지막 10분에 돌아와서 나는 그것을 해결했다.", "Oxirgi o'n daqiqa ichida qaytib keldim va uni yechdim."),
        ("맞았는지는 다음 주에야 알게 되었다.", "To'g'ri yoki yo'qligini faqat keyingi haftada bilardim."),
        ("역사 시험은 절박한 날짜 외움의 밤 후에 왔다.", "Tarix imtihoni sanalarning bitta umidsiz kechasidan keyin keldi."),
        ("내 뇌는 왕들을 무작위 전화번호처럼 저장했다.", "Miyam podshohlarni tasodifiy telefon raqamlari kabi saqladi."),
        ("운 좋게도 에세이 주제는 실크로드였다. 내 최애.", "Omadinga, esse mavzusi Ipak yo'li edi — mening sevimlim."),
        ("나는 상단, 향신료, 언어들, 그리고 고향의 역할에 대해 썼다.", "Karvonlar, ziravorlar, tillar va tug'ilgan shahrim roli haqida yozdim."),
        ("사랑하는 것에 대해 쓰는 것은 시험이 아니라 대화처럼 느껴졌다.", "Sevgan narsa haqida yozish suhbatlashgandek, sinovdan o'tmagandek tuyuladi."),
        ("영어는 마지막이었고 교실은 눈에 띄게 편안해졌다.", "Ingliz tili oxiri keldi va xona ko'rinib tinchlantirdi."),
        ("독해 지문은 등대지기에 관한 이야기였다.", "O'qish tushunishi mayoqchining hikoyasini aytib berdi."),
        ("거의 즐겼는데 시험 중이라 불법처럼 느껴졌다.", "Deyarli zavqlandim, bu imtihon paytida noqonuniy tuyuldi."),
        ("마지막 종소리 후 복도는 자유로 폭발했다.", "Oxirgi jiringlashdan keyin koridor ozodlikka portladi."),
        ("낯선 사람들이 낯선 사람을 안았다. 책들이 의례적으로 쓰레기통으로 날아갔다.", "Tanish emaslar tanish emaslarni quchoqladi; kitoblar marosim ravishda axlat idishiga uchdi."),
        ("일부 학생들은 모든 것을 즉시 잊고 멍하게 미소 지었다.", "Ba'zi talabalar hamma narsani darhol unutdilar, bo'sh tabassum bilan."),
        ("우리 조는 강 근처 공원으로 바로 갔다.", "Guruhimiz to'g'ridan-to'g'ri daryo yaqinidagi bog'ga bordi."),
        ("차가운 바람에도 아이스크림을 샀다.", "Sovuq shamolga qaramay muzqaymoq sotib oldik."),
        ("결과는 끝없는 3일 후에 이메일로 도착했다.", "Natijalar cheksiz uch kundan keyin elektron pochta orqali keldi."),
        ("나는 복도 한가운데 서서 내 것을 열었다.", "O'zinikini koridorning o'rtasida turub ochdim."),
        ("수학: 합격. 역사: 합격. 영어: 91점.", "Matematika: o'tdim. Tarix: o'tdim. Ingliz tili: to'qson bir ball."),
        ("집 문을 열기 전에 먼저 어머니께 전화드렸다.", "Uy eshigini ochishdan avval birinchi navbatda onamga qo'ng'iroq qildim."),
        ("어머니는 조금 우시면서 또 밥은 먹었냐고 물으셨다.", "U biroz yig'ladi va yana ovqat yeganimni so'radi."),
        ("그 주는 나에게 공황이 책보다 무겁다는 것을 가르쳤다.", "O'sha hafta vahim kitoblardan og'iroq ekanini o'rgatdi."),
        ("다음 학기에는 1일부터 침착하게 공부할 계획이다.", "Keyingi semestrda birinchi kundan sokin o'qishni rejalashtiryapman."),
    ],
    9: [
        ("나는 저녁 근무 후 막차 야간 버스로 집에 간다.", "Kechki smenadan keyin oxirgi tungi avtobusda uyga qaytaman."),
        ("그 버스는 광장에서 정확히 23시 40분에 출발한다.", "U maydondan aynan yigirma uch qirq daqiqada jo'naydi."),
        ("이 시간에는 승객이 나와 함께 3~4명뿐이다.", "Bu soatda menga faqat uch-to'rt yo'lovchi hamroh bo'ladi."),
        ("운전사는 이제 단골 승객들을 얼굴로 모두 안다.", "Haydovchi endi har bir doimiy yo'lovchini yuzidan tanib oladi."),
        ("그가 나에게 말없이 끄덕이면 우정처럼 느껴진다.", "U menga jim bosh irg'adi, bu esa do'stlikdek tuyuladi."),
        ("버스에서는 디젤, 비, 누군가의 저녁 냄새가 은은하게 난다.", "Avtobusda dizel, yomg'ir va kimningdir kechki ovqati hidi seziladi."),
        ("오늘 밤은 늙은 여성이 큰 자루를 안고 내 뒷좌석에 앉아 있다.", "Bugun kechqurun orqamda katta sumka tutgan keksa ayol o'tiradi."),
        ("그녀의 자루에서 빈 유리병들의 조용한 달그락 소리가 난다.", "Sumkasidan bo'sh idishlarning sokin jiringlashi keladi."),
        ("그녀는 매일 저녁 병들을 시장으로 돌려준다.", "U har shom bozorga idishlarni qaytarib beradi."),
        ("복도 건너편에서 학생 하나가 배낭에 기대 잠들어 있다.", "Yo'lak narida talaba chamadoniga suyanib uxlab yotadi."),
        ("그의 교과서가 무릎 가장자리를 향해 천천히 미끄러진다.", "Uning darsligi tizzalari chetiga sekin sirg'aladi."),
        ("밖의 도시가 느린 텔레비전처럼 미끄러져 지나간다.", "Tashqaridagi shahar sekin televideniedek o'tib ketadi."),
        ("닫힌 상점들은 금속 눈꺼풀을 쓰고 있다. 길잃은 개들이 횡단보도를 소유한다.", "Yopiq do'konlar metall ko'z qovoqlari kiyadi; adashgan itlar chorrahani egallaydi."),
        ("신호등에서 우리는 거리 전체에서 홀로 기다린다.", "Svetoforlarda butun ko'chada yolg'iz kutamiz."),
        ("낡은 노래가 운전사의 라디오에서 조용히 흘러나온다.", "Haydovchining radio eshitish qurilmasidan eski qo'shiq jim chalinadi."),
        ("그는 누구나 들을 수 있다는 걸 모른 채 따라 흥얼거린다.", "U kimdir eshitishini sezmasdan kuylaydi."),
        ("다리 근처 어딘가에서 더 많은 승객들이 올라탄다.", "Ko'prik yaqinidagi bir joyda boshqa yo'lovchilar ham chiqishadi."),
        ("흰 신발의 두 간호사들이 교대 후 탈진한 채 앉았다.", "Oq poyabzallik ikki hamshira smenadan keyin charchagan holda o'tirishadi."),
        ("그들은 짧고 피곤한 문장들로 환자들에 대해 이야기한다.", "Ular bemorlar haqida qisqa charchagan gaplarda gapirishadi."),
        ("젊은 작업자가 강한 냄새나는 페인트 통을 나르고 있다.", "Yosh ishchi kuchli hid beradigan bo'yoq idishlarini olib chiqyapti."),
        ("아무도 불평하지 않는다. 야간 버스에는 인내라는 성문화되지 않은 규칙이 있다.", "Hech kim shikoyat qilmaydi; tungi avtobuslarda sabrning yozilmagan qoidalari bor."),
        ("내 정류장은 약 15분 후에 다가온다.", "Beketim taxminan o'n beshta daqiqa ichida yaqinlashadi."),
        ("나는 습관 때문에 항상 버튼을 너무 일찍 누른다.", "Men doim odatdan erta tugmani bosaman."),
        ("늙은 여성이 갑자기 운전사에게 내일 시간표를 물었다.", "Keksa ayol birdan haydovchidan ertangi jadval haqida so'raydi."),
        ("그녀의 목소리는 밤을 방해하는 게 두려운 듯 부드러웠다.", "Ovozi yumshoq, xuddi kechani bezovta qilishdan qo'rqqanday."),
        ("운전사는 인내심 있게 대답했고 거울 속으로까지 미소 지었다.", "Haydovchi sabrli javob beradi va hatto oynaga tabassum ham qiladi."),
        ("밖에서 비가 다시 시작되며 모든 창문 위에 선을 그었다.", "Tashqarida yomg'ir yana boshlanadi, har bir oynada chiziqlar chizadi."),
        ("학생이 자기 정류장 한 정거장 전에서 공포에 깨어났다.", "Talaba o'z beketidan bir oldingi bekatda vahima bilan uyg'onadi."),
        ("우리 모두는 그가 어둠 속으로 뛰어드는 것을 조용히 웃으며 지켜보았다.", "Hammamiz uni zulmatga yugurganini kuzatib jim kulamiz."),
        ("간호사들은 작은 우산 하나를 나눠 쓰며 함께 내렸다.", "Hamshiralar birga ketishadi, bitta kichik soyabonni bo'lishib."),
        ("이제 유리병을 든 그 여성과 나만 남았다.", "Endi faqat idishli ayol bilan men avtobusda qoldik."),
        ("버스가 추억의 심야 택시처럼 사적인 공간이 되었다.", "Avtobus endi xususiy tuyuladi, xotiralarning kechgi taksidek."),
        ("나는 그 여성에게 손주들이 병을 나르는 것을 도와주냐고 물었다.", "Ayoldan nabiralari idish ko'tarishga yordam berishini so'rayman."),
        ("그녀는 웃으며 그들은 중요한 사람이 되느라 바쁘다고 말했다.", "U kulib, ular muhim odamlar bo'lish bilan band deb javob beradi."),
        ("그녀의 목소리에는 슬픔이 없었고 오직 부드러운 풍자만 있었다.", "Ovozida hafsala yo'q, faqat muloyim hazil bor."),
        ("그녀는 병들이 손녀의 연필값을 마련해 준다고 말했다.", "U idishlar nabirasining qalam pullarini to'lashini aytadi."),
        ("내 정류장이 마침내 왔을 때 나는 그녀의 자루를 내려 드는 것을 도왔다.", "Beketim nihoyat kelganda, sumkasini tushirishga yordam beraman."),
        ("그녀는 굳이 병에서 작은 살구 하나를 주겠다고 했다.", "U menga idishdan bitta mayda o'rik berishga qat'iy qaror qiladi."),
        ("우산 아래 집으로 걸으며 나는 그 살구를 천천히 먹었다.", "Soyabon ostida uyga piyoda qaytayotib, o'rikni sekin yeyman."),
        ("새콤달콤한 맛이 났다. 대부분의 정직한 대화처럼.", "U achchiq-shirin ta'mga ega, eng samimiy suhbatlar kabi."),
        ("도시가 반쯤 잠든 채 내 주위에서 조용히 웅웅거렸다.", "Shahar atrofimdagi jim g'urraydi, yarim uxlagan holda."),
        ("내일 이 버스는 같은 거리들을 또 굴러갈 것이다.", "Ertaga bu avtobus xuddi shu ko'chalar orqali yana yuradi."),
        ("같은 운전사, 같은 침묵, 매일 밤 다른 작은 이야기들.", "Xuddi shu haydovchi, xuddi shu jimlik, har kecha boshqa kichik hikoyalar."),
        ("그래서 나는 야간 버스 위에서 진정으로 외롭다고 느낀 적이 없다.", "Shuning uchun tungi avtobusda hech qachon chin ma'noda yolg'iz his qilmayman."),
    ],
}
