LONG_STORIES_F = {
    9: [
        ("I take the last night bus home after my evening shift.", "Kechki smenadan keyin oxirgi tungi avtobusda uyga qaytaman."),
        ("It leaves from the square at exactly twenty-three forty.", "U maydondan aynan yigirma uch qirq daqiqada jo'naydi."),
        ("Only three or four passengers ride with me at this hour.", "Bu soatda menga faqat uch-to'rt yo'lovchi hamroh bo'ladi."),
        ("The driver knows every regular passenger by face now.", "Haydovchi endi har bir doimiy yo'lovchini yuzidan tanib oladi."),
        ("He nods at me silently, which feels like friendship.", "U menga jim bosh irg'adi, bu esa do'stlikdek tuyuladi."),
        ("The bus smells faintly of diesel, rain, and someone's dinner.", "Avtobusda dizel, yomg'ir va kimningdir kechki ovqati hidi seziladi."),
        ("Tonight, an old woman sits behind me holding a large bag.", "Bugun kechqurun orqamda katta sumka tutgan keksa ayol o'tiradi."),
        ("From her bag comes the quiet clinking of empty jars.", "Sumkasidan bo'sh idishlarning sokin jiringlashi keladi."),
        ("She returns bottles to the market every single evening.", "U har shom bozorga idishlarni qaytarib beradi."),
        ("Across the aisle, a student sleeps against his backpack.", "Yo'lak narida talaba chamadoniga suyanib uxlab yotadi."),
        ("His textbook slides slowly towards the edge of his knees.", "Uning darsligi tizzalari chetiga sekin sirg'aladi."),
        ("The city outside glides past like slow television.", "Tashqaridagi shahar sekin televideniedek o'tib ketadi."),
        ("Closed shops wear metal eyelids; stray dogs own the crossings.", "Yopiq do'konlar metall ko'z qovoqlari kiyadi; adashgan itlar chorrahani egallaydi."),
        ("At the traffic lights, we wait alone in the whole street.", "Svetoforlarda butun ko'chada yolg'iz kutamiz."),
        ("An old song plays quietly from the driver's radio.", "Haydovchining radio eshitish qurilmasidan eski qo'shiq jim chalinadi."),
        ("He hums along without realizing that anyone can hear.", "U kimdir eshitishini sezmasdan kuylaydi."),
        ("Somewhere near the bridge, more passengers climb aboard.", "Ko'prik yaqinidagi bir joyda boshqa yo'lovchilar ham chiqishadi."),
        ("Two nurses in white shoes sit down, exhausted after their shift.", "Oq poyabzallik ikki hamshira smenadan keyin charchagan holda o'tirishadi."),
        ("They speak about patients in short tired sentences.", "Ular bemorlar haqida qisqa charchagan gaplarda gapirishadi."),
        ("A young worker carries paint buckets that smell strongly.", "Yosh ishchi kuchli hid beradigan bo'yoq idishlarini olib chiqyapti."),
        ("Nobody complains; night buses have unwritten rules of patience.", "Hech kim shikoyat qilmaydi; tungi avtobuslarda sabrning yozilmagan qoidalari bor."),
        ("My stop approaches in about fifteen minutes.", "Beketim taxminan o'n beshta daqiqa ichida yaqinlashadi."),
        ("I always press the button too early, out of habit.", "Men doim odatdan erta tugmani bosaman."),
        ("The old woman suddenly asks the driver about tomorrow's schedule.", "Keksa ayol birdan haydovchidan ertangi jadval haqida so'raydi."),
        ("Her voice is soft, like she is afraid to disturb the night.", "Ovozi yumshoq, xuddi kechani bezovta qilishdan qo'rqqanday."),
        ("The driver answers patiently and even smiles into the mirror.", "Haydovchi sabrli javob beradi va hatto oynaga tabassum ham qiladi."),
        ("Outside, rain begins again, drawing lines on every window.", "Tashqarida yomg'ir yana boshlanadi, har bir oynada chiziqlar chizadi."),
        ("The student wakes up in panic one stop before his.", "Talaba o'z beketidan bir oldingi bekatda vahima bilan uyg'onadi."),
        ("We all watch him run into the dark, laughing quietly.", "Hammamiz uni zulmatga yugurganini kuzatib jim kulamiz."),
        ("The nurses leave together, sharing one small umbrella.", "Hamshiralar birga ketishadi, bitta kichik soyabonni bo'lishib."),
        ("Now only the woman with jars and I remain aboard.", "Endi faqat idishli ayol bilan men avtobusda qoldik."),
        ("The bus feels private now, like a late-night taxi of memories.", "Avtobus endi xususiy tuyuladi, xotiralarning kechgi taksidek."),
        ("I ask the woman whether her grandchildren help her carry jars.", "Ayoldan nabiralari idish ko'tarishga yordam berishini so'rayman."),
        ("She laughs and says they are busy becoming important people.", "U kulib, ular muhim odamlar bo'lish bilan band deb javob beradi."),
        ("There is no sadness in her voice, only gentle irony.", "Ovozida hafsala yo'q, faqat muloyim hazil bor."),
        ("She tells me jars pay for her granddaughter's pencils.", "U idishlar nabirasining qalam pullarini to'lashini aytadi."),
        ("When my stop finally arrives, I help lift her bag down.", "Beketim nihoyat kelganda, sumkasini tushirishga yordam beraman."),
        ("She insists on giving me one small apricot from a jar.", "U menga idishdan bitta mayda o'rik berishga qat'iy qaror qiladi."),
        ("Walking home under my umbrella, I eat the apricot slowly.", "Soyabon ostida uyga piyoda qaytayotib, o'rikni sekin yeyman."),
        ("It tastes sweet-sour, like most honest conversations.", "U achchiq-shirin ta'mga ega, eng samimiy suhbatlar kabi."),
        ("The city hums quietly around me, half asleep.", "Shahar atrofimdagi jim g'urraydi, yarim uxlagan holda."),
        ("Tomorrow this bus will roll again through the same streets.", "Ertaga bu avtobus xuddi shu ko'chalar orqali yana yuradi."),
        ("Same driver, same silence, different small stories every night.", "Xuddi shu haydovchi, xuddi shu jimlik, har kecha boshqa kichik hikoyalar."),
        ("That is why I never feel truly lonely on the night bus.", "Shuning uchun tungi avtobusda hech qachon chin ma'noda yolg'iz his qilmayman."),
    ],
}
