LONG_STORIES_AR = {
    0: [
        ("صباح يوم السبت الماضي، استيقظتُ أبكر من المعتاد.", "Shanba kuni ertalab odatdagidan erta turdim."),
        ("كانت الشمس تُشرق من نافذتي، والسماء صافية تمامًا.", "Quyosh derazamdan porlab kirayotgan edi, osmon esa butunlay ochiq."),
        ("رنّ هاتفي، وكان صديقي المفضّل عزيز.", "Telefonim jiringladi — bu eng yaxshi do'stim Aziz edi."),
        ("قال لي: «استعدّ، سنقضي اليوم كلّه معًا!»", "U dediki: 'Tayyorlan, biz butun kunni birga o'tkazamiz!'"),
        ("ضحكتُ لأنه دائمًا يخطّط لشيء غير متوقّع.", "Men kulib qo'ydim, chunki u doim kutilmagan narsa rejalashtiradi."),
        ("التقينا عند موقف الحافلة القريب من بيتي في الساعة التاسعة.", "Biz soat to'qqizda uyim yaqinidagi avtobus bekatida uchrashdik."),
        ("كانت المدينة هادئة، والشوارع شبه خالية.", "Shahar tinch edi, ko'chalar deyarli bo'sh."),
        ("أوّلًا، مشينا إلى مخبز صغير عند الزاوية.", "Avval burchakdagi kichik nonvoyxonaga piyoda bordik."),
        ("رائحة الخبز الطازج جعلتنا نبتسم على الفور.", "Yangi non hidi ikkovimizni darhol tabassumga keltirdi."),
        ("اشترى عزيز قطعتَي خبز دافئتين وأعطاني واحدةً دون أن أطلب.", "Aziz ikkita issiq bulochka oldi va so'ramasdan bittasini menga berdi."),
        ("هذا هو نوع الصديق الذي كان عليه دائمًا.", "U har doim shunday do'st bo'lgan."),
        ("بعد الفطور، قرّرنا أن نتمشّى في الحديقة المركزية.", "Nonushtadan keyin markaziy bog' bo'ylab yurishga qaror qildik."),
        ("كان رجال مسنّون يلعبون الشطرنج تحت الأشجار الخضراء الطويلة.", "Qariyalar baland yashil daraxtlar ostida shaxmat o'ynayotgan edi."),
        ("كان الأطفال يركبون درّاجاتهم ويضحكون بصوت عالٍ.", "Bolalar velosiped haydab, baland ovozda kulayotgan edilar."),
        ("جلسنا على مقعد وتحدّثنا عن خططنا للمستقبل.", "Biz skameykada o'tirdik va kelajak rejalarimiz haqida gaplashdik."),
        ("يريد عزيز أن يفتح مشروعه التجاري الصغير الخاص به العام المقبل.", "Aziz kelasi yili o'zining kichik biznesini ochmoqchi."),
        ("أخبرته عن حلمي بالسفر وتعلّم لغات جديدة.", "Men unga sayohat qilish va yangi tillar o'rganish orzim haqida gapirdim."),
        ("وعدنا بعضنا بالعمل بجدّ وعدم الاستسلام أبدًا.", "Bir-birimizga qattiq ishlash va hech qachon taslim bo'lmaslikka va'da berdik."),
        ("قرابة الظهر، بدأت بطوننا تُصدر قرقرة عالية.", "Taxminan peshin vaqtida qorinlarimiz baland ovozda g'urillay boshladi."),
        ("لذا ذهبنا إلى مكاني المفضّل في المدينة كلّها.", "Shuning uchun shahardagi sevimli joyimga bordik."),
        ("إنه مقهى صغير يُعِدّون فيه أفضل حساء في المدينة.", "Bu shaharda eng mazali sho'rva tayyorlaydigan juda kichik kafe."),
        ("يعرفنا صاحب المقهى جيدًا ويضيف دائمًا خبزًا إضافيًا.", "Egasi bizni yaxshi biladi va doim qo'shimcha non qo'shib beradi."),
        ("أكلنا ببطء وشاهدنا الناس يمرّون أمام النافذة.", "Biz sekin-asta yedik va derazadan o'tayotgan odamlarni kuzatdik."),
        ("فجأة، رأينا معلّمتنا القديمة في المدرسة تعبر الشارع.", "Birdan ko'chani kesib o'tayotgan eski maktab o'qituvchimizni ko'rdik."),
        ("بدت سعيدة، فركضنا إلى الخارج لنُحيّيها.", "U baxtli ko'rindi, shuning uchun uni kutib olish uchun tashqariga yugurdik."),
        ("تذكّرتنا كلينا بعد كلّ هذه السنوات.", "U shu yillar davomida ikkovimizni ham esladi."),
        ("تحدّثنا لمدة عشر دقائق عن ذكريات المدرسة.", "Biz maktab xotiralari haqida o'n daqiqa suhbatlashdik."),
        ("قالت إنها فخورة بالأشخاص الذين أصبحنا عليهم.", "U biz aylanayotgan odamlar bilan faxrlanishini aytdi."),
        ("بقيت كلماتها في قلبي لبقية اليوم.", "Uning so'zlari kun davomida yuragimda qoldi."),
        ("بعد الظهر، زرنا المكتبة الكبيرة في وسط المدينة.", "Tushdan keyin shahar markazidagi katta kitob do'koniga bordik."),
        ("تصفّح عزيز كتبًا عن التجارة والمال.", "Aziz biznes va pul haqidagi kitoblarga qaradi."),
        ("وجدتُ قاموسًا مصوّرًا جميلًا للتعابير الإنجليزية.", "Men inglizcha iboralarning chiroyli rasmli lug'atini topdim."),
        ("اشترينا كتبنا وتقاسمنا لوح شوكولاتة في الخارج.", "Kitoblarimizni oldik va tashqarida bir shokoladni bo'lishdik."),
        ("في طريق العودة إلى البيت، غطّت السحب الداكنة السماء.", "Uyga qaytayotganda qora bulutlar osmonni qopladi."),
        ("بدأ المطر الغزير بمجرد وصولنا إلى موقف الحافلة.", "Avtobus bekatiga yetib kelganimizda kuchli yomg'ir boshlandi."),
        ("وقفنا متقاربَين، نحمي كتبنا الجديدة.", "Yangi kitoblarimizni himoya qilib, yonma-yon turdik."),
        ("كانت رائحة المطر نقيّة، وأصبح الهواء باردًا ومنعشًا.", "Yomg'ir toza hid berdi va havo salqin, yangi bo'lib qoldi."),
        ("عندما وصلنا أخيرًا إلى البيت، كنّا مبتلَّين تمامًا.", "Nihoyat uyga yetganimizda butunlay ho'l bo'lgan edik."),
        ("ضحكت أمي عندما رأتنا نقطر ماءً عند الباب.", "Onam eshik oldida tomchiqayotganimizni ko'rib kuldi."),
        ("أعطتنا شايًا ساخنًا بالليمون وملابس جافّة.", "U bizga limon issiq choy va quruq kiyim berdi."),
        ("شربنا الشاي وأخبرناها عن يومنا كاملًا.", "Choyni ichdik va unga butun kunimiz haqida gapirdik."),
        ("في المساء، أرسل لي عزيز صورةً لنا تحت المطر.", "Kechqurun Aziz menga yomg'irdagi suratimizni yubordi."),
        ("وكتب تحت الصورة: «أفضل يوم سبت على الإطلاق».", "Surat ostiga esa shunday yozdi: 'Eng zo'r shanba.'"),
        ("ابتسمتُ وكتبتُ له أنه يجب أن نكرّر ذلك قريبًا.", "Men tabassum bilan tez orada takrorlashimiz kerak deb yozdim."),
        ("الأصدقاء الحقيقيون يجعلون الأيام العادية تبدو مميّزة.", "Yaxshi do'stlar oddiy kunlarni maxsus qilib ko'rsatadi."),
    ],
    1: [
        ("قبل عامَين، قمتُ برحلتي الجوية الأولى بمفردي.", "Ikki yil oldin birinchi parvozimni yolg'iz amalga oshirdim."),
        ("كنتُ مسافرًا من طشقند إلى إسطنبول لزيارة عمّي.", "Toshkentdan amakisini ko'rgani Istanbulga uchyotgan edim."),
        ("في الليلة السابقة، لم أستطع النوم إطلاقًا.", "Oldingi kechqurun umuman uxlolmadim."),
        ("تفقّدتُ جواز سفري وتذكرتي ربما عشرين مرة.", "Pasportim va biletimni ehtimol yigirma marta tekshirdim."),
        ("جهّزت لي أمي شطائر وحلويات وجوارب دافئة.", "Onam menga tovoq-tort, shirinlik va iliq paypoq solib berdi."),
        ("في المطار، بدا كلّ شيء ضخمًا ومربكًا.", "Aeroportda hamma narsa ulkan va chalkash tuyuldi."),
        ("التفّت طوابير طويلة من المسافرين حول كلّ زاوية.", "Sayohatchilarning uzun navatlari har bir burchakda egri-bugri edi."),
        ("أظهرتُ جواز سفري فابتسم الموظّف بلطف.", "Pasportimi ko'rsatdim va xodim mehribon tabassum qildi."),
        ("طلب مني رجال الأمن أن أخلع حزامي وأفرغ جيوبي.", "Xavfsizlik xodimlari kamarimni yechish va cho'ntaklarimni bo'shatishni so'radi."),
        ("كان قلبي يخفق بسرعة، لكنّ كلّ شيء سار بسلاسة.", "Yuragim tez urayotgan edi, lekin hammasi silliq o'tdi."),
        ("عند البوّابة، شاهدتُ طائرات ضخمة تُقلع واحدة تلو الأخرى.", "Reja oldida ulkan samolyotlarning birma-bir ko'tarilishini kuzatdim."),
        ("كانت محرّكاتها تُزمجر مثل حيوانات عملاقة نائمة.", "Ularning dvigatellari ulkan uxlagan hayvonlar kabi g'irladi."),
        ("بدأ الصعود إلى الطائرة قبل ثلاثين دقيقة من الإقلاع.", "Yo'lovchilarni o'tkazish jo'nashdan o'ttiz daqiqa oldin boshlandi."),
        ("سلّمتُ تذكرتي بيدَين ترتجفان قليلًا.", "Biletimni biroz titrayotgan qo'llarim bilan topshirdim."),
        ("رحّبت بي مضيفة طيران ودودة على متن الطائرة.", "Samimiy stuardessa menga bortda xush kelibsiz dedi."),
        ("كان مقعدي بجانب النافذة، تمامًا كما تمنّيت.", "O'rinishim oynaga yondosh edi, aynan umid qilganimdek."),
        ("جلست سيدة مسنّة بجانبي ورحّبت بي بحرارة.", "Yonimga keksa ayol o'tirdi va meni iliqlik bilan kutib oldi."),
        ("لاحظت توتّر وجهي فبدأت حديثًا.", "U bezovta yuzimni sezib, suhbatni boshladi."),
        ("أخبرتني أنها سافرت جوًّا أكثر من خمسين مرة.", "U ellik martadan ortiq parvoz qilganini aytdi."),
        ("صوتها الهادئ جعلني أسترخي تدريجيًا.", "Uning osoyishta ovozi meni asta-sekin tinchlantirdi."),
        ("تحرّكت الطائرة إلى المدرج وتوقّفت للحظة.", "Samolyot uchish yo'lagiga chiqib bir lahza to'xtadi."),
        ("ثم دفعتنا المحرّكات إلى الأمام بسرعة متزايدة.", "Keyin dvigatellar bizni tobora tezroq oldinga surdi."),
        ("فارقت العجلات الأرض، وشعرتُ بمعدتي تهبط.", "G'ildiraklar yerdan uzildi va qornim tushib ketdi."),
        ("أصبحت البيوت صغيرة، وتحوّلت الطرق إلى خطوط رفيعة.", "Uylar kichiklashdi, yo'llar ingichka chiziqlarga aylandi."),
        ("فوق السحب، كان العالم مشرقًا وصامتًا.", "Bulutlar ustida dunyo ravon va jim edi."),
        ("بدت السحب تحتنا وكأنها جبال بيضاء ناعمة.", "Ostimizdagi bulutlar yumshoq oq tog'largagina o'xshardi."),
        ("أشارت السيدة إلى البحر البعيد عند الأفق.", "Ayol ufqdagi uzoq dengizni ko'rsatdi."),
        ("وصلت وجبة بعد الإقلاع بوقت قصير، دجاج مع أرز.", "Ko'tarilishdan ko'p o'tmay ovqat keldi — tovuq guruch bilan."),
        ("أكلتُ كلّ شيء لأنّ الحماس يجعلني جائعًا.", "Hammasini yedim, chunki hayajon meni och qiladi."),
        ("لاحقًا، حاولتُ مشاهدة فيلم لكنني ظللتُ أنظر من النافذة.", "Keyinchalik film ko'rishga harakat qildim, lekin doimo oyna tomonga qaradim."),
        ("في مكان ما فوق البحر الأسود، دخلنا في اضطراب هوائي خفيف.", "Qora dengiz ustidagi bir joyda yengil silkinishga kirishdik."),
        ("اهتزّت الطائرة قليلًا، وتجمّدت يداي.", "Samolyot biroz larzaga keldi va qo'llarim qotib qoldi."),
        ("قالت السيدة ببساطة: «إنها مجرّد مطبّات على الطريق».", "Ayol shunchaki dediki: 'Faqat yo'ldagi to'siqlar'."),
        ("سرعان ما هدأت السماء تمامًا من جديد.", "Tez orada osmon yana butunlay tinchlandi."),
        ("أعلن القبطان أننا سنهبط بعد خمس عشرة دقيقة.", "Kapitan o'n beshta daqiqada qo'nishimizni e'lon qildi."),
        ("من الأعلى، تلألأت إسطنبول بآلاف الأضواء.", "Yuqoridan Istanbul minglab chiroqlar bilan yaltiradi."),
        ("ظهر مضيق البوسفور مثل شريط فضّي بين قارّتين.", "Bosfor ikki qit'a orasida kumir lenta kabi namoyon bo'ldi."),
        ("كان الهبوط أكثر سلاسة من المرور فوق مطبّ سرعة.", "Qo'nish tezlik to'sig'idan o'tishdan ham silliqroq tuyuldi."),
        ("صفّق الجميع بهدوء عندما توقّفت الطائرة.", "Samolyot to'xtaganda hammam yengil qarsak chaldi."),
        ("شكرتُ السيدة اللطيفة وتمنّيتُ لها الصحة.", "Mehmondo'st ayolga rahmat aytdi va sog'liq tiladim."),
        ("عند استلام الأمتعة، وصلت حقيبتي أولًا، على نحو مفاجئ.", "Bagaj olish joyida chamadonim kutilmaganda birinchi bo'lib keldi."),
        ("كان عمّي ينتظر خلف الزجاج ممسكًا بلافتة كبيرة.", "Amakim katta yozuv bilan shisha ortida kutib turgan edi."),
        ("جعل عناقه كلّ خوفي يختفي على الفور.", "Uning quchoqlashi barcha qo'rquvni darhol yo'q qildi."),
        ("ونحن ندخل المدينة، ظللتُ أردّد: «لقد طرتُ فعلًا!»", "Shahar tomon ketayotib, doim takrorladim: 'Men rostan uchdim!'"),
        ("منذ ذلك اليوم، أحببتُ كلّ رحلة طيران.", "O'sha kundan buyon har bir parvozni yaxshi ko'raman."),
    ],
    2: [
        ("في يوم ثلاثاء ممطر، اكتشفتُ مقهى صغيرًا قرب المكتبة.", "Yomg'irli seshanba kuni kutubxona yaqinida kichik kafeni kashf etdim."),
        ("كان لبابه الخشبي مقبضٌ نحاسي صغير على شكل حبّة قهوة.", "Uning yog'och eshigida qahva donasiga o'xshash kichik guruch dastasi bor edi."),
        ("في الداخل، كانت رائحة القرفة وحبوب القهوة المحمّصة تملأ الهواء.", "Ichkarida havoda doljin va qovurilgan don hidi bor edi."),
        ("كانت موسيقى جاز هادئة تُعزف بخفوت من مكبّر صوت قديم.", "Eski karnaydan nozik jaz musiqasi jim chalinayotgan edi."),
        ("لم يكن مشغولًا سوى ثلاث طاولات بطلّاب يحملون حواسيبهم المحمولة.", "Faqat uch stul noutbukli talabalar bilan band edi."),
        ("رحّبت بي شابّة خلف المنضدة بإيماءة دافئة.", "Dollar ortidagi yosh ayol meni iliqlik bilan bosh irg'ab kutib oldi."),
        ("طلبتُ كابتشينو وقطعة من فطيرة التفّاح.", "Men kapuchino va olcha pie bo'lagini buyurtma qildim."),
        ("بينما كنتُ أنتظر، قرأتُ قائمة الطعام المكتوبة بخط اليد على السبّورة.", "Kutayotib, doskadagi qo'lyozma menyuni o'qidim."),
        ("كانوا يقدّمون مشروبات بأسماء طريفة مثل «لاتيه السحابة».", "Ularda 'Bulut latte' kabi kulgili nomlar bilan ichimliklar bor edi."),
        ("وصلت قهوتي مع ورقة صغيرة مرسومة على رغوة الحليب.", "Mening kahvam sut ko'pigi ichiga chizilgan mayda yaproq bilan keldi."),
        ("كانت فطيرة التفّاح لا تزال دافئة من الفرن.", "Olcha pie hali ham tandirdan chiqqancha iliq edi."),
        ("كانت كلّ قضمة تشبه طعم الخريف في بلدة صغيرة.", "Har bir luqma kichik shaharchadagi kuzni eslatardi."),
        ("فتحتُ دفتري وبدأتُ أكتب رسالة إلى نفسي.", "Daftarchamni ochdim va o'zimga xat yozishni boshladim."),
        ("كان المطر يطرق بلطف على النافذة الكبيرة بجانبي.", "Yomg'ir yonimdagi katta oynaga yumshoq urildi."),
        ("دخل رجل عجوز، ينفض الماء عن مظلّته الرمادية.", "Keksaygan erkak kirdi, kulrang soyabonidan suv silkitib."),
        ("حيّا الجميع بأسمائهم، حتى الطاهي في المطبخ.", "U hammaga, hatto oshxona oshpazi ham, ismi bilan salom berdi."),
        ("كان واضحًا أنه زبون دائم هنا منذ سنوات عديدة.", "Aniqki, u bu yerda ko'p yillardan beri doimiy mehmon edi."),
        ("أحضرت له النادلة طلبه المعتاد من دون أن يسأل.", "Ofitsiant uning odatbuy buyurtmasini so'ramasdin keltirdi."),
        ("شاي قويّ، وسكّر واحد بجانبه، وقطعة بسكويت بالزبدة.", "Kuchli choy, bir qoshiq shakar alohida va saryog'li pechene."),
        ("وأنا أراقبه، فهمتُ لماذا يحبّ الناس المقاهي الصغيرة.", "Uni kuzatib, odamlarning kichik kaflarni nega sevishi tushundim."),
        ("الأماكن الكبيرة تخدمك، أمّا الأماكن الصغيرة فتتذكّرك.", "Katta joylar sizga xizmat qiladi, kichik joylar esa eslab qoladi."),
        ("بعد نصف ساعة، جلست صديقتان بالقرب مني.", "Yarim soatdan keyin yonimga ikki dugona o'tirdi."),
        ("تجادلتا بمرح حول أيّ حلوى يتقاسمانها.", "Ular qaysi desertni bo'lishish masalasida o'yinkam bahslashdi."),
        ("أخيرًا، اخترتا كعكة الجبن بصلصة الفراولة.", "Nihoyat, ular maydalangan pishiriqni tanlashdi."),
        ("امتزج ضحكهما بجمال مع أصوات المطر.", "Ularning kulishi yomg'ir tovushlari bilan chiroyli qorishdi."),
        ("أنهيتُ قهوتي وطلبتُ فنجانًا ثانيًا دون شعور بالذنب.", "Kahvamni tugatib, ikkinchi finjanni vijdontsiz buyurtma qildim."),
        ("ابتسمت النادلة وكأنها توافق تمامًا.", "Ofitsiant xuddi to'liq ma'qullayotgandek tabassum qildi."),
        ("بين رشفة وأخرى، شاهدتُ صانع القهوة يرسم فنّ اللاتيه.", "Luqmalar orasida barista latte san'atini quyayotganini tomosha qildim."),
        ("تحرّكت يداها بثقة، مثل فنّانة ترسم لوحة.", "Uning qo'llari rassom chizayotgandek ishonch bilan harakatlanardi."),
        ("حصلت فتاة صغيرة على الطاولة المجاورة على شوكولاتة ساخنة.", "Qo'shni stoladagi kichkina qiz issiq shokolad oldi."),
        ("اتّسعت عيناها عندما رأت حلوى المارشميلو تطفو بداخلها.", "Ichida suzayotgan zefirni ko'rib, ko'zlari kengaydi."),
        ("همست: «هذا أفضل يوم في حياتي».", "U shivirladi: 'Bu mening hayotimdagi eng yaxshi kun.'"),
        ("ضحكت أمّها وسرقت قطعة مارشميلو واحدة خلسةً.", "Onasi kuldi va bir zefirni maxfiy o'g'irladi."),
        ("لحظات كهذه لا يمكن التخطيط لها أو شراؤها.", "Bunday lahzalarni rejalashtirib yoki sotib olb bo'lmaydi."),
        ("في الخارج، خفّ المطر أخيرًا إلى قطرات خفيفة.", "Tashqarida yomg'ir nihoyat yengil tomchilarga aylandi."),
        ("انعكست أضواء الشوارع الذهبية على الرصيف المبلّل.", "Oltin ko'cha chiroqlari ho'l troyni aks ettirdi."),
        ("دفعتُ حسابي وتركتُ إكرامية سخيّة.", "Hisobni to'lab, saxiy chaqa qoldirdim."),
        ("شكرتني النادلة ولوّحت بيدها مودّعةً بحرارة.", "Ofitsiant menga rahmat aytdi va iliq xayrli yol dedi."),
        ("عند الباب، التفتُّ لألقي نظرة أخيرة.", "Eshik oldida oxirgi marta orqaga burilib qaradim."),
        ("كان المقهى يتوهّج مثل فانوس في المساء الرمادي.", "Kafe kulrang kechda fonar kabi yonib turardi."),
        ("الآن أزور ذلك المقهى كلّ يوم ثلاثاء.", "Endi har seshanba kuni o'sha kafega boraman."),
        ("نفس الطاولة، ونفس الكابتشينو، ونفس الشعور الدافئ.", "Xuddi shu stol, xuddi shu kapuchino, xuddi shu iliq tuygu."),
        ("أحيانًا تحتفظ لي النادلة بآخر قطعة من الفطيرة.", "Ba'zan ofitsiant menga oxirgi pie bo'lagini saqlab qo'yadi."),
        ("طقوس صغيرة كهذه تجعل الحياة حلوة ومستقرّة.", "Bunday kichik an'anelar hayotni shirin va muqim qiladi."),
    ],
    3: [
        ("شعرتُ أنّ أسبوعي الأول في المكتب الجديد كان أشبه بحلم.", "Yangi ofisdagi ilk haftam tushga o'xshab tuyuldi."),
        ("جهّزتُ ملابسي في الليلة التي سبقت أول يوم لي.", "Birinchi kundan oldingi kechqurun kiyimlarimni tayyorladim."),
        ("وصلتُ قبل الموعد بأربعين دقيقة بسبب توتّري.", "Asabiyligidan qirq daqiqa erta yetib keldim."),
        ("كان حارس الأمن أول شخص تحدّث إليّ.", "Qo'riqchi menga gapirgan birinchi odam bo'ldi."),
        ("قال لي: «اهدأ، الجميع ينجو من يوم اثنينه الأول».", "U dediki: 'Bo'shasangiz, hamma birinchi dushanbasidan o'tadi.'"),
        ("استقبلتني مديرتي عند الاستقبال بابتسامة مشرقة.", "Mening menejerim meni qabulxonda yorqin tabassum bilan kutib oldi."),
        ("أخذتني في جولة سريعة على الطابق بأكمله.", "U menga butun qavatni tezkor sayohat qilib ko'rsatdi."),
        ("كانت رائحة كلّ شيء جديدة، من السجّاد إلى شاشات الحواسيب.", "Hamma narsa yangi hid berdi — gilamlardan kompyuter ekranlarigacha."),
        ("كان مكتبي صغيرًا لكنه بجوار نافذة واسعة مباشرة.", "Stolim kichik edi, lekin katta oynaning yonida joylashgan."),
        ("عرّف عشرة غرباء بأنفسهم قبل موعد الغداء.", "Tushlikkacha o'n noma'lum odam o'zini tanishtirdi."),
        ("نسيتُ نصف أسمائهم على الفور، بصراحة.", "Halos, ularning ismlarining yarmisini darhol unutdim."),
        ("أنقذني زميلي دوستون لاحقًا بقائمة مطبوعة بالأسماء.", "Jamoadoshim Doston keyinroq chop etilgan ro'yxat bilan menga yordam berdi."),
        ("شرح لي قواعد المكتب بروح فكاهية لطيفة.", "U ofis qoidalarini muloyim hazil bilan tushuntirib berdi."),
        ("على سبيل المثال، تبدأ الاجتماعات دائمًا متأخّرة خمس دقائق.", "Masalan, uchrashuvlar doim besh daqiqa kech boshlanadi."),
        ("وتتعطّل آلة القهوة كلّ يوم جمعة بعد الظهر.", "Va qahva mashinasi har juma kuni tushdan keyin buziladi."),
        ("في الثلاثاء، حضرتُ أوّل اجتماع فريق حقيقي لي.", "Seshanba kuni ilk haqiqiy jamoa uchrashuvimda qatnashdim."),
        ("كان الجميع يتحدّثون بسرعة ويستخدمون اختصارات غامضة.", "Hamma tez gapirdi va sirli qisqartmalardan foydalandi."),
        ("أومأتُ برأسي بجدّية رغم أنني لم أفهم سوى ستين بالمئة.", "Faqt faqat oltmish foizini tushungan bo'lsamda, jiddiy bosh irg'adim."),
        ("بعد ذلك، دوّنتُ كلّ كلمة غير مألوفة.", "Keyin har bir tanish emas so'zni yozib oldim."),
        ("في ذلك المساء، درستُها مثل مفردات مدرسية.", "O'sha kechqurun ularni maktab lug'ati kabi o'rgandim."),
        ("بحلول الأربعاء، أصلحتُ أوّل خطأ صغير لي في النظام.", "Chorshanba kunga kelib, tizimdagi ilk kichik xatoni tuzatdim."),
        ("أثنى مشرفي على عملي أمام الجميع.", "Rahbarim ishimni hamma oldida maqtadi."),
        ("احمرّت أذناي، لكنني شعرتُ وكأنني أطول بعشرة سنتيمترات.", "Quloqlarim qizaridi, lekin o'zimni o'n santimetr balandroq his qildim."),
        ("جاء يوم الخميس بتقليد غداء المكتب.", "Payshanba kuni ofis tushlik an'anasini olib keldi."),
        ("يطهو الجميع أو يُحضر طبقًا واحدًا من المنزل.", "Har kim uyida bir taom tayyorlaydi yoki olib keladi."),
        ("أحضرتُ أرز البيلاف الذي أعدّته أمي، فاختفى بسرعة.", "Onamning guruch palovini olib keldim, u tez tugadi."),
        ("جاء أشخاص من أقسام أخرى ليسألوا عن الوصفة.", "Boshqa bo'limlardagi odamlar retseptni so'rab kelishdi."),
        ("انتهى يوم الجمعة بكعكة لأنّ أحدهم كان في عيد ميلاده.", "Juma kuni tort bilan tugadi, chunki kimningdir tug'ilgan kuni edi."),
        ("غنّينا بهدوء، كما تفعل المكاتب، بين الغناء والهمس.", "Biz jim qo'shiq aytdik, ofislarda odat bo'lganidek, yarim kuylanib yarim shivirlab."),
        ("خلال ذلك الأسبوع، تعلّمتُ ثلاثة دروس مهمّة.", "O'sha hafta davomida uch muhim darsni o'rgandim."),
        ("أولًا، طرح الأسئلة قوّة لا ضعف.", "Birinchisi, savol berish kuchsizlik emas, kuch."),
        ("ثانيًا، مشية قصيرة تُنعش العقل المتعب.", "Ikkinchisi, qisqa sayr charchagan miygacha yordam beradi."),
        ("ثالثًا، يصبح الزملاء أصدقاء أسرع ممّا تتوقّع.", "Uchinchisi, hamkasblar kutgandan ham tezroq do'stga aylanadi."),
        ("مساء الجمعة، أصبح صندوق بريدي فارغًا أخيرًا.", "Juma kechqurun pochtam nihoyat bo'sh edi."),
        ("نظرتُ إلى مكتبي وشعرتُ بفخر هادئ.", "Stolimga qarab sokin iftixor his qildim."),
        ("قبل أسبوع واحد، كان هذا المكان مجهولًا ومخيفًا.", "Bir hafta oldin bu joy noma'lum va qo'rqinchli edi."),
        ("الآن أصبح يشعرني وكأنه بيتي الثاني.", "Endi u allaqachon ikkinchi uyday tuyuladi."),
        ("لوّح لي حارس الأمن وأنا أغادر.", "Chiqib ketayotib, qo'riqchi menga qo'l silkitdi."),
        ("قال: «أراك يوم الاثنين»، وكأنه صديق قديم.", "'Dushanba ko'rishamiz', deb aytdi u eski do'stday."),
        ("في الحافلة عائدًا إلى البيت، ابتسمتُ من دون سبب محدّد.", "Uyga qaytayotgan avtobusda hech kimga bog'liq bo'lmagan sababsiz tabassum qildim."),
        ("كانت قدماي تؤلماني، لكنّ قلبي كان خفيفًا.", "Oyoqlarim og'ridi, lekin yuragim yengil edi."),
        ("أرسلتُ رسالة إلى والدَيّ أخبرهما أنّ هذه الوظيفة مناسبة لي.", "Ota-onamga bu ish to'g'ri kelayotganini yozdim."),
        ("ردّ أبي بكلمة واحدة: «أخيرًا».", "Otam bitta so'z bilan javob berdi: 'Nihoyat.'"),
        ("غفوتُ تلك الليلة وبطاقة عملي لا تزال معلّقة عليّ.", "O'sha kechqurun ish belgisimni yechmasdan uxlab qoldim."),
    ],
    4: [
        ("في كلّ أحد ثانٍ، تجتمع عائلتنا في بيت جدّتي.", "Har juftshanba kuni oilamiz bobomizning uyida yig'iladi."),
        ("يقع بيتها في نهاية شارع هادئ مليء بأشجار الحور.", "Uning uyi teraklar bilan to'lgan sokin ko'chaning oxirida joylashgan."),
        ("يمكنك سماع العصافير حتى قبل أن تطرق الباب.", "Darvoza urishdan avval qushlar ovozini eshitishingiz mumkin."),
        ("تبدأ جدّتي الطبخ عند الفجر، مرتديةً مئزرها الأرجواني.", "Bobomiz tong otishidan boshlab oshxona boshlaydi, binafsha fartugi kiyingan holda."),
        ("تستقبلنا رائحة السمبوسة الطازجة عند الباب.", "Yangi somsa hidi bizni eshik oldida kutib oladi."),
        ("يتجادل الأعمام بمرح حول سيارة مَن ركنها أفضل.", "Amakilar kimning mashinasi yaxshi to'xtaganligi haqida quvonch bilan bahslashadi."),
        ("يركض أبناء العمّ في الحديقة ملاحقين كرة قدم قديمة.", "Amakivachchalar bog'da eskicha futbol ortidan yugurishadi."),
        ("يتعثّر أحدهم دائمًا بخرطوم الحديقة، في كلّ مرّة.", "Har safar kimdir bog'dagi shlangaga tiqilib yiqiladi."),
        ("تجلس العمّات على الشرفة يقارنّ الصور على هواتفهنّ.", "Xolalar verandada telefonlaridagi suratlarni solishtirib o'tirishadi."),
        ("يحرس جدّي رقعة الشطرنج مثل ملك صغير.", "Bobomiz shaxmat taxtasini kichik qirol kabi qo'riqlaydi."),
        ("يتحدّى كلّ حفيد ويهزم معظمنا.", "U har bir nabirasini o'yin chorlaydi va ko'pchiligimizni mag'lub etadi."),
        ("خسرتُ مرّتين اليوم وطالبتُ بمباراة إعادة بعد الغداء.", "Bugun ikki marta yutqazdim va tushlikdan keyin revansh talab qildim."),
        ("في المطبخ، لا تقيس جدّتي أيّ شيء أبدًا.", "Oshxonada Bobomiz hech narsani o'lchamaydi."),
        ("تقول إنها تضيف الملح «بالإنصات إلى الطعام».", "U tuzni 'ovqat tinglab' qo'shishini aytadi."),
        ("تتمدّد عجينتها رقيقة مثل ورق ذهبي.", "Uning xamiri oltin qog'oz kabi ingichka cho'ziladi."),
        ("كلّ الأسرار تكمن في معصمَيها، لا في الوصفات.", "Barcha sirlar retseptlarda emas, bilaklarida yashirilgan."),
        ("أساعد بغسل الأطباق وسرقة الخبز الدافئ.", "Men idish yuvgani va iliq non o'g'irlashga yordam beraman."),
        ("تتظاهر بعدم رؤيتي في كلّ مرّة.", "U har safar meni ko'rmagan bo'lib qiyofa beradi."),
        ("في الساعة الثانية، تئنّ الطاولة الطويلة تحت ثقل الأطباق.", "Soat ikkida uzun stol taomlar ostida ingichka ovoz chiqaradi."),
        ("بيلاف، وسلطات، وسمبوسة، وفواكه، وثلاثة أنواع من الشاي.", "Palov, salatlar, somsa, mevalar va uch xil choy."),
        ("قبل الأكل، يقول جدّي كلمات شكر هادئة.", "Yeyishdan oldin Bobomiz bir nechta sokin minnatdorchilik so'zi aytadi."),
        ("ثم تنفجر الغرفة بالحديث والضحك.", "Keyin xona gapirish va kulish bilan portlaydi."),
        ("يتحدّث الجميع في آنٍ واحد، وبطريقة ما ينجح الأمر.", "Hamma bir vaqtda gapiradi va bir yo'l bilan hammasi mos keladi."),
        ("تُلقي زهرة الصغيرة قصيدة وهي واقفة على كرسي.", "Kichkina Zuhra kursida turub she'r aytyapti."),
        ("نصفّق بصوت عالٍ جدًا، فتنحني مثل ممثّلة.", "Biz juda baland qarsak chaldik va u aktrisa kabi egildi."),
        ("بعد الوجبة، يروي الكبار قصصًا من شبابهم.", "Ovqatdan keyin kattalar yoshliklaridagi hikoyalarni aytishadi."),
        ("كانت حكاية اليوم عن فقدان جدّي لعنزة عام ١٩٧٥.", "Bugungi hikoya Bobomizning 1975-yilda echisini yo'qotishi haqida edi."),
        ("ينكر نصفها، وهذا ما يثبت صحّتها.", "U yarmi inkor etadi, bu esa uning rostligini isbotlaydi."),
        ("يتظاهر المراهقون بعدم الاستماع لكنهم يسمعون كلّ شيء.", "O'smirliklar tinglamaslikka harakat qiladi, ammo hammasini eshitishadi."),
        ("لاحقًا، نقطف التفّاح من الشجرة خلف البيت.", "Keyinchalik uy ortidagi daraxtdan olma teramiz."),
        ("أفضل الثمار تُعلَّق في الأعلى، بطبيعة الحال.", "Eng zo'rlari tabiiy ravishda balandda osilgan bo'ladi."),
        ("يحملني ابن عمّي على كتفَيه كما في الأيّام الخوالي.", "Amakivachcham meni eski vaqtlarday yelkasiga ko'taradi."),
        ("نملأ سلّة واحدة ونأكل سلّة أخرى بهدوء.", "Bir savat to'ldiramiz va yana bir savatni jim yeymiz."),
        ("تعدّ جدّتي التفّاح لاحقًا وتكتفي بابتسامة عارفة.", "Bobomiz keyinchalik olmalarni sanab, anglagan holda tabassum qiladi."),
        ("قرب المساء، يُحضر أحدهم ألبوم الصور القديم.", "Kechga yaqin kimdir eskicha fotoalbomni olib chiqadi."),
        ("يحدّق أجدادنا بالأبيض والأسود إلينا، شبابًا إلى الأبد.", "Qora-oq bobolarimiz bizga abadiy yosh holda qarashadi."),
        ("تُشير أمي إلى فستان زفاف جدّتي وتتنهّد.", "Onam Bobomizning to'y ko'ylagini ko'rsatib nafas oladi."),
        ("تُلوّح جدّتي بيدها وتقول إنّ الموضة تتكرّر.", "Bobomiz qo'l silkitadi va moda takrorlanishini aytadi."),
        ("عندما تتحوّل السماء إلى برتقالي، تبدأ السيارات بالاصطفاف.", "Osmon to'qsarig' aylanganda mashinalar navbatga turadi."),
        ("لا أحد يريد أن يكون أوّل عائلة تغادر.", "Hech kim birinchi bo'lib ketadigan oila bo'lishni istamaydi."),
        ("نتعانق مئة مرّة عند البوّابة، كالمعتاد.", "Odatdagidek darvoza oldida yuz marta quchoqlashamiz."),
        ("تملأ جدّتي حقائبنا حتى تكاد لا تُغلق.", "Bobomiz sumkalarimizni zo'rg'a yopiladigan darajada to'ldiradi."),
        ("في طريق العودة، تفوح من السيارة رائحة التفّاح والخبز الدافئ.", "Uyga qaytayotib, mashina olma va iliq non hidi beradi."),
        ("يغفو أخي الصغير ممسكًا ببسكويتة نصف مأكولة.", "Kichik ukam yarim yegan pecheneni qo'liga olib uxlab qoladi."),
        ("أيّام الأحد هذه بسيطة، صاخبة، ومثالية تمامًا.", "Bu shanbalar oddiy, shovqinli va mutlaqo mukammal."),
    ],
    5: [
        ("في الشتاء الماضي، قرّرتُ شراء معطف شتوي جادّ.", "O'tgan qish men jiddiy qishki palto sotib olishga qaror qildim."),
        ("كانت سترتي القديمة رقيقة وتخذلني في كلّ ديسمبر.", "Eski kurtkam ingichka edi va har dekabrda menga xiyonat qilardi."),
        ("ادّخرتُ المال لمدة شهرَين مثل سنجاب مصمّم.", "Ikki oy davomida qat'iyatli sichqon kabi pul yig'dim."),
        ("صباح السبت، ذهبتُ أنا وأختي إلى السوق الكبير.", "Shanba ertalab opam bilan katta bozorga bordik."),
        ("السوق في الشتاء بحر من المعاطف الرمادية والسوداء.", "Qishda bozor kulrang va qora paltolar dengizidir."),
        ("كان كلّ بائع يصيح بأنّ متجره يقدّم أفضل سعر.", "Har bir savdogar o'z do'konida eng zo'r narx borligini baqirdi."),
        ("دعانا أحد الباعة لشرب الشاي قبل أن نتفقّد المكان حتى.", "Bir savdogar atrofga qaramay choyga taklif qildi."),
        ("ضحكنا وقبلنا، لأنّ الرفض بدا وقاحة.", "Kulib qabul qildik, chunki rad etish qo'pollik tuyuldi."),
        ("كان الشاي ساخنًا وحلوًا، ويُعاد ملؤه بشكل خطير.", "Choy issiq, shirin va xavfli darajada qayta quyiladigan edi."),
        ("بعد ثلاثة أكواب، تحدّثنا أخيرًا عن المعاطف.", "Uch piyola choynan keyin nihoyat paltolar haqida gaplashdik."),
        ("أراني معطفًا أسود ثقيلًا بجيوب عميقة.", "U menga chuqur cho'ntakli og'ir qora paltoni ko'rsatdi."),
        ("كان دافئًا لكنه جعلني أبدو كخزانة ملابس متحرّكة.", "U iliq edi, lekin meni yuruvchi shkafga o'xshatdi."),
        ("حاولت أختي ألّا تضحك ففشلت تمامًا.", "Opam kulmaslikka harakat qildi va butunlay muvaffaqiyatsiz bo'ldi."),
        ("اعترف البائع بأنه «معطف للآباء».", "Savdogar bu 'otolar uchun palto' ekanini tan oldi."),
        ("في المتجر التالي، وجدتُ معطفًا كحليًا بأزرار فضّية.", "Keyingi do'konda kumush tugmali to'q ko'k palto topdim."),
        ("قالت المرآة نعم قبل أن تحتجّ محفظتي.", "Oyna hamyonim bahslashidan oldin 'ha' dedi."),
        ("لكنّ السعر جعلني أجلس للحظة.", "Lekin narx meni bir lahza o'tirishga majbur qildi."),
        ("بدأت أختي المفاوضة مثل دبلوماسية محترفة.", "Opam professional diplomatchidek savdohni boshladi."),
        ("ذكرت متجرًا آخر، والجودة، وراتب أخيها الصغير.", "U boshqa do'konni, sifatni va akasining kichik maoshini tilga oldi."),
        ("تظاهر البائع بالاتّصال بمديره لطلب الإذن.", "Savdogar ruxsat uchun boshlig'iga qo'ng'iroq qilganday bo'ldi."),
        ("الجميع، بمن فيهم هو، عرف أنه لم يتّصل بأحد.", "Qo'ng'iroq yo'qligini hamma, hatto u ham bilardi."),
        ("أخيرًا، اتّفقنا على سعر فاجأنا كلينا.", "Nihoyat ikkovimizni ham hayron qoldirgan narxda kelishdik."),
        ("دفعتُ الثمن، ووقع المعطف بين ذراعَيّ كصديق جديد.", "To'lov qildim va palto yangi do'stdek quchoqlarimga sig'di."),
        ("في طريق الخروج، اشترينا ذرة مشوية من بائع متجوّل.", "Chiqib ketayotib, ko'cha sotuvchisidan qovurilgan makkajo'xori oldik."),
        ("أكل الذرة في الريح الباردة موهبة خاصّة هنا.", "Sovuq shamolda makkajo'xori yeyish bu yerda maxsus qobiliyat."),
        ("في البيت، فحص أبي المعطف مثل موظّف جمارك.", "Uyda otam paltoni bojxona xodimidek tekshirdi."),
        ("فحص الخياطة والبطانة والأزرار، بل شمّه أيضًا.", "U choklar, astar, tugmalarni tekshirdi, hatto hidini ham sinadi."),
        ("ثم أومأ برأسه ببطء، وهي أعلى درجات إطرائه.", "Keyin u sekin bosh irg'adi — bu uning eng baland maqtovi."),
        ("خاطت أمي زرًا واحدًا بإحكام أكبر «احتياطًا».", "Onam bir tugmani 'ehtiyot uchun' darhol mustahkam tikdi."),
        ("تلك الليلة، علّقتُ المعطف في مكان أراه فيه.", "O'sha kechqurun paltoni ko'radigan joyimga osdim."),
        ("أعلم أنّ هذا يبدو سخيفًا، لكنني كنتُ فخورًا حقًا.", "Ahmoqona tuyulishini bilaman, lekin chin dildan faxrlanardim."),
        ("بعد يومَين، حلّ الصقيع الحقيقي في المدينة.", "Ikki kundan keyin shaharga haqiqiy qattiq sovuq keldi."),
        ("لفّني المعطف مثل صمت دافئ في وجه الريح.", "Palto meni shamolga qarshi iliq sokinlik kabi o'ray oldi."),
        ("عند موقف الحافلة، سألني رجل عجوز أين اشتريته.", "Avtobus bekatida keksa odam uni qayerdan olganimni so'radi."),
        ("أشرتُ بفخر نحو السوق وأعطيته كلّ التفاصيل.", "Faxr bilan bozor tomonga ishora qilib barcha tafsilotlarni berdim."),
        ("كتب العنوان على يده بقلم رصاص قصير.", "U manzilni qalam bo'lagi bilan kaftiga yozib oldi."),
        ("في يناير، طلبت أختي استعارته لأمسية واحدة.", "Yanvarda opam uni bir kecha so'rab oldi."),
        ("أعادته وتفوح منه رائحة عطرها الخفيفة.", "Uni engil parfyum hidi bilan qaytarib berdi."),
        ("تظاهرتُ بالغضب وأعرته إياه مجدّدًا الأسبوع التالي.", "Jahl ko'ringanday qildim va keyingi haftada yana berdim."),
        ("بحلول فبراير، كانت العائلة كلّها قد ارتدت ذلك المعطف مرّة.", "Fevralga kelib butun oila o'sha paltoni bir marta kiyyan edi."),
        ("نجا من الثلج والمطر وتدريبات كرة القدم لابن عمّي.", "U qor, yomg'ir va amakivachchamning futbol mashg'ulotidan omon chiqdi."),
        ("الآن يبدأ كلّ شتاء بطقس واحد مهمّ.", "Endi har qish muhim bir marosim bilan boshlanadi."),
        ("أفتح الخزانة، وأهزّ المعطف بلطف، وأبتسم.", "Shkafni ochaman, paltoni yumshoq silkitaman va tabassum qilaman."),
        ("بعض المشتريات عملية؛ وهذا صار أيضًا قصّة.", "Ba'zi xaridlar amaliy; bu esa hikoyaga ham aylandi."),
    ],
    6: [
        ("خسر فريق كرة القدم في حيّنا خمس مباريات على التوالي.", "Ko'cha futbol jamoamiz ketma-ket beshta o'yinda mag'lub bo'ldi."),
        ("كان السبت موعد نهائي كأس الحيّ.", "Shanba kuni mahalla kubogining final o'yini bo'lishi kerak edi."),
        ("كان خصومنا شبّان الشارع المجاور، طوال القامة وسريعون.", "Raqiblarimiz qo'shni ko'chaning baland va tez yigitlari edi."),
        ("قال الجميع إنّ علينا أن نستسلم ونبقى في البيت.", "Hamma uyda qolib taslim bo'lishimizni aytdi."),
        ("لكنّ كابتننا جسور كان له خطط أخرى لنا.", "Lekin sardorimiz Jasurning biz uchun boshqa rejalar bor edi."),
        ("دعا إلى تدريب إضافي مساء الخميس.", "U payshanba kechqurun qo'shimcha mashg'ulot chaqirdi."),
        ("حضر سبعة لاعبين فقط، واثنان منهم مريضان.", "Faqat yetti o'yinchi keldi, ikkovimiz kasal edik."),
        ("تدرّبنا على التمريرات حتى أُضيئت أعمدة إنارة الشارع.", "Ko'cha chiroqlari yoqilguncha paslar mashq qildik."),
        ("ظلّ جسور يردّد عبارة واحدة: «مرّر الكرة قبل أن تراوغ».", "Jasur bitta jumlani takrorladi: 'Chalib ketishdan oldin pass ber.'"),
        ("ليلة الجمعة، بالكاد نمتُ من شدّة الحماس.", "Juma kechqurun hayajondan zo'rg'a uxladim."),
        ("تخيّلتُ تسجيل هدف الفوز نحو أربعين مرّة.", "G'alaba golini urganini taxminan qirq marta xayolimdan o'tkazdim."),
        ("كان صباح السبت باردًا، وعلت البرك طبقة رقيقة من الجليد.", "Shanba ertalab sovuq edi, suv havzalarida ingichka muz bor."),
        ("كان الملعب خلف المصنع القديم طريًّا بالطين.", "Eski zavod ortidagi maydon loy bilan yumshoq edi."),
        ("اصطفّ المتفرّجون على الجانبَين، ومنهم أجداد يحملون ترمسات.", "Tomoshabinlar ikki tomonda saf tortdi, termosli bobolar ham bor edi."),
        ("كان الحكم معلّمًا متقاعدًا مشهورًا بصرامته.", "Hakim qat'iyligi bilan mashhur nafaqadagi o'qituvchi edi."),
        ("كانت الدقائق الخمس عشرة الأولى كارثة بالنسبة لنا.", "Dastlabki o'n beshta daqiqa biz uchun ofat bo'ldi."),
        ("سجّلوا هدفَين، وغنّى مشجّعوهم بصوت عالٍ.", "Ular ikki marta gol urdi va muxlislarari baland qo'shiq aytdi."),
        ("صاح حارس مرمانا بالتعليمات مثل جنرال.", "Darvozabonimiz generaldek ko'rsatmalar baqirdi."),
        ("شيئًا فشيئًا، تذكّرنا قاعدة الخميس البسيطة.", "Astasekin, payshanbadagi oddiy qoidani esladi."),
        ("مرّر، تحرّك، مرّر مجدّدًا — لا أبطال منفردون.", "Pass, harakat, yana pass — yakka qahramonlar bo'lmaslik."),
        ("أصبحت لعبتنا فجأة سريعة ونظيفة.", "O'yinimiz birdan tez va toza bo'lib qoldi."),
        ("قبل الشوط الأول بقليل، سجّل عزيز من زاوية ضيّقة.", "Tanaffus oldi rostida, Aziz tor burchakdan gol urdi."),
        ("ركضنا لنعانقه، منزلقين على العشب المبلّل.", "Uni quchoqlash uchun yugurdik, ho'l o'tloqda sirg'alib."),
        ("استمرّت الاستراحة عشر دقائق من التنفّس الثقيل.", "Tanaffus o'n daqiqa og'ir nafas olish bilan o'tdi."),
        ("رسم جسور دوائر على الأرض الطينية وهو يشرح الخطط.", "Jasur loy tuproqga aylanalar chizib taktikani tushuntirdi."),
        ("بدأ الشوط الثاني بشراسة، تكاد تكون غاضبة.", "Ikkinchi bo'lim shiddat bilan, deyarli g'azablangan holda boshlandi."),
        ("داس أطول لاعب لديهم على إصبع قدمي عمدًا.", "Ularning eng baland o'yinchisi oyog'imni ataylab bosdi."),
        ("لم أقل شيئًا وركّزتُ على الكرة بدلًا من ذلك.", "Men hech narsa demadim va o'rniga to'pga e'tibor berdim."),
        ("مع تبقّي عشرين دقيقة، حصلنا على ركلة حرّة.", "Yigirma daqiqa qolganda jarima zarbasiga erishdik."),
        ("نظر الجميع إلى ساردور، خبيرنا الهادئ.", "Hamma jim ko'rinishdagi mutaxassisimiz Sardorga qaradi."),
        ("وضع الكرة بعناية ومسح جبينه.", "U to'pni ehtiyotkorlik joylashtirdi va peshonasini artidi."),
        ("قفز السور الدفاعي؛ والتفّت الكرة حوله بجمال.", "Devor sakradi; to'p uning atrofidan chiroyli egilib o'tdi."),
        ("تعادل اثنان-اثنين، وانفجر الشارع ضجيجًا.", "Ikk-ikki, va ko'cha shovqin bilan portladi."),
        ("في الدقيقة الأخيرة، شعرتُ أنّ ساقَيّ عصيّان خشبيّان.", "Oxirgi daqiqada oyog'im yog'och tayoqlardek his qildi."),
        ("ثم تدحرجت كرة حرّة نحوي مصادفةً.", "Keyin erkin to'p tasodifan menga tomonga aylanib keldi."),
        ("سمعتُ جسور يصيح باسمي من مكان بعيد.", "Jasurning ismimni uzoqdan baqirayotganini eshitdim."),
        ("مرّرتُ الكرة بدلًا من التسديد — أنقذتني القاعدة.", "Zarba o'rniga pass berdim — qoida meni qutqardi."),
        ("استلمها عزيز وسجّل هدف الفوز بهدوء.", "Aziz uni qabul qildi va g'alaba golini tinch urdi."),
        ("دوّت الصفّارة، وسقطتُ على العشب وأنا أضحك.", "Chalqildi chalinadi va men kulgan holda o'tloqqa yiqildim."),
        ("لوّح الأجداد بترمساتهم فوق رؤوسهم مثل كؤوس البطولة.", "Bobolar termoslarni boshlaridan mukofotday silkitishdi."),
        ("حتى الحكم الصارم ابتسم للحظة لكابتننا.", "Hattoning qattiqqo'l hakimi ham sardorimizga bir lahza tabassum qildi."),
        ("احتفلنا بعصير ليمون فاتر وخبز دافئ.", "Biz gazsiz limonad va iliq non bilan nishonladik."),
        ("بصراحة، لا أحد يتذكّر النتيجة الدقيقة اليوم.", "Bugun hech kim aniq hisobni eslamaydi, rostini aytsam."),
        ("لكنّ الجميع يتذكّر أننا لعبنا أخيرًا معًا.", "Lekin hamma nihoyat birga o'ynaganimizi eslaydi."),
    ],
    7: [
        ("في يونيو، قمتُ أنا وأصدقائي برحلة سير إلى جبال تشيمغان.", "Iyun oyida do'stlarim bilan Chimyon tog'lariga yurish qildik."),
        ("وعدت النشرة الجوية بشمس، فلم يحمل أحد معطف مطر.", "Bashorat quyoshni va'da qilgandi, shuning uchun hech kim yomg'irpoq olmadi."),
        ("كان ذلك أوّل خطأ في رحلتنا.", "Bu bizning sayohatimizdagi birinchi xato edi."),
        ("بدأنا التسلّق في الساعة السادسة وسط هواء الصباح البارد.", "Salqin ertalabki havoda soat oltida chiqishni boshladik."),
        ("غطّت أشجار الصنوبر السفوح السفلى مثل جيوش خضراء.", "Qarag'aylar pastki yonbag'irlarni yashil armiyalardek qoplaydi."),
        ("غنّت الطيور من كلّ اتجاه، تستعرض صباحها.", "Qushlar har tomondan kuyladi, ertalablarini ko'rsatib turardi."),
        ("بحلول العاشرة، رسم العرق خرائط داكنة على قمصاننا.", "O'nlikka kelib, ter ko'ylaklarimizda qora xaritalar chizdi."),
        ("شربنا الماء بسرعة زائدة وضحكنا على ذلك.", "Suvni juda tez ichdik va buning ustidan kuldik."),
        ("ضاق الدرب على طول منحدر يجري تحته جدول صغير.", "Yo'l pastda kichik soy bo'lgan jarlik bo'ylab toraydi."),
        ("تخلّف فارس عن الركب، متذمّرًا بشكل مبالَغ من حقيبته.", "Faris orqada qoldi, chamadoni haqida dramatik shikoyat qilib."),
        ("مازحناه، لكننا أبطأنا سويًّا على أيّ حال.", "Uni masxara qildik, lekin baribir birga sekinlashtirdik."),
        ("قرابة الظهر، تغيّر مزاج السماء تمامًا.", "Taxminan peshin vaqtida osmon kayfiyatini butunlay o'zgartirdi."),
        ("تسلّق جدار رمادي من السحب فوق التلّة البعيدة.", "Kulrang bulut devori uzoq tizmadan oshib chiqa boshladi."),
        ("انخفضت الحرارة وكأنّ أحدهم أغلق نافذة على الصيف.", "Harorat tushdi, xuddi kimdir yozga oynani yopib qo'yganidek."),
        ("كانت القطرات الأولى كبيرة وباردة، وودودة على نحو مفاجئ.", "Birinchi tomchilar katta, sovuq va kutilmaganda samimiy edi."),
        ("ثم هطل المطر مثل تصفيق — غزيرًا وفي كلّ مكان.", "Keyin yomg'ir olqish kabi keldi — kuchli va hamma joyda."),
        ("ركضنا ضاحكين نحو صخرة كبيرة مسطّحة قريبة.", "Yaqin atrofdagi ulkan tekis toshga kulib yugurdik."),
        ("تكدّس سبعة أشخاص تحت حافة صخرية ضيّقة مثل السردين.", "Yetti kishi bir tor qoyalarga sardinalardek sig'ishdi."),
        ("وضعنا الحقائب في الوسط؛ وبقينا نحن في الخارج نصف مبلّلين.", "Chamadonlar o'rtaga kirdi; biz yarim ho'l holda tashqarida qoldik."),
        ("حوّل المطر الوادي كلّه إلى لون فضّي صاخب.", "Yomg'ir butun vodini kumushrang va shovqinli qildi."),
        ("ظهرت شلالات على منحدرات لم يكن فيها شلال من قبل.", "Oldin sharshara bo'lmagan jarliklarda sharsharalar paydo bo'ldi."),
        ("رسم البرق فروعًا بيضاء صامتة عبر الجبل المقابل.", "Chaqqon oppoq shoxlarni qarama-qarshi tog' bo'ylab jim chizdi."),
        ("عددنا الثواني بين الوميض والرعد مثل الأطفال.", "Biz yalt-ylt va g'umburlash orasidagi soniyalarni sanadik."),
        ("في مكان ما بالأسفل، صفّر راعٍ لأغنامه ليعود بها مبكّرًا.", "Pastlarda cho'pon qo'ylarini erta uyga chalqitdi."),
        ("ملتفّين معًا في بطانية طوارئ واحدة، تقاسمنا الشوكولاتة.", "Bir favqulodda ko'rpachaga o'ralgan holda shokolad bo'lishdik."),
        ("روت دلنوزا قصص أشباح حتى توسّلنا إليها أن تتوقّف.", "Dilnoza arvoh hikoyalarini aytdi, biz uni to'xtashiga yalinmaguncha."),
        ("استمرّت العاصفة أربعين دقيقة بالضبط وفق ساعة جسور.", "Bo'ron Jasurning soatiga aynan qirq daqiqa davom etdi."),
        ("عندما انقشعت، فاحت من العالم رائحة الولادة الجديدة.", "U ketganda, dunyo butunlay yangi tug'ilgandek hid berdi."),
        ("حملت كلّ ورقة قطرة ماء صغيرة مرتجفة كالماس.", "Har bir yaproqda mayda titrayotgan suv olmosi bor edi."),
        ("تصاعد الضباب ببطء من الوادي مثل دخان رقيق.", "Tuman vodidan yumshoq tutun singari sekin ko'tarildi."),
        ("ثم جاء قوس قزح — ضخمًا، مزدوجًا، شبه متغطرس.", "Va kamalak keldi — ulkan, juftlashgan, deyarli mag'rur."),
        ("لم يتكلّم أحد؛ حتى فارس نسي شكاواه.", "Hech kim gapirmadi; hatto Faris ham shikoyatlarini unutdi."),
        ("واصلنا التسلّق عبر عشب مبلّل وحجارة لامعة.", "Ho'l o'tloq va yalt-yaltiroq toshlar orasida chiqishda davom etdik."),
        ("ظهرت القمّة فجأة، مرتديةً سحابة كقبّعة.", "Cho'qqi birdan namoyon bo'ldi, bulutni shlyapa kabi kiygan holda."),
        ("صرخنا في الضباب لمجرّد سماع الصدى يعود.", "Tumanga aks sadoni eshitish uchun baqirdik."),
        ("كان الغداء خبزًا وجبنًا وطماطم، ونصرًا خالصًا.", "Nonushta non, pishloq, pomidor va sof g'alaba edi."),
        ("كلّ شيء يصبح ألذّ بعد المطر والجهد.", "Yomg'ir va mehnatdan keyin har narsa mazaliroq tuyuladi."),
        ("استغرق النزول وقتًا أقلّ لكنه تطلّب تركيزًا أكبر.", "Pasayish kamroq vaqt oldi, lekin ko'proq e'tibor talab qildi."),
        ("الحجارة المبلّلة زلقة باحترافية، تعلّمنا ذلك بسرعة.", "Ho'l toshlar professional darajadagi sirg'aluvchan ekanini tez o'rgandik."),
        ("في القرية، باعتنا جدّة شايًا ساخنًا وعسلًا.", "Qishloqda keksa ayol bizga issiq choy va asal sotdi."),
        ("قالت إنّ مطر الجبل يجلب دائمًا الحظّ الجيّد للزوّار.", "U tog' yomg'iri mehmonlarga doimo omad keltirishini aytdi."),
        ("فاحت من الحافلة في طريق العودة رائحة الصوف المبلّل والعشب.", "Uyga avtobusda ho'l jun va o't hidi bor edi."),
        ("نام الجميع باستثناء السائق وقصص دلنوزا عن الأشباح.", "Haydovchi va Dilnozaning arvoh hikoyalaridan boshqa hamma uxlab qoldi."),
        ("منذ تلك الرحلة، لم نعد نثق أبدًا بالنشرات الجوية.", "O'sha sayohatdan keyin ob-havo bashoratiga umuman ishonmaymiz."),
    ],
    8: [
        ("وصل أسبوع الامتحانات إلى جامعتنا مثل جيش غازٍ.", "Imtihon haftasi universitetimizga bosqinchilar armiyasiday keldi."),
        ("أصبحت المكتبة فجأة أكثر ازدحامًا من السوق.", "Kutubxona birdan bozordan ham gavjum bo'lib qoldi."),
        ("احتلّ الطلّاب الطاولات برايات: دفاتر وأقلام تحديد ومشروبات طاقة.", "Talabalar stollarni bayroqlar bilan band qildi: daftarlar, flomasterlar, energiya ichimliklari."),
        ("طبع زميلي في الغرفة الجدول وعلّقه على جدارنا.", "Xonadoshim jadvalni chop etib devoriga yopishtirdi."),
        ("ثلاثة امتحانات في أربعة أيام — رياضيات، وتاريخ، وإنجليزية.", "To'rt kunda uch imtihon — matematika, tarix va ingliz tili."),
        ("جُدولت الرياضيات أولًا، وهو ما بدا لي إهانة شخصية.", "Matematika birinchi bo'lib belgilandi, bu shaxsan haqoratli tuyuldi."),
        ("وضعتُ خطّة مرمّزة بالألوان واتّبعتها ليوم واحد.", "Rang kodli reja tuzdim va uni bir kun bajardim."),
        ("بصراحة، انهار اليوم الثاني إلى تصفّح للهاتف وذعر.", "Ikkinchi kun rostini aytsam aylansh va vahimaga aylandi."),
        ("اتّصلت أمي كلّ مساء بالسؤال نفسه.", "Onam har kechqurun bir xil savol bilan qo'ng'iroq qildi."),
        ("«هل أكلتَ؟» — لا تسأل أبدًا عن الدرجات، بل دائمًا عن الطعام.", "'Ovqat yedingizmi?' — hech qachon baholar haqida emas, doimo ovqat haqida."),
        ("ليلة امتحان الرياضيات، نظّمت مجموعتنا جلسة مذاكرة.", "Matematikadan oldingi kechqurun guruhimiz o'quv mashg'uloti uyushtirdi."),
        ("التقينا في مطبخ السكن الجامعي بين غلّايتَين.", "Ikki choynak orasida yotoqxona oshxonasida uchrashdik."),
        ("شرح أحدهم المشتقّات مستخدمًا شرائح الخبز كأمثلة.", "Kimdir hosilalarni non bo'laklari misolida tushuntirib berdi."),
        ("رسم آخر معادلات مباشرة على الطاولة بالدقيق.", "Yanasi formulalarni to'g'ridan-to'g'ri stolga un bilan chizdi."),
        ("بحلول منتصف الليل، بدأت حتى المواضيع الضعيفة تصبح مفهومة.", "Yarim kechaga kelib hatto zaif mavzular ham ma'noli bo'la boshladi."),
        ("احتفلنا مبكّرًا جدًا وذهبنا إلى الفراش في الساعة الثانية.", "Biz juda erta nishonladik va ikkida uxlab qoldik."),
        ("لامتحانات الصباح نوع خاصّ من الصمت.", "Ertalabki imtihonlarda maxsus jimlik bor."),
        ("مئتا قلم رصاص تكتب في آنٍ واحد تصدر صوتًا كالمطر الخفيف.", "Ikkita yuz qalam bir vaqtda yozganda yumshoq yomg'irdek tovush chiqaradi."),
        ("مشى المراقب ببطء، منتعلًا حذاءً ينضح تهديدًا خالصًا.", "Nazoratchi sekin yurdi, sof tahdid poyabzalini kiyyan holda."),
        ("كان السؤال الأول رحيمًا؛ والسؤال الرابع كان إجراميًا.", "Birinchi savol rahmli edi; to'rtinchi esa jinoyat edi."),
        ("تركتُه لوقت لاحق وواصلتُ التقدّم.", "Uni keyinga qoldirdim va oldinga siljiy berdim."),
        ("في مكان ما خلفي، تنهّد أحدهم مثل محرّك يحتضر.", "Ortamda kimdir o'layotgan dvigatelday nafas oldi."),
        ("في الدقائق العشر الأخيرة، عدتُ إليه وحللته.", "Oxirgi o'n daqiqa ichida qaytib keldim va uni yechdim."),
        ("لن أعرف إن كنتُ محقًّا إلّا في الأسبوع التالي.", "To'g'ri yoki yo'qligini faqat keyingi haftada bilardim."),
        ("جاء امتحان التاريخ بعد ليلة يائسة من حفظ التواريخ.", "Tarix imtihoni sanalarning bitta umidsiz kechasidan keyin keldi."),
        ("خزّن دماغي أسماء الملوك مثل أرقام هواتف عشوائية.", "Miyam podshohlarni tasodifiy telefon raqamlari kabi saqladi."),
        ("لحسن الحظّ، كان موضوع المقال طريق الحرير — المفضّل لديّ.", "Omadinga, esse mavzusi Ipak yo'li edi — mening sevimlim."),
        ("كتبتُ عن القوافل، والتوابل، واللغات، ودور مدينتي.", "Karvonlar, ziravorlar, tillar va tug'ilgan shahrim roli haqida yozdim."),
        ("الكتابة عن شيء تحبّه أشبه بالحديث، لا بالاختبار.", "Sevgan narsa haqida yozish suhbatlashgandek, sinovdan o'tmagandek tuyuladi."),
        ("جاءت الإنجليزية أخيرًا، واسترخت القاعة بوضوح.", "Ingliz tili oxiri keldi va xona ko'rinib tinchlantirdi."),
        ("روى نصّ الفهم القرائي قصّة عن حارس منارة.", "O'qish tushunishi mayoqchining hikoyasini aytib berdi."),
        ("كدتُ أستمتع به، وهو ما بدا وكأنه ممنوع خلال الامتحانات.", "Deyarli zavqlandim, bu imtihon paytida noqonuniy tuyuldi."),
        ("بعد الجرس الأخير، انفجر الممرّ بالحرّية.", "Oxirgi jiringlashdan keyin koridor ozodlikka portladi."),
        ("تعانق غرباء غرباء؛ وطارت الكتب إلى سلال المهملات باحتفالية.", "Tanish emaslar tanish emaslarni quchoqladi; kitoblar marosim ravishda axlat idishiga uchdi."),
        ("نسي بعض الطلّاب كلّ شيء على الفور، مبتسمين بلا تعبير.", "Ba'zi talabalar hamma narsani darhol unutdilar, bo'sh tabassum bilan."),
        ("توجّهت مجموعتنا مباشرة إلى الحديقة قرب النهر.", "Guruhimiz to'g'ridan-to'g'ri daryo yaqinidagi bog'ga bordi."),
        ("اشترينا مثلّجات رغم الريح الباردة.", "Sovuq shamolga qaramay muzqaymoq sotib oldik."),
        ("وصلت النتائج بالبريد الإلكتروني بعد ثلاثة أيام لا تنتهي.", "Natijalar cheksiz uch kundan keyin elektron pochta orqali keldi."),
        ("فتحتُ نتيجتي وأنا واقف في منتصف الممرّ.", "O'zinikini koridorning o'rtasida turub ochdim."),
        ("الرياضيات: ناجح. التاريخ: ناجح. الإنجليزية: واحد وتسعون نقطة.", "Matematika: o'tdim. Tarix: o'tdim. Ingliz tili: to'qson bir ball."),
        ("اتّصلتُ بأمي أوّلًا، قبل أن أفتح باب البيت.", "Uy eshigini ochishdan avval birinchi navbatda onamga qo'ng'iroq qildim."),
        ("بكت قليلًا وسألتني مجدّدًا إن كنتُ قد أكلت.", "U biroz yig'ladi va yana ovqat yeganimni so'radi."),
        ("علّمني ذلك الأسبوع أنّ الذعر أثقل من الكتب.", "O'sha hafta vahim kitoblardan og'iroq ekanini o'rgatdi."),
        ("في الفصل الدراسي القادم، أخطّط للمذاكرة بهدوء منذ اليوم الأول.", "Keyingi semestrda birinchi kundan sokin o'qishni rejalashtiryapman."),
    ],
    9: [
        ("أستقلّ آخر حافلة ليلية عائدًا إلى البيت بعد نوبتي المسائية.", "Kechki smenadan keyin oxirgi tungi avtobusda uyga qaytaman."),
        ("تنطلق من الساحة في تمام الحادية عشرة وأربعين دقيقة مساءً.", "U maydondan aynan yigirma uch qirq daqiqada jo'naydi."),
        ("لا يركب معي في هذه الساعة سوى ثلاثة أو أربعة ركّاب.", "Bu soatda menga faqat uch-to'rt yo'lovchi hamroh bo'ladi."),
        ("أصبح السائق يعرف كلّ راكب دائم من وجهه الآن.", "Haydovchi endi har bir doimiy yo'lovchini yuzidan tanib oladi."),
        ("يومئ لي برأسه بصمت، وهو ما يبدو أشبه بالصداقة.", "U menga jim bosh irg'adi, bu esa do'stlikdek tuyuladi."),
        ("تفوح من الحافلة رائحة خفيفة من الديزل والمطر وعشاء أحدهم.", "Avtobusda dizel, yomg'ir va kimningdir kechki ovqati hidi seziladi."),
        ("الليلة، تجلس امرأة عجوز خلفي ممسكة بحقيبة كبيرة.", "Bugun kechqurun orqamda katta sumka tutgan keksa ayol o'tiradi."),
        ("يصدر من حقيبتها صليل هادئ لعلب زجاجية فارغة.", "Sumkasidan bo'sh idishlarning sokin jiringlashi keladi."),
        ("تعيد الزجاجات إلى السوق كلّ مساء.", "U har shom bozorga idishlarni qaytarib beradi."),
        ("عبر الممرّ، ينام طالب مستندًا إلى حقيبته.", "Yo'lak narida talaba chamadoniga suyanib uxlab yotadi."),
        ("ينزلق كتابه المدرسي ببطء نحو حافّة ركبتَيه.", "Uning darsligi tizzalari chetiga sekin sirg'aladi."),
        ("تنزلق المدينة في الخارج أمام النظر مثل تلفاز بطيء.", "Tashqaridagi shahar sekin televideniedek o'tib ketadi."),
        ("ترتدي المحلّات المغلقة جفونًا معدنية؛ وتمتلك الكلاب الضالّة التقاطعات.", "Yopiq do'konlar metall ko'z qovoqlari kiyadi; adashgan itlar chorrahani egallaydi."),
        ("عند إشارات المرور، ننتظر وحدنا في الشارع كلّه.", "Svetoforlarda butun ko'chada yolg'iz kutamiz."),
        ("تُعزف أغنية قديمة بهدوء من مذياع السائق.", "Haydovchining radio eshitish qurilmasidan eski qo'shiq jim chalinadi."),
        ("يدندن معها دون أن يدرك أنّ بإمكان أحد سماعه.", "U kimdir eshitishini sezmasdan kuylaydi."),
        ("قرب الجسر، يصعد ركّاب آخرون إلى الحافلة.", "Ko'prik yaqinidagi bir joyda boshqa yo'lovchilar ham chiqishadi."),
        ("تجلس ممرّضتان بحذاء أبيض، منهكتَين بعد نوبتهما.", "Oq poyabzallik ikki hamshira smenadan keyin charchagan holda o'tirishadi."),
        ("تتحدّثان عن المرضى بجمل قصيرة متعبة.", "Ular bemorlar haqida qisqa charchagan gaplarda gapirishadi."),
        ("يحمل عامل شابّ دلاء طلاء ذات رائحة نفّاذة.", "Yosh ishchi kuchli hid beradigan bo'yoq idishlarini olib chiqyapti."),
        ("لا أحد يشتكي؛ فللحافلات الليلية قواعد صبر غير مكتوبة.", "Hech kim shikoyat qilmaydi; tungi avtobuslarda sabrning yozilmagan qoidalari bor."),
        ("تقترب محطّتي خلال نحو خمس عشرة دقيقة.", "Beketim taxminan o'n beshta daqiqa ichida yaqinlashadi."),
        ("أضغط الزرّ دائمًا مبكّرًا جدًا، من باب العادة.", "Men doim odatdan erta tugmani bosaman."),
        ("تسأل المرأة العجوز فجأة السائق عن جدول الغد.", "Keksa ayol birdan haydovchidan ertangi jadval haqida so'raydi."),
        ("صوتها ليّن، وكأنها تخشى إزعاج الليل.", "Ovozi yumshoq, xuddi kechani bezovta qilishdan qo'rqqanday."),
        ("يجيب السائق بصبر بل ويبتسم عبر المرآة.", "Haydovchi sabrli javob beradi va hatto oynaga tabassum ham qiladi."),
        ("في الخارج، يبدأ المطر من جديد، راسمًا خطوطًا على كلّ نافذة.", "Tashqarida yomg'ir yana boshlanadi, har bir oynada chiziqlar chizadi."),
        ("يستيقظ الطالب في ذعر قبل محطّته بمحطّة واحدة.", "Talaba o'z beketidan bir oldingi bekatda vahima bilan uyg'onadi."),
        ("نراقبه جميعًا وهو يركض في الظلام، ونضحك بهدوء.", "Hammamiz uni zulmatga yugurganini kuzatib jim kulamiz."),
        ("تغادر الممرّضتان معًا، تتقاسمان مظلّة صغيرة واحدة.", "Hamshiralar birga ketishadi, bitta kichik soyabonni bo'lishib."),
        ("الآن لم يبقَ على متن الحافلة سوى المرأة صاحبة العلب وأنا.", "Endi faqat idishli ayol bilan men avtobusda qoldik."),
        ("تبدو الحافلة الآن خاصّة، مثل سيّارة أجرة ليلية للذكريات.", "Avtobus endi xususiy tuyuladi, xotiralarning kechgi taksidek."),
        ("أسأل المرأة إن كان أحفادها يساعدونها في حمل العلب.", "Ayoldan nabiralari idish ko'tarishga yordam berishini so'rayman."),
        ("تضحك وتقول إنهم مشغولون بأن يصبحوا أشخاصًا مهمّين.", "U kulib, ular muhim odamlar bo'lish bilan band deb javob beradi."),
        ("لا حزن في صوتها، بل سخرية لطيفة فقط.", "Ovozida hafsala yo'q, faqat muloyim hazil bor."),
        ("تخبرني أنّ ثمن العلب يدفع أقلام حفيدتها.", "U idishlar nabirasining qalam pullarini to'lashini aytadi."),
        ("عندما تصل محطّتي أخيرًا، أساعدها في إنزال حقيبتها.", "Beketim nihoyat kelganda, sumkasini tushirishga yordam beraman."),
        ("تصرّ على إعطائي حبّة مشمش صغيرة من إحدى العلب.", "U menga idishdan bitta mayda o'rik berishga qat'iy qaror qiladi."),
        ("وأنا أمشي إلى البيت تحت مظلّتي، آكل المشمشة ببطء.", "Soyabon ostida uyga piyoda qaytayotib, o'rikni sekin yeyman."),
        ("طعمها حلو حامض، مثل معظم الأحاديث الصادقة.", "U achchiq-shirin ta'mga ega, eng samimiy suhbatlar kabi."),
        ("تدندن المدينة بهدوء من حولي، نصف نائمة.", "Shahar atrofimdagi jim g'urraydi, yarim uxlagan holda."),
        ("غدًا ستجوب هذه الحافلة الشوارع نفسها من جديد.", "Ertaga bu avtobus xuddi shu ko'chalar orqali yana yuradi."),
        ("نفس السائق، ونفس الصمت، وقصص صغيرة مختلفة كلّ ليلة.", "Xuddi shu haydovchi, xuddi shu jimlik, har kecha boshqa kichik hikoyalar."),
        ("لهذا السبب لا أشعر أبدًا بوحدة حقيقية في الحافلة الليلية.", "Shuning uchun tungi avtobusda hech qachon chin ma'noda yolg'iz his qilmayman."),
    ],
}
