LONG_STORIES_C = {
    6: [
        ("Our street football team had lost five matches in a row.", "Ko'cha futbol jamoamiz ketma-ket beshta o'yinda mag'lub bo'ldi."),
        ("Saturday promised the final match of the neighbourhood cup.", "Shanba kuni mahalla kubogining final o'yini bo'lishi kerak edi."),
        ("Our opponents were the boys from the next street, tall and fast.", "Raqiblarimiz qo'shni ko'chaning baland va tez yigitlari edi."),
        ("Everyone said we should just give up and stay home.", "Hamma uyda qolib taslim bo'lishimizni aytdi."),
        ("But our captain Jasur had other plans for us.", "Lekin sardorimiz Jasurning biz uchun boshqa rejalar bor edi."),
        ("He called an extra practice on Thursday evening.", "U payshanba kechqurun qo'shimcha mashg'ulot chaqirdi."),
        ("Only seven players came, and two of them were sick.", "Faqat yetti o'yinchi keldi, ikkovimiz kasal edik."),
        ("We practiced passes until the streetlights switched on.", "Ko'cha chiroqlari yoqilguncha paslar mashq qildik."),
        ("Jasur kept repeating one phrase: 'Pass before you dribble.'", "Jasur bitta jumlani takrorladi: 'Chalib ketishdan oldin pass ber.'"),
        ("On Friday night, I barely slept from excitement.", "Juma kechqurun hayajondan zo'rg'a uxladim."),
        ("I imagined scoring the winning goal about forty times.", "G'alaba golini urganini taxminan qirq marta xayolimdan o'tkazdim."),
        ("Saturday morning was cold, with thin ice on puddles.", "Shanba ertalab sovuq edi, suv havzalarida ingichka muz bor."),
        ("The field behind the old factory was soft with mud.", "Eski zavod ortidagi maydon loy bilan yumshoq edi."),
        ("Spectators lined both sides, including grandfathers with thermoses.", "Tomoshabinlar ikki tomonda saf tortdi, termosli bobolar ham bor edi."),
        ("The referee was a retired teacher famous for strictness.", "Hakim qat'iyligi bilan mashhur nafaqadagi o'qituvchi edi."),
        ("The first fifteen minutes were a disaster for us.", "Dastlabki o'n beshta daqiqa biz uchun ofat bo'ldi."),
        ("They scored twice, and their fans sang loudly.", "Ular ikki marta gol urdi va muxlislarari baland qo'shiq aytdi."),
        ("Our goalkeeper shouted instructions like a general.", "Darvozabonimiz generaldek ko'rsatmalar baqirdi."),
        ("Slowly, we remembered Thursday's simple rule.", "Astasekin, payshanbadagi oddiy qoidani esladi."),
        ("Pass, move, pass again — no heroes alone.", "Pass, harakat, yana pass — yakka qahramonlar bo'lmaslik."),
        ("Our game suddenly became quick and clean.", "O'yinimiz birdan tez va toza bo'lib qoldi."),
        ("Just before halftime, Aziz scored from a narrow angle.", "Tanaffus oldi rostida, Aziz tor burchakdan gol urdi."),
        ("We ran to hug him, slipping on the wet grass.", "Uni quchoqlash uchun yugurdik, ho'l o'tloqda sirg'alib."),
        ("Halftime lasted ten minutes of heavy breathing.", "Tanaffus o'n daqiqa og'ir nafas olish bilan o'tdi."),
        ("Jasur drew circles on the muddy ground explaining tactics.", "Jasur loy tuproqga aylanalar chizib taktikani tushuntirdi."),
        ("The second half started fiercely, almost angrily.", "Ikkinchi bo'lim shiddat bilan, deyarli g'azablangan holda boshlandi."),
        ("Their tallest player stepped on my toe deliberately.", "Ularning eng baland o'yinchisi oyog'imni ataylab bosdi."),
        ("I said nothing and focused on the ball instead.", "Men hech narsa demadim va o'rniga to'pga e'tibor berdim."),
        ("With twenty minutes left, we earned a free kick.", "Yigirma daqiqa qolganda jarima zarbasiga erishdik."),
        ("Everyone looked at Sardor, our quiet specialist.", "Hamma jim ko'rinishdagi mutaxassisimiz Sardorga qaradi."),
        ("He placed the ball carefully and wiped his forehead.", "U to'pni ehtiyotkorlik joylashtirdi va peshonasini artidi."),
        ("The wall jumped; the ball curved beautifully around it.", "Devor sakradi; to'p uning atrofidan chiroyli egilib o'tdi."),
        ("Two-two, and the street exploded with noise.", "Ikk-ikki, va ko'cha shovqin bilan portladi."),
        ("In the last minute, my legs felt like wooden sticks.", "Oxirgi daqiqada oyog'im yog'och tayoqlardek his qildi."),
        ("Then a loose ball rolled towards me by accident.", "Keyin erkin to'p tasodifan menga tomonga aylanib keldi."),
        ("I heard Jasur shouting my name somewhere far away.", "Jasurning ismimni uzoqdan baqirayotganini eshitdim."),
        ("I passed instead of shooting — the rule saved me.", "Zarba o'rniga pass berdim — qoida meni qutqardi."),
        ("Aziz received it and scored the winning goal calmly.", "Aziz uni qabul qildi va g'alaba golini tinch urdi."),
        ("The whistle blew, and I fell onto the grass laughing.", "Chalqildi chalinadi va men kulgan holda o'tloqqa yiqildim."),
        ("Grandfathers waved their thermoses like trophies above their heads.", "Bobolar termoslarni boshlaridan mukofotday silkitishdi."),
        ("Even the strict referee smiled briefly at our captain.", "Hattoning qattiqqo'l hakimi ham sardorimizga bir lahza tabassum qildi."),
        ("We celebrated with flat lemonade and warm bread.", "Biz gazsiz limonad va iliq non bilan nishonladik."),
        ("Nobody remembers the exact score today, honestly.", "Bugun hech kim aniq hisobni eslamaydi, rostini aytsam."),
        ("But everyone remembers that we finally played together.", "Lekin hamma nihoyat birga o'ynaganimizi eslaydi."),
    ],
}
