LONG_STORIES_TR = {
    0: [
        ("Geçen cumartesi sabahı her zamankinden erken uyandım.", "Shanba kuni ertalab odatdagidan erta turdim."),
        ("Güneş pencereden içeri parlıyordu, gökyüzü ise tamamen açıktı.", "Quyosh derazamdan porlab kirayotgan edi, osmon esa butunlay ochiq."),
        ("Telefonum çaldı, arayan en yakın arkadaşım Aziz'di.", "Telefonim jiringladi — bu eng yaxshi do'stim Aziz edi."),
        ("\"Hazırlan, bütün günü birlikte geçireceğiz!\" dedi.", "U dediki: 'Tayyorlan, biz butun kunni birga o'tkazamiz!'"),
        ("Güldüm, çünkü o her zaman beklenmedik bir şey planlar.", "Men kulib qo'ydim, chunki u doim kutilmagan narsa rejalashtiradi."),
        ("Saat dokuzda evimin yakınındaki otobüs durağında buluştuk.", "Biz soat to'qqizda uyim yaqinidagi avtobus bekatida uchrashdik."),
        ("Şehir sessizdi, sokaklar neredeyse bomboştu.", "Shahar tinch edi, ko'chalar deyarli bo'sh."),
        ("Önce köşedeki küçük fırına yürüdük.", "Avval burchakdagi kichik nonvoyxonaga piyoda bordik."),
        ("Taze ekmek kokusu ikimizi de hemen gülümsetti.", "Yangi non hidi ikkovimizni darhol tabassumga keltirdi."),
        ("Aziz iki sıcak çörek aldı ve sormadan birini bana verdi.", "Aziz ikkita issiq bulochka oldi va so'ramasdan bittasini menga berdi."),
        ("O her zaman böyle bir arkadaş olmuştur.", "U har doim shunday do'st bo'lgan."),
        ("Kahvaltıdan sonra merkez parktan yürümeye karar verdik.", "Nonushtadan keyin markaziy bog' bo'ylab yurishga qaror qildik."),
        ("Yaşlı adamlar uzun yeşil ağaçların altında satranç oynuyordu.", "Qariyalar baland yashil daraxtlar ostida shaxmat o'ynayotgan edi."),
        ("Çocuklar bisikletlerine biniyor ve kahkahalarla gülüyordu.", "Bolalar velosiped haydab, baland ovozda kulayotgan edilar."),
        ("Bir bankta oturduk ve gelecek planlarımız hakkında konuştuk.", "Biz skameykada o'tirdik va kelajak rejalarimiz haqida gaplashdik."),
        ("Aziz gelecek yıl kendi küçük işini açmak istiyor.", "Aziz kelasi yili o'zining kichik biznesini ochmoqchi."),
        ("Ona seyahat etme ve yeni diller öğrenme hayalimi anlattım.", "Men unga sayohat qilish va yangi tillar o'rganish orzim haqida gapirdim."),
        ("Birbirimize çok çalışacağımıza ve asla vazgeçmeyeceğimize söz verdik.", "Bir-birimizga qattiq ishlash va hech qachon taslim bo'lmaslikka va'da berdik."),
        ("Öğleye doğru midelerimiz yüksek sesle guruldamaya başladı.", "Taxminan peshin vaqtida qorinlarimiz baland ovozda g'urillay boshladi."),
        ("Bu yüzden şehirdeki en sevdiğim yere gittik.", "Shuning uchun shahardagi sevimli joyimga bordik."),
        ("Orası şehirdeki en lezzetli çorbayı yapan küçücük bir kafe.", "Bu shaharda eng mazali sho'rva tayyorlaydigan juda kichik kafe."),
        ("Sahibi bizi çok iyi tanır ve her zaman fazladan ekmek ekler.", "Egasi bizni yaxshi biladi va doim qo'shimcha non qo'shib beradi."),
        ("Yavaş yavaş yedik ve pencereden geçen insanları izledik.", "Biz sekin-asta yedik va derazadan o'tayotgan odamlarni kuzatdik."),
        ("Birden eski okul öğretmenimizin caddeyi geçtiğini gördük.", "Birdan ko'chani kesib o'tayotgan eski maktab o'qituvchimizni ko'rdik."),
        ("Mutlu görünüyordu, bu yüzden onu selamlamak için dışarı koştuk.", "U baxtli ko'rindi, shuning uchun uni kutib olish uchun tashqariga yugurdik."),
        ("Bunca yıldan sonra ikimizi de hatırlıyordu.", "U shu yillar davomida ikkovimizni ham esladi."),
        ("On dakika boyunca okul anılarımız hakkında konuştuk.", "Biz maktab xotiralari haqida o'n daqiqa suhbatlashdik."),
        ("Nasıl insanlar olduğumuzla gurur duyduğunu söyledi.", "U biz aylanayotgan odamlar bilan faxrlanishini aytdi."),
        ("Sözleri günün geri kalanında kalbimde kaldı.", "Uning so'zlari kun davomida yuragimda qoldi."),
        ("Öğleden sonra şehir merkezindeki büyük kitapçıyı ziyaret ettik.", "Tushdan keyin shahar markazidagi katta kitob do'koniga bordik."),
        ("Aziz iş ve para hakkındaki kitaplara baktı.", "Aziz biznes va pul haqidagi kitoblarga qaradi."),
        ("Ben İngilizce deyimlerin resimli güzel bir sözlüğünü buldum.", "Men inglizcha iboralarning chiroyli rasmli lug'atini topdim."),
        ("Kitaplarımızı aldık ve dışarıda bir çikolatayı paylaştık.", "Kitoblarimizni oldik va tashqarida bir shokoladni bo'lishdik."),
        ("Eve dönerken karanlık bulutlar gökyüzünü kapladı.", "Uyga qaytayotganda qora bulutlar osmonni qopladi."),
        ("Otobüs durağına vardığımız anda şiddetli yağmur başladı.", "Avtobus bekatiga yetib kelganimizda kuchli yomg'ir boshlandi."),
        ("Yeni kitaplarımızı korurken birbirimize sokulduk.", "Yangi kitoblarimizni himoya qilib, yonma-yon turdik."),
        ("Yağmur temiz kokuyordu, hava serin ve taze oldu.", "Yomg'ir toza hid berdi va havo salqin, yangi bo'lib qoldi."),
        ("Sonunda eve vardığımızda tamamen ıslanmıştık.", "Nihoyat uyga yetganimizda butunlay ho'l bo'lgan edik."),
        ("Annem bizi kapıda sırılsıklam görünce güldü.", "Onam eshik oldida tomchiqayotganimizni ko'rib kuldi."),
        ("Bize limonlu sıcak çay ve kuru kıyafetler verdi.", "U bizga limon issiq choy va quruq kiyim berdi."),
        ("Çayımızı içtik ve ona bütün günümüzü anlattık.", "Choyni ichdik va unga butun kunimiz haqida gapirdik."),
        ("Akşam Aziz bana yağmurdaki fotoğrafımızı gönderdi.", "Kechqurun Aziz menga yomg'irdagi suratimizni yubordi."),
        ("Fotoğrafın altına \"Şimdiye kadarki en iyi cumartesi\" yazmıştı.", "Surat ostiga esa shunday yozdi: 'Eng zo'r shanba.'"),
        ("Gülümsedim ve yakında tekrar yapmamız gerektiğini yazdım.", "Men tabassum bilan tez orada takrorlashimiz kerak deb yozdim."),
        ("İyi arkadaşlar sıradan günleri özel hissettirir.", "Yaxshi do'stlar oddiy kunlarni maxsus qilib ko'rsatadi."),
    ],
    1: [
        ("İki yıl önce ilk uçak yolculuğumu tek başıma yaptım.", "Ikki yil oldin birinchi parvozimni yolg'iz amalga oshirdim."),
        ("Amcamı ziyaret etmek için Taşkent'ten İstanbul'a uçuyordum.", "Toshkentdan amakisini ko'rgani Istanbulga uchyotgan edim."),
        ("Bir önceki gece hiç uyuyamadım.", "Oldingi kechqurun umuman uxlolmadim."),
        ("Pasaportumu ve biletimi belki yirmi kez kontrol ettim.", "Pasportim va biletimni ehtimol yigirma marta tekshirdim."),
        ("Annem bana sandviçler, tatlılar ve sıcak çoraplar hazırladı.", "Onam menga tovoq-tort, shirinlik va iliq paypoq solib berdi."),
        ("Havalimanında her şey devasa ve kafa karıştırıcı görünüyordu.", "Aeroportda hamma narsa ulkan va chalkash tuyuldi."),
        ("Yolcuların uzun kuyrukları her köşeden dolanıyordu.", "Sayohatchilarning uzun navatlari har bir burchakda egri-bugri edi."),
        ("Pasaportumu gösterdim ve görevli nazikçe gülümsedi.", "Pasportimi ko'rsatdim va xodim mehribon tabassum qildi."),
        ("Güvenlik kemerimi çıkarmamı ve ceplerimi boşaltmamı istedi.", "Xavfsizlik xodimlari kamarimni yechish va cho'ntaklarimni bo'shatishni so'radi."),
        ("Kalbim hızlı atıyordu ama her şey sorunsuz geçti.", "Yuragim tez urayotgan edi, lekin hammasi silliq o'tdi."),
        ("Kapıda dev uçakların birer birer havalandığını izledim.", "Reja oldida ulkan samolyotlarning birma-bir ko'tarilishini kuzatdim."),
        ("Motorları uykulu dev hayvanlar gibi kükrüyordu.", "Ularning dvigatellari ulkan uxlagan hayvonlar kabi g'irladi."),
        ("Biniş, kalkıştan otuz dakika önce başladı.", "Yo'lovchilarni o'tkazish jo'nashdan o'ttiz daqiqa oldin boshlandi."),
        ("Biletimi hafifçe titreyen ellerle uzattım.", "Biletimni biroz titrayotgan qo'llarim bilan topshirdim."),
        ("Güler yüzlü bir kabin memuru beni uçağa hoş geldin dedi.", "Samimiy stuardessa menga bortda xush kelibsiz dedi."),
        ("Koltuğum tam umduğum gibi pencere kenarındaydı.", "O'rinishim oynaga yondosh edi, aynan umid qilganimdek."),
        ("Yaşlı bir kadın yanıma oturdu ve beni sıcak bir şekilde selamladı.", "Yonimga keksa ayol o'tirdi va meni iliqlik bilan kutib oldi."),
        ("Gergin yüzümü fark etti ve sohbet başlattı.", "U bezovta yuzimni sezib, suhbatni boshladi."),
        ("Bana elliden fazla kez uçtuğunu söyledi.", "U ellik martadan ortiq parvoz qilganini aytdi."),
        ("Sakin sesi beni yavaş yavaş rahatlattı.", "Uning osoyishta ovozi meni asta-sekin tinchlantirdi."),
        ("Uçak piste çıktı ve bir an için durdu.", "Samolyot uchish yo'lagiga chiqib bir lahza to'xtadi."),
        ("Sonra motorlar bizi gittikçe daha hızlı ileri itti.", "Keyin dvigatellar bizni tobora tezroq oldinga surdi."),
        ("Tekerlekler yerden kesildi ve midem gitti.", "G'ildiraklar yerdan uzildi va qornim tushib ketdi."),
        ("Evler küçüldü, yollar ince çizgilere dönüştü.", "Uylar kichiklashdi, yo'llar ingichka chiziqlarga aylandi."),
        ("Bulutların üstünde dünya aydınlık ve sessizdi.", "Bulutlar ustida dunyo ravon va jim edi."),
        ("Altımızdaki bulutlar yumuşak beyaz dağlara benziyordu.", "Ostimizdagi bulutlar yumshoq oq tog'largagina o'xshardi."),
        ("Kadın ufukta uzaktaki denizi işaret etti.", "Ayol ufqdagi uzoq dengizni ko'rsatdi."),
        ("Kalkıştan kısa süre sonra yemek geldi, pirinçli tavuk.", "Ko'tarilishdan ko'p o'tmay ovqat keldi — tovuq guruch bilan."),
        ("Her şeyi yedim, çünkü heyecan beni acıktırır.", "Hammasini yedim, chunki hayajon meni och qiladi."),
        ("Sonra bir film izlemeye çalıştım ama sürekli pencereden dışarı bakıyordum.", "Keyinchalik film ko'rishga harakat qildim, lekin doimo oyna tomonga qaradim."),
        ("Karadeniz üzerinde bir yerde hafif bir türbülansa girdik.", "Qora dengiz ustidagi bir joyda yengil silkinishga kirishdik."),
        ("Uçak biraz sarsıldı ve ellerim dondu kaldı.", "Samolyot biroz larzaga keldi va qo'llarim qotib qoldi."),
        ("Kadın sadece \"Yoldaki tümsekler işte\" dedi.", "Ayol shunchaki dediki: 'Faqat yo'ldagi to'siqlar'."),
        ("Çok geçmeden gökyüzü tamamen sakinleşti.", "Tez orada osmon yana butunlay tinchlandi."),
        ("Kaptan on beş dakika içinde ineceğimizi duyurdu.", "Kapitan o'n beshta daqiqada qo'nishimizni e'lon qildi."),
        ("Yukarıdan İstanbul binlerce ışıkla parıldıyordu.", "Yuqoridan Istanbul minglab chiroqlar bilan yaltiradi."),
        ("Boğaz, iki kıta arasında gümüş bir kurdele gibi göründü.", "Bosfor ikki qit'a orasida kumir lenta kabi namoyon bo'ldi."),
        ("İniş, bir kasisten geçmekten bile daha yumuşak hissettirdi.", "Qo'nish tezlik to'sig'idan o'tishdan ham silliqroq tuyuldi."),
        ("Uçak durduğunda herkes hafifçe alkışladı.", "Samolyot to'xtaganda hammam yengil qarsak chaldi."),
        ("Nazik kadına teşekkür ettim ve sağlık diledim.", "Mehmondo'st ayolga rahmat aytdi va sog'liq tiladim."),
        ("Bagaj alanında, şaşırtıcı bir şekilde valizim ilk çıkanlardan oldu.", "Bagaj olish joyida chamadonim kutilmaganda birinchi bo'lib keldi."),
        ("Amcam camın arkasında büyük bir tabelayla bekliyordu.", "Amakim katta yozuv bilan shisha ortida kutib turgan edi."),
        ("Sarılması tüm korkumu anında yok etti.", "Uning quchoqlashi barcha qo'rquvni darhol yo'q qildi."),
        ("Şehre doğru giderken sürekli \"Gerçekten uçtum!\" diye tekrarladım.", "Shahar tomon ketayotib, doim takrorladim: 'Men rostan uchdim!'"),
        ("O günden beri her uçuşu seviyorum.", "O'sha kundan buyon har bir parvozni yaxshi ko'raman."),
    ],
    2: [
        ("Yağmurlu bir salı günü, kütüphanenin yakınında küçük bir kafe keşfettim.", "Yomg'irli seshanba kuni kutubxona yaqinida kichik kafeni kashf etdim."),
        ("Ahşap kapısında kahve çekirdeği şeklinde küçük pirinç bir tokmak vardı.", "Uning yog'och eshigida qahva donasiga o'xshash kichik guruch dastasi bor edi."),
        ("İçeride hava tarçın ve kavrulmuş çekirdek kokuyordu.", "Ichkarida havoda doljin va qovurilgan don hidi bor edi."),
        ("Eski bir hoparlörden yumuşak caz müziği çalıyordu.", "Eski karnaydan nozik jaz musiqasi jim chalinayotgan edi."),
        ("Sadece üç masa dizüstü bilgisayarlı öğrenciler tarafından doluydu.", "Faqat uch stul noutbukli talabalar bilan band edi."),
        ("Tezgahın arkasındaki genç bir kadın beni sıcak bir baş selamıyla karşıladı.", "Dollar ortidagi yosh ayol meni iliqlik bilan bosh irg'ab kutib oldi."),
        ("Bir kapuçino ve bir dilim elmalı turta sipariş ettim.", "Men kapuchino va olcha pie bo'lagini buyurtma qildim."),
        ("Beklerken karatahtadaki el yazısı menüyü okudum.", "Kutayotib, doskadagi qo'lyozma menyuni o'qidim."),
        ("\"Bulut Latte\" gibi komik isimler taşıyan içecekler sunuyorlardı.", "Ularda 'Bulut latte' kabi kulgili nomlar bilan ichimliklar bor edi."),
        ("Kahvem, süt köpüğüne çizilmiş küçük bir yaprakla geldi.", "Mening kahvam sut ko'pigi ichiga chizilgan mayda yaproq bilan keldi."),
        ("Elmalı turta fırından yeni çıkmış gibi hâlâ sıcaktı.", "Olcha pie hali ham tandirdan chiqqancha iliq edi."),
        ("Her lokma küçük bir kasabadaki sonbaharın tadını taşıyordu.", "Har bir luqma kichik shaharchadagi kuzni eslatardi."),
        ("Defterimi açtım ve kendime bir mektup yazmaya başladım.", "Daftarchamni ochdim va o'zimga xat yozishni boshladim."),
        ("Yağmur yanımdaki büyük pencereye hafifçe vuruyordu.", "Yomg'ir yonimdagi katta oynaga yumshoq urildi."),
        ("Yaşlı bir adam içeri girdi, gri şemsiyesindeki suyu silkeliyordu.", "Keksaygan erkak kirdi, kulrang soyabonidan suv silkitib."),
        ("Mutfaktaki aşçı dahil herkese ismiyle selam verdi.", "U hammaga, hatto oshxona oshpazi ham, ismi bilan salom berdi."),
        ("Belli ki yıllardır buranın müdavimiydi.", "Aniqki, u bu yerda ko'p yillardan beri doimiy mehmon edi."),
        ("Garson sormadan onun her zamanki siparişini getirdi.", "Ofitsiant uning odatbuy buyurtmasini so'ramasdin keltirdi."),
        ("Sert bir çay, yanında bir şeker ve tereyağlı bir kurabiye.", "Kuchli choy, bir qoshiq shakar alohida va saryog'li pechene."),
        ("Onu izlerken insanların küçük kafeleri neden bu kadar sevdiğini anladım.", "Uni kuzatib, odamlarning kichik kaflarni nega sevishi tushundim."),
        ("Büyük yerler size hizmet eder, küçük yerler ise sizi hatırlar.", "Katta joylar sizga xizmat qiladi, kichik joylar esa eslab qoladi."),
        ("Yarım saat sonra yanıma iki arkadaş oturdu.", "Yarim soatdan keyin yonimga ikki dugona o'tirdi."),
        ("Hangi tatlıyı paylaşacakları konusunda şakayla tartıştılar.", "Ular qaysi desertni bo'lishish masalasida o'yinkam bahslashdi."),
        ("Sonunda çilek soslu cheesecake'te karar kıldılar.", "Nihoyat, ular maydalangan pishiriqni tanlashdi."),
        ("Kahkahaları yağmur sesleriyle güzelce karıştı.", "Ularning kulishi yomg'ir tovushlari bilan chiroyli qorishdi."),
        ("Kahvemi bitirdim ve hiç vicdan azabı duymadan ikinci bir fincan daha sipariş ettim.", "Kahvamni tugatib, ikkinchi finjanni vijdontsiz buyurtma qildim."),
        ("Garson sanki bunu tamamen onaylıyormuş gibi gülümsedi.", "Ofitsiant xuddi to'liq ma'qullayotgandek tabassum qildi."),
        ("Yudumlar arasında baristanın latte art yaptığını izledim.", "Luqmalar orasida barista latte san'atini quyayotganini tomosha qildim."),
        ("Elleri, resim yapan bir sanatçı gibi kendinden emin hareket ediyordu.", "Uning qo'llari rassom chizayotgandek ishonch bilan harakatlanardi."),
        ("Yandaki masadaki küçük bir kıza sıcak çikolata geldi.", "Qo'shni stoladagi kichkina qiz issiq shokolad oldi."),
        ("İçinde yüzen marshmallowları görünce gözleri büyüdü.", "Ichida suzayotgan zefirni ko'rib, ko'zlari kengaydi."),
        ("\"Bu hayatımın en güzel günü\" diye fısıldadı.", "U shivirladi: 'Bu mening hayotimdagi eng yaxshi kun.'"),
        ("Annesi güldü ve gizlice bir marshmallow aşırdı.", "Onasi kuldi va bir zefirni maxfiy o'g'irladi."),
        ("Böyle anlar ne planlanabilir ne de satın alınabilir.", "Bunday lahzalarni rejalashtirib yoki sotib olb bo'lmaydi."),
        ("Dışarıda yağmur sonunda hafif damlalara dönüştü.", "Tashqarida yomg'ir nihoyat yengil tomchilarga aylandi."),
        ("Altın rengi sokak lambaları ıslak kaldırımda yansıyordu.", "Oltin ko'cha chiroqlari ho'l troyni aks ettirdi."),
        ("Hesabımı ödedim ve cömert bir bahşiş bıraktım.", "Hisobni to'lab, saxiy chaqa qoldirdim."),
        ("Garson bana teşekkür etti ve sıcak bir şekilde el sallayarak vedalaştı.", "Ofitsiant menga rahmat aytdi va iliq xayrli yol dedi."),
        ("Kapıda son bir bakış için arkamı döndüm.", "Eshik oldida oxirgi marta orqaga burilib qaradim."),
        ("Kafe, gri akşamda bir fener gibi parlıyordu.", "Kafe kulrang kechda fonar kabi yonib turardi."),
        ("Şimdi her salı o kafeye gidiyorum.", "Endi har seshanba kuni o'sha kafega boraman."),
        ("Aynı masa, aynı kapuçino, aynı sıcak his.", "Xuddi shu stol, xuddi shu kapuchino, xuddi shu iliq tuygu."),
        ("Bazen garson bana turtanın son dilimini saklıyor.", "Ba'zan ofitsiant menga oxirgi pie bo'lagini saqlab qo'yadi."),
        ("Bunun gibi küçük alışkanlıklar hayatı tatlı ve istikrarlı kılar.", "Bunday kichik an'anelar hayotni shirin va muqim qiladi."),
    ],
    3: [
        ("Yeni ofisteki ilk haftam bir rüya gibiydi.", "Yangi ofisdagi ilk haftam tushga o'xshab tuyuldi."),
        ("İlk günümden önceki gece kıyafetlerimi hazırladım.", "Birinchi kundan oldingi kechqurun kiyimlarimni tayyorladim."),
        ("Heyecanımdan dolayı kırk dakika erken vardım.", "Asabiyligidan qirq daqiqa erta yetib keldim."),
        ("Benimle konuşan ilk kişi güvenlik görevlisiydi.", "Qo'riqchi menga gapirgan birinchi odam bo'ldi."),
        ("\"Rahat ol, herkes ilk pazartesisini atlatır\" dedi.", "U dediki: 'Bo'shasangiz, hamma birinchi dushanbasidan o'tadi.'"),
        ("Yöneticim beni resepsiyonda parlak bir gülümsemeyle karşıladı.", "Mening menejerim meni qabulxonda yorqin tabassum bilan kutib oldi."),
        ("Bana tüm katı hızlıca gezdirdi.", "U menga butun qavatni tezkor sayohat qilib ko'rsatdi."),
        ("Halılardan bilgisayar ekranlarına kadar her şey yeni kokuyordu.", "Hamma narsa yangi hid berdi — gilamlardan kompyuter ekranlarigacha."),
        ("Masam küçüktü ama geniş bir pencerenin hemen yanındaydı.", "Stolim kichik edi, lekin katta oynaning yonida joylashgan."),
        ("Öğle yemeğinden önce on yabancı kendini tanıttı.", "Tushlikkacha o'n noma'lum odam o'zini tanishtirdi."),
        ("Doğrusu isimlerinin yarısını hemen unuttum.", "Halos, ularning ismlarining yarmisini darhol unutdim."),
        ("Ekip arkadaşım Doston daha sonra basılı bir listeyle beni kurtardı.", "Jamoadoshim Doston keyinroq chop etilgan ro'yxat bilan menga yordam berdi."),
        ("Ofis kurallarını nazik bir mizahla anlattı.", "U ofis qoidalarini muloyim hazil bilan tushuntirib berdi."),
        ("Örneğin, toplantılar her zaman beş dakika geç başlar.", "Masalan, uchrashuvlar doim besh daqiqa kech boshlanadi."),
        ("Ve kahve makinesi her cuma öğleden sonra bozulur.", "Va qahva mashinasi har juma kuni tushdan keyin buziladi."),
        ("Salı günü ilk gerçek ekip toplantıma katıldım.", "Seshanba kuni ilk haqiqiy jamoa uchrashuvimda qatnashdim."),
        ("Herkes hızlı konuşuyor ve gizemli kısaltmalar kullanıyordu.", "Hamma tez gapirdi va sirli qisqartmalardan foydalandi."),
        ("Sadece yüzde altmışını anlasam da ciddi ciddi başımı salladım.", "Faqt faqat oltmish foizini tushungan bo'lsamda, jiddiy bosh irg'adim."),
        ("Sonrasında bilmediğim her kelimeyi not aldım.", "Keyin har bir tanish emas so'zni yozib oldim."),
        ("O akşam onları okul kelimeleri gibi çalıştım.", "O'sha kechqurun ularni maktab lug'ati kabi o'rgandim."),
        ("Çarşambaya kadar sistemdeki ilk küçük hatamı düzelttim.", "Chorshanba kunga kelib, tizimdagi ilk kichik xatoni tuzatdim."),
        ("Amirim çalışmamı herkesin önünde övdü.", "Rahbarim ishimni hamma oldida maqtadi."),
        ("Kulaklarım kızardı ama kendimi on santim daha uzun hissettim.", "Quloqlarim qizaridi, lekin o'zimni o'n santimetr balandroq his qildim."),
        ("Perşembe günü ofis öğle yemeği geleneğini getirdi.", "Payshanba kuni ofis tushlik an'anasini olib keldi."),
        ("Herkes evden bir yemek pişirir ya da getirir.", "Har kim uyida bir taom tayyorlaydi yoki olib keladi."),
        ("Annemin pirinç pilavını getirdim ve hızla bitti.", "Onamning guruch palovini olib keldim, u tez tugadi."),
        ("Diğer departmanlardan insanlar tarifi sormaya geldi.", "Boshqa bo'limlardagi odamlar retseptni so'rab kelishdi."),
        ("Cuma günü birinin doğum günü olduğu için pastayla bitti.", "Juma kuni tort bilan tugadi, chunki kimningdir tug'ilgan kuni edi."),
        ("Ofislerde olduğu gibi yarı şarkı söyleyip yarı fısıldayarak sessizce şarkı söyledik.", "Biz jim qo'shiq aytdik, ofislarda odat bo'lganidek, yarim kuylanib yarim shivirlab."),
        ("O hafta boyunca üç önemli ders öğrendim.", "O'sha hafta davomida uch muhim darsni o'rgandim."),
        ("Birincisi, soru sormak zayıflık değil güçtür.", "Birinchisi, savol berish kuchsizlik emas, kuch."),
        ("İkincisi, kısa bir yürüyüş yorgun bir beyni toparlar.", "Ikkinchisi, qisqa sayr charchagan miygacha yordam beradi."),
        ("Üçüncüsü, iş arkadaşları beklediğinizden daha hızlı dost olur.", "Uchinchisi, hamkasblar kutgandan ham tezroq do'stga aylanadi."),
        ("Cuma akşamı gelen kutum sonunda boştu.", "Juma kechqurun pochtam nihoyat bo'sh edi."),
        ("Masama baktım ve sessiz bir gurur hissettim.", "Stolimga qarab sokin iftixor his qildim."),
        ("Bir hafta önce burası bilinmeyen ve korkutucu bir yerdi.", "Bir hafta oldin bu joy noma'lum va qo'rqinchli edi."),
        ("Şimdi ise şimdiden ikinci bir yuva gibi hissettiriyor.", "Endi u allaqachon ikkinchi uyday tuyuladi."),
        ("Ayrılırken güvenlik görevlisi bana el salladı.", "Chiqib ketayotib, qo'riqchi menga qo'l silkitdi."),
        ("\"Pazartesi görüşürüz\" dedi, eski bir dost gibi.", "'Dushanba ko'rishamiz', deb aytdi u eski do'stday."),
        ("Eve dönen otobüste hiçbir şey yokken gülümsedim.", "Uyga qaytayotgan avtobusda hech kimga bog'liq bo'lmagan sababsiz tabassum qildim."),
        ("Ayaklarım ağrıyordu ama kalbim hafifti.", "Oyoqlarim og'ridi, lekin yuragim yengil edi."),
        ("Aileme bu işin bana uygun hissettirdiğini yazdım.", "Ota-onamga bu ish to'g'ri kelayotganini yozdim."),
        ("Babam tek kelimeyle cevap verdi: \"Sonunda.\"", "Otam bitta so'z bilan javob berdi: 'Nihoyat.'"),
        ("O gece hâlâ yaka kartımı takarken uyuyakaldım.", "O'sha kechqurun ish belgisimni yechmasdan uxlab qoldim."),
    ],
    4: [
        ("Her iki haftada bir pazar günü ailemiz büyükannemin evinde toplanır.", "Har juftshanba kuni oilamiz bobomizning uyida yig'iladi."),
        ("Evi, kavak ağaçlarıyla dolu sessiz bir sokağın sonunda bulunur.", "Uning uyi teraklar bilan to'lgan sokin ko'chaning oxirida joylashgan."),
        ("Kapıyı çalmadan önce bile kuşları duyabilirsiniz.", "Darvoza urishdan avval qushlar ovozini eshitishingiz mumkin."),
        ("Büyükannem şafak vakti mor önlüğünü giyip yemek yapmaya başlar.", "Bobomiz tong otishidan boshlab oshxona boshlaydi, binafsha fartugi kiyingan holda."),
        ("Taze somsa kokusu bizi kapıda karşılar.", "Yangi somsa hidi bizni eshik oldida kutib oladi."),
        ("Amcalar kimin arabasını daha iyi park ettiği konusunda neşeyle tartışır.", "Amakilar kimning mashinasi yaxshi to'xtaganligi haqida quvonch bilan bahslashadi."),
        ("Kuzenler eski bir futbol topunun peşinde bahçede koşuşturur.", "Amakivachchalar bog'da eskicha futbol ortidan yugurishadi."),
        ("Her seferinde biri mutlaka bahçe hortumuna takılıp düşer.", "Har safar kimdir bog'dagi shlangaga tiqilib yiqiladi."),
        ("Teyzeler verandada oturup telefonlarındaki fotoğrafları karşılaştırır.", "Xolalar verandada telefonlaridagi suratlarni solishtirib o'tirishadi."),
        ("Büyükbabam satranç tahtasını küçük bir kral gibi korur.", "Bobomiz shaxmat taxtasini kichik qirol kabi qo'riqlaydi."),
        ("Her torununa meydan okur ve çoğumuzu yener.", "U har bir nabirasini o'yin chorlaydi va ko'pchiligimizni mag'lub etadi."),
        ("Bugün iki kez kaybettim ve öğle yemeğinden sonra rövanş istedim.", "Bugun ikki marta yutqazdim va tushlikdan keyin revansh talab qildim."),
        ("Mutfakta büyükannem hiçbir şeyi ölçmez.", "Oshxonada Bobomiz hech narsani o'lchamaydi."),
        ("Tuzu \"yemeği dinleyerek\" eklediğini söyler.", "U tuzni 'ovqat tinglab' qo'shishini aytadi."),
        ("Hamuru altın rengi kağıt gibi ince açılır.", "Uning xamiri oltin qog'oz kabi ingichka cho'ziladi."),
        ("Tüm sırlar tariflerde değil, onun bileklerinde saklıdır.", "Barcha sirlar retseptlarda emas, bilaklarida yashirilgan."),
        ("Bulaşıkları yıkayıp sıcak ekmek aşırarak yardım ederim.", "Men idish yuvgani va iliq non o'g'irlashga yordam beraman."),
        ("Her seferinde beni görmezden geliyormuş gibi yapar.", "U har safar meni ko'rmagan bo'lib qiyofa beradi."),
        ("Saat ikide uzun masa yemeklerin ağırlığıyla inler.", "Soat ikkida uzun stol taomlar ostida ingichka ovoz chiqaradi."),
        ("Pilav, salatalar, somsa, meyveler ve üç çeşit çay.", "Palov, salatlar, somsa, mevalar va uch xil choy."),
        ("Yemekten önce büyükbabam birkaç sessiz teşekkür sözü söyler.", "Yeyishdan oldin Bobomiz bir nechta sokin minnatdorchilik so'zi aytadi."),
        ("Sonra oda konuşma ve kahkahalarla patlar.", "Keyin xona gapirish va kulish bilan portlaydi."),
        ("Herkes aynı anda konuşur ve nasılsa işe yarar.", "Hamma bir vaqtda gapiradi va bir yo'l bilan hammasi mos keladi."),
        ("Küçük Zuhra bir sandalyenin üstünde durup şiir okur.", "Kichkina Zuhra kursida turub she'r aytyapti."),
        ("Çok yüksek sesle alkışlarız ve o bir aktris gibi eğilir.", "Biz juda baland qarsak chaldik va u aktrisa kabi egildi."),
        ("Yemekten sonra büyükler gençliklerinden hikayeler anlatır.", "Ovqatdan keyin kattalar yoshliklaridagi hikoyalarni aytishadi."),
        ("Bugünkü hikaye büyükbabamın 1975'te bir keçisini kaybetmesiyle ilgiliydi.", "Bugungi hikoya Bobomizning 1975-yilda echisini yo'qotishi haqida edi."),
        ("Hikayenin yarısını inkar eder, bu da onun doğru olduğunu kanıtlar.", "U yarmi inkor etadi, bu esa uning rostligini isbotlaydi."),
        ("Gençler dinlemiyormuş gibi yapar ama her şeyi duyar.", "O'smirliklar tinglamaslikka harakat qiladi, ammo hammasini eshitishadi."),
        ("Sonra evin arkasındaki ağaçtan elma toplarız.", "Keyinchalik uy ortidagi daraxtdan olma teramiz."),
        ("En iyileri doğal olarak en yükseklerde asılıdır.", "Eng zo'rlari tabiiy ravishda balandda osilgan bo'ladi."),
        ("Kuzenim beni eski günlerdeki gibi omuzlarına kaldırır.", "Amakivachcham meni eski vaqtlarday yelkasiga ko'taradi."),
        ("Bir sepeti doldururuz, bir sepeti de sessizce yeriz.", "Bir savat to'ldiramiz va yana bir savatni jim yeymiz."),
        ("Büyükannem daha sonra elmaları sayar ve sadece anlayışlı bir gülümseme atar.", "Bobomiz keyinchalik olmalarni sanab, anglagan holda tabassum qiladi."),
        ("Akşama doğru biri eski fotoğraf albümünü çıkarır.", "Kechga yaqin kimdir eskicha fotoalbomni olib chiqadi."),
        ("Siyah beyaz büyükanne büyükbabalarımız bize bakar, sonsuza dek genç.", "Qora-oq bobolarimiz bizga abadiy yosh holda qarashadi."),
        ("Annem büyükannemin gelinliğini işaret eder ve iç çeker.", "Onam Bobomizning to'y ko'ylagini ko'rsatib nafas oladi."),
        ("Büyükannem elini sallar ve modanın kendini tekrarladığını söyler.", "Bobomiz qo'l silkitadi va moda takrorlanishini aytadi."),
        ("Gökyüzü turuncuya döndüğünde arabalar sıraya girmeye başlar.", "Osmon to'qsarig' aylanganda mashinalar navbatga turadi."),
        ("Kimse ayrılan ilk aile olmak istemez.", "Hech kim birinchi bo'lib ketadigan oila bo'lishni istamaydi."),
        ("Her zamanki gibi kapıda yüzlerce kez sarılırız.", "Odatdagidek darvoza oldida yuz marta quchoqlashamiz."),
        ("Büyükannem çantalarımızı zar zor kapanana kadar doldurur.", "Bobomiz sumkalarimizni zo'rg'a yopiladigan darajada to'ldiradi."),
        ("Eve dönerken araba elma ve sıcak ekmek kokar.", "Uyga qaytayotib, mashina olma va iliq non hidi beradi."),
        ("Küçük kardeşim yarım yenmiş bir kurabiyeyi elinde tutarak uykuya dalar.", "Kichik ukam yarim yegan pecheneni qo'liga olib uxlab qoladi."),
        ("Bu pazarlar basit, gürültülü ve kesinlikle mükemmeldir.", "Bu shanbalar oddiy, shovqinli va mutlaqo mukammal."),
    ],
    5: [
        ("Geçen kış ciddi bir kışlık mont almaya karar verdim.", "O'tgan qish men jiddiy qishki palto sotib olishga qaror qildim."),
        ("Eski montum inceydi ve her aralık ayında beni yüzüstü bırakırdı.", "Eski kurtkam ingichka edi va har dekabrda menga xiyonat qilardi."),
        ("Kararlı bir sincap gibi iki ay para biriktirdim.", "Ikki oy davomida qat'iyatli sichqon kabi pul yig'dim."),
        ("Cumartesi sabahı ablamla büyük pazara gittik.", "Shanba ertalab opam bilan katta bozorga bordik."),
        ("Kışın pazar, gri ve siyah montların denizidir.", "Qishda bozor kulrang va qora paltolar dengizidir."),
        ("Her satıcı kendi dükkanında en iyi fiyatın olduğunu bağırıyordu.", "Har bir savdogar o'z do'konida eng zo'r narx borligini baqirdi."),
        ("Bir satıcı biz etrafa bakmadan önce bizi çaya davet etti.", "Bir savdogar atrofga qaramay choyga taklif qildi."),
        ("Güldük ve kabul ettik, çünkü reddetmek kaba görünüyordu.", "Kulib qabul qildik, chunki rad etish qo'pollik tuyuldi."),
        ("Çay sıcaktı, tatlıydı ve tehlikeli derecede sürekli dolduruluyordu.", "Choy issiq, shirin va xavfli darajada qayta quyiladigan edi."),
        ("Üç bardaktan sonra sonunda montlar hakkında konuşmaya başladık.", "Uch piyola choynan keyin nihoyat paltolar haqida gaplashdik."),
        ("Bana derin cepli, ağır siyah bir mont gösterdi.", "U menga chuqur cho'ntakli og'ir qora paltoni ko'rsatdi."),
        ("Sıcaktı ama beni yürüyen bir gardırop gibi gösteriyordu.", "U iliq edi, lekin meni yuruvchi shkafga o'xshatdi."),
        ("Ablam gülmemeye çalıştı ve tamamen başarısız oldu.", "Opam kulmaslikka harakat qildi va butunlay muvaffaqiyatsiz bo'ldi."),
        ("Satıcı bunun \"babalar için bir mont\" olduğunu kabul etti.", "Savdogar bu 'otolar uchun palto' ekanini tan oldi."),
        ("Sonraki dükkanda gümüş düğmeli koyu mavi bir mont buldum.", "Keyingi do'konda kumush tugmali to'q ko'k palto topdim."),
        ("Cüzdanım itiraz edemeden ayna \"evet\" dedi.", "Oyna hamyonim bahslashidan oldin 'ha' dedi."),
        ("Ama fiyat beni bir an oturmaya mecbur bıraktı.", "Lekin narx meni bir lahza o'tirishga majbur qildi."),
        ("Ablam profesyonel bir diplomat gibi pazarlık yapmaya başladı.", "Opam professional diplomatchidek savdohni boshladi."),
        ("Başka bir dükkandan, kaliteden ve erkek kardeşinin düşük maaşından bahsetti.", "U boshqa do'konni, sifatni va akasining kichik maoshini tilga oldi."),
        ("Satıcı izin almak için patronunu arıyormuş gibi yaptı.", "Savdogar ruxsat uchun boshlig'iga qo'ng'iroq qilganday bo'ldi."),
        ("Onun da dahil olduğu herkes, aslında bir arama olmadığını biliyordu.", "Qo'ng'iroq yo'qligini hamma, hatto u ham bilardi."),
        ("Sonunda ikimizi de şaşırtan bir fiyatta anlaştık.", "Nihoyat ikkovimizni ham hayron qoldirgan narxda kelishdik."),
        ("Ödemeyi yaptım ve mont yeni bir dost gibi kollarıma sığdı.", "To'lov qildim va palto yangi do'stdek quchoqlarimga sig'di."),
        ("Çıkarken bir sokak satıcısından kavrulmuş mısır aldık.", "Chiqib ketayotib, ko'cha sotuvchisidan qovurilgan makkajo'xori oldik."),
        ("Soğuk rüzgarda mısır yemek burada özel bir yetenektir.", "Sovuq shamolda makkajo'xori yeyish bu yerda maxsus qobiliyat."),
        ("Evde babam montu bir gümrük memuru gibi inceledi.", "Uyda otam paltoni bojxona xodimidek tekshirdi."),
        ("Dikişleri, astarı, düğmeleri kontrol etti, hatta kokladı bile.", "U choklar, astar, tugmalarni tekshirdi, hatto hidini ham sinadi."),
        ("Sonra yavaşça başını salladı, ki bu onun en yüksek övgüsüdür.", "Keyin u sekin bosh irg'adi — bu uning eng baland maqtovi."),
        ("Annem \"ne olur ne olmaz\" diye hemen bir düğmeyi daha sıkı dikti.", "Onam bir tugmani 'ehtiyot uchun' darhol mustahkam tikdi."),
        ("O gece montu görebileceğim bir yere astım.", "O'sha kechqurun paltoni ko'radigan joyimga osdim."),
        ("Kulağa saçma geldiğini biliyorum, ama gerçekten gurur duyuyordum.", "Ahmoqona tuyulishini bilaman, lekin chin dildan faxrlanardim."),
        ("İki gün sonra şehre gerçek bir don geldi.", "Ikki kundan keyin shaharga haqiqiy qattiq sovuq keldi."),
        ("Mont beni rüzgara karşı sıcak bir sessizlik gibi sardı.", "Palto meni shamolga qarshi iliq sokinlik kabi o'ray oldi."),
        ("Otobüs durağında yaşlı bir adam nereden aldığımı sordu.", "Avtobus bekatida keksa odam uni qayerdan olganimni so'radi."),
        ("Gururla pazarı işaret ettim ve tüm ayrıntıları anlattım.", "Faxr bilan bozor tomonga ishora qilib barcha tafsilotlarni berdim."),
        ("Adresi kısacık bir kalemle eline yazdı.", "U manzilni qalam bo'lagi bilan kaftiga yozib oldi."),
        ("Ocak ayında ablam bir akşamlığına ödünç istedi.", "Yanvarda opam uni bir kecha so'rab oldi."),
        ("Onu hafifçe parfüm kokarak geri getirdi.", "Uni engil parfyum hidi bilan qaytarib berdi."),
        ("Kızmış gibi yaptım ve ertesi hafta yine ödünç verdim.", "Jahl ko'ringanday qildim va keyingi haftada yana berdim."),
        ("Şubata gelindiğinde ailenin herkesi o montu bir kez giymişti.", "Fevralga kelib butun oila o'sha paltoni bir marta kiyyan edi."),
        ("Kar, yağmur ve kuzenimin futbol antrenmanından sağ çıktı.", "U qor, yomg'ir va amakivachchamning futbol mashg'ulotidan omon chiqdi."),
        ("Şimdi her kış önemli bir törenle başlıyor.", "Endi har qish muhim bir marosim bilan boshlanadi."),
        ("Gardırobu açıyorum, montu nazikçe silkeliyorum ve gülümsüyorum.", "Shkafni ochaman, paltoni yumshoq silkitaman va tabassum qilaman."),
        ("Bazı alışverişler pratiktir; bu ise aynı zamanda bir hikayeye dönüştü.", "Ba'zi xaridlar amaliy; bu esa hikoyaga ham aylandi."),
    ],
    6: [
        ("Sokak futbol takımımız üst üste beş maç kaybetmişti.", "Ko'cha futbol jamoamiz ketma-ket beshta o'yinda mag'lub bo'ldi."),
        ("Cumartesi günü mahalle kupasının finali oynanacaktı.", "Shanba kuni mahalla kubogining final o'yini bo'lishi kerak edi."),
        ("Rakiplerimiz bir sonraki sokaktan uzun boylu ve hızlı çocuklardı.", "Raqiblarimiz qo'shni ko'chaning baland va tez yigitlari edi."),
        ("Herkes pes edip evde kalmamız gerektiğini söyledi.", "Hamma uyda qolib taslim bo'lishimizni aytdi."),
        ("Ama kaptanımız Jasur'un bizim için başka planları vardı.", "Lekin sardorimiz Jasurning biz uchun boshqa rejalar bor edi."),
        ("Perşembe akşamı fazladan bir antrenman çağırdı.", "U payshanba kechqurun qo'shimcha mashg'ulot chaqirdi."),
        ("Sadece yedi oyuncu geldi ve ikisi hastaydı.", "Faqat yetti o'yinchi keldi, ikkovimiz kasal edik."),
        ("Sokak lambaları yanana kadar pas çalıştık.", "Ko'cha chiroqlari yoqilguncha paslar mashq qildik."),
        ("Jasur tek bir cümleyi tekrarlayıp durdu: \"Çalım atmadan önce pas ver.\"", "Jasur bitta jumlani takrorladi: 'Chalib ketishdan oldin pass ber.'"),
        ("Cuma gecesi heyecandan zor uyuyabildim.", "Juma kechqurun hayajondan zo'rg'a uxladim."),
        ("Kazandıran golü atmayı aklımdan yaklaşık kırk kez geçirdim.", "G'alaba golini urganini taxminan qirq marta xayolimdan o'tkazdim."),
        ("Cumartesi sabahı soğuktu, su birikintilerinin üzerinde ince bir buz vardı.", "Shanba ertalab sovuq edi, suv havzalarida ingichka muz bor."),
        ("Eski fabrikanın arkasındaki saha çamurdan yumuşamıştı.", "Eski zavod ortidagi maydon loy bilan yumshoq edi."),
        ("Termoslu dedeler dahil, seyirciler iki tarafa da dizilmişti.", "Tomoshabinlar ikki tomonda saf tortdi, termosli bobolar ham bor edi."),
        ("Hakem, sertliğiyle ünlü emekli bir öğretmendi.", "Hakim qat'iyligi bilan mashhur nafaqadagi o'qituvchi edi."),
        ("İlk on beş dakika bizim için felaketti.", "Dastlabki o'n beshta daqiqa biz uchun ofat bo'ldi."),
        ("İki gol attılar ve taraftarları yüksek sesle şarkı söyledi.", "Ular ikki marta gol urdi va muxlislarari baland qo'shiq aytdi."),
        ("Kalecimiz bir general gibi talimatlar bağırdı.", "Darvozabonimiz generaldek ko'rsatmalar baqirdi."),
        ("Yavaş yavaş perşembe günkü basit kuralı hatırladık.", "Astasekin, payshanbadagi oddiy qoidani esladi."),
        ("Pas ver, hareket et, tekrar pas ver — tek başına kahraman olmak yok.", "Pass, harakat, yana pass — yakka qahramonlar bo'lmaslik."),
        ("Oyunumuz birden hızlı ve temiz hale geldi.", "O'yinimiz birdan tez va toza bo'lib qoldi."),
        ("Devre arasından hemen önce, Aziz dar bir açıdan gol attı.", "Tanaffus oldi rostida, Aziz tor burchakdan gol urdi."),
        ("Islak çimde kayarak ona sarılmaya koştuk.", "Uni quchoqlash uchun yugurdik, ho'l o'tloqda sirg'alib."),
        ("Devre arası on dakika boyunca ağır nefes almakla geçti.", "Tanaffus o'n daqiqa og'ir nafas olish bilan o'tdi."),
        ("Jasur taktikleri anlatırken çamurlu zemine daireler çizdi.", "Jasur loy tuproqga aylanalar chizib taktikani tushuntirdi."),
        ("İkinci yarı sertçe, neredeyse öfkeyle başladı.", "Ikkinchi bo'lim shiddat bilan, deyarli g'azablangan holda boshlandi."),
        ("En uzun boylu oyuncuları bilerek ayak parmağıma bastı.", "Ularning eng baland o'yinchisi oyog'imni ataylab bosdi."),
        ("Hiçbir şey söylemedim ve bunun yerine topa odaklandım.", "Men hech narsa demadim va o'rniga to'pga e'tibor berdim."),
        ("Yirmi dakika kala bir serbest vuruş kazandık.", "Yigirma daqiqa qolganda jarima zarbasiga erishdik."),
        ("Herkes sessiz uzmanımız Sardor'a baktı.", "Hamma jim ko'rinishdagi mutaxassisimiz Sardorga qaradi."),
        ("Topu dikkatle yerleştirdi ve alnını sildi.", "U to'pni ehtiyotkorlik joylashtirdi va peshonasini artidi."),
        ("Duvar zıpladı; top onun etrafından güzelce kıvrılarak geçti.", "Devor sakradi; to'p uning atrofidan chiroyli egilib o'tdi."),
        ("İki-iki, ve sokak gürültüyle patladı.", "Ikk-ikki, va ko'cha shovqin bilan portladi."),
        ("Son dakikada bacaklarım tahta çubuklar gibi hissettirdi.", "Oxirgi daqiqada oyog'im yog'och tayoqlardek his qildi."),
        ("Sonra kaçak bir top tesadüfen bana doğru yuvarlandı.", "Keyin erkin to'p tasodifan menga tomonga aylanib keldi."),
        ("Jasur'un uzaklardan ismimi bağırdığını duydum.", "Jasurning ismimni uzoqdan baqirayotganini eshitdim."),
        ("Şut çekmek yerine pas verdim — kural beni kurtardı.", "Zarba o'rniga pass berdim — qoida meni qutqardi."),
        ("Aziz topu aldı ve kazandıran golü sakince attı.", "Aziz uni qabul qildi va g'alaba golini tinch urdi."),
        ("Düdük çaldı ve gülerek çimenlere yığıldım.", "Chalqildi chalinadi va men kulgan holda o'tloqqa yiqildim."),
        ("Dedeler termoslarını başlarının üzerinde kupa gibi salladılar.", "Bobolar termoslarni boshlaridan mukofotday silkitishdi."),
        ("Sert hakem bile kaptanımıza kısaca gülümsedi.", "Hattoning qattiqqo'l hakimi ham sardorimizga bir lahza tabassum qildi."),
        ("Gazı kaçmış limonata ve sıcak ekmekle kutladık.", "Biz gazsiz limonad va iliq non bilan nishonladik."),
        ("Doğrusu, bugün kimse skoru tam olarak hatırlamıyor.", "Bugun hech kim aniq hisobni eslamaydi, rostini aytsam."),
        ("Ama herkes sonunda birlikte oynadığımızı hatırlıyor.", "Lekin hamma nihoyat birga o'ynaganimizi eslaydi."),
    ],
    7: [
        ("Haziranda arkadaşlarımla Çimyon dağlarına tırmandık.", "Iyun oyida do'stlarim bilan Chimyon tog'lariga yurish qildik."),
        ("Hava tahmini güneş sözü vermişti, bu yüzden kimse yağmurluk almadı.", "Bashorat quyoshni va'da qilgandi, shuning uchun hech kim yomg'irpoq olmadi."),
        ("Bu, gezimizin ilk hatasıydı.", "Bu bizning sayohatimizdagi birinchi xato edi."),
        ("Serin sabah havasında saat altıda tırmanmaya başladık.", "Salqin ertalabki havoda soat oltida chiqishni boshladik."),
        ("Çam ağaçları alt yamaçları yeşil ordular gibi kaplıyordu.", "Qarag'aylar pastki yonbag'irlarni yashil armiyalardek qoplaydi."),
        ("Kuşlar her yönden şakıyor, sabahlarını sergiliyordu.", "Qushlar har tomondan kuyladi, ertalablarini ko'rsatib turardi."),
        ("Saat ona kadar ter gömleklerimizde karanlık haritalar çizmişti.", "O'nlikka kelib, ter ko'ylaklarimizda qora xaritalar chizdi."),
        ("Suyu çok hızlı içtik ve buna güldük.", "Suvni juda tez ichdik va buning ustidan kuldik."),
        ("Patika, altında küçük bir dere olan bir uçurum boyunca daralıyordu.", "Yo'l pastda kichik soy bo'lgan jarlik bo'ylab toraydi."),
        ("Faris geride kaldı, sırt çantasından dramatik bir şekilde şikayet ederek.", "Faris orqada qoldi, chamadoni haqida dramatik shikoyat qilib."),
        ("Onunla dalga geçtik ama yine de birlikte yavaşladık.", "Uni masxara qildik, lekin baribir birga sekinlashtirdik."),
        ("Öğleye doğru gökyüzü ruh halini tamamen değiştirdi.", "Taxminan peshin vaqtida osmon kayfiyatini butunlay o'zgartirdi."),
        ("Uzak sırtın üzerinden gri bir bulut duvarı yükseldi.", "Kulrang bulut devori uzoq tizmadan oshib chiqa boshladi."),
        ("Sanki biri yaza bir pencere kapatmış gibi sıcaklık düştü.", "Harorat tushdi, xuddi kimdir yozga oynani yopib qo'yganidek."),
        ("İlk damlalar büyük, soğuk ve şaşırtıcı derecede dostçaydı.", "Birinchi tomchilar katta, sovuq va kutilmaganda samimiy edi."),
        ("Sonra yağmur bir alkış gibi geldi — yoğun ve her yerde.", "Keyin yomg'ir olqish kabi keldi — kuchli va hamma joyda."),
        ("Yakındaki büyük, düz bir kayaya doğru gülerek koştuk.", "Yaqin atrofdagi ulkan tekis toshga kulib yugurdik."),
        ("Yedi kişi sardalya gibi tek bir dar çıkıntının altına sıkıştı.", "Yetti kishi bir tor qoyalarga sardinalardek sig'ishdi."),
        ("Çantalarımız ortaya girdi; biz yarı ıslak dışarıda kaldık.", "Chamadonlar o'rtaga kirdi; biz yarim ho'l holda tashqarida qoldik."),
        ("Yağmur bütün vadiyi gümüş rengine ve gürültülü hale getirdi.", "Yomg'ir butun vodini kumushrang va shovqinli qildi."),
        ("Daha önce şelale olmayan uçurumlarda şelaleler belirdi.", "Oldin sharshara bo'lmagan jarliklarda sharsharalar paydo bo'ldi."),
        ("Şimşek, karşı dağın üzerinde sessiz beyaz dallar çizdi.", "Chaqqon oppoq shoxlarni qarama-qarshi tog' bo'ylab jim chizdi."),
        ("Çocuklar gibi şimşek ile gök gürültüsü arasındaki saniyeleri saydık.", "Biz yalt-ylt va g'umburlash orasidagi soniyalarni sanadik."),
        ("Aşağıda bir yerde bir çoban koyunlarını erkenden ıslıkla eve çağırdı.", "Pastlarda cho'pon qo'ylarini erta uyga chalqitdi."),
        ("Tek bir acil durum battaniyesine sarılmış halde çikolata paylaştık.", "Bir favqulodda ko'rpachaga o'ralgan holda shokolad bo'lishdik."),
        ("Dilnoza, durmasını yalvarana kadar hayalet hikayeleri anlattı.", "Dilnoza arvoh hikoyalarini aytdi, biz uni to'xtashiga yalinmaguncha."),
        ("Fırtına, Jasur'un saatine göre tam kırk dakika sürdü.", "Bo'ron Jasurning soatiga aynan qirq daqiqa davom etdi."),
        ("Fırtına geçtiğinde dünya yepyeni doğmuş gibi kokuyordu.", "U ketganda, dunyo butunlay yangi tug'ilgandek hid berdi."),
        ("Her yaprak minik, titreyen bir su elması taşıyordu.", "Har bir yaproqda mayda titrayotgan suv olmosi bor edi."),
        ("Sis, hafif bir duman gibi vadiden yavaşça yükseldi.", "Tuman vodidan yumshoq tutun singari sekin ko'tarildi."),
        ("Sonra gökkuşağı geldi — devasa, çift ve neredeyse kibirli.", "Va kamalak keldi — ulkan, juftlashgan, deyarli mag'rur."),
        ("Kimse konuşmadı; Faris bile şikayetlerini unuttu.", "Hech kim gapirmadi; hatto Faris ham shikoyatlarini unutdi."),
        ("Islak çim ve parlayan taşların arasında tırmanmaya devam ettik.", "Ho'l o'tloq va yalt-yaltiroq toshlar orasida chiqishda davom etdik."),
        ("Zirve aniden, bir bulutu şapka gibi giymiş halde belirdi.", "Cho'qqi birdan namoyon bo'ldi, bulutni shlyapa kabi kiygan holda."),
        ("Sadece yankıların geri gelişini duymak için sisin içine bağırdık.", "Tumanga aks sadoni eshitish uchun baqirdik."),
        ("Öğle yemeği ekmek, peynir, domates ve saf bir zaferdi.", "Nonushta non, pishloq, pomidor va sof g'alaba edi."),
        ("Yağmur ve çaba sonrasında her şey daha lezzetli oluyor.", "Yomg'ir va mehnatdan keyin har narsa mazaliroq tuyuladi."),
        ("İniş daha az zaman aldı ama daha fazla dikkat gerektirdi.", "Pasayish kamroq vaqt oldi, lekin ko'proq e'tibor talab qildi."),
        ("Islak taşların profesyonel düzeyde kaygan olduğunu hızlıca öğrendik.", "Ho'l toshlar professional darajadagi sirg'aluvchan ekanini tez o'rgandik."),
        ("Köyde yaşlı bir kadın bize sıcak çay ve bal sattı.", "Qishloqda keksa ayol bizga issiq choy va asal sotdi."),
        ("Dağ yağmurunun ziyaretçilere her zaman şans getirdiğini söyledi.", "U tog' yomg'iri mehmonlarga doimo omad keltirishini aytdi."),
        ("Eve dönüş otobüsü ıslak yün ve ot kokuyordu.", "Uyga avtobusda ho'l jun va o't hidi bor edi."),
        ("Şoför ve Dilnoza'nın hayalet hikayeleri hariç herkes uyudu.", "Haydovchi va Dilnozaning arvoh hikoyalaridan boshqa hamma uxlab qoldi."),
        ("O geziden beri hava durumu tahminlerine bir daha asla güvenmedik.", "O'sha sayohatdan keyin ob-havo bashoratiga umuman ishonmaymiz."),
    ],
    8: [
        ("Sınav haftası üniversitemize istila eden bir ordu gibi geldi.", "Imtihon haftasi universitetimizga bosqinchilar armiyasiday keldi."),
        ("Kütüphane birden pazardan bile daha kalabalık hale geldi.", "Kutubxona birdan bozordan ham gavjum bo'lib qoldi."),
        ("Öğrenciler masaları bayraklarla işgal etti: defterler, kalemler, enerji içecekleri.", "Talabalar stollarni bayroqlar bilan band qildi: daftarlar, flomasterlar, energiya ichimliklari."),
        ("Oda arkadaşım programı yazdırdı ve duvarımıza yapıştırdı.", "Xonadoshim jadvalni chop etib devoriga yopishtirdi."),
        ("Dört günde üç sınav — matematik, tarih ve İngilizce.", "To'rt kunda uch imtihon — matematika, tarix va ingliz tili."),
        ("Matematik ilk sıraya konmuştu, bu kişisel bir hakaret gibi hissettirdi.", "Matematika birinchi bo'lib belgilandi, bu shaxsan haqoratli tuyuldi."),
        ("Renk kodlu bir plan yaptım ve bir gün boyunca ona uydum.", "Rang kodli reja tuzdim va uni bir kun bajardim."),
        ("Doğrusu, ikinci gün ekran kaydırma ve panikle çöktü.", "Ikkinchi kun rostini aytsam aylansh va vahimaga aylandi."),
        ("Annem her akşam aynı soruyla aradı.", "Onam har kechqurun bir xil savol bilan qo'ng'iroq qildi."),
        ("\"Yemek yedin mi?\" — asla notlar hakkında değil, hep yemek hakkında.", "'Ovqat yedingizmi?' — hech qachon baholar haqida emas, doimo ovqat haqida."),
        ("Matematikten önceki gece grubumuz bir çalışma seansı düzenledi.", "Matematikadan oldingi kechqurun guruhimiz o'quv mashg'uloti uyushtirdi."),
        ("Yurt mutfağında iki su ısıtıcısı arasında buluştuk.", "Ikki choynak orasida yotoqxona oshxonasida uchrashdik."),
        ("Biri türevleri örnek olarak ekmek dilimlerini kullanarak anlattı.", "Kimdir hosilalarni non bo'laklari misolida tushuntirib berdi."),
        ("Bir başkası formülleri doğrudan masaya unla çizdi.", "Yanasi formulalarni to'g'ridan-to'g'ri stolga un bilan chizdi."),
        ("Gece yarısına kadar zayıf konular bile anlam kazanmaya başladı.", "Yarim kechaga kelib hatto zaif mavzular ham ma'noli bo'la boshladi."),
        ("Çok erken kutlama yaptık ve saat ikide yattık.", "Biz juda erta nishonladik va ikkida uxlab qoldik."),
        ("Sabah sınavlarının kendine özgü bir sessizliği vardır.", "Ertalabki imtihonlarda maxsus jimlik bor."),
        ("Aynı anda yazan iki yüz kalem hafif bir yağmur gibi ses çıkarır.", "Ikkita yuz qalam bir vaqtda yozganda yumshoq yomg'irdek tovush chiqaradi."),
        ("Gözetmen yavaşça yürüdü, tam bir tehdit havasında ayakkabılarla.", "Nazoratchi sekin yurdi, sof tahdid poyabzalini kiyyan holda."),
        ("Birinci soru merhametliydi; dördüncü soru ise suç gibiydi.", "Birinchi savol rahmli edi; to'rtinchi esa jinoyat edi."),
        ("Onu sonraya bıraktım ve ilerlemeye devam ettim.", "Uni keyinga qoldirdim va oldinga siljiy berdim."),
        ("Arkamda bir yerde biri, ölmekte olan bir motor gibi iç çekti.", "Ortamda kimdir o'layotgan dvigatelday nafas oldi."),
        ("Son on dakikada geri döndüm ve onu çözdüm.", "Oxirgi o'n daqiqa ichida qaytib keldim va uni yechdim."),
        ("Doğru olup olmadığını ancak gelecek hafta öğrenecektim.", "To'g'ri yoki yo'qligini faqat keyingi haftada bilardim."),
        ("Tarih sınavı, tarihlerle geçen umutsuz bir geceden sonra geldi.", "Tarix imtihoni sanalarning bitta umidsiz kechasidan keyin keldi."),
        ("Beynim kralları rastgele telefon numaraları gibi depoladı.", "Miyam podshohlarni tasodifiy telefon raqamlari kabi saqladi."),
        ("Neyse ki, kompozisyon konusu İpek Yolu'ydu — en sevdiğim konu.", "Omadinga, esse mavzusi Ipak yo'li edi — mening sevimlim."),
        ("Kervanlar, baharatlar, diller ve memleketimin rolü hakkında yazdım.", "Karvonlar, ziravorlar, tillar va tug'ilgan shahrim roli haqida yozdim."),
        ("Sevilen bir şey hakkında yazmak, sınav değil sohbet gibi hissettiriyor.", "Sevgan narsa haqida yozish suhbatlashgandek, sinovdan o'tmagandek tuyuladi."),
        ("İngilizce en sona kaldı ve oda belirgin şekilde rahatladı.", "Ingliz tili oxiri keldi va xona ko'rinib tinchlantirdi."),
        ("Okuduğunu anlama bölümü bir deniz feneri bekçisinin hikayesini anlatıyordu.", "O'qish tushunishi mayoqchining hikoyasini aytib berdi."),
        ("Neredeyse keyif aldım, ki bu sınav sırasında yasak gibi hissettirdi.", "Deyarli zavqlandim, bu imtihon paytida noqonuniy tuyuldi."),
        ("Son zilden sonra koridor özgürlükle patladı.", "Oxirgi jiringlashdan keyin koridor ozodlikka portladi."),
        ("Yabancılar yabancılara sarıldı; kitaplar tören havasında çöp kutularına uçtu.", "Tanish emaslar tanish emaslarni quchoqladi; kitoblar marosim ravishda axlat idishiga uchdi."),
        ("Bazı öğrenciler her şeyi hemen unuttu, boş boş gülümseyerek.", "Ba'zi talabalar hamma narsani darhol unutdilar, bo'sh tabassum bilan."),
        ("Grubumuz doğruca nehrin yanındaki parka gitti.", "Guruhimiz to'g'ridan-to'g'ri daryo yaqinidagi bog'ga bordi."),
        ("Soğuk rüzgara rağmen dondurma aldık.", "Sovuq shamolga qaramay muzqaymoq sotib oldik."),
        ("Sonuçlar sonsuz gibi gelen üç günün ardından e-postayla geldi.", "Natijalar cheksiz uch kundan keyin elektron pochta orqali keldi."),
        ("Kendi sonucumu koridorun ortasında ayakta açtım.", "O'zinikini koridorning o'rtasida turub ochdim."),
        ("Matematik: geçtim. Tarih: geçtim. İngilizce: doksan bir puan.", "Matematika: o'tdim. Tarix: o'tdim. Ingliz tili: to'qson bir ball."),
        ("Eve girmeden önce ilk olarak annemi aradım.", "Uy eshigini ochishdan avval birinchi navbatda onamga qo'ng'iroq qildim."),
        ("Biraz ağladı ve yine yemek yiyip yemediğimi sordu.", "U biroz yig'ladi va yana ovqat yeganimni so'radi."),
        ("O hafta bana panik duygusunun kitaplardan daha ağır olduğunu öğretti.", "O'sha hafta vahim kitoblardan og'iroq ekanini o'rgatdi."),
        ("Gelecek dönem, ilk günden itibaren sakince çalışmayı planlıyorum.", "Keyingi semestrda birinchi kundan sokin o'qishni rejalashtiryapman."),
    ],
    9: [
        ("Akşam vardiyamdan sonra eve son gece otobüsüyle giderim.", "Kechki smenadan keyin oxirgi tungi avtobusda uyga qaytaman."),
        ("Meydandan tam yirmi üç kırkta kalkar.", "U maydondan aynan yigirma uch qirq daqiqada jo'naydi."),
        ("Bu saatte benimle sadece üç dört yolcu olur.", "Bu soatda menga faqat uch-to'rt yo'lovchi hamroh bo'ladi."),
        ("Şoför artık her düzenli yolcuyu yüzünden tanır.", "Haydovchi endi har bir doimiy yo'lovchini yuzidan tanib oladi."),
        ("Bana sessizce başını sallar, bu bir dostluk gibi hissettiriyor.", "U menga jim bosh irg'adi, bu esa do'stlikdek tuyuladi."),
        ("Otobüs hafifçe mazot, yağmur ve birinin akşam yemeği kokar.", "Avtobusda dizel, yomg'ir va kimningdir kechki ovqati hidi seziladi."),
        ("Bu gece arkamda büyük bir çanta tutan yaşlı bir kadın oturuyor.", "Bugun kechqurun orqamda katta sumka tutgan keksa ayol o'tiradi."),
        ("Çantasından boş kavanozların sessiz şıngırtısı geliyor.", "Sumkasidan bo'sh idishlarning sokin jiringlashi keladi."),
        ("Her akşam şişeleri markete geri götürüyor.", "U har shom bozorga idishlarni qaytarib beradi."),
        ("Koridorun karşısında bir öğrenci sırt çantasına yaslanmış uyuyor.", "Yo'lak narida talaba chamadoniga suyanib uxlab yotadi."),
        ("Ders kitabı yavaşça dizlerinin kenarına doğru kayıyor.", "Uning darsligi tizzalari chetiga sekin sirg'aladi."),
        ("Dışarıdaki şehir yavaş bir televizyon gibi kayıp geçiyor.", "Tashqaridagi shahar sekin televideniedek o'tib ketadi."),
        ("Kapalı dükkanlar metal göz kapakları takıyor; sokak köpekleri kavşaklara hükmediyor.", "Yopiq do'konlar metall ko'z qovoqlari kiyadi; adashgan itlar chorrahani egallaydi."),
        ("Trafik ışıklarında bütün sokakta tek başımıza bekliyoruz.", "Svetoforlarda butun ko'chada yolg'iz kutamiz."),
        ("Şoförün radyosundan eski bir şarkı sessizce çalıyor.", "Haydovchining radio eshitish qurilmasidan eski qo'shiq jim chalinadi."),
        ("Birinin duyabileceğini fark etmeden mırıldanıyor.", "U kimdir eshitishini sezmasdan kuylaydi."),
        ("Köprünün yakınında bir yerde daha fazla yolcu biniyor.", "Ko'prik yaqinidagi bir joyda boshqa yo'lovchilar ham chiqishadi."),
        ("Beyaz ayakkabılı iki hemşire, vardiyalarından sonra bitkin bir halde oturuyor.", "Oq poyabzallik ikki hamshira smenadan keyin charchagan holda o'tirishadi."),
        ("Hastalar hakkında kısa, yorgun cümlelerle konuşuyorlar.", "Ular bemorlar haqida qisqa charchagan gaplarda gapirishadi."),
        ("Genç bir işçi güçlü bir koku yayan boya kovaları taşıyor.", "Yosh ishchi kuchli hid beradigan bo'yoq idishlarini olib chiqyapti."),
        ("Kimse şikayet etmiyor; gece otobüslerinin yazılmamış sabır kuralları vardır.", "Hech kim shikoyat qilmaydi; tungi avtobuslarda sabrning yozilmagan qoidalari bor."),
        ("Durağım yaklaşık on beş dakika içinde yaklaşıyor.", "Beketim taxminan o'n beshta daqiqa ichida yaqinlashadi."),
        ("Alışkanlıktan her zaman düğmeye çok erken basarım.", "Men doim odatdan erta tugmani bosaman."),
        ("Yaşlı kadın birden şoföre yarınki programı soruyor.", "Keksa ayol birdan haydovchidan ertangi jadval haqida so'raydi."),
        ("Sesi yumuşak, sanki geceyi rahatsız etmekten korkuyormuş gibi.", "Ovozi yumshoq, xuddi kechani bezovta qilishdan qo'rqqanday."),
        ("Şoför sabırla cevap veriyor ve hatta aynaya gülümsüyor.", "Haydovchi sabrli javob beradi va hatto oynaga tabassum ham qiladi."),
        ("Dışarıda yağmur yeniden başlıyor, her camda çizgiler çiziyor.", "Tashqarida yomg'ir yana boshlanadi, har bir oynada chiziqlar chizadi."),
        ("Öğrenci kendi durağından bir önceki durakta panik içinde uyanıyor.", "Talaba o'z beketidan bir oldingi bekatda vahima bilan uyg'onadi."),
        ("Hepimiz onun karanlığa doğru koşmasını izliyor, sessizce gülüyoruz.", "Hammamiz uni zulmatga yugurganini kuzatib jim kulamiz."),
        ("Hemşireler küçük bir şemsiyeyi paylaşarak birlikte iniyorlar.", "Hamshiralar birga ketishadi, bitta kichik soyabonni bo'lishib."),
        ("Şimdi otobüste sadece kavanozlu kadın ve ben kaldık.", "Endi faqat idishli ayol bilan men avtobusda qoldik."),
        ("Otobüs şimdi özel hissettiriyor, gecenin geç saatinde hatıraların taksisi gibi.", "Avtobus endi xususiy tuyuladi, xotiralarning kechgi taksidek."),
        ("Kadına torunlarının kavanozları taşımasına yardım edip etmediğini soruyorum.", "Ayoldan nabiralari idish ko'tarishga yordam berishini so'rayman."),
        ("Gülüyor ve onların önemli insanlar olma yolunda meşgul olduklarını söylüyor.", "U kulib, ular muhim odamlar bo'lish bilan band deb javob beradi."),
        ("Sesinde hüzün yok, sadece hafif bir alay var.", "Ovozida hafsala yo'q, faqat muloyim hazil bor."),
        ("Kavanozların torununun kalemlerine para kazandırdığını söylüyor.", "U idishlar nabirasining qalam pullarini to'lashini aytadi."),
        ("Durağım sonunda geldiğinde çantasını indirmesine yardım ediyorum.", "Beketim nihoyat kelganda, sumkasini tushirishga yordam beraman."),
        ("Bir kavanozdan bana küçük bir kayısı vermekte ısrar ediyor.", "U menga idishdan bitta mayda o'rik berishga qat'iy qaror qiladi."),
        ("Şemsiyemin altında eve yürürken kayısıyı yavaşça yiyorum.", "Soyabon ostida uyga piyoda qaytayotib, o'rikni sekin yeyman."),
        ("Tadı ekşi tatlı, çoğu samimi sohbet gibi.", "U achchiq-shirin ta'mga ega, eng samimiy suhbatlar kabi."),
        ("Şehir etrafımda yarı uykulu bir şekilde sessizce mırıldanıyor.", "Shahar atrofimdagi jim g'urraydi, yarim uxlagan holda."),
        ("Yarın bu otobüs yine aynı sokaklardan geçecek.", "Ertaga bu avtobus xuddi shu ko'chalar orqali yana yuradi."),
        ("Aynı şoför, aynı sessizlik, her gece farklı küçük hikayeler.", "Xuddi shu haydovchi, xuddi shu jimlik, har kecha boshqa kichik hikoyalar."),
        ("Bu yüzden gece otobüsünde asla gerçekten yalnız hissetmiyorum.", "Shuning uchun tungi avtobusda hech qachon chin ma'noda yolg'iz his qilmayman."),
    ],
}
