LONG_STORIES_A = {
    0: [
        ("Last Saturday morning, I woke up earlier than usual.", "Shanba kuni ertalab odatdagidan erta turdim."),
        ("The sun was shining through my window, and the sky was perfectly clear.", "Quyosh derazamdan porlab kirayotgan edi, osmon esa butunlay ochiq."),
        ("My phone rang, and it was my best friend Aziz.", "Telefonim jiringladi — bu eng yaxshi do'stim Aziz edi."),
        ("He said, 'Get ready, we are going to spend the whole day together!'", "U dediki: 'Tayyorlan, biz butun kunni birga o'tkazamiz!'"),
        ("I laughed because he always plans something unexpected.", "Men kulib qo'ydim, chunki u doim kutilmagan narsa rejalashtiradi."),
        ("We met at the bus stop near my house at nine o'clock.", "Biz soat to'qqizda uyim yaqinidagi avtobus bekatida uchrashdik."),
        ("The city was quiet, and the streets were almost empty.", "Shahar tinch edi, ko'chalar deyarli bo'sh."),
        ("First, we walked to a small bakery on the corner.", "Avval burchakdagi kichik nonvoyxonaga piyoda bordik."),
        ("The smell of fresh bread made us both smile immediately.", "Yangi non hidi ikkovimizni darhol tabassumga keltirdi."),
        ("Aziz bought two warm rolls and gave me one without asking.", "Aziz ikkita issiq bulochka oldi va so'ramasdan bittasini menga berdi."),
        ("That is the kind of friend he has always been.", "U har doim shunday do'st bo'lgan."),
        ("After breakfast, we decided to walk through the central park.", "Nonushtadan keyin markaziy bog' bo'ylab yurishga qaror qildik."),
        ("Old men were playing chess under the tall green trees.", "Qariyalar baland yashil daraxtlar ostida shaxmat o'ynayotgan edi."),
        ("Children were riding their bicycles and laughing loudly.", "Bolalar velosiped haydab, baland ovozda kulayotgan edilar."),
        ("We sat on a bench and talked about our plans for the future.", "Biz skameykada o'tirdik va kelajak rejalarimiz haqida gaplashdik."),
        ("Aziz wants to open his own small business next year.", "Aziz kelasi yili o'zining kichik biznesini ochmoqchi."),
        ("I told him about my dream to travel and learn new languages.", "Men unga sayohat qilish va yangi tillar o'rganish orzim haqida gapirdim."),
        ("We promised each other to work hard and never give up.", "Bir-birimizga qattiq ishlash va hech qachon taslim bo'lmaslikka va'da berdik."),
        ("Around noon, our stomachs started to growl loudly.", "Taxminan peshin vaqtida qorinlarimiz baland ovozda g'urillay boshladi."),
        ("So we went to my favourite place in the whole city.", "Shuning uchun shahardagi sevimli joyimga bordik."),
        ("It is a tiny café where they make the best soup in town.", "Bu shaharda eng mazali sho'rva tayyorlaydigan juda kichik kafe."),
        ("The owner knows us well and always adds extra bread.", "Egasi bizni yaxshi biladi va doim qo'shimcha non qo'shib beradi."),
        ("We ate slowly and watched people passing by the window.", "Biz sekin-asta yedik va derazadan o'tayotgan odamlarni kuzatdik."),
        ("Suddenly, we saw our old school teacher crossing the street.", "Birdan ko'chani kesib o'tayotgan eski maktab o'qituvchimizni ko'rdik."),
        ("She looked happy, so we ran outside to greet her.", "U baxtli ko'rindi, shuning uchun uni kutib olish uchun tashqariga yugurdik."),
        ("She remembered both of us after all these years.", "U shu yillar davomida ikkovimizni ham esladi."),
        ("We talked for ten minutes about school memories.", "Biz maktab xotiralari haqida o'n daqiqa suhbatlashdik."),
        ("She said she was proud of the people we were becoming.", "U biz aylanayotgan odamlar bilan faxrlanishini aytdi."),
        ("Her words stayed in my heart for the rest of the day.", "Uning so'zlari kun davomida yuragimda qoldi."),
        ("In the afternoon, we visited the big bookshop downtown.", "Tushdan keyin shahar markazidagi katta kitob do'koniga bordik."),
        ("Aziz looked at books about business and money.", "Aziz biznes va pul haqidagi kitoblarga qaradi."),
        ("I found a beautiful illustrated dictionary of English idioms.", "Men inglizcha iboralarning chiroyli rasmli lug'atini topdim."),
        ("We bought our books and shared a chocolate bar outside.", "Kitoblarimizni oldik va tashqarida bir shokoladni bo'lishdik."),
        ("On the way home, dark clouds covered the sky.", "Uyga qaytayotganda qora bulutlar osmonni qopladi."),
        ("Heavy rain started just as we reached the bus stop.", "Avtobus bekatiga yetib kelganimizda kuchli yomg'ir boshlandi."),
        ("We stood close together, protecting our new books.", "Yangi kitoblarimizni himoya qilib, yonma-yon turdik."),
        ("The rain smelled clean, and the air became cool and fresh.", "Yomg'ir toza hid berdi va havo salqin, yangi bo'lib qoldi."),
        ("When we finally got home, we were completely wet.", "Nihoyat uyga yetganimizda butunlay ho'l bo'lgan edik."),
        ("My mother laughed when she saw us dripping at the door.", "Onam eshik oldida tomchiqayotganimizni ko'rib kuldi."),
        ("She gave us hot tea with lemon and dry clothes.", "U bizga limon issiq choy va quruq kiyim berdi."),
        ("We drank tea and told her about our whole day.", "Choyni ichdik va unga butun kunimiz haqida gapirdik."),
        ("In the evening, Aziz sent me a photo of us in the rain.", "Kechqurun Aziz menga yomg'irdagi suratimizni yubordi."),
        ("Under the photo he wrote: 'Best Saturday ever.'", "Surat ostiga esa shunday yozdi: 'Eng zo'r shanba.'"),
        ("I smiled and wrote back that we must repeat it soon.", "Men tabassum bilan tez orada takrorlashimiz kerak deb yozdim."),
        ("Good friends make ordinary days feel special.", "Yaxshi do'stlar oddiy kunlarni maxsus qilib ko'rsatadi."),
    ],
    1: [
        ("Two years ago, I took my first flight alone.", "Ikki yil oldin birinchi parvozimni yolg'iz amalga oshirdim."),
        ("I was flying from Tashkent to Istanbul to visit my uncle.", "Toshkentdan amakisini ko'rgani Istanbulga uchyotgan edim."),
        ("The night before, I could not sleep at all.", "Oldingi kechqurun umuman uxlolmadim."),
        ("I checked my passport and ticket maybe twenty times.", "Pasportim va biletimni ehtimol yigirma marta tekshirdim."),
        ("My mother packed sandwiches, sweets, and warm socks for me.", "Onam menga tovoq-tort, shirinlik va iliq paypoq solib berdi."),
        ("At the airport, everything seemed enormous and confusing.", "Aeroportda hamma narsa ulkan va chalkash tuyuldi."),
        ("Long lines of travellers curled around every corner.", "Sayohatchilarning uzun navatlari har bir burchakda egri-bugri edi."),
        ("I showed my passport and the officer smiled kindly.", "Pasportimi ko'rsatdim va xodim mehribon tabassum qildi."),
        ("Security asked me to remove my belt and empty my pockets.", "Xavfsizlik xodimlari kamarimni yechish va cho'ntaklarimni bo'shatishni so'radi."),
        ("My heart was beating fast, but everything went smoothly.", "Yuragim tez urayotgan edi, lekin hammasi silliq o'tdi."),
        ("At the gate, I watched huge planes taking off one by one.", "Reja oldida ulkan samolyotlarning birma-bir ko'tarilishini kuzatdim."),
        ("Their engines roared like giant sleepy animals.", "Ularning dvigatellari ulkan uxlagan hayvonlar kabi g'irladi."),
        ("Boarding started thirty minutes before departure.", "Yo'lovchilarni o'tkazish jo'nashdan o'ttiz daqiqa oldin boshlandi."),
        ("I handed over my ticket with slightly shaking hands.", "Biletimni biroz titrayotgan qo'llarim bilan topshirdim."),
        ("A friendly flight attendant welcomed me aboard.", "Samimiy stuardessa menga bortda xush kelibsiz dedi."),
        ("My seat was next to the window, exactly as I hoped.", "O'rinishim oynaga yondosh edi, aynan umid qilganimdek."),
        ("An elderly woman sat beside me and greeted me warmly.", "Yonimga keksa ayol o'tirdi va meni iliqlik bilan kutib oldi."),
        ("She noticed my nervous face and started a conversation.", "U bezovta yuzimni sezib, suhbatni boshladi."),
        ("She told me she had flown more than fifty times.", "U ellik martadan ortiq parvoz qilganini aytdi."),
        ("Her calm voice slowly relaxed me.", "Uning osoyishta ovozi meni asta-sekin tinchlantirdi."),
        ("The plane moved onto the runway and stopped for a moment.", "Samolyot uchish yo'lagiga chiqib bir lahza to'xtadi."),
        ("Then the engines pushed us forward faster and faster.", "Keyin dvigatellar bizni tobora tezroq oldinga surdi."),
        ("The wheels left the ground, and my stomach dropped.", "G'ildiraklar yerdan uzildi va qornim tushib ketdi."),
        ("Houses became small, and roads turned into thin lines.", "Uylar kichiklashdi, yo'llar ingichka chiziqlarga aylandi."),
        ("Above the clouds, the world was bright and silent.", "Bulutlar ustida dunyo ravon va jim edi."),
        ("The clouds below us looked like soft white mountains.", "Ostimizdagi bulutlar yumshoq oq tog'largagina o'xshardi."),
        ("The woman pointed out the sea far away on the horizon.", "Ayol ufqdagi uzoq dengizni ko'rsatdi."),
        ("A meal came shortly after takeoff, chicken with rice.", "Ko'tarilishdan ko'p o'tmay ovqat keldi — tovuq guruch bilan."),
        ("I ate everything because excitement makes me hungry.", "Hammasini yedim, chunki hayajon meni och qiladi."),
        ("Later, I tried to watch a film but kept looking out the window.", "Keyinchalik film ko'rishga harakat qildim, lekin doimo oyna tomonga qaradim."),
        ("Somewhere over the Black Sea, we flew into gentle turbulence.", "Qora dengiz ustidagi bir joyda yengil silkinishga kirishdik."),
        ("The plane shook a little, and my hands froze.", "Samolyot biroz larzaga keldi va qo'llarim qotib qoldi."),
        ("The woman simply said, 'Just bumps on a road.'", "Ayol shunchaki dediki: 'Faqat yo'ldagi to'siqlar'."),
        ("Soon the sky calmed down again completely.", "Tez orada osmon yana butunlay tinchlandi."),
        ("The captain announced that we would land in fifteen minutes.", "Kapitan o'n beshta daqiqada qo'nishimizni e'lon qildi."),
        ("From above, Istanbul glittered with thousands of lights.", "Yuqoridan Istanbul minglab chiroqlar bilan yaltiradi."),
        ("The Bosphorus appeared like a silver ribbon between two continents.", "Bosfor ikki qit'a orasida kumir lenta kabi namoyon bo'ldi."),
        ("Landing felt smoother than driving over a speed bump.", "Qo'nish tezlik to'sig'idan o'tishdan ham silliqroq tuyuldi."),
        ("Everyone clapped softly when the plane stopped.", "Samolyot to'xtaganda hammam yengil qarsak chaldi."),
        ("I thanked the kind woman and wished her good health.", "Mehmondo'st ayolga rahmat aytdi va sog'liq tiladim."),
        ("At baggage claim, my suitcase arrived first, surprisingly.", "Bagaj olish joyida chamadonim kutilmaganda birinchi bo'lib keldi."),
        ("My uncle was waiting behind the glass with a big sign.", "Amakim katta yozuv bilan shisha ortida kutib turgan edi."),
        ("His hug made all my fear disappear instantly.", "Uning quchoqlashi barcha qo'rquvni darhol yo'q qildi."),
        ("Driving into the city, I kept repeating: 'I really flew!'", "Shahar tomon ketayotib, doim takrorladim: 'Men rostan uchdim!'"),
        ("Since that day, I have loved every single flight.", "O'sha kundan buyon har bir parvozni yaxshi ko'raman."),
    ],
    2: [
        ("On a rainy Tuesday, I discovered a little café near the library.", "Yomg'irli seshanba kuni kutubxona yaqinida kichik kafeni kashf etdim."),
        ("Its wooden door had a small brass handle shaped like a coffee bean.", "Uning yog'och eshigida qahva donasiga o'xshash kichik guruch dastasi bor edi."),
        ("Inside, the air smelled of cinnamon and roasted beans.", "Ichkarida havoda doljin va qovurilgan don hidi bor edi."),
        ("Soft jazz music played quietly from an old speaker.", "Eski karnaydan nozik jaz musiqasi jim chalinayotgan edi."),
        ("Only three tables were occupied by students with laptops.", "Faqat uch stul noutbukli talabalar bilan band edi."),
        ("A young woman behind the counter greeted me with a warm nod.", "Dollar ortidagi yosh ayol meni iliqlik bilan bosh irg'ab kutib oldi."),
        ("I ordered a cappuccino and a slice of apple pie.", "Men kapuchino va olcha pie bo'lagini buyurtma qildim."),
        ("While waiting, I read the handwritten menu on the blackboard.", "Kutayotib, doskadagi qo'lyozma menyuni o'qidim."),
        ("They offered drinks with funny names like 'Cloud Latte'.", "Ularda 'Bulut latte' kabi kulgili nomlar bilan ichimliklar bor edi."),
        ("My coffee arrived with a tiny leaf drawn in milk foam.", "Mening kahvam sut ko'pigi ichiga chizilgan mayda yaproq bilan keldi."),
        ("The apple pie was still warm from the oven.", "Olcha pie hali ham tandirdan chiqqancha iliq edi."),
        ("Each bite tasted like autumn in a small town.", "Har bir luqma kichik shaharchadagi kuzni eslatardi."),
        ("I opened my notebook and started writing a letter to myself.", "Daftarchamni ochdim va o'zimga xat yozishni boshladim."),
        ("Rain tapped gently against the large window beside me.", "Yomg'ir yonimdagi katta oynaga yumshoq urildi."),
        ("An old man entered, shaking water from his grey umbrella.", "Keksaygan erkak kirdi, kulrang soyabonidan suv silkitib."),
        ("He greeted everyone by name, including the cook in the kitchen.", "U hammaga, hatto oshxona oshpazi ham, ismi bilan salom berdi."),
        ("Clearly, he was a regular guest here for many years.", "Aniqki, u bu yerda ko'p yillardan beri doimiy mehmon edi."),
        ("The waitress brought his usual order without asking.", "Ofitsiant uning odatbuy buyurtmasini so'ramasdin keltirdi."),
        ("Strong tea, one sugar on the side, and a butter cookie.", "Kuchli choy, bir qoshiq shakar alohida va saryog'li pechene."),
        ("Watching him, I understood why people love small cafés.", "Uni kuzatib, odamlarning kichik kaflarni nega sevishi tushundim."),
        ("Big places serve you, but small places remember you.", "Katta joylar sizga xizmat qiladi, kichik joylar esa eslab qoladi."),
        ("Half an hour later, two friends sat down near me.", "Yarim soatdan keyin yonimga ikki dugona o'tirdi."),
        ("They argued playfully about which dessert to share.", "Ular qaysi desertni bo'lishish masalasida o'yinkam bahslashdi."),
        ("Finally, they chose the cheesecake with strawberry sauce.", "Nihoyat, ular maydalangan pishiriqni tanlashdi."),
        ("Their laughter mixed beautifully with the rain sounds.", "Ularning kulishi yomg'ir tovushlari bilan chiroyli qorishdi."),
        ("I finished my coffee and ordered a second cup without guilt.", "Kahvamni tugatib, ikkinchi finjanni vijdontsiz buyurtma qildim."),
        ("The waitress smiled as if she fully approved.", "Ofitsiant xuddi to'liq ma'qullayotgandek tabassum qildi."),
        ("Between sips, I watched the barista pour latte art.", "Luqmalar orasida barista latte san'atini quyayotganini tomosha qildim."),
        ("Her hands moved confidently, like an artist painting.", "Uning qo'llari rassom chizayotgandek ishonch bilan harakatlanardi."),
        ("A little girl at the next table received hot chocolate.", "Qo'shni stoladagi kichkina qiz issiq shokolad oldi."),
        ("Her eyes grew wide when she saw marshmallows floating inside.", "Ichida suzayotgan zefirni ko'rib, ko'zlari kengaydi."),
        ("She whispered, 'This is the best day of my life.'", "U shivirladi: 'Bu mening hayotimdagi eng yaxshi kun.'"),
        ("Her mother laughed and stole one marshmallow secretly.", "Onasi kuldi va bir zefirni maxfiy o'g'irladi."),
        ("Moments like this cannot be planned or bought.", "Bunday lahzalarni rejalashtirib yoki sotib olb bo'lmaydi."),
        ("Outside, the rain finally softened into light drops.", "Tashqarida yomg'ir nihoyat yengil tomchilarga aylandi."),
        ("Golden streetlights reflected in the wet pavement.", "Oltin ko'cha chiroqlari ho'l troyni aks ettirdi."),
        ("I paid my bill and left a generous tip.", "Hisobni to'lab, saxiy chaqa qoldirdim."),
        ("The waitress thanked me and waved goodbye warmly.", "Ofitsiant menga rahmat aytdi va iliq xayrli yol dedi."),
        ("At the door, I turned around for one last look.", "Eshik oldida oxirgi marta orqaga burilib qaradim."),
        ("The café glowed like a lantern in the grey evening.", "Kafe kulrang kechda fonar kabi yonib turardi."),
        ("Now I visit that café every single Tuesday.", "Endi har seshanba kuni o'sha kafega boraman."),
        ("Same table, same cappuccino, same warm feeling.", "Xuddi shu stol, xuddi shu kapuchino, xuddi shu iliq tuygu."),
        ("Sometimes the waitress saves me the last piece of pie.", "Ba'zan ofitsiant menga oxirgi pie bo'lagini saqlab qo'yadi."),
        ("Small rituals like this make life sweet and steady.", "Bunday kichik an'anelar hayotni shirin va muqim qiladi."),
    ],
    3: [
        ("My first week at the new office felt like a dream.", "Yangi ofisdagi ilk haftam tushga o'xshab tuyuldi."),
        ("I prepared my clothes the night before my first day.", "Birinchi kundan oldingi kechqurun kiyimlarimni tayyorladim."),
        ("I arrived forty minutes early because of my nerves.", "Asabiyligidan qirq daqiqa erta yetib keldim."),
        ("The security guard was the first person who spoke to me.", "Qo'riqchi menga gapirgan birinchi odam bo'ldi."),
        ("He said, 'Relax, everyone survives their first Monday.'", "U dediki: 'Bo'shasangiz, hamma birinchi dushanbasidan o'tadi.'"),
        ("My manager met me at reception with a bright smile.", "Mening menejerim meni qabulxonda yorqin tabassum bilan kutib oldi."),
        ("She gave me a quick tour of the whole floor.", "U menga butun qavatni tezkor sayohat qilib ko'rsatdi."),
        ("Everything smelled new, from carpets to computer screens.", "Hamma narsa yangi hid berdi — gilamlardan kompyuter ekranlarigacha."),
        ("My desk was small but right beside a wide window.", "Stolim kichik edi, lekin katta oynaning yonida joylashgan."),
        ("Ten strangers introduced themselves before lunchtime.", "Tushlikkacha o'n noma'lum odam o'zini tanishtirdi."),
        ("I forgot half of their names immediately, honestly.", "Halos, ularning ismlarining yarmisini darhol unutdim."),
        ("My teammate Doston saved me with a printed list later.", "Jamoadoshim Doston keyinroq chop etilgan ro'yxat bilan menga yordam berdi."),
        ("He explained the office rules with gentle humour.", "U ofis qoidalarini muloyim hazil bilan tushuntirib berdi."),
        ("For example, meetings always start five minutes late.", "Masalan, uchrashuvlar doim besh daqiqa kech boshlanadi."),
        ("And the coffee machine breaks every Friday afternoon.", "Va qahva mashinasi har juma kuni tushdan keyin buziladi."),
        ("On Tuesday, I attended my first real team meeting.", "Seshanba kuni ilk haqiqiy jamoa uchrashuvimda qatnashdim."),
        ("Everyone spoke fast and used mysterious abbreviations.", "Hamma tez gapirdi va sirli qisqartmalardan foydalandi."),
        ("I nodded seriously although I understood only sixty percent.", "Faqt faqat oltmish foizini tushungan bo'lsamda, jiddiy bosh irg'adim."),
        ("Afterwards, I wrote down every unfamiliar word.", "Keyin har bir tanish emas so'zni yozib oldim."),
        ("That evening, I studied them like school vocabulary.", "O'sha kechqurun ularni maktab lug'ati kabi o'rgandim."),
        ("By Wednesday, I fixed my first small bug in the system.", "Chorshanba kunga kelib, tizimdagi ilk kichik xatoni tuzatdim."),
        ("My supervisor praised my work in front of everyone.", "Rahbarim ishimni hamma oldida maqtadi."),
        ("My ears turned red, but I felt ten centimetres taller.", "Quloqlarim qizaridi, lekin o'zimni o'n santimetr balandroq his qildim."),
        ("Thursday brought the office lunch tradition.", "Payshanba kuni ofis tushlik an'anasini olib keldi."),
        ("Everyone cooks or brings one dish from home.", "Har kim uyida bir taom tayyorlaydi yoki olib keladi."),
        ("I brought my mother's rice pilaf, and it disappeared fast.", "Onamning guruch palovini olib keldim, u tez tugadi."),
        ("People from other departments came to ask the recipe.", "Boshqa bo'limlardagi odamlar retseptni so'rab kelishdi."),
        ("Friday ended with cake because someone had a birthday.", "Juma kuni tort bilan tugadi, chunki kimningdir tug'ilgan kuni edi."),
        ("We sang quietly, as offices do, half-singing half-whispering.", "Biz jim qo'shiq aytdik, ofislarda odat bo'lganidek, yarim kuylanib yarim shivirlab."),
        ("During that week, I learned three important lessons.", "O'sha hafta davomida uch muhim darsni o'rgandim."),
        ("First, asking questions is strength, not weakness.", "Birinchisi, savol berish kuchsizlik emas, kuch."),
        ("Second, a short walk fixes a tired brain.", "Ikkinchisi, qisqa sayr charchagan miygacha yordam beradi."),
        ("Third, colleagues become friends faster than you expect.", "Uchinchisi, hamkasblar kutgandan ham tezroq do'stga aylanadi."),
        ("On Friday evening, my inbox was finally empty.", "Juma kechqurun pochtam nihoyat bo'sh edi."),
        ("I looked at my desk and felt quiet pride.", "Stolimga qarab sokin iftixor his qildim."),
        ("One week ago, this place was unknown and scary.", "Bir hafta oldin bu joy noma'lum va qo'rqinchli edi."),
        ("Now it already feels like a second home.", "Endi u allaqachon ikkinchi uyday tuyuladi."),
        ("The security guard waved at me as I left.", "Chiqib ketayotib, qo'riqchi menga qo'l silkitdi."),
        ("'See you Monday,' he said like an old friend.", "'Dushanba ko'rishamiz', deb aytdi u eski do'stday."),
        ("On the bus home, I smiled at nothing particular.", "Uyga qaytayotgan avtobusda hech kimga bog'liq bo'lmagan sababsiz tabassum qildim."),
        ("My feet hurt, but my heart was light.", "Oyoqlarim og'ridi, lekin yuragim yengil edi."),
        ("I texted my parents that the job feels right.", "Ota-onamga bu ish to'g'ri kelayotganini yozdim."),
        ("My father replied with one word: 'Finally.'", "Otam bitta so'z bilan javob berdi: 'Nihoyat.'"),
        ("I fell asleep that night still wearing my work badge.", "O'sha kechqurun ish belgisimni yechmasdan uxlab qoldim."),
    ],
    4: [
        ("Every second Sunday, our family gathers at Grandma's house.", "Har juftshanba kuni oilamiz bobomizning uyida yig'iladi."),
        ("Her house sits at the end of a quiet street full of poplars.", "Uning uyi teraklar bilan to'lgan sokin ko'chaning oxirida joylashgan."),
        ("You can hear birds before you even knock on the gate.", "Darvoza urishdan avval qushlar ovozini eshitishingiz mumkin."),
        ("Grandma starts cooking at dawn, wearing her purple apron.", "Bobomiz tong otishidan boshlab oshxona boshlaydi, binafsha fartugi kiyingan holda."),
        ("The smell of fresh samsa greets us at the door.", "Yangi somsa hidi bizni eshik oldida kutib oladi."),
        ("Uncles argue cheerfully about whose car parked better.", "Amakilar kimning mashinasi yaxshi to'xtaganligi haqida quvonch bilan bahslashadi."),
        ("Cousins run through the garden chasing an old football.", "Amakivachchalar bog'da eskicha futbol ortidan yugurishadi."),
        ("Someone always trips over the garden hose, every time.", "Har safar kimdir bog'dagi shlangaga tiqilib yiqiladi."),
        ("Aunts sit on the veranda comparing photos on their phones.", "Xolalar verandada telefonlaridagi suratlarni solishtirib o'tirishadi."),
        ("Grandpa guards his chess board like a small king.", "Bobomiz shaxmat taxtasini kichik qirol kabi qo'riqlaydi."),
        ("He challenges every grandson and defeats most of us.", "U har bir nabirasini o'yin chorlaydi va ko'pchiligimizni mag'lub etadi."),
        ("I lost twice today and demanded a rematch after lunch.", "Bugun ikki marta yutqazdim va tushlikdan keyin revansh talab qildim."),
        ("In the kitchen, Grandma never measures anything.", "Oshxonada Bobomiz hech narsani o'lchamaydi."),
        ("She adds salt 'by listening to the food', she says.", "U tuzni 'ovqat tinglab' qo'shishini aytadi."),
        ("Her dough stretches thin like golden paper.", "Uning xamiri oltin qog'oz kabi ingichka cho'ziladi."),
        ("All the secrets live in her wrists, not in recipes.", "Barcha sirlar retseptlarda emas, bilaklarida yashirilgan."),
        ("I help by washing dishes and stealing warm bread.", "Men idish yuvgani va iliq non o'g'irlashga yordam beraman."),
        ("She pretends not to see me every single time.", "U har safar meni ko'rmagan bo'lib qiyofa beradi."),
        ("At two o'clock, the long table groans under dishes.", "Soat ikkida uzun stol taomlar ostida ingichka ovoz chiqaradi."),
        ("Pilaf, salads, samsa, fruits, and three kinds of tea.", "Palov, salatlar, somsa, mevalar va uch xil choy."),
        ("Before eating, Grandpa says a few quiet words of thanks.", "Yeyishdan oldin Bobomiz bir nechta sokin minnatdorchilik so'zi aytadi."),
        ("Then the room explodes with talking and laughing.", "Keyin xona gapirish va kulish bilan portlaydi."),
        ("Everyone speaks at once, and somehow it works.", "Hamma bir vaqtda gapiradi va bir yo'l bilan hammasi mos keladi."),
        ("Little Zuhra recites a poem standing on a chair.", "Kichkina Zuhra kursida turub she'r aytyapti."),
        ("We applaud too loudly, and she bows like an actress.", "Biz juda baland qarsak chaldik va u aktrisa kabi egildi."),
        ("After the meal, the elders tell stories from their youth.", "Ovqatdan keyin kattalar yoshliklaridagi hikoyalarni aytishadi."),
        ("Today's tale was about Grandpa losing a goat in 1975.", "Bugungi hikoya Bobomizning 1975-yilda echisini yo'qotishi haqida edi."),
        ("He denies half of it, which proves it is true.", "U yarmi inkor etadi, bu esa uning rostligini isbotlaydi."),
        ("The teenagers pretend not to listen but hear everything.", "O'smirliklar tinglamaslikka harakat qiladi, ammo hammasini eshitishadi."),
        ("Later, we pick apples from the tree behind the house.", "Keyinchalik uy ortidagi daraxtdan olma teramiz."),
        ("The best ones hang highest, naturally.", "Eng zo'rlari tabiiy ravishda balandda osilgan bo'ladi."),
        ("My cousin lifts me on his shoulders like old times.", "Amakivachcham meni eski vaqtlarday yelkasiga ko'taradi."),
        ("We fill one basket and eat another basket quietly.", "Bir savat to'ldiramiz va yana bir savatni jim yeymiz."),
        ("Grandma counts apples later and just smiles knowingly.", "Bobomiz keyinchalik olmalarni sanab, anglagan holda tabassum qiladi."),
        ("Towards evening, someone brings out the old photo album.", "Kechga yaqin kimdir eskicha fotoalbomni olib chiqadi."),
        ("Black-and-white grandparents stare back at us, young forever.", "Qora-oq bobolarimiz bizga abadiy yosh holda qarashadi."),
        ("Mom points at Grandma's wedding dress and sighs.", "Onam Bobomizning to'y ko'ylagini ko'rsatib nafas oladi."),
        ("Grandma waves her hand and says fashion repeats itself.", "Bobomiz qo'l silkitadi va moda takrorlanishini aytadi."),
        ("When the sky turns orange, cars start lining up.", "Osmon to'qsarig' aylanganda mashinalar navbatga turadi."),
        ("Nobody wants to be the first family to leave.", "Hech kim birinchi bo'lib ketadigan oila bo'lishni istamaydi."),
        ("We hug a hundred times at the gate, as usual.", "Odatdagidek darvoza oldida yuz marta quchoqlashamiz."),
        ("Grandma fills our bags until they barely close.", "Bobomiz sumkalarimizni zo'rg'a yopiladigan darajada to'ldiradi."),
        ("Driving home, the car smells of apples and warm bread.", "Uyga qaytayotib, mashina olma va iliq non hidi beradi."),
        ("My little brother falls asleep holding a half-eaten cookie.", "Kichik ukam yarim yegan pecheneni qo'liga olib uxlab qoladi."),
        ("These Sundays are simple, loud, and absolutely perfect.", "Bu shanbalar oddiy, shovqinli va mutlaqo mukammal."),
    ],
}
