LONG_STORIES_D = {
    7: [
        ("In June, my friends and I hiked into the Chimgan mountains.", "Iyun oyida do'stlarim bilan Chimyon tog'lariga yurish qildik."),
        ("The forecast promised sun, so nobody packed a raincoat.", "Bashorat quyoshni va'da qilgandi, shuning uchun hech kim yomg'irpoq olmadi."),
        ("That was the first mistake of our trip.", "Bu bizning sayohatimizdagi birinchi xato edi."),
        ("We started climbing at six in the cool morning air.", "Salqin ertalabki havoda soat oltida chiqishni boshladik."),
        ("Pine trees covered the lower slopes like green armies.", "Qarag'aylar pastki yonbag'irlarni yashil armiyalardek qoplaydi."),
        ("Birds sang from every direction, showing off their morning.", "Qushlar har tomondan kuyladi, ertalablarini ko'rsatib turardi."),
        ("By ten, sweat had drawn dark maps on our shirts.", "O'nlikka kelib, ter ko'ylaklarimizda qora xaritalar chizdi."),
        ("We drank water too fast and laughed about it.", "Suvni juda tez ichdik va buning ustidan kuldik."),
        ("The trail narrowed along a cliff with a small stream below.", "Yo'l pastda kichik soy bo'lgan jarlik bo'ylab toraydi."),
        ("Faris fell behind, complaining dramatically about his backpack.", "Faris orqada qoldi, chamadoni haqida dramatik shikoyat qilib."),
        ("We teased him, but slowed down together anyway.", "Uni masxara qildik, lekin baribir birga sekinlashtirdik."),
        ("Around noon, the sky changed its mood completely.", "Taxminan peshin vaqtida osmon kayfiyatini butunlay o'zgartirdi."),
        ("A grey wall of clouds climbed over the far ridge.", "Kulrang bulut devori uzoq tizmadan oshib chiqa boshladi."),
        ("The temperature dropped as if someone closed a window on summer.", "Harorat tushdi, xuddi kimdir yozga oynani yopib qo'yganidek."),
        ("First drops were big, cold, and surprisingly friendly.", "Birinchi tomchilar katta, sovuq va kutilmaganda samimiy edi."),
        ("Then the rain arrived like applause — heavy and everywhere.", "Keyin yomg'ir olqish kabi keldi — kuchli va hamma joyda."),
        ("We ran laughing towards a huge flat rock nearby.", "Yaqin atrofdagi ulkan tekis toshga kulib yugurdik."),
        ("Seven people squeezed under one narrow ledge like sardines.", "Yetti kishi bir tor qoyalarga sardinalardek sig'ishdi."),
        ("Our backpacks went under the middle; we stayed outside half-wet.", "Chamadonlar o'rtaga kirdi; biz yarim ho'l holda tashqarida qoldik."),
        ("The rain turned the whole valley silver and loud.", "Yomg'ir butun vodini kumushrang va shovqinli qildi."),
        ("Waterfalls appeared on cliffs where no waterfall existed before.", "Oldin sharshara bo'lmagan jarliklarda sharsharalar paydo bo'ldi."),
        ("Lightning drew silent white branches across the opposite mountain.", "Chaqqon oppoq shoxlarni qarama-qarshi tog' bo'ylab jim chizdi."),
        ("We counted seconds between flash and thunder like children.", "Biz yalt-ylt va g'umburlash orasidagi soniyalarni sanadik."),
        ("Somewhere below, a shepherd whistled his sheep home early.", "Pastlarda cho'pon qo'ylarini erta uyga chalqitdi."),
        ("Wrapped together in one emergency blanket, we shared chocolate.", "Bir favqulodda ko'rpachaga o'ralgan holda shokolad bo'lishdik."),
        ("Dilnoza told ghost stories until we begged her to stop.", "Dilnoza arvoh hikoyalarini aytdi, biz uni to'xtashiga yalinmaguncha."),
        ("The storm lasted exactly forty minutes by Jasur's watch.", "Bo'ron Jasurning soatiga aynan qirq daqiqa davom etdi."),
        ("When it left, the world smelled completely newborn.", "U ketganda, dunyo butunlay yangi tug'ilgandek hid berdi."),
        ("Every leaf held a tiny trembling diamond of water.", "Har bir yaproqda mayda titrayotgan suv olmosi bor edi."),
        ("Fog rose slowly from the valley like gentle smoke.", "Tuman vodidan yumshoq tutun singari sekin ko'tarildi."),
        ("And then came the rainbow — enormous, doubled, almost arrogant.", "Va kamalak keldi — ulkan, juftlashgan, deyarli mag'rur."),
        ("Nobody spoke; even Faris forgot his complaints.", "Hech kim gapirmadi; hatto Faris ham shikoyatlarini unutdi."),
        ("We continued climbing through wet grass and shining stones.", "Ho'l o'tloq va yalt-yaltiroq toshlar orasida chiqishda davom etdik."),
        ("The summit appeared suddenly, wearing a cloud like a hat.", "Cho'qqi birdan namoyon bo'ldi, bulutni shlyapa kabi kiygan holda."),
        ("We shouted into the fog just to hear echoes return.", "Tumanga aks sadoni eshitish uchun baqirdik."),
        ("Lunch was bread, cheese, tomatoes, and pure victory.", "Nonushta non, pishloq, pomidor va sof g'alaba edi."),
        ("Everything tastes better after rain and effort.", "Yomg'ir va mehnatdan keyin har narsa mazaliroq tuyuladi."),
        ("Descending took less time but more concentration.", "Pasayish kamroq vaqt oldi, lekin ko'proq e'tibor talab qildi."),
        ("Wet stones are professional-level slippery, we learned quickly.", "Ho'l toshlar professional darajadagi sirg'aluvchan ekanini tez o'rgandik."),
        ("At the village, a grandmother sold us hot tea and honey.", "Qishloqda keksa ayol bizga issiq choy va asal sotdi."),
        ("She said mountain rain always brings good luck to visitors.", "U tog' yomg'iri mehmonlarga doimo omad keltirishini aytdi."),
        ("The bus ride home smelled of wet wool and grass.", "Uyga avtobusda ho'l jun va o't hidi bor edi."),
        ("Everyone slept except the driver and Dilnoza's ghost stories.", "Haydovchi va Dilnozaning arvoh hikoyalaridan boshqa hamma uxlab qoldi."),
        ("Since that trip, we never trust weather forecasts again.", "O'sha sayohatdan keyin ob-havo bashoratiga umuman ishonmaymiz."),
    ],
}
