PART2 = {
    4: [
        ("Каждое второе воскресенье наша семья собирается в доме у бабушки.", "Har juftshanba kuni oilamiz bobomizning uyida yig'iladi."),
        ("Её дом стоит в конце тихой улицы, полной тополей.", "Uning uyi teraklar bilan to'lgan sokin ko'chaning oxirida joylashgan."),
        ("Птиц слышно ещё до того, как постучишь в ворота.", "Darvoza urishdan avval qushlar ovozini eshitishingiz mumkin."),
        ("Бабушка начинает готовить на рассвете, надев свой фиолетовый фартук.", "Bobomiz tong otishidan boshlab oshxona boshlaydi, binafsha fartugi kiyingan holda."),
        ("Запах свежей самсы встречает нас у двери.", "Yangi somsa hidi bizni eshik oldida kutib oladi."),
        ("Дядья весело спорят о том, чья машина лучше припаркована.", "Amakilar kimning mashinasi yaxshi to'xtaganligi haqida quvonch bilan bahslashadi."),
        ("Двоюродные братья носятся по саду, гоняя старый футбольный мяч.", "Amakivachchalar bog'da eskicha futbol ortidan yugurishadi."),
        ("Кто-нибудь обязательно спотыкается о садовый шланг, каждый раз.", "Har safar kimdir bog'dagi shlangaga tiqilib yiqiladi."),
        ("Тёти сидят на веранде и сравнивают фотографии в своих телефонах.", "Xolalar verandada telefonlaridagi suratlarni solishtirib o'tirishadi."),
        ("Дедушка сторожит свою шахматную доску, как маленький король.", "Bobomiz shaxmat taxtasini kichik qirol kabi qo'riqlaydi."),
        ("Он вызывает на партию каждого внука и побеждает большинство из нас.", "U har bir nabirasini o'yin chorlaydi va ko'pchiligimizni mag'lub etadi."),
        ("Сегодня я дважды проиграл и потребовал реванш после обеда.", "Bugun ikki marta yutqazdim va tushlikdan keyin revansh talab qildim."),
        ("На кухне бабушка никогда ничего не отмеряет.", "Oshxonada Bobomiz hech narsani o'lchamaydi."),
        ("Соль она добавляет «прислушиваясь к еде», как говорит она сама.", "U tuzni 'ovqat tinglab' qo'shishini aytadi."),
        ("Её тесто раскатывается тонко, словно золотая бумага.", "Uning xamiri oltin qog'oz kabi ingichka cho'ziladi."),
        ("Все секреты живут не в рецептах, а в её запястьях.", "Barcha sirlar retseptlarda emas, bilaklarida yashirilgan."),
        ("Я помогаю тем, что мою посуду и краду тёплый хлеб.", "Men idish yuvgani va iliq non o'g'irlashga yordam beraman."),
        ("Каждый раз она делает вид, что не замечает меня.", "U har safar meni ko'rmagan bo'lib qiyofa beradi."),
        ("В два часа длинный стол прогибается под тяжестью блюд.", "Soat ikkida uzun stol taomlar ostida ingichka ovoz chiqaradi."),
        ("Плов, салаты, самса, фрукты и три вида чая.", "Palov, salatlar, somsa, mevalar va uch xil choy."),
        ("Перед едой дедушка произносит несколько тихих слов благодарности.", "Yeyishdan oldin Bobomiz bir nechta sokin minnatdorchilik so'zi aytadi."),
        ("Потом комната взрывается разговорами и смехом.", "Keyin xona gapirish va kulish bilan portlaydi."),
        ("Все говорят одновременно, и каким-то чудом это работает.", "Hamma bir vaqtda gapiradi va bir yo'l bilan hammasi mos keladi."),
        ("Маленькая Зухра читает стихотворение, стоя на стуле.", "Kichkina Zuhra kursida turub she'r aytyapti."),
        ("Мы хлопаем слишком громко, а она кланяется как актриса.", "Biz juda baland qarsak chaldik va u aktrisa kabi egildi."),
        ("После еды старшие рассказывают истории из своей молодости.", "Ovqatdan keyin kattalar yoshliklaridagi hikoyalarni aytishadi."),
        ("Сегодняшняя история была о том, как дедушка потерял козу в 1975 году.", "Bugungi hikoya Bobomizning 1975-yilda echisini yo'qotishi haqida edi."),
        ("Он отрицает половину, что и доказывает: всё это правда.", "U yarmi inkor etadi, bu esa uning rostligini isbotlaydi."),
        ("Подростки делают вид, что не слушают, но слышат всё.", "O'smirliklar tinglamaslikka harakat qiladi, ammo hammasini eshitishadi."),
        ("Позже мы собираем яблоки с дерева за домом.", "Keyinchalik uy ortidagi daraxtdan olma teramiz."),
        ("Самые лучшие, конечно же, висят выше всех.", "Eng zo'rlari tabiiy ravishda balandda osilgan bo'ladi."),
        ("Двоюродный брат сажает меня на плечи, как в старые времена.", "Amakivachcham meni eski vaqtlarday yelkasiga ko'taradi."),
        ("Мы наполняем одну корзину и тихонько съедаем вторую.", "Bir savat to'ldiramiz va yana bir savatni jim yeymiz."),
        ("Бабушка позже пересчитывает яблоки и просто понимающе улыбается.", "Bobomiz keyinchalik olmalarni sanab, anglagan holda tabassum qiladi."),
        ("К вечеру кто-нибудь достаёт старый фотоальбом.", "Kechga yaqin kimdir eskicha fotoalbomni olib chiqadi."),
        ("Чёрно-белые дедушка и бабушка глядят на нас, вечно молодые.", "Qora-oq bobolarimiz bizga abadiy yosh holda qarashadi."),
        ("Мама показывает на свадебное платье бабушки и вздыхает.", "Onam Bobomizning to'y ko'ylagini ko'rsatib nafas oladi."),
        ("Бабушка отмахивается и говорит, что мода повторяется.", "Bobomiz qo'l silkitadi va moda takrorlanishini aytadi."),
        ("Когда небо становится оранжевым, машины начинают выстраиваться в ряд.", "Osmon to'qsarig' aylanganda mashinalar navbatga turadi."),
        ("Никто не хочет стать первой семьёй, которая уедет.", "Hech kim birinchi bo'lib ketadigan oila bo'lishni istamaydi."),
        ("Как обычно, мы сто раз обнимаемся у ворот.", "Odatdagidek darvoza oldida yuz marta quchoqlashamiz."),
        ("Бабушка набивает наши сумки так, что они едва закрываются.", "Bobomiz sumkalarimizni zo'rg'a yopiladigan darajada to'ldiradi."),
        ("По дороге домой машина пахнет яблоками и тёплым хлебом.", "Uyga qaytayotib, mashina olma va iliq non hidi beradi."),
        ("Мой младший брат засыпает, держа в руке надкушенное печенье.", "Kichik ukam yarim yegan pecheneni qo'liga olib uxlab qoladi."),
        ("Эти воскресенья простые, шумные и абсолютно идеальные.", "Bu shanbalar oddiy, shovqinli va mutlaqo mukammal."),
    ],
    5: [
        ("Прошлой зимой я решил купить серьёзное зимнее пальто.", "O'tgan qish men jiddiy qishki palto sotib olishga qaror qildim."),
        ("Моя старая куртка была тонкой и подводила меня каждый декабрь.", "Eski kurtkam ingichka edi va har dekabrda menga xiyonat qilardi."),
        ("Я два месяца копил деньги, как решительная белка.", "Ikki oy davomida qat'iyatli sichqon kabi pul yig'dim."),
        ("В субботу утром мы с сестрой пошли на большой базар.", "Shanba ertalab opam bilan katta bozorga bordik."),
        ("Зимний базар — это море серых и чёрных пальто.", "Qishda bozor kulrang va qora paltolar dengizidir."),
        ("Каждый продавец кричал, что у него в лавке лучшая цена.", "Har bir savdogar o'z do'konida eng zo'r narx borligini baqirdi."),
        ("Один продавец позвал нас на чай, ещё до того как мы успели осмотреться.", "Bir savdogar atrofga qaramay choyga taklif qildi."),
        ("Мы рассмеялись и согласились, потому что отказаться казалось невежливым.", "Kulib qabul qildik, chunki rad etish qo'pollik tuyuldi."),
        ("Чай был горячий, сладкий и опасно неиссякаемый.", "Choy issiq, shirin va xavfli darajada qayta quyiladigan edi."),
        ("После трёх пиал мы наконец заговорили о пальто.", "Uch piyola choynan keyin nihoyat paltolar haqida gaplashdik."),
        ("Он показал мне тяжёлое чёрное пальто с глубокими карманами.", "U menga chuqur cho'ntakli og'ir qora paltoni ko'rsatdi."),
        ("Оно было тёплым, но делало меня похожим на передвигающийся шкаф.", "U iliq edi, lekin meni yuruvchi shkafga o'xshatdi."),
        ("Сестра попыталась не смеяться и полностью провалилась.", "Opam kulmaslikka harakat qildi va butunlay muvaffaqiyatsiz bo'ldi."),
        ("Продавец признал, что это «пальто для отцов».", "Savdogar bu 'otolar uchun palto' ekanini tan oldi."),
        ("В следующей лавке я нашёл тёмно-синее пальто с серебристыми пуговицами.", "Keyingi do'konda kumush tugmali to'q ko'k palto topdim."),
        ("Зеркало сказало «да» раньше, чем мой кошелёк успел возразить.", "Oyna hamyonim bahslashidan oldin 'ha' dedi."),
        ("Но цена заставила меня на миг присесть.", "Lekin narx meni bir lahza o'tirishga majbur qildi."),
        ("Сестра начала торговаться как профессиональный дипломат.", "Opam professional diplomatchidek savdohni boshladi."),
        ("Она упомянула другую лавку, качество и скромную зарплату своего брата.", "U boshqa do'konni, sifatni va akasining kichik maoshini tilga oldi."),
        ("Продавец сделал вид, что звонит хозяину за разрешением.", "Savdogar ruxsat uchun boshlig'iga qo'ng'iroq qilganday bo'ldi."),
        ("Все знали, что никакого звонка нет, включая его самого.", "Qo'ng'iroq yo'qligini hamma, hatto u ham bilardi."),
        ("Наконец мы сошлись на цене, которая удивила нас обоих.", "Nihoyat ikkovimizni ham hayron qoldirgan narxda kelishdik."),
        ("Я заплатил, и пальто легло мне в руки, словно новый друг.", "To'lov qildim va palto yangi do'stdek quchoqlarimga sig'di."),
        ("На выходе мы купили жареную кукурузу у уличного торговца.", "Chiqib ketayotib, ko'cha sotuvchisidan qovurilgan makkajo'xori oldik."),
        ("Есть кукурузу на холодном ветру — здесь это особый талант.", "Sovuq shamolda makkajo'xori yeyish bu yerda maxsus qobiliyat."),
        ("Дома отец осмотрел пальто, как таможенный офицер.", "Uyda otam paltoni bojxona xodimidek tekshirdi."),
        ("Он проверил швы, подкладку, пуговицы и даже понюхал его.", "U choklar, astar, tugmalarni tekshirdi, hatto hidini ham sinadi."),
        ("Потом он медленно кивнул — это его высшая похвала.", "Keyin u sekin bosh irg'adi — bu uning eng baland maqtovi."),
        ("Мама тут же крепче пришила одну пуговицу «на всякий случай».", "Onam bir tugmani 'ehtiyot uchun' darhol mustahkam tikdi."),
        ("Той ночью я повесил пальто там, где мог его видеть.", "O'sha kechqurun paltoni ko'radigan joyimga osdim."),
        ("Знаю, звучит глупо, но я искренне гордился.", "Ahmoqona tuyulishini bilaman, lekin chin dildan faxrlanardim."),
        ("Через два дня в город пришёл настоящий мороз.", "Ikki kundan keyin shaharga haqiqiy qattiq sovuq keldi."),
        ("Пальто окутало меня, словно тёплая тишина против ветра.", "Palto meni shamolga qarshi iliq sokinlik kabi o'ray oldi."),
        ("На автобусной остановке пожилой мужчина спросил, где я его купил.", "Avtobus bekatida keksa odam uni qayerdan olganimni so'radi."),
        ("Я с гордостью указал в сторону базара и дал все подробности.", "Faxr bilan bozor tomonga ishora qilib barcha tafsilotlarni berdim."),
        ("Он записал адрес на ладони огрызком карандаша.", "U manzilni qalam bo'lagi bilan kaftiga yozib oldi."),
        ("В январе сестра попросила одолжить ей пальто на один вечер.", "Yanvarda opam uni bir kecha so'rab oldi."),
        ("Она вернула его с лёгким ароматом своих духов.", "Uni engil parfyum hidi bilan qaytarib berdi."),
        ("Я сделал вид, что сержусь, и на следующей неделе снова одолжил его.", "Jahl ko'ringanday qildim va keyingi haftada yana berdim."),
        ("К февралю вся семья успела хоть раз походить в этом пальто.", "Fevralga kelib butun oila o'sha paltoni bir marta kiyyan edi."),
        ("Оно пережило снег, дождь и футбольные тренировки моего двоюродного брата.", "U qor, yomg'ir va amakivachchamning futbol mashg'ulotidan omon chiqdi."),
        ("Теперь каждая зима начинается с одной важной церемонии.", "Endi har qish muhim bir marosim bilan boshlanadi."),
        ("Я открываю шкаф, слегка встряхиваю пальто и улыбаюсь.", "Shkafni ochaman, paltoni yumshoq silkitaman va tabassum qilaman."),
        ("Некоторые покупки практичны; эта стала ещё и историей.", "Ba'zi xaridlar amaliy; bu esa hikoyaga ham aylandi."),
    ],
    6: [
        ("Наша дворовая футбольная команда проиграла пять матчей подряд.", "Ko'cha futbol jamoamiz ketma-ket beshta o'yinda mag'lub bo'ldi."),
        ("В субботу должен был состояться финал кубка квартала.", "Shanba kuni mahalla kubogining final o'yini bo'lishi kerak edi."),
        ("Нашими соперниками были парни с соседней улицы, высокие и быстрые.", "Raqiblarimiz qo'shni ko'chaning baland va tez yigitlari edi."),
        ("Все говорили, что нам лучше просто сдаться и остаться дома.", "Hamma uyda qolib taslim bo'lishimizni aytdi."),
        ("Но у нашего капитана Жасура были на нас другие планы.", "Lekin sardorimiz Jasurning biz uchun boshqa rejalar bor edi."),
        ("Он назначил дополнительную тренировку на вечер четверга.", "U payshanba kechqurun qo'shimcha mashg'ulot chaqirdi."),
        ("Пришли только семеро игроков, и двое из них болели.", "Faqat yetti o'yinchi keldi, ikkovimiz kasal edik."),
        ("Мы тренировали передачи, пока не зажглись уличные фонари.", "Ko'cha chiroqlari yoqilguncha paslar mashq qildik."),
        ("Жасур повторял одну и ту же фразу: «Пасуй, прежде чем вести мяч».", "Jasur bitta jumlani takrorladi: 'Chalib ketishdan oldin pass ber.'"),
        ("В пятницу ночью я почти не спал от волнения.", "Juma kechqurun hayajondan zo'rg'a uxladim."),
        ("Я раз сорок представил себе, как забиваю победный гол.", "G'alaba golini urganini taxminan qirq marta xayolimdan o'tkazdim."),
        ("Субботнее утро было холодным, на лужах стоял тонкий лёд.", "Shanba ertalab sovuq edi, suv havzalarida ingichka muz bor."),
        ("Поле за старым заводом было мягким от грязи.", "Eski zavod ortidagi maydon loy bilan yumshoq edi."),
        ("Зрители выстроились вдоль обеих сторон, включая дедушек с термосами.", "Tomoshabinlar ikki tomonda saf tortdi, termosli bobolar ham bor edi."),
        ("Судьёй был учитель на пенсии, известный своей строгостью.", "Hakim qat'iyligi bilan mashhur nafaqadagi o'qituvchi edi."),
        ("Первые пятнадцать минут были для нас катастрофой.", "Dastlabki o'n beshta daqiqa biz uchun ofat bo'ldi."),
        ("Они забили дважды, и их болельщики громко пели.", "Ular ikki marta gol urdi va muxlislarari baland qo'shiq aytdi."),
        ("Наш вратарь выкрикивал команды, как генерал.", "Darvozabonimiz generaldek ko'rsatmalar baqirdi."),
        ("Постепенно мы вспомнили простое правило четверга.", "Astasekin, payshanbadagi oddiy qoidani esladi."),
        ("Пас, движение, снова пас — никаких героев-одиночек.", "Pass, harakat, yana pass — yakka qahramonlar bo'lmaslik."),
        ("Наша игра вдруг стала быстрой и чистой.", "O'yinimiz birdan tez va toza bo'lib qoldi."),
        ("Как раз перед перерывом Азиз забил с острого угла.", "Tanaffus oldi rostida, Aziz tor burchakdan gol urdi."),
        ("Мы побежали обнимать его, поскальзываясь на мокрой траве.", "Uni quchoqlash uchun yugurdik, ho'l o'tloqda sirg'alib."),
        ("Перерыв длился десять минут тяжёлого дыхания.", "Tanaffus o'n daqiqa og'ir nafas olish bilan o'tdi."),
        ("Жасур чертил круги на грязной земле, объясняя тактику.", "Jasur loy tuproqga aylanalar chizib taktikani tushuntirdi."),
        ("Второй тайм начался яростно, почти зло.", "Ikkinchi bo'lim shiddat bilan, deyarli g'azablangan holda boshlandi."),
        ("Их самый высокий игрок нарочно наступил мне на ногу.", "Ularning eng baland o'yinchisi oyog'imni ataylab bosdi."),
        ("Я ничего не сказал и сосредоточился вместо этого на мяче.", "Men hech narsa demadim va o'rniga to'pga e'tibor berdim."),
        ("За двадцать минут до конца мы заработали штрафной удар.", "Yigirma daqiqa qolganda jarima zarbasiga erishdik."),
        ("Все посмотрели на Сардора, нашего тихого специалиста.", "Hamma jim ko'rinishdagi mutaxassisimiz Sardorga qaradi."),
        ("Он аккуратно установил мяч и вытер лоб.", "U to'pni ehtiyotkorlik joylashtirdi va peshonasini artidi."),
        ("Стенка подпрыгнула; мяч красиво обогнул её по дуге.", "Devor sakradi; to'p uning atrofidan chiroyli egilib o'tdi."),
        ("Два-два — и улица взорвалась шумом.", "Ikk-ikki, va ko'cha shovqin bilan portladi."),
        ("В последнюю минуту мои ноги были как деревянные палки.", "Oxirgi daqiqada oyog'im yog'och tayoqlardek his qildi."),
        ("Потом свободный мяч случайно прокатился ко мне.", "Keyin erkin to'p tasodifan menga tomonga aylanib keldi."),
        ("Я услышал, как Жасур где-то далеко кричит моё имя.", "Jasurning ismimni uzoqdan baqirayotganini eshitdim."),
        ("Я отдал пас вместо удара — правило спасло меня.", "Zarba o'rniga pass berdim — qoida meni qutqardi."),
        ("Азиз принял мяч и спокойно забил победный гол.", "Aziz uni qabul qildi va g'alaba golini tinch urdi."),
        ("Прозвучал свисток, и я, смеясь, упал на траву.", "Chalqildi chalinadi va men kulgan holda o'tloqqa yiqildim."),
        ("Дедушки махали термосами над головами, словно трофеями.", "Bobolar termoslarni boshlaridan mukofotday silkitishdi."),
        ("Даже строгий судья на мгновение улыбнулся нашему капитану.", "Hattoning qattiqqo'l hakimi ham sardorimizga bir lahza tabassum qildi."),
        ("Мы праздновали выдохшимся лимонадом и тёплым хлебом.", "Biz gazsiz limonad va iliq non bilan nishonladik."),
        ("Сегодня никто не помнит точный счёт, честно говоря.", "Bugun hech kim aniq hisobni eslamaydi, rostini aytsam."),
        ("Но все помнят, что мы наконец-то сыграли вместе.", "Lekin hamma nihoyat birga o'ynaganimizi eslaydi."),
    ],
}
