CONTRU = {
    0: [
        ("На следующее утро Азиз снова позвонил мне ровно в семь.", "Ertasi kuni ertalab Aziz yana soat yettida aniq qo'ng'iroq qildi."),
        ("Он хотел поблагодарить женщину из пекарни настоящим завтраком.", "U nonvoyxonachi ayolga to'g'ri nonushta bilan minnatdorchilik bildirmoqchi edi."),
        ("Мы встретились на той же автобусной остановке, всё ещё пропахшей вчерашним дождём.", "Biz xuddi shu bekatda uchrashdik, kechagi yomg'ir hidida."),
        ("Город казался только что умытым, и всюду блестели серебристые лужи.", "Shahar endigina yuvilgandek ko'rindi, hamma joyda kumush suv havzalari."),
        ("В кафе мы заказали два латте и одно огромное печенье.", "Kafeda ikkita latte va bitta ulkan pechene buyurtma qildik."),
        ("Азиз открыл свою тетрадь, полную бизнес-расчётов.", "Aziz biznes hisob-kitoblari bilan to'lgan daftarini ochdi."),
        ("Числа немного пугали его, но он смело смотрел им в лицо.", "Raqamlar uni biroz qo'rqitardi, lekin u ularga jasurlik bilan yuzlashdi."),
        ("Я помог ему дважды проверить расчёты, очень серьёзно.", "Men uning hisoblarini ikki marta juda jiddiy tekshirib berdim."),
        ("В ответ он мягко поправлял моё ужасное английское произношение.", "Buning evaziga u mening dahshatli inglizcha talaffuzimni muloyimlik bilan tuzatdi."),
        ("Пожилой официант наблюдал за нами и улыбался, будто вспоминал молодость.", "Keksa ofitsiant bizni kuzatdi va yoshligini eslagondek tabassum qildi."),
        ("Он сказал, что молодёжь с планами даёт ему надежду.", "U rejaga ega yoshlar unga umid berishini aytdi."),
        ("После кофе мы медленно прошли мимо старого здания кинотеатра.", "Qahvadan keyin eski kinoteatr binosi oldidan sekin o'tdik."),
        ("Его наконец перекрашивали после двадцати серых лет.", "Yigirma kulrang yildan keyin u nihoyat bo'yalayotgan edi."),
        ("Рабочие на высоких лестницах весело махали нам руками.", "Baland narlarda turgan ishchilar bizga quvonch bilan qo'l silkitdi."),
        ("Азиз фотографировал всё для своей «папки будущих воспоминаний».", "Aziz hammasini 'kelajak xotiralari papkasi' uchun suratga oldi."),
        ("Его забавная фраза всегда заставляет меня смеяться вслух.", "Uning bu kulgili iborasi meni doim baland ovozda kuldiradi."),
        ("К вечеру мы каким-то образом оказались на речном причале.", "Kechki paytga kelib bir yo'i daryo pristaniga borib qoldik."),
        ("Мы кормили нетерпеливых уток хлебными крошками и спорили о лодках.", "Biz sabzavot nonlarini sabrsiz o'rdaklarga berdik va kemalar haqida bahslashdik."),
        ("По дороге домой мы пообещали продолжать исследовать собственный город.", "Uyga qaytayotib, o'z shahrimizni o'rganishda davom etishga va'da berdik."),
        ("Некоторые выходные стоят дороже дорогого отдыха за границей.", "Ba'zi dam olish kunlari chet eldagi qimmat ta'tillardan ham qadrli."),
    ],
    1: [
        ("Стамбул встретил меня запахом соли и жареных каштанов.", "Istanbul meni tuz va qovurilgan kashtan hidi bilan kutib oldi."),
        ("Квартира дяди стояла на узкой улице, полной кошек.", "Amakimning kvartirasi mushuklarga to'la tor ko'chada joylashgan edi."),
        ("Каждый вечер мы спускались в крошечный рыбный ресторанчик.", "Har kechqurun mayda baliq restoraniga pastga tushardik."),
        ("Официанты подшучивали над моим акцентом, но учили настоящим фразам.", "Ofitsiantlar talaffuzimni masxara qilishdi, lekin haqiqiy iboralarni o'rgatishdi."),
        ("Я понял, что ошибки заставляют людей улыбаться и раскрываться.", "Xatolar odamlarni tabassumga keltiradi va ochilishga undaydi deb o'rgandim."),
        ("Однажды утром мы переправились на пароме через Босфор.", "Bir ertalab Bosfor bo'ylab paromga chiqdik."),
        ("Чайки летели за кораблём, ловя хлеб из рук пассажиров.", "Chag'alalar kemaning ortidan borib, yo'lovchilar qo'lidan non tutdi."),
        ("Стоять между двумя континентами поначалу казалось нереальным.", "Ikki qit'a orasida turish avvaliga g'ayrioddiy tuyuldi."),
        ("На азиатской стороне мы пили чай из стаканчиков в форме тюльпана.", "Osiyo tomonida lola shaklidagi stakanda choy ichdik."),
        ("Старый капитан рассказывал про каждый проплывающий мимо остров и крепость.", "Keksa kapitan o'tayotgan har bir orol va qal'ani tushuntirdi."),
        ("Его турецкий был медленным и ясным — идеально для начинающих.", "Uning turkchasi sekin va ravon edi, boshlovchilar uchun mukammal."),
        ("Я понимал половину, угадывал четверть и любил всё это.", "Yarmisini tushundim, choragini taxmin qildim va hammasini sevdim."),
        ("Дома все спрашивали о кебабах и рынках.", "Vatanimga qaytgach, hamma shashlik va bozorlar haqida so'radi."),
        ("Но я вместо этого всё время говорил о той поездке на пароме.", "Lekin men o'rniga o'sha parom sayohati haqida gapirib berardim."),
        ("Что-то в движущейся воде превращает незнакомцев в друзей.", "Harakatlanuvchi suv odamlar nimani do'stlarga aylantirishining sirini bildi."),
        ("В аэропорт, улетая домой, я приехал на три часа раньше.", "Uyga qaytayotganda aeroportga uch soat oldin bordim."),
        ("В этот раз досмотр казался знакомым, почти рутиной.", "Bu safar xavfsizlik tekshiruvi tanish, deyarli kundalik ishdek tuyuldi."),
        ("Я купил открытки и писал их, пока ждал у выхода на посадку.", "Postkartalar sotib oldim va reja kutayotib ularni yozdim."),
        ("Когда наш самолёт взлетел, я прижался лицом к окну.", "Samolyotimiz ko'tarilganda yuzimni oynaga bosdim."),
        ("Стамбул уменьшался внизу, словно красивая нарисованная от руки карта.", "Istanbul ostda go'zal qo'lda chizilgan xaritadek kichiklashdi."),
        ("Полёт домой ощущался иначе: спокойнее, гордее, уже с ностальгией.", "Uyga parvoz boshqacha tuyuldi: sokinroq, faxrliroq, allaqachon nostaljiya bilan."),
    ],
    2: [
        ("Следующий вторник принёс неожиданный сюрприз в кафе.", "Keyingi seshanba kuni kafeda kutilmagan syurpriz kutib turardi."),
        ("Официантка вспомнила мой заказ ещё до того, как я подошёл к стойке.", "Ofitsiant men dollar oldiga yetmasdan buyurtmamni esladi."),
        ("«Капучино и яблочный пирог?» — спросила она с тихой гордостью.", "'Kapuchino va olcha pie?' deb so'radi u sokin iftixor bilan."),
        ("Я кивнул, чувствуя себя членом тайного клуба.", "Men bosh irg'atdim, sirli klubga a'zo bo'lgandek his qildim."),
        ("В тот день нервный молодой человек сидел один в углу.", "O'sha kun burchakda asabiylashgan yosh yigit yolg'iz o'tirdi."),
        ("Он тихо репетировал что-то перед камерой телефона.", "U bir narsani telefon kamerasiga jim mashq qilib ko'rardi."),
        ("Бариста без просьбы поставил рядом с ним горячий шоколад.", "Barista so'ralmasdan uning yoniga issiq shokolad qo'ydi."),
        ("Она прошептала, что каждому нужна смелость перед собеседованием.", "U ish suhbatidan oldin hammaga jur'at kerakligini shivirladi."),
        ("Когда он наконец ушёл, он поднял кулак, как чемпион.", "Nihoyat chiqib ketayotib, u g'olib kabi mushtini ko'tardi."),
        ("Всё кафе молча аплодировало, двигая одними руками.", "Butun kafe jim qarsak chaldi, faqat qo'llarni harakatga keltirib."),
        ("Спустя мгновение у окна началось старое шахматное соперничество.", "Lahzadan keyin oynaning yaqinida eski shaxmat raqobati boshlandi."),
        ("Два пенсионера спорили о ходе прошлой недели.", "Ikkita nafaqaxur o'tgan haftadagi yurish haqida bahslashdi."),
        ("Они пригласили меня судьёй, хотя я едва знаю шахматы.", "Ular menga hakamlikni taklif qilishdi, holbuki men shaxmatni zo'rg'a bilaman."),
        ("Я показал наугад; один игрок благодарно поцеловал мне руку.", "Men tasodifiy ko'rsatdim; bir o'yinchi minnatdorchilik bilan qo'llarimni o'pdi."),
        ("Второй потребовал реванш и заказал праздничный торт.", "Ikkinchisi revansh talab qildi va nishon tortini buyurtma qildi."),
        ("Снаружи снова пошёл дождь, но никто, казалось, не спешил.", "Tashqarida yomg'ir qaytdi, lekin hech kim shoshilmayotganday edi."),
        ("Кафе стало моим университетом маленьких человеческих историй.", "Kafe mening kichik insoniy hikoyalar universitetiga aylandi."),
        ("Я начал носить свой блокнот повсюду, чтобы записывать их.", "Daftarchamni ularni yozib olish uchun hamma joyga olib yuradigan bo'ldim."),
        ("На одной странице просто написано: «Люди добрее, чем говорят новости».", "Bir sahifada shunday deyilgan: 'Odamlar yangiliklardagidan ham mehrliroq.'"),
        ("Каждый вторник снова и снова доказывает правоту этой фразы.", "Har seshanba bu jumlaning rostligini yana bir bor tasdiqlaydi."),
    ],
    3: [
        ("Моя вторая неделя в офисе принесла настоящую ответственность.", "Ofisdagi ikkinchi haftam haqiqiy mas'uliyat olib keldi."),
        ("Менеджер вручил мне собственный маленький проект.", "Menejer menga o'zimning kichik loyihani topshirdi."),
        ("Руки слегка дрожали, когда я принимал папку.", "Papkani qabul qilayotib qo'llarim biroz titradi."),
        ("Это был отчёт об отзывах клиентов, который никто не хотел читать.", "Bu hech kim o'qishni istamagan mijoz fikrlari hisoboti edi."),
        ("Я решил сделать его таким, чтобы невозможно было игнорировать.", "Men uni e'tiborsiz qoldirib bo'lmaydigan qilishga qaror qildim."),
        ("Вместо таблиц я нарисовал простые разноцветные диаграммы.", "Jadvalalar o'rniga men oddiy rangli diagrammalar chizdim."),
        ("Достон терпеливо научил меня офисной программе для презентаций.", "Doston ofis taqdimot dasturini sabr bilan o'rgatdi."),
        ("Дважды мы засиделись допоздна, смеясь над нашими провалами с форматированием.", "Biz ikki marta kechgacha qoldik, formatlash baxtsizliklaridan kulib."),
        ("Уборщица принесла нам печенье и крепкий чай.", "Tozalovchi ayol bizga pechene va kuchli choy olib keldi."),
        ("Она сказала, что усталым глазам нужны сахар и свежий воздух.", "U charchagan ko'zlar shakar va toza havoga muhtoj deb aytdi."),
        ("В четверг я представил свои выводы всей команде.", "Payshanba kuni xulosalarimni butun jamoaga taqdim etdim."),
        ("Мой голос дрожал ровно одну минуту, затем успокоился.", "Ovozim aynan bir daqiqa titradi, keyin barqarorlashdi."),
        ("Люди задавали вопросы, на которые я действительно мог уверенно ответить.", "Odamlar men ishonch bilan javob bera oladigan savollar berishdi."),
        ("Директор сказал: «Наконец-то кто-то заставил данные говорить».", "Direktor dedi: 'Nihoyat, kimdir ma'lumotlarni gapira qildi.'"),
        ("Эта фраза весь вечер прокручивалась у меня в голове.", "O'sha jumla butun kechqurun miyamda takrorlandi."),
        ("В пятницу утром коллега из бухгалтерии пригласила меня на обед.", "Juma ertalab hisob bo'limidagi hamkasb tushlikka taklif qildi."),
        ("Она вспомнила, что всего восемь месяцев назад сама была здесь новичком.", "U sakkiz oy oldin bu yerda yangi bo'lganini esladi."),
        ("Её совет был прост: записывай имена всех людей.", "Uning maslahati oddiy edi: hamma odamning ismi haqida yozib boring."),
        ("Мелкие детали, сказала она, медленно создают большое доверие.", "Kichik tafsilotlar katta ishonchni sekin quradi dedi u."),
        ("К вечеру пятницы мой проект был официально утверждён.", "Juma kechqurunga kelib loyham rasman tasdiqlandi."),
        ("Я отпраздновал в одиночестве дешёвой пиццей и дорогим счастьем.", "Men arzon pitsa va qimmat baxt bilan yolg'iz nishonladim."),
    ],
    4: [
        ("После обеда в то воскресенье Бабушка объявила особую миссию.", "O'sha shanba tushlikdan keyin Bobomiz maxsus vazifa e'lon qildi."),
        ("Виноградную лозу за теплицей нужно было срочно собрать.", "Issiqxona ortidagi uzum tokining shoshilinch terilishi kerak edi."),
        ("Все ссылались на занятость, кроме нас внуков, конечно.", "Hamma band jadvalini da'vo qildi, albatta biz nabiralar bundan mustasno."),
        ("Она раздавала ножницы и плетёные корзины, словно медали.", "U bizga medallar kabi qaychi va to'qima savatlarni berdi."),
        ("Лозы стояли высокими и тяжёлыми от фиолетовых гроздей.", "Toklar binafsha gullari bilan baland va og'ir turardi."),
        ("Двоюродный брат Баходир вскарабкался на половину высоты раньше, чем кто-либо успел его остановить.", "Amakivachcha Bahodir hech kim to'xtatmasdan yarmigacha chiqib oldi."),
        ("Оса исследовала его ухо, и лестница сильно затряслась.", "Bir asalari qulog'ini tekshirdi narlar kuchli silkindi."),
        ("Он спустился быстрее, чем поднялся, слегка потеряв достоинство.", "U chiqqanidan tezroq tushdi, izzati biroz shikastlangan holda."),
        ("Бабушка наблюдала за всем снизу, смеясь беззвучно.", "Bobomiz hamma narsani pastdan kuzatdi, ovozisiz kuldi."),
        ("Мы наполнили три корзины примерно за час липкой работы.", "Yopishqoq ishning bir soati ichida uch savat to'ldirdik."),
        ("Фиолетовые пятна покрыли наши пальцы, как временные татуировки.", "Binafsha dog'lar barmoqlarimizni vaqtinchalik tatuka kabi qoplaydi."),
        ("Самая младшая двоюродная сестра, естественно, съела больше винограда, чем собрала.", "Eng kichkina amakivachcha tabiiyki terganidan ko'p uzum yedi."),
        ("Бабушка ничего не считала, но поблагодарила всех дважды.", "Bobomiz hech narsani sanamadi lekin hammaga ikki marta rahmat aytdi."),
        ("Вечером она сварила из винограда тёмный сок.", "Kechkirib u uzumlarni qora sharbatga qaynatdi."),
        ("Весь дом сладко пах, словно фруктовая фабрика.", "Butun uy mevazavoddek shirin hid berardi."),
        ("Мы пили тёплый сок на веранде, наблюдая, как появляются звёзды.", "Verandada iliq sharbat ichib, yulduzlar paydo bo'lishini kuzatdik."),
        ("Дедушка рассказал, как посадил эти лозы в 1980 году.", "Bobo o'sha toklarni 1980-yilda ekkanini gapirdi."),
        ("Сорок лет терпения зреют внутри маленьких фиолетовых плодов.", "Qirq yillik sabr mayda binafsha mevalar ichida yetilibdi."),
        ("Никто не хотел спать; даже телефоны остались забытыми дома.", "Hech kim uxlamoqchi emas edi; hatto telefonlar ham uyda unutilgan edi."),
        ("Когда мы наконец уехали, машина везла сок, виноград и покой.", "Nihoyat ketganda mashina sharbat, uzum va tinchlik olib ketaardi."),
    ],
    5: [
        ("Первое настоящее испытание пальто случилось во время школьной поездки.", "Paltoning birinchi haqiqiy sinovi maktab sayohati paytida keldi."),
        ("В пятницу мы повезли сорок детей в зимний зоопарк.", "Juma kuni qirq bolani qishki zooparkga olib bordik."),
        ("Я был ответственным взрослым, что до сих пор удивляет мою семью.", "Men mas'ul katta odam edim, bu hali ham oilamni hayron qiladi."),
        ("С девяти утра снег шёл не переставая.", "Qor soat to'qqizdan boshlab uzluksiz tushardi."),
        ("Пальто согревало меня три часа среди пингвинов и попкорна.", "Palto uch soat pengvinlar va popkorn orasida meni iliq saqladi."),
        ("В тот день маленькая девочка по имени Малика навсегда меня «усыновила».", "Malika ismli mayda qiz o'sha kun menga abadiy biriktirildi."),
        ("Всюду она держалась за мой рукав, как крошечный охранник.", "U hamma joyda kurtagimdan mayda xavfsizlik xodimidek ushlab turdi."),
        ("У вольера с волками она прошептала свой самый важный вопрос.", "Bo'ri qafasi oldida eng katta savolini shivirladi."),
        ("«Волкам бывает холодно?» — Я сказал, что их шубы становятся гуще.", "'Bo'rilar muzlaydimi?' — Ularning paltolari qalinroq o'sadi dedim."),
        ("Она серьёзно это обдумала и решила, что людям нужны магазины.", "U buni jiddiy o'ylob odamlarga do'konlar kerak deb qaror qildi."),
        ("Во время обеда мы обнаружили, что палатка с горячим шоколадом закрылась.", "Tushlik paytida issiq shokolad savati yopilganini aniqladik."),
        ("Двадцать разочарованных лиц разом поднялись на меня.", "Yigirma xafa yuz birdan menga qaradi."),
        ("Так пальто стало историей: я обменивал шутки на улыбки.", "Shuning uchun palto hikoyaga aylandi: hazillarimni tabassumlarga almashtirdim."),
        ("В автобусе обратно все уснули за считанные минуты.", "Orqaga qaytayotgan avtobusda hamma bir necha daqiqada uxlab qoldi."),
        ("Малика спала, сжимая мою пуговицу одним маленьким кулачком.", "Malika bitta kichik musht bilan tugmamni ushlab uxlab qoldi."),
        ("Их учительница поблагодарила меня и предложила горячий чай из своего термоса.", "Ular o'qituvchisi menga rahmat aytdi va termosidan issiq choy taklif qildi."),
        ("Тем вечером я аккуратно счистил снег с пальто.", "O'sha kechqurun paltoni qordan ehtiyotkorlik bilan artib oldim."),
        ("Оно уже носило истории в своих глубоких карманах.", "U allaqachon chuqur cho'ntaklarida hikoyalar olib yurardi."),
        ("Мама нашла восковой рисунок, сложенный в левом кармане.", "Onam chap cho'ntak ichida bukilgan rangli chizma topdi."),
        ("Два человечка из палочек под большими белыми каракулями снега.", "Katta oppoq qor chizig'i ostida ikkita cho'p odamcha."),
        ("Малика подписала его одной гордой кривоватой буквой М.", "Malika uni faxr bilan bitta qiyshiq M harfi bilan imzolagan edi."),
    ],
    6: [
        ("Утром после финала наша улица казалась другой.", "Finaldan keyingi ertalab ko'chamiz boshqacha tuyuldi."),
        ("Соседи, которые никогда с нами не здоровались, вдруг махали с балконов.", "Hech qachon salom bermagan qo'shnilar birdan verandalardan qo'l silkitdi."),
        ("Кто-то за ночь написал мелом «ЧЕМПИОНЫ» на стене старого завода.", "Kimdir kechasi eski zavod devoriga bo'rdan 'CHEMPIONLAR' yozdi."),
        ("Жасур пришёл на тренировку, неся настоящий пластиковый кубок.", "Jasur mashg'ulotga haqiqiy plastik kubok olib keldi."),
        ("У его дяди был магазин, торговавший товарами для праздников.", "Uncasining to'y buyumlari sotadigan do'koni bor edi."),
        ("Мы смеялись десять минут, а потом всё равно серьёзно тренировались.", "Biz o'n daqiqa kuldik va baribir jiddiy mashq qilishda davom etdik."),
        ("Побеждать, объяснил Жасур, проще, чем оставаться победителями.", "G'alaba, deb tushuntirdi Jasur, g'olib bo'lib qolishdan osonroq."),
        ("Поэтому мы разработали упражнения для передач под давлением.", "Shuning uchun bosim ostida pass berish uchun mashqlar tuzdik."),
        ("Двое игроков прессинговали, а один убегал с мячом.", "Ikkala o'yinchi bosim berganda bittasi to'p bilan qochardi."),
        ("Моей ролью стал тихий связующий в центре поля.", "Mening rolim markazdagi sokin bog'lovchiga aylandi."),
        ("Я не быстрый, но вижу свободные зоны заранее.", "Men tez emasman, lekin bo'sh joylarni erta ko'raman."),
        ("Сардор каждый день тренировал штрафные удары до заката.", "Sardor har kuni quyosh botguncha jarima zarbalari mashq qildi."),
        ("Азиз работал над завершением атак обеими ногами, в основном левой.", "Aziz ikkala oyog' bilan, ko'pincha chap bilan zarba yakunlash ustida ishladi."),
        ("Наш вратарь придумывал странные танцы перед каждым упражнением.", "Darvozabonimiz har bir mashqdan oldin g'alati raqslar ixtiro qildi."),
        ("Никто их не понимал, но никто ему и не забивал.", "Hech kim ularni tushunmadi, lekin hech kim unga gol ham urmadi."),
        ("Через месяц команда из другого района вызвала нас на матч.", "Bir oy o'tib boshqa tumanlik jamoa bizga chiqishdi."),
        ("Они приехали в одинаковой форме и с одинаковой уверенностью.", "Ular bir xil forma va bir xil ishonch bilan kelishdi."),
        ("Мы же надели разные футболки, зато с абсолютной верой.", "Biz esa nomuvofiq ko'ylaklar va mutlaqo ishonch kiydik."),
        ("Тот матч закончился со счётом три-один, и наш футбол заговорил первым.", "O'sha uchrashuv uch-bir yakunlandi va futbolimiz avval gapirdi."),
        ("После этого мы вместе ели арбуз на заводских ступенях.", "Keyinchalik zavod narlarida birga tarvuz yedik."),
        ("Жасур поднял свою коробку сока и сказал: «Пасуй, прежде чем вести мяч, — и в жизни тоже».", "Jasur sharbat qutisini ko'tarib dedi: 'Hayotda ham chalg'idan oldin pass ber.'"),
    ],
    7: [
        ("Нам так понравились горы, что осенью мы вернулись туда снова.", "Biz tog'larni shu qadar yaxshi ko'rdik kech kuzda qaytib bordik."),
        ("Октябрь раскрасил склоны в медный, золотой и тёмно-красный цвета.", "Oktyabr yon bag'irlarni mis, oltin va to'q qizil ranglarga bo'ydi."),
        ("В этот раз все взяли дождевик и запасные носки.", "Bu safar hamma yomg'irpoq va ehtiyot paypoq olib chiqdi."),
        ("Опыт обходится дорого, но его уроки остаются навсегда.", "Tajriba qimmat turadi, lekin uning darslari abadiy qoladi."),
        ("Воздух был свежим и бодрым, словно слегка покусывал.", "Havo yumshoq tishlashga yetarli darajada tetik edi."),
        ("Фарис шёл впереди, как человек, лично мстящий силе тяжести.", "Faris tortishish kuchiga shaxsiy qasos oluvchi odamdek oldinda yurardi."),
        ("Дильноза собирала листья для папки своего проекта по ботанике.", "Dilnoza botanika loyiha papkasi uchun yaproqlar yig'di."),
        ("Она могла назвать каждое дерево, кроме тех, что фотографировала.", "U suratga olganlaridan boshqa har bir daraxt nomini biladi."),
        ("На полпути вверх мы нашли деревянную скамейку, обращённую к долине.", "Yarmiga kelib vodiga qaragan yog'och skameyka topdik."),
        ("Кто-то много лет назад вырезал на её спинке «Дыши здесь».", "Kimdir yillar oldin orqasiga 'Bu yerda nafas ol' deb o'yma edi."),
        ("Поэтому мы послушались древнего наставления и глубоко подышали.", "Shuning uchun qadimiy ko'rsatmaga bo'ysundik va chuqur nafas oldik."),
        ("Под нами деревня выглядела как рассыпанные игрушечные домики.", "Ostimizda qishloq tarqoq o'yinchoq uylarga o'xshab ko'rindi."),
        ("Из труб поднимался дым идеально ленивыми столбами.", "Mo'rilardan mukammal dangasa ustunlar bo'ylab tutun ko'tarildi."),
        ("Ястреб кружил над нами несколько долгих минут.", "Bir lochin bizning atrofimizda bir necha uzun daqiqa aylanardi."),
        ("Жасур утверждал, что тот проверял, готовы ли мы на этот раз.", "Jasur bu safar biz tayyorlanganimizni tekshirayotganini da'vo qildi."),
        ("Возле вершины мы обнаружили крошечный замёрзший водопад.", "Cho'qqi yaqinida mayda muzlagan sharshara topdik."),
        ("Вода застыла на лету, как стеклянная скульптура, невероятно терпеливая.", "Suv o'rtada oyna haykali kabi osilgan edi, aql bovar qilmas sabr bilan."),
        ("Дильноза объясняла научную сторону; мы в основном просто смотрели.", "Dilnoza ilmiy tomonni tushuntirdi; biz asosan faqat boqib turardik."),
        ("На вершине ветер мгновенно стёр всю усталость.", "Eng yuqorida shamol barcha charchoqni birdan o'chirib tashladi."),
        ("Мы ели бутерброды, наблюдая, как облака мчатся под нашими ботинками.", "Bo'tinkalar ostida poyga qilayotgan bulutlarni kuzatib sendvich yedik."),
        ("Спуск казался лёгким, и деревенский чай снова казался легендарным на вкус.", "Pasayish oson tuyuldi va qishloq choyi yana afsonaviy ta'm berdi."),
    ],
    8: [
        ("День результатов ещё и открыл мне моих друзей.", "Natijalar kuni do'stlarim haqida ham dars berdi."),
        ("Рустам провалил математику ровно на два балла.", "Rustam matematikadan aynan ikki bal bilan o'tolmadi."),
        ("Он мужественно улыбался, хотя глаза говорили другое.", "U jasur tabassum qildi, ko'zlari esa boshqa gapirardi."),
        ("Мы организовали план спасения раньше, чем он успел возразить.", "U e'tiroz qilmasdan oldin qutqaruv rejasini uyushtirdik."),
        ("Каждый вечер на протяжении двух недель с ним кто-нибудь занимался.", "Ikki hafta davomida har kechqurun kimdir uning bilan o'qidi."),
        ("Я взял производные; Дильноза — интегралы; мы чередовались.", "Men hosilalarni oldim; Dilnoza integrallarni; almashib ishladik."),
        ("Его пересдача была назначена на последний день июня.", "Qayta imtihoni iyun oxirgi kuniga belgilandi."),
        ("В то утро мы все проводили его до здания.", "O'sha ertalab hamma binogacha uni kutib bordik."),
        ("Дильноза вложила плитку шоколада в его ладонь, как медаль.", "Dilnoza shokoladni mushtiga mukofotday bosdi."),
        ("Он вернулся через девяносто минут, снова идя как обычный человек.", "U to'qson daqiqadan keyin yana oddiy odamdek yurib qaytdi."),
        ("«Семьдесят восемь», — объявил он, и улица зааплодировала.", "'Yetmish sakkiz', deb e'lon qildi va ko'cha olqish chaldi."),
        ("Ректор нашего университета упомянула нашу учебную группу в своей речи.", "Universitet rektorimiz nutqida o'quv guruhimizni tilga oldi."),
        ("Она назвала взаимопомощь «настоящей учебной программой».", "U o'zaro yordamni 'haqiqiy o'quv dasturi' dedi."),
        ("Эта фраза сделала две недели усталых вечеров бесценными.", "Bu jumla charchoqli kechki mashg'ulotlarning ikki haftasini arziydigon qildi."),
        ("Теперь Рустам добровольно занимается с первокурсниками каждый четверг.", "Endi Rustam har payshanba birinchi kurs talabalariga ko'ngilli ravishda saboq beradi."),
        ("Он говорит, что преподавание — это просто обучение при свидетелях.", "U o'qitish guvohlar bilan o'rganish ekanini aytdi."),
        ("Моя паника экзаменационной недели теперь кажется старой фотографией.", "Mening imtihon haftasi vahimi endi eski suratga o'xshaydi."),
        ("Она показывает, кем я был, а не кем я стал.", "U kim bo'lganimni ko'rsatadi, kim bo'lganimni emas."),
    ],
    9: [
        ("Иногда ночной автобус возвращает больше, чем забирает.", "Ba'zan tungi avtobus olganidan ko'proq qaytaradi."),
        ("В прошлом месяце я помог пожилому мужчине найти его улицу.", "O'tgan oy keksa odamga o'z ko'chasini topishda yordam berdim."),
        ("Он переехал в город всего два дня назад.", "U shaharga atigi ikki kun oldin kelgan edi."),
        ("На его бумажке был адрес, старательно выведенный буквами.", "Qog'oz varag'i diqqat bilan yozilgan manzilni ko'rsatardi."),
        ("Водитель сделал крюк в три остановки, лишь бы высадить его поближе.", "Haydovchi uni yaqinroq tushirish uchun uch bekat chetlab o'tdi."),
        ("Никто не возразил; ночные пассажиры образуют тихий парламент.", "Hech kim e'tiroz etmadi; tungi yo'lovchilar sokin parlament bo'lishadi."),
        ("Другим вечером дождь запер невесту на моей остановке.", "Boshqa bir shom yomg'ir kelingni bekatcha qamab qo'ydi."),
        ("Белое платье, без зонта, смех над некстати испортившейся погодой.", "Oq libos, soyabonsiz, ob-havoning yomon vaqtini kulib."),
        ("Шесть незнакомцев одновременно и громко предложили шесть решений.", "Olti begona odam bir vaqtda baland ovozda oltita yechim taklif qildi."),
        ("Она села к нам, оберегая своё платье, как флаг.", "U biz bilan chiqib ketdi, libosini bayroqday asrab."),
        ("Кто-то позвонил её жениху; кто-то другой поделился салфетками.", "Kimdir kuyoviga qo'ng'iroq qildi; kimdir boshqasi sovuq qog'oz berdi."),
        ("К её остановке весь автобус уже знал меню её свадьбы.", "Uning bekatiga kelib butun avtobus to'y menyusini bildi."),
        ("Она махала рукой, пока автобус не свернул за угол.", "Avtobus burilib ketguncha u qo'l silkitib turdi."),
        ("Подобные маленькие театры играют каждый вечер по цене одного билета.", "Bunday mayda teatrlar har kecha bitta chipta narxida o'ynaydi."),
        ("Теперь я веду блокнот персонажей ночного автобуса.", "Endi tungi avtobus qahramonlari haqidagi daftarchani saqlayman."),
        ("Водитель знает об этом и добавляет записи устно.", "Haydovchi bundan xabardor va og'zaki qatorlar qo'shib beradi."),
        ("Его лучшая история — про спящего гармониста.", "Eng zo'r hikoyasi uyloqotgan garmonchi haqida."),
        ("Может быть, однажды я запишу их все как следует.", "Ehtimol bir kuni ularning hammasini to'g'ri yozaman."),
        ("Пока же я просто езжу, слушаю и помню, какие люди хорошие.", "Hozircha men faqat o'tiraman, tinglayman va odamlarning qanchalik yaxshi ekanini eslayman."),
    ],
}
