PART1 = {
    0: [
        ("В прошлую субботу утром я проснулся раньше обычного.", "Shanba kuni ertalab odatdagidan erta turdim."),
        ("Солнце светило в моё окно, а небо было совершенно ясным.", "Quyosh derazamdan porlab kirayotgan edi, osmon esa butunlay ochiq."),
        ("Зазвонил телефон — это был мой лучший друг Азиз.", "Telefonim jiringladi — bu eng yaxshi do'stim Aziz edi."),
        ("Он сказал: «Собирайся, мы проведём весь день вместе!»", "U dediki: 'Tayyorlan, biz butun kunni birga o'tkazamiz!'"),
        ("Я рассмеялся, потому что он всегда планирует что-то неожиданное.", "Men kulib qo'ydim, chunki u doim kutilmagan narsa rejalashtiradi."),
        ("В девять часов мы встретились на автобусной остановке возле моего дома.", "Biz soat to'qqizda uyim yaqinidagi avtobus bekatida uchrashdik."),
        ("Город был тихим, и улицы были почти пустыми.", "Shahar tinch edi, ko'chalar deyarli bo'sh."),
        ("Сначала мы пошли пешком к маленькой пекарне на углу.", "Avval burchakdagi kichik nonvoyxonaga piyoda bordik."),
        ("Запах свежего хлеба сразу заставил нас обоих улыбнуться.", "Yangi non hidi ikkovimizni darhol tabassumga keltirdi."),
        ("Азиз купил две тёплые булочки и, не спрашивая, отдал мне одну.", "Aziz ikkita issiq bulochka oldi va so'ramasdan bittasini menga berdi."),
        ("Таким другом он был всегда.", "U har doim shunday do'st bo'lgan."),
        ("После завтрака мы решили прогуляться по центральному парку.", "Nonushtadan keyin markaziy bog' bo'ylab yurishga qaror qildik."),
        ("Старики играли в шахматы под высокими зелёными деревьями.", "Qariyalar baland yashil daraxtlar ostida shaxmat o'ynayotgan edi."),
        ("Дети катались на велосипедах и громко смеялись.", "Bolalar velosiped haydab, baland ovozda kulayotgan edilar."),
        ("Мы сели на скамейку и поговорили о наших планах на будущее.", "Biz skameykada o'tirdik va kelajak rejalarimiz haqida gaplashdik."),
        ("Азиз хочет открыть в следующем году своё собственное небольшое дело.", "Aziz kelasi yili o'zining kichik biznesini ochmoqchi."),
        ("Я рассказал ему о своей мечте путешествовать и учить новые языки.", "Men unga sayohat qilish va yangi tillar o'rganish orzim haqida gapirdim."),
        ("Мы пообещали друг другу усердно работать и никогда не сдаваться.", "Bir-birimizga qattiq ishlash va hech qachon taslim bo'lmaslikka va'da berdik."),
        ("Около полудня наши животы начали громко урчать.", "Taxminan peshin vaqtida qorinlarimiz baland ovozda g'urillay boshladi."),
        ("Поэтому мы пошли в моё любимое место во всём городе.", "Shuning uchun shahardagi sevimli joyimga bordik."),
        ("Это крошечное кафе, где готовят лучший суп в городе.", "Bu shaharda eng mazali sho'rva tayyorlaydigan juda kichik kafe."),
        ("Хозяин хорошо нас знает и всегда добавляет дополнительный хлеб.", "Egasi bizni yaxshi biladi va doim qo'shimcha non qo'shib beradi."),
        ("Мы ели неспешно и наблюдали за людьми, проходившими мимо окна.", "Biz sekin-asta yedik va derazadan o'tayotgan odamlarni kuzatdik."),
        ("Вдруг мы увидели, как наша старая школьная учительница переходит улицу.", "Birdan ko'chani kesib o'tayotgan eski maktab o'qituvchimizni ko'rdik."),
        ("Она выглядела счастливой, поэтому мы выбежали на улицу, чтобы поприветствовать её.", "U baxtli ko'rindi, shuning uchun uni kutib olish uchun tashqariga yugurdik."),
        ("После всех этих лет она помнила нас обоих.", "U shu yillar davomida ikkovimizni ham esladi."),
        ("Мы десять минут говорили о школьных воспоминаниях.", "Biz maktab xotiralari haqida o'n daqiqa suhbatlashdik."),
        ("Она сказала, что гордится теми людьми, которыми мы становимся.", "U biz aylanayotgan odamlar bilan faxrlanishini aytdi."),
        ("Её слова оставались в моём сердце до конца дня.", "Uning so'zlari kun davomida yuragimda qoldi."),
        ("Во второй половине дня мы посетили большой книжный магазин в центре города.", "Tushdan keyin shahar markazidagi katta kitob do'koniga bordik."),
        ("Азиз смотрел книги о бизнесе и деньгах.", "Aziz biznes va pul haqidagi kitoblarga qaradi."),
        ("Я нашёл красивый иллюстрированный словарь английских идиом.", "Men inglizcha iboralarning chiroyli rasmli lug'atini topdim."),
        ("Мы купили свои книги и разделили плитку шоколада на улице.", "Kitoblarimizni oldik va tashqarida bir shokoladni bo'lishdik."),
        ("По дороге домой тёмные тучи закрыли небо.", "Uyga qaytayotganda qora bulutlar osmonni qopladi."),
        ("Сильный дождь начался, как только мы дошли до автобусной остановки.", "Avtobus bekatiga yetib kelganimizda kuchli yomg'ir boshlandi."),
        ("Мы стояли, тесно прижавшись друг к другу, оберегая наши новые книги.", "Yangi kitoblarimizni himoya qilib, yonma-yon turdik."),
        ("От дождя пахло чистотой, и воздух стал прохладным и свежим.", "Yomg'ir toza hid berdi va havo salqin, yangi bo'lib qoldi."),
        ("Когда мы наконец пришли домой, мы были насквозь промокшими.", "Nihoyat uyga yetganimizda butunlay ho'l bo'lgan edik."),
        ("Мама рассмеялась, когда увидела нас, промокших до нитки, на пороге.", "Onam eshik oldida tomchiqayotganimizni ko'rib kuldi."),
        ("Она дала нам горячий чай с лимоном и сухую одежду.", "U bizga limon issiq choy va quruq kiyim berdi."),
        ("Мы пили чай и рассказали ей обо всём нашем дне.", "Choyni ichdik va unga butun kunimiz haqida gapirdik."),
        ("Вечером Азиз прислал мне фотографию нас под дождём.", "Kechqurun Aziz menga yomg'irdagi suratimizni yubordi."),
        ("Под фото он написал: «Лучшая суббота в жизни».", "Surat ostiga esa shunday yozdi: 'Eng zo'r shanba.'"),
        ("Я улыбнулся и ответил, что нам нужно скоро это повторить.", "Men tabassum bilan tez orada takrorlashimiz kerak deb yozdim."),
        ("Хорошие друзья делают обычные дни особенными.", "Yaxshi do'stlar oddiy kunlarni maxsus qilib ko'rsatadi."),
    ],
    1: [
        ("Два года назад я совершил свой первый полёт в одиночку.", "Ikki yil oldin birinchi parvozimni yolg'iz amalga oshirdim."),
        ("Я летел из Ташкента в Стамбул, чтобы навестить дядю.", "Toshkentdan amakisini ko'rgani Istanbulga uchyotgan edim."),
        ("Накануне ночью я совсем не мог уснуть.", "Oldingi kechqurun umuman uxlolmadim."),
        ("Я проверил паспорт и билет, наверное, раз двадцать.", "Pasportim va biletimni ehtimol yigirma marta tekshirdim."),
        ("Мама собрала мне бутерброды, сладости и тёплые носки.", "Onam menga tovoq-tort, shirinlik va iliq paypoq solib berdi."),
        ("В аэропорту всё казалось огромным и запутанным.", "Aeroportda hamma narsa ulkan va chalkash tuyuldi."),
        ("Длинные очереди путешественников извивались за каждым углом.", "Sayohatchilarning uzun navatlari har bir burchakda egri-bugri edi."),
        ("Я показал паспорт, и сотрудник добродушно улыбнулся.", "Pasportimi ko'rsatdim va xodim mehribon tabassum qildi."),
        ("Служба безопасности попросила меня снять ремень и опустошить карманы.", "Xavfsizlik xodimlari kamarimni yechish va cho'ntaklarimni bo'shatishni so'radi."),
        ("Сердце билось часто, но всё прошло гладко.", "Yuragim tez urayotgan edi, lekin hammasi silliq o'tdi."),
        ("У выхода на посадку я смотрел, как один за другим взлетают огромные самолёты.", "Reja oldida ulkan samolyotlarning birma-bir ko'tarilishini kuzatdim."),
        ("Их двигатели ревели, как огромные сонные звери.", "Ularning dvigatellari ulkan uxlagan hayvonlar kabi g'irladi."),
        ("Посадка началась за тридцать минут до вылета.", "Yo'lovchilarni o'tkazish jo'nashdan o'ttiz daqiqa oldin boshlandi."),
        ("Я протянул билет слегка дрожащими руками.", "Biletimni biroz titrayotgan qo'llarim bilan topshirdim."),
        ("Приветливая стюардесса поприветствовала меня на борту.", "Samimiy stuardessa menga bortda xush kelibsiz dedi."),
        ("Моё место было у окна, точно как я надеялся.", "O'rinishim oynaga yondosh edi, aynan umid qilganimdek."),
        ("Рядом со мной села пожилая женщина и тепло поздоровалась со мной.", "Yonimga keksa ayol o'tirdi va meni iliqlik bilan kutib oldi."),
        ("Она заметила моё нервное лицо и завела разговор.", "U bezovta yuzimni sezib, suhbatni boshladi."),
        ("Она рассказала мне, что летала больше пятидесяти раз.", "U ellik martadan ortiq parvoz qilganini aytdi."),
        ("Её спокойный голос постепенно успокаивал меня.", "Uning osoyishta ovozi meni asta-sekin tinchlantirdi."),
        ("Самолёт вырулил на взлётную полосу и на мгновение остановился.", "Samolyot uchish yo'lagiga chiqib bir lahza to'xtadi."),
        ("Потом двигатели толкали нас вперёд всё быстрее и быстрее.", "Keyin dvigatellar bizni tobora tezroq oldinga surdi."),
        ("Колёса оторвались от земли, и у меня ёкнуло сердце.", "G'ildiraklar yerdan uzildi va qornim tushib ketdi."),
        ("Дома стали маленькими, а дороги превратились в тонкие линии.", "Uylar kichiklashdi, yo'llar ingichka chiziqlarga aylandi."),
        ("Над облаками мир был ярким и безмолвным.", "Bulutlar ustida dunyo ravon va jim edi."),
        ("Облака под нами походили на мягкие белые горы.", "Ostimizdagi bulutlar yumshoq oq tog'largagina o'xshardi."),
        ("Женщина показала рукой на море далеко на горизонте.", "Ayol ufqdagi uzoq dengizni ko'rsatdi."),
        ("Вскоре после взлёта принесли еду — курицу с рисом.", "Ko'tarilishdan ko'p o'tmay ovqat keldi — tovuq guruch bilan."),
        ("Я съел всё, потому что от волнения мне хочется есть.", "Hammasini yedim, chunki hayajon meni och qiladi."),
        ("Позже я попытался посмотреть фильм, но всё время глядел в окно.", "Keyinchalik film ko'rishga harakat qildim, lekin doimo oyna tomonga qaradim."),
        ("Где-то над Чёрным морем мы попали в лёгкую турбулентность.", "Qora dengiz ustidagi bir joyda yengil silkinishga kirishdik."),
        ("Самолёт слегка затрясло, и мои руки замерли.", "Samolyot biroz larzaga keldi va qo'llarim qotib qoldi."),
        ("Женщина просто сказала: «Просто кочки на дороге».", "Ayol shunchaki dediki: 'Faqat yo'ldagi to'siqlar'."),
        ("Вскоре небо снова полностью успокоилось.", "Tez orada osmon yana butunlay tinchlandi."),
        ("Командир корабля объявил, что мы приземлимся через пятнадцать минут.", "Kapitan o'n beshta daqiqada qo'nishimizni e'lon qildi."),
        ("Сверху Стамбул сверкал тысячами огней.", "Yuqoridan Istanbul minglab chiroqlar bilan yaltiradi."),
        ("Босфор появился серебряной лентой между двумя континентами.", "Bosfor ikki qit'a orasida kumir lenta kabi namoyon bo'ldi."),
        ("Посадка оказалась плавнее, чем езда через лежачего полицейского.", "Qo'nish tezlik to'sig'idan o'tishdan ham silliqroq tuyuldi."),
        ("Когда самолёт остановился, все тихонько захлопали в ладоши.", "Samolyot to'xtaganda hammam yengil qarsak chaldi."),
        ("Я поблагодарил добрую женщину и пожелал ей крепкого здоровья.", "Mehmondo'st ayolga rahmat aytdi va sog'liq tiladim."),
        ("У выдачи багажа мой чемодан, как ни удивительно, приехал первым.", "Bagaj olish joyida chamadonim kutilmaganda birinchi bo'lib keldi."),
        ("Дядя ждал за стеклом с большой табличкой.", "Amakim katta yozuv bilan shisha ortida kutib turgan edi."),
        ("Его объятия мгновенно развеяли весь мой страх.", "Uning quchoqlashi barcha qo'rquvni darhol yo'q qildi."),
        ("По дороге в город я всё повторял: «Я действительно полетел!»", "Shahar tomon ketayotib, doim takrorladim: 'Men rostan uchdim!'"),
        ("С того дня я люблю каждый-каждый полёт.", "O'sha kundan buyon har bir parvozni yaxshi ko'raman."),
    ],
    2: [
        ("В дождливый вторник я обнаружил маленькое кафе неподалёку от библиотеки.", "Yomg'irli seshanba kuni kutubxona yaqinida kichik kafeni kashf etdim."),
        ("На его деревянной двери была маленькая латунная ручка в форме кофейного зёрнышка.", "Uning yog'och eshigida qahva donasiga o'xshash kichik guruch dastasi bor edi."),
        ("Внутри воздух пах корицей и жареными зёрнами.", "Ichkarida havoda doljin va qovurilgan don hidi bor edi."),
        ("Из старого динамика тихо играла мягкая джазовая музыка.", "Eski karnaydan nozik jaz musiqasi jim chalinayotgan edi."),
        ("Только три столика были заняты студентами с ноутбуками.", "Faqat uch stul noutbukli talabalar bilan band edi."),
        ("Молодая женщина за стойкой поприветствовала меня тёплым кивком.", "Dollar ortidagi yosh ayol meni iliqlik bilan bosh irg'ab kutib oldi."),
        ("Я заказал капучино и кусок яблочного пирога.", "Men kapuchino va olcha pie bo'lagini buyurtma qildim."),
        ("Пока я ждал, я прочитал меню, написанное от руки на доске.", "Kutayotib, doskadagi qo'lyozma menyuni o'qidim."),
        ("Там предлагали напитки с забавными названиями вроде «Облачное латте».", "Ularda 'Bulut latte' kabi kulgili nomlar bilan ichimliklar bor edi."),
        ("Мой кофе подали с крошечным листиком, нарисованным на молочной пенке.", "Mening kahvam sut ko'pigi ichiga chizilgan mayda yaproq bilan keldi."),
        ("Яблочный пирог был ещё тёплым, прямо из печи.", "Olcha pie hali ham tandirdan chiqqancha iliq edi."),
        ("Каждый кусочек был на вкус словно осень в маленьком городке.", "Har bir luqma kichik shaharchadagi kuzni eslatardi."),
        ("Я открыл блокнот и начал писать письмо самому себе.", "Daftarchamni ochdim va o'zimga xat yozishni boshladim."),
        ("Дождь мягко постукивал в большое окно рядом со мной.", "Yomg'ir yonimdagi katta oynaga yumshoq urildi."),
        ("Вошёл пожилой мужчина, стряхивая воду со своего серого зонта.", "Keksaygan erkak kirdi, kulrang soyabonidan suv silkitib."),
        ("Он здоровался со всеми по имени, включая повара на кухне.", "U hammaga, hatto oshxona oshpazi ham, ismi bilan salom berdi."),
        ("Очевидно, он был здесь постоянным гостем уже много лет.", "Aniqki, u bu yerda ko'p yillardan beri doimiy mehmon edi."),
        ("Официантка принесла его привычный заказ, не спрашивая.", "Ofitsiant uning odatbuy buyurtmasini so'ramasdin keltirdi."),
        ("Крепкий чай, один кусочек сахара отдельно и печенье с маслом.", "Kuchli choy, bir qoshiq shakar alohida va saryog'li pechene."),
        ("Наблюдая за ним, я понял, почему люди любят маленькие кафе.", "Uni kuzatib, odamlarning kichik kaflarni nega sevishi tushundim."),
        ("Большие места обслуживают тебя, а маленькие места запоминают тебя.", "Katta joylar sizga xizmat qiladi, kichik joylar esa eslab qoladi."),
        ("Полчаса спустя рядом со мной сели двое друзей.", "Yarim soatdan keyin yonimga ikki dugona o'tirdi."),
        ("Они шутя спорили, каким десертом им поделиться.", "Ular qaysi desertni bo'lishish masalasida o'yinkam bahslashdi."),
        ("Наконец они выбрали чизкейк с клубничным соусом.", "Nihoyat, ular maydalangan pishiriqni tanlashdi."),
        ("Их смех красиво смешивался со звуками дождя.", "Ularning kulishi yomg'ir tovushlari bilan chiroyli qorishdi."),
        ("Я допил кофе и без всяких угрызений заказал вторую чашку.", "Kahvamni tugatib, ikkinchi finjanni vijdontsiz buyurtma qildim."),
        ("Официантка улыбнулась, словно полностью одобряла мой выбор.", "Ofitsiant xuddi to'liq ma'qullayotgandek tabassum qildi."),
        ("Между глотками я наблюдал, как бариста рисует латте-арт.", "Luqmalar orasida barista latte san'atini quyayotganini tomosha qildim."),
        ("Её руки двигались уверенно, как художница за работой.", "Uning qo'llari rassom chizayotgandek ishonch bilan harakatlanardi."),
        ("Маленькой девочке за соседним столиком подали горячий шоколад.", "Qo'shni stoladagi kichkina qiz issiq shokolad oldi."),
        ("Её глаза расширились, когда она увидела плавающие внутри зефирки.", "Ichida suzayotgan zefirni ko'rib, ko'zlari kengaydi."),
        ("Она прошептала: «Это лучший день в моей жизни».", "U shivirladi: 'Bu mening hayotimdagi eng yaxshi kun.'"),
        ("Мама засмеялась и потихоньку стащила одну зефирку.", "Onasi kuldi va bir zefirni maxfiy o'g'irladi."),
        ("Такие моменты нельзя ни запланировать, ни купить.", "Bunday lahzalarni rejalashtirib yoki sotib olb bo'lmaydi."),
        ("На улице дождь наконец перешёл в лёгкие капли.", "Tashqarida yomg'ir nihoyat yengil tomchilarga aylandi."),
        ("Золотые фонари отражались в мокром тротуаре.", "Oltin ko'cha chiroqlari ho'l troyni aks ettirdi."),
        ("Я оплатил счёт и оставил щедрые чаевые.", "Hisobni to'lab, saxiy chaqa qoldirdim."),
        ("Официантка поблагодарила меня и тепло помахала на прощание.", "Ofitsiant menga rahmat aytdi va iliq xayrli yol dedi."),
        ("У двери я обернулся, чтобы бросить последний взгляд.", "Eshik oldida oxirgi marta orqaga burilib qaradim."),
        ("Кафе светилось, как фонарик в сером вечере.", "Kafe kulrang kechda fonar kabi yonib turardi."),
        ("Теперь я хожу в то кафе каждый вторник без исключения.", "Endi har seshanba kuni o'sha kafega boraman."),
        ("Тот же столик, тот же капучино, то же тёплое чувство.", "Xuddi shu stol, xuddi shu kapuchino, xuddi shu iliq tuygu."),
        ("Иногда официантка приберегает для меня последний кусок пирога.", "Ba'zan ofitsiant menga oxirgi pie bo'lagini saqlab qo'yadi."),
        ("Такие маленькие ритуалы делают жизнь сладкой и устойчивой.", "Bunday kichik an'anelar hayotni shirin va muqim qiladi."),
    ],
    3: [
        ("Моя первая неделя в новом офисе была похожа на сон.", "Yangi ofisdagi ilk haftam tushga o'xshab tuyuldi."),
        ("Накануне моего первого дня я приготовил одежду с вечера.", "Birinchi kundan oldingi kechqurun kiyimlarimni tayyorladim."),
        ("Из-за нервов я приехал на сорок минут раньше.", "Asabiyligidan qirq daqiqa erta yetib keldim."),
        ("Охранник оказался первым человеком, который заговорил со мной.", "Qo'riqchi menga gapirgan birinchi odam bo'ldi."),
        ("Он сказал: «Расслабьтесь, каждый переживает свой первый понедельник».", "U dediki: 'Bo'shasangiz, hamma birinchi dushanbasidan o'tadi.'"),
        ("Мой руководитель встретил меня у ресепшена с сияющей улыбкой.", "Mening menejerim meni qabulxonda yorqin tabassum bilan kutib oldi."),
        ("Она быстро провела меня по всему этажу.", "U menga butun qavatni tezkor sayohat qilib ko'rsatdi."),
        ("Всё пахло новизной — от ковров до экранов компьютеров.", "Hamma narsa yangi hid berdi — gilamlardan kompyuter ekranlarigacha."),
        ("Мой стол был маленьким, но находился прямо у широкого окна.", "Stolim kichik edi, lekin katta oynaning yonida joylashgan."),
        ("До обеда десять незнакомцев успели представиться.", "Tushlikkacha o'n noma'lum odam o'zini tanishtirdi."),
        ("Честно говоря, половину их имён я тут же забыл.", "Halos, ularning ismlarining yarmisini darhol unutdim."),
        ("Позже мой коллега Достон спас меня распечатанным списком.", "Jamoadoshim Doston keyinroq chop etilgan ro'yxat bilan menga yordam berdi."),
        ("Он объяснил офисные правила с мягким юмором.", "U ofis qoidalarini muloyim hazil bilan tushuntirib berdi."),
        ("Например, встречи всегда начинаются на пять минут позже.", "Masalan, uchrashuvlar doim besh daqiqa kech boshlanadi."),
        ("А кофемашина ломается каждую пятницу во второй половине дня.", "Va qahva mashinasi har juma kuni tushdan keyin buziladi."),
        ("Во вторник я присутствовал на своей первой настоящей командной встрече.", "Seshanba kuni ilk haqiqiy jamoa uchrashuvimda qatnashdim."),
        ("Все говорили быстро и использовали таинственные аббревиатуры.", "Hamma tez gapirdi va sirli qisqartmalardan foydalandi."),
        ("Я серьёзно кивал, хотя понимал только шестьдесят процентов.", "Faqt faqat oltmish foizini tushungan bo'lsamda, jiddiy bosh irg'adim."),
        ("После этого я записал каждое незнакомое слово.", "Keyin har bir tanish emas so'zni yozib oldim."),
        ("В тот вечер я изучал их, как школьную лексику.", "O'sha kechqurun ularni maktab lug'ati kabi o'rgandim."),
        ("К среде я исправил первую небольшую ошибку в системе.", "Chorshanba kunga kelib, tizimdagi ilk kichik xatoni tuzatdim."),
        ("Мой руководитель похвалил мою работу при всех.", "Rahbarim ishimni hamma oldida maqtadi."),
        ("Уши у меня покраснели, но я чувствовал себя на десять сантиметров выше.", "Quloqlarim qizaridi, lekin o'zimni o'n santimetr balandroq his qildim."),
        ("В четверг состоялась офисная традиция общего обеда.", "Payshanba kuni ofis tushlik an'anasini olib keldi."),
        ("Каждый готовит или приносит одно блюдо из дома.", "Har kim uyida bir taom tayyorlaydi yoki olib keladi."),
        ("Я принёс мамин рисовый плов, и он быстро исчез.", "Onamning guruch palovini olib keldim, u tez tugadi."),
        ("Люди из других отделов приходили спросить рецепт.", "Boshqa bo'limlardagi odamlar retseptni so'rab kelishdi."),
        ("Пятница закончилась тортом, потому что у кого-то был день рождения.", "Juma kuni tort bilan tugadi, chunki kimningdir tug'ilgan kuni edi."),
        ("Мы тихо пели, как это водится в офисах, — наполовину пением, наполовину шёпотом.", "Biz jim qo'shiq aytdik, ofislarda odat bo'lganidek, yarim kuylanib yarim shivirlab."),
        ("За ту неделю я усвоил три важных урока.", "O'sha hafta davomida uch muhim darsni o'rgandim."),
        ("Во-первых, задавать вопросы — это сила, а не слабость.", "Birinchisi, savol berish kuchsizlik emas, kuch."),
        ("Во-вторых, короткая прогулка приводит в порядок усталый мозг.", "Ikkinchisi, qisqa sayr charchagan miygacha yordam beradi."),
        ("В-третьих, коллеги становятся друзьями быстрее, чем вы ожидаете.", "Uchinchisi, hamkasblar kutgandan ham tezroq do'stga aylanadi."),
        ("В пятницу вечером мой почтовый ящик наконец опустел.", "Juma kechqurun pochtam nihoyat bo'sh edi."),
        ("Я взглянул на свой стол и ощутил тихую гордость.", "Stolimga qarab sokin iftixor his qildim."),
        ("Неделю назад это место было незнакомым и пугающим.", "Bir hafta oldin bu joy noma'lum va qo'rqinchli edi."),
        ("Теперь оно уже чувствуется как второй дом.", "Endi u allaqachon ikkinchi uyday tuyuladi."),
        ("Когда я уходил, охранник помахал мне рукой.", "Chiqib ketayotib, qo'riqchi menga qo'l silkitdi."),
        ("«До понедельника», — сказал он, словно старый друг.", "'Dushanba ko'rishamiz', deb aytdi u eski do'stday."),
        ("В автобусе домой я улыбался без всякой причины.", "Uyga qaytayotgan avtobusda hech kimga bog'liq bo'lmagan sababsiz tabassum qildim."),
        ("Ноги у меня болели, но сердце было лёгким.", "Oyoqlarim og'ridi, lekin yuragim yengil edi."),
        ("Я написал родителям, что эта работа мне подходит.", "Ota-onamga bu ish to'g'ri kelayotganini yozdim."),
        ("Отец ответил одним словом: «Наконец-то».", "Otam bitta so'z bilan javob berdi: 'Nihoyat.'"),
        ("Той ночью я уснул, всё ещё в рабочем бейдже.", "O'sha kechqurun ish belgisimni yechmasdan uxlab qoldim."),
    ],
}
