PART3 = {
    7: [
        ("В июне мы с друзьями отправились в поход в горы Чимгана.", "Iyun oyida do'stlarim bilan Chimyon tog'lariga yurish qildik."),
        ("Прогноз обещал солнце, поэтому никто не взял дождевик.", "Bashorat quyoshni va'da qilgandi, shuning uchun hech kim yomg'irpoq olmadi."),
        ("Это была первая ошибка нашей поездки.", "Bu bizning sayohatimizdagi birinchi xato edi."),
        ("Мы начали подъём в шесть утра, в прохладном воздухе.", "Salqin ertalabki havoda soat oltida chiqishni boshladik."),
        ("Сосны покрывали нижние склоны, словно зелёные армии.", "Qarag'aylar pastki yonbag'irlarni yashil armiyalardek qoplaydi."),
        ("Птицы пели со всех сторон, будто хвастаясь своим утром.", "Qushlar har tomondan kuyladi, ertalablarini ko'rsatib turardi."),
        ("К десяти часам пот нарисовал тёмные карты на наших рубашках.", "O'nlikka kelib, ter ko'ylaklarimizda qora xaritalar chizdi."),
        ("Мы слишком быстро выпили воду и посмеялись над этим.", "Suvni juda tez ichdik va buning ustidan kuldik."),
        ("Тропа сужалась вдоль обрыва, под которым бежал маленький ручей.", "Yo'l pastda kichik soy bo'lgan jarlik bo'ylab toraydi."),
        ("Фарис отстал, драматично жалуясь на свой рюкзак.", "Faris orqada qoldi, chamadoni haqida dramatik shikoyat qilib."),
        ("Мы подшучивали над ним, но всё равно замедлили шаг вместе.", "Uni masxara qildik, lekin baribir birga sekinlashtirdik."),
        ("Около полудня небо полностью изменило настроение.", "Taxminan peshin vaqtida osmon kayfiyatini butunlay o'zgartirdi."),
        ("Серая стена облаков поднялась над дальним хребтом.", "Kulrang bulut devori uzoq tizmadan oshib chiqa boshladi."),
        ("Температура упала так, будто кто-то закрыл окно перед летом.", "Harorat tushdi, xuddi kimdir yozga oynani yopib qo'yganidek."),
        ("Первые капли были крупными, холодными и на удивление дружелюбными.", "Birinchi tomchilar katta, sovuq va kutilmaganda samimiy edi."),
        ("Потом хлынул дождь, словно аплодисменты — сильный и повсюду.", "Keyin yomg'ir olqish kabi keldi — kuchli va hamma joyda."),
        ("Мы со смехом побежали к огромной плоской скале неподалёку.", "Yaqin atrofdagi ulkan tekis toshga kulib yugurdik."),
        ("Семеро человек втиснулись под один узкий выступ, как сардины в банке.", "Yetti kishi bir tor qoyalarga sardinalardek sig'ishdi."),
        ("Рюкзаки мы сложили в середину, а сами остались снаружи, наполовину мокрые.", "Chamadonlar o'rtaga kirdi; biz yarim ho'l holda tashqarida qoldik."),
        ("Дождь превратил всю долину в серебряную и шумную.", "Yomg'ir butun vodini kumushrang va shovqinli qildi."),
        ("На скалах появились водопады там, где раньше их не было.", "Oldin sharshara bo'lmagan jarliklarda sharsharalar paydo bo'ldi."),
        ("Молния бесшумно чертила белые ветви на противоположной горе.", "Chaqqon oppoq shoxlarni qarama-qarshi tog' bo'ylab jim chizdi."),
        ("Мы, как дети, считали секунды между вспышкой и громом.", "Biz yalt-ylt va g'umburlash orasidagi soniyalarni sanadik."),
        ("Где-то внизу пастух рано свистом позвал овец домой.", "Pastlarda cho'pon qo'ylarini erta uyga chalqitdi."),
        ("Завернувшись вместе в одно спасательное одеяло, мы делили шоколад.", "Bir favqulodda ko'rpachaga o'ralgan holda shokolad bo'lishdik."),
        ("Дильноза рассказывала истории про привидения, пока мы не взмолились, чтобы она остановилась.", "Dilnoza arvoh hikoyalarini aytdi, biz uni to'xtashiga yalinmaguncha."),
        ("По часам Жасура гроза длилась ровно сорок минут.", "Bo'ron Jasurning soatiga aynan qirq daqiqa davom etdi."),
        ("Когда она ушла, мир пах совсем как новорождённый.", "U ketganda, dunyo butunlay yangi tug'ilgandek hid berdi."),
        ("На каждом листе дрожала крошечная алмазная капля воды.", "Har bir yaproqda mayda titrayotgan suv olmosi bor edi."),
        ("Туман медленно поднимался из долины, словно лёгкий дым.", "Tuman vodidan yumshoq tutun singari sekin ko'tarildi."),
        ("А потом появилась радуга — огромная, двойная, почти надменная.", "Va kamalak keldi — ulkan, juftlashgan, deyarli mag'rur."),
        ("Никто не произнёс ни слова; даже Фарис забыл о своих жалобах.", "Hech kim gapirmadi; hatto Faris ham shikoyatlarini unutdi."),
        ("Мы продолжили подъём через мокрую траву и блестящие камни.", "Ho'l o'tloq va yalt-yaltiroq toshlar orasida chiqishda davom etdik."),
        ("Вершина вдруг показалась, надев облако, словно шляпу.", "Cho'qqi birdan namoyon bo'ldi, bulutni shlyapa kabi kiygan holda."),
        ("Мы кричали в туман просто для того, чтобы услышать эхо.", "Tumanga aks sadoni eshitish uchun baqirdik."),
        ("На обед были хлеб, сыр, помидоры и чистая победа.", "Nonushta non, pishloq, pomidor va sof g'alaba edi."),
        ("После дождя и усилий всё кажется вкуснее.", "Yomg'ir va mehnatdan keyin har narsa mazaliroq tuyuladi."),
        ("Спуск занял меньше времени, но потребовал больше внимания.", "Pasayish kamroq vaqt oldi, lekin ko'proq e'tibor talab qildi."),
        ("Мы быстро поняли: мокрые камни скользкие на профессиональном уровне.", "Ho'l toshlar professional darajadagi sirg'aluvchan ekanini tez o'rgandik."),
        ("В деревне пожилая женщина продала нам горячий чай и мёд.", "Qishloqda keksa ayol bizga issiq choy va asal sotdi."),
        ("Она сказала, что горный дождь всегда приносит удачу гостям.", "U tog' yomg'iri mehmonlarga doimo omad keltirishini aytdi."),
        ("В автобусе по дороге домой пахло мокрой шерстью и травой.", "Uyga avtobusda ho'l jun va o't hidi bor edi."),
        ("Все спали, кроме водителя — и историй Дильнозы про привидения.", "Haydovchi va Dilnozaning arvoh hikoyalaridan boshqa hamma uxlab qoldi."),
        ("С той поездки мы больше никогда не доверяем прогнозу погоды.", "O'sha sayohatdan keyin ob-havo bashoratiga umuman ishonmaymiz."),
    ],
    8: [
        ("Экзаменационная неделя пришла в наш университет, словно вторгшаяся армия.", "Imtihon haftasi universitetimizga bosqinchilar armiyasiday keldi."),
        ("Библиотека вдруг стала многолюднее базара.", "Kutubxona birdan bozordan ham gavjum bo'lib qoldi."),
        ("Студенты заняли столы своими флагами: тетрадями, маркерами, энергетиками.", "Talabalar stollarni bayroqlar bilan band qildi: daftarlar, flomasterlar, energiya ichimliklari."),
        ("Мой сосед по комнате распечатал расписание и приклеил его на стену.", "Xonadoshim jadvalni chop etib devoriga yopishtirdi."),
        ("Три экзамена за четыре дня — математика, история и английский.", "To'rt kunda uch imtihon — matematika, tarix va ingliz tili."),
        ("Математику поставили первой, и это ощущалось как личное оскорбление.", "Matematika birinchi bo'lib belgilandi, bu shaxsan haqoratli tuyuldi."),
        ("Я составил план с цветными пометками и следовал ему целый день.", "Rang kodli reja tuzdim va uni bir kun bajardim."),
        ("Второй день, честно говоря, превратился в листание ленты и панику.", "Ikkinchi kun rostini aytsam aylansh va vahimaga aylandi."),
        ("Мама звонила каждый вечер с одним и тем же вопросом.", "Onam har kechqurun bir xil savol bilan qo'ng'iroq qildi."),
        ("«Ты поел?» — никогда про оценки, всегда про еду.", "'Ovqat yedingizmi?' — hech qachon baholar haqida emas, doimo ovqat haqida."),
        ("Накануне математики наша группа устроила совместную подготовку.", "Matematikadan oldingi kechqurun guruhimiz o'quv mashg'uloti uyushtirdi."),
        ("Мы собрались на кухне в общежитии, между двумя чайниками.", "Ikki choynak orasida yotoqxona oshxonasida uchrashdik."),
        ("Кто-то объяснял производные на примере кусков хлеба.", "Kimdir hosilalarni non bo'laklari misolida tushuntirib berdi."),
        ("Другой чертил формулы прямо на столе мукой.", "Yanasi formulalarni to'g'ridan-to'g'ri stolga un bilan chizdi."),
        ("К полуночи даже слабые темы стали проясняться.", "Yarim kechaga kelib hatto zaif mavzular ham ma'noli bo'la boshladi."),
        ("Мы порадовались слишком рано и легли спать в два часа ночи.", "Biz juda erta nishonladik va ikkida uxlab qoldik."),
        ("У утренних экзаменов есть особая тишина.", "Ertalabki imtihonlarda maxsus jimlik bor."),
        ("Двести карандашей, пишущих одновременно, звучат как тихий дождь.", "Ikkita yuz qalam bir vaqtda yozganda yumshoq yomg'irdek tovush chiqaradi."),
        ("Наблюдатель ходил медленно, в туфлях, полных угрозы.", "Nazoratchi sekin yurdi, sof tahdid poyabzalini kiyyan holda."),
        ("Первый вопрос был милосердным; четвёртый — просто преступным.", "Birinchi savol rahmli edi; to'rtinchi esa jinoyat edi."),
        ("Я оставил его на потом и двигался дальше.", "Uni keyinga qoldirdim va oldinga siljiy berdim."),
        ("Где-то позади меня кто-то вздохнул, как умирающий двигатель.", "Ortamda kimdir o'layotgan dvigatelday nafas oldi."),
        ("В последние десять минут я вернулся к нему и решил его.", "Oxirgi o'n daqiqa ichida qaytib keldim va uni yechdim."),
        ("Правильно ли — я узнал бы только на следующей неделе.", "To'g'ri yoki yo'qligini faqat keyingi haftada bilardim."),
        ("Экзамен по истории пришёл после одной отчаянной ночи с датами.", "Tarix imtihoni sanalarning bitta umidsiz kechasidan keyin keldi."),
        ("Мой мозг хранил королей, как случайные номера телефонов.", "Miyam podshohlarni tasodifiy telefon raqamlari kabi saqladi."),
        ("К счастью, темой эссе оказался Шёлковый путь — мой любимый.", "Omadinga, esse mavzusi Ipak yo'li edi — mening sevimlim."),
        ("Я писал о караванах, специях, языках и роли моего родного города.", "Karvonlar, ziravorlar, tillar va tug'ilgan shahrim roli haqida yozdim."),
        ("Писать о том, что любишь, похоже на разговор, а не на испытание.", "Sevgan narsa haqida yozish suhbatlashgandek, sinovdan o'tmagandek tuyuladi."),
        ("Английский был последним, и аудитория заметно расслабилась.", "Ingliz tili oxiri keldi va xona ko'rinib tinchlantirdi."),
        ("В тексте для чтения рассказывалась история о смотрителе маяка.", "O'qish tushunishi mayoqchining hikoyasini aytib berdi."),
        ("Мне это почти понравилось, что во время экзаменов казалось почти запретным.", "Deyarli zavqlandim, bu imtihon paytida noqonuniy tuyuldi."),
        ("После последнего звонка коридор взорвался свободой.", "Oxirgi jiringlashdan keyin koridor ozodlikka portladi."),
        ("Незнакомые люди обнимали незнакомых; книги торжественно летели в мусорные баки.", "Tanish emaslar tanish emaslarni quchoqladi; kitoblar marosim ravishda axlat idishiga uchdi."),
        ("Некоторые студенты тут же всё забыли, бессмысленно улыбаясь.", "Ba'zi talabalar hamma narsani darhol unutdilar, bo'sh tabassum bilan."),
        ("Наша группа сразу отправилась в парк у реки.", "Guruhimiz to'g'ridan-to'g'ri daryo yaqinidagi bog'ga bordi."),
        ("Мы купили мороженое, несмотря на холодный ветер.", "Sovuq shamolga qaramay muzqaymoq sotib oldik."),
        ("Результаты пришли по электронной почте спустя три бесконечных дня.", "Natijalar cheksiz uch kundan keyin elektron pochta orqali keldi."),
        ("Я открыл своё письмо, стоя посреди коридора.", "O'zinikini koridorning o'rtasida turub ochdim."),
        ("Математика: сдал. История: сдал. Английский: девяносто один балл.", "Matematika: o'tdim. Tarix: o'tdim. Ingliz tili: to'qson bir ball."),
        ("Прежде чем открыть дверь дома, я сначала позвонил маме.", "Uy eshigini ochishdan avval birinchi navbatda onamga qo'ng'iroq qildim."),
        ("Она немного всплакнула и снова спросила, поел ли я.", "U biroz yig'ladi va yana ovqat yeganimni so'radi."),
        ("Та неделя научила меня, что паника тяжелее книг.", "O'sha hafta vahim kitoblardan og'iroq ekanini o'rgatdi."),
        ("В следующем семестре я планирую готовиться спокойно с первого дня.", "Keyingi semestrda birinchi kundan sokin o'qishni rejalashtiryapman."),
    ],
    9: [
        ("После вечерней смены я еду домой на последнем ночном автобусе.", "Kechki smenadan keyin oxirgi tungi avtobusda uyga qaytaman."),
        ("Он отправляется с площади ровно в двадцать три сорок.", "U maydondan aynan yigirma uch qirq daqiqada jo'naydi."),
        ("В этот час со мной едут всего три-четыре пассажира.", "Bu soatda menga faqat uch-to'rt yo'lovchi hamroh bo'ladi."),
        ("Водитель теперь знает в лицо каждого постоянного пассажира.", "Haydovchi endi har bir doimiy yo'lovchini yuzidan tanib oladi."),
        ("Он молча кивает мне, и это похоже на дружбу.", "U menga jim bosh irg'adi, bu esa do'stlikdek tuyuladi."),
        ("В автобусе едва слышно пахнет дизелем, дождём и чьим-то ужином.", "Avtobusda dizel, yomg'ir va kimningdir kechki ovqati hidi seziladi."),
        ("Сегодня вечером позади меня сидит пожилая женщина с большой сумкой.", "Bugun kechqurun orqamda katta sumka tutgan keksa ayol o'tiradi."),
        ("Из её сумки доносится тихое позвякивание пустых банок.", "Sumkasidan bo'sh idishlarning sokin jiringlashi keladi."),
        ("Каждый вечер она сдаёт бутылки на рынке.", "U har shom bozorga idishlarni qaytarib beradi."),
        ("Через проход студент спит, прислонившись к рюкзаку.", "Yo'lak narida talaba chamadoniga suyanib uxlab yotadi."),
        ("Его учебник медленно сползает к краю колен.", "Uning darsligi tizzalari chetiga sekin sirg'aladi."),
        ("Город за окном проплывает мимо, словно медленный телевизор.", "Tashqaridagi shahar sekin televideniedek o'tib ketadi."),
        ("Закрытые магазины опустили металлические веки; перекрёстки принадлежат бродячим собакам.", "Yopiq do'konlar metall ko'z qovoqlari kiyadi; adashgan itlar chorrahani egallaydi."),
        ("У светофора мы ждём одни на всей улице.", "Svetoforlarda butun ko'chada yolg'iz kutamiz."),
        ("Из радио водителя тихо звучит старая песня.", "Haydovchining radio eshitish qurilmasidan eski qo'shiq jim chalinadi."),
        ("Он подпевает, не замечая, что его можно услышать.", "U kimdir eshitishini sezmasdan kuylaydi."),
        ("Где-то у моста в автобус заходят ещё пассажиры.", "Ko'prik yaqinidagi bir joyda boshqa yo'lovchilar ham chiqishadi."),
        ("Две медсестры в белых туфлях садятся, измученные после смены.", "Oq poyabzallik ikki hamshira smenadan keyin charchagan holda o'tirishadi."),
        ("Они говорят о пациентах короткими усталыми фразами.", "Ular bemorlar haqida qisqa charchagan gaplarda gapirishadi."),
        ("Молодой рабочий несёт вёдра с краской с резким запахом.", "Yosh ishchi kuchli hid beradigan bo'yoq idishlarini olib chiqyapti."),
        ("Никто не жалуется; у ночных автобусов свои неписаные правила терпения.", "Hech kim shikoyat qilmaydi; tungi avtobuslarda sabrning yozilmagan qoidalari bor."),
        ("Моя остановка приближается примерно через пятнадцать минут.", "Beketim taxminan o'n beshta daqiqa ichida yaqinlashadi."),
        ("По привычке я всегда нажимаю на кнопку слишком рано.", "Men doim odatdan erta tugmani bosaman."),
        ("Пожилая женщина вдруг спрашивает водителя о завтрашнем расписании.", "Keksa ayol birdan haydovchidan ertangi jadval haqida so'raydi."),
        ("Её голос мягкий, будто она боится потревожить ночь.", "Ovozi yumshoq, xuddi kechani bezovta qilishdan qo'rqqanday."),
        ("Водитель терпеливо отвечает и даже улыбается в зеркало.", "Haydovchi sabrli javob beradi va hatto oynaga tabassum ham qiladi."),
        ("На улице снова начинается дождь, рисуя линии на каждом окне.", "Tashqarida yomg'ir yana boshlanadi, har bir oynada chiziqlar chizadi."),
        ("Студент в панике просыпается за одну остановку до своей.", "Talaba o'z beketidan bir oldingi bekatda vahima bilan uyg'onadi."),
        ("Мы все смотрим, как он убегает в темноту, тихо смеясь.", "Hammamiz uni zulmatga yugurganini kuzatib jim kulamiz."),
        ("Медсёстры выходят вместе, деля один маленький зонт.", "Hamshiralar birga ketishadi, bitta kichik soyabonni bo'lishib."),
        ("Теперь в автобусе остаёмся только я и женщина с банками.", "Endi faqat idishli ayol bilan men avtobusda qoldik."),
        ("Теперь автобус кажется личным пространством, как ночное такси воспоминаний.", "Avtobus endi xususiy tuyuladi, xotiralarning kechgi taksidek."),
        ("Я спрашиваю женщину, помогают ли ей внуки носить банки.", "Ayoldan nabiralari idish ko'tarishga yordam berishini so'rayman."),
        ("Она смеётся и говорит, что они заняты — становятся важными людьми.", "U kulib, ular muhim odamlar bo'lish bilan band deb javob beradi."),
        ("В её голосе нет грусти, только лёгкая ирония.", "Ovozida hafsala yo'q, faqat muloyim hazil bor."),
        ("Она говорит, что банки оплачивают карандаши её внучки.", "U idishlar nabirasining qalam pullarini to'lashini aytadi."),
        ("Когда наконец подъезжает моя остановка, я помогаю ей снять сумку.", "Beketim nihoyat kelganda, sumkasini tushirishga yordam beraman."),
        ("Она настаивает и даёт мне маленький абрикос из банки.", "U menga idishdan bitta mayda o'rik berishga qat'iy qaror qiladi."),
        ("Идя домой под зонтом, я медленно ем абрикос.", "Soyabon ostida uyga piyoda qaytayotib, o'rikni sekin yeyman."),
        ("На вкус он кисло-сладкий, как большинство честных разговоров.", "U achchiq-shirin ta'mga ega, eng samimiy suhbatlar kabi."),
        ("Город вокруг меня тихо гудит, наполовину уснувший.", "Shahar atrofimdagi jim g'urraydi, yarim uxlagan holda."),
        ("Завтра этот автобус снова покатится по тем же улицам.", "Ertaga bu avtobus xuddi shu ko'chalar orqali yana yuradi."),
        ("Тот же водитель, та же тишина, но каждую ночь — новые маленькие истории.", "Xuddi shu haydovchi, xuddi shu jimlik, har kecha boshqa kichik hikoyalar."),
        ("Именно поэтому в ночном автобусе я никогда не чувствую себя по-настоящему одиноким.", "Shuning uchun tungi avtobusda hech qachon chin ma'noda yolg'iz his qilmayman."),
    ],
}
