# Generated by Django 6.1 on 2026-08-23 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('progress', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyactivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='languageactivity',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_activities', to='catalog.language'),
        ),
        migrations.AddField(
            model_name='languageactivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progresses', to='catalog.book'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.booksection'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='dailyactivity',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='uniq_user_day_activity'),
        ),
        migrations.AddConstraint(
            model_name='languageactivity',
            constraint=models.UniqueConstraint(fields=('user', 'language'), name='uniq_user_lang_time'),
        ),
        migrations.AddConstraint(
            model_name='userprogress',
            constraint=models.UniqueConstraint(fields=('user', 'book'), name='uniq_user_book_progress'),
        ),
    ]
