# Generated by Django 6.1 on 2026-08-23 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('cover_image_url', models.CharField(blank=True, default='', max_length=300)),
                ('order_index', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=150)),
                ('emoji', models.CharField(blank=True, default='', max_length=8)),
                ('cover_image_url', models.CharField(blank=True, default='', max_length=300)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='catalog.language')),
            ],
            options={
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='BookSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('original_text', models.TextField()),
                ('translated_text', models.TextField()),
                ('sentences', models.JSONField(default=list)),
                ('translated_sentences', models.JSONField(default=list)),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio')),
                ('timestamps', models.JSONField(default=list)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='catalog.book')),
            ],
            options={
                'ordering': ['order_index'],
                'constraints': [models.UniqueConstraint(fields=('book', 'order_index'), name='uniq_section_order')],
            },
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.UniqueConstraint(fields=('language', 'order_index'), name='uniq_book_order'),
        ),
    ]
